SELECT   R030FIL.NOMFIL AS FILIAL
		 ,R024CAR.TITCAR
             , R030FIL.NUMCGC AS CODFILIAL
             , T1.CGC
             , R034FUN.NOMFUN AS COLABORADOR
             , R024CAR.TITCAR AS CARGO
             , R018CCU.CCUTXT AS CENTROCUSTO
             , R010SIT.DESSIT AS SITUACAO
             , R034FUN.BENREA AS REABILITADO
             , T1.Regional regionalcentrocusto
             , T1.NOME filialcentrocusto
             , R030FIL.codest
             , CASE when DBO.REGIONALASSOCIADA(R030FIL.codest) = t1.regional
					then 1
					ELSE 0
               END AS TOTALDENTROREGIONAL 
             , 1 AS TOTAL
             ,DBO.REGIONALASSOCIADA2(codfilial)  As Regional
			 ,case when R034FUN.NUMEMP = 1 AND R034FUN.TIPCOL = 1  AND R034FUN.DEFFIS = 'S' then 'S'
			 else 
			 case when R034FUN.NUMEMP = 1 AND R034FUN.TIPCOL = 1 AND R034FUN.DEFFIS = 'N' AND R034FUN.BENREA = 'S' then 'S'
			 else 'N'
			 end end
			  as PCD,
			 CASE WHEN R030FIL.NUMCGC <> T1.CGC THEN 1 ELSE 0 
			 END AS FILIALEMPRESTADO

--into #teste
       FROM [SQLAZGERAL].[VETORRH].[dbo].R034FUN R034FUN
       LEFT JOIN [SQLAZGERAL].[VETORRH].[dbo].R016ORN R016ORN ON (R034FUN.NUMLOC = R016ORN.NUMLOC)
       LEFT JOIN [SQLAZGERAL].[VETORRH].[dbo].R016HIE R016HIE ON (R016ORN.NUMLOC = R016HIE.NUMLOC)
       LEFT JOIN [SQLAZGERAL].[VETORRH].[dbo].R038HLO R038HLO ON (R016HIE.TABORG = R038HLO.TABORG AND R016HIE.NUMLOC = R038HLO.NUMLOC AND R038HLO.NUMEMP = R034FUN.NUMEMP AND R038HLO.TIPCOL = R034FUN.TIPCOL AND R038HLO.NUMCAD = R034FUN.NUMCAD AND R038HLO.NUMEMP = R034FUN.NUMEMP AND R038HLO.TIPCOL = R034FUN.TIPCOL AND R038HLO.NUMCAD = R034FUN.NUMCAD)
       LEFT JOIN [SQLAZGERAL].[VETORRH].[dbo].R024CAR R024CAR ON (R034FUN.CODCAR = R024CAR.CODCAR)
       LEFT JOIN [SQLAZGERAL].[VETORRH].[dbo].R038HCA R038HCA ON (R038HCA.ESTCAR = R024CAR.ESTCAR AND R038HCA.CODCAR = R024CAR.CODCAR AND R038HCA.NUMEMP = R034FUN.NUMEMP AND R038HCA.TIPCOL = R034FUN.TIPCOL AND R038HCA.NUMCAD = R034FUN.NUMCAD)
       LEFT JOIN [SQLAZGERAL].[VETORRH].[dbo].R038HFI R038HFI ON (R034FUN.NUMCAD = R038HFI.NUMCAD AND R034FUN.NUMEMP = R038HFI.NUMEMP AND R034FUN.TIPCOL = R038HFI.TIPCOL)
       LEFT JOIN [SQLAZGERAL].[VETORRH].[dbo].R030FIL R030FIL ON (R038HFI.CODFIL = R030FIL.CODFIL AND R038HFI.NUMEMP = R030FIL.NUMEMP AND R034FUN.NUMCAD = R038HFI.NUMCAD AND R034FUN.NUMEMP = R038HFI.NUMEMP AND R034FUN.TIPCOL = R038HFI.TIPCOL)
       LEFT JOIN [SQLAZGERAL].[VETORRH].[dbo].R022DEF R022DEF ON (R034FUN.CODDEF = R022DEF.CODDEF)
       LEFT JOIN [SQLAZGERAL].[VETORRH].[dbo].R018CCU R018CCU ON (R034FUN.CODCCU = R018CCU.CODCCU AND R018CCU.NUMEMP = 1)
       LEFT JOIN [SQLAZGERAL].[VETORRH].[dbo].R010SIT R010SIT ON (R034FUN.SITAFA = R010SIT.CODSIT)
       LEFT JOIN (
                           select CT_CC.estrutura, filiais.nome,filiais.handle as codfilial,
                                     DBO.REGIONALASSOCIADA(ESTADOS.SIGLA)  Regional
                                     , REPLACE(REPLACE(REPLACE(FILIAIS.CGC,'.',''),'-',''),'/','') AS CGC
                        from CT_CC
                                  inner join FILIAIS on filiais.handle = CT_CC.K_filialcc
                                  INNER JOIN GLGL_FILIAIS ON FILIAIS.HANDLE = GLGL_FILIAIS.FILIAL
                                  INNER JOIN ESTADOS ON ESTADOS.HANDLE = FILIAIS.ESTADO
                                  LEFT JOIN GN_PESSOAS REGIONAL ON REGIONAL.HANDLE = GLGL_FILIAIS.K_GERENTEREGIONAL
                           where CT_CC.ULTIMONIVEL = 'S'
                           

                       ) T1 ON T1.ESTRUTURA COLLATE SQL_Latin1_General_CP1_CI_AS =R018CCU.CCUTXT COLLATE SQL_Latin1_General_CP1_CI_AS



       WHERE 
       R034FUN.NUMEMP = 1
       AND R034FUN.TIPCOL = 1 
       AND R034FUN.SITAFA <> 7
       AND R038HLO.DATALT = (SELECT MAX (DATALT) FROM [SQLAZGERAL].[VETORRH].[dbo].R038HLO TABELA001 WHERE
       (TABELA001.NUMEMP = R038HLO.NUMEMP) AND
       (TABELA001.TIPCOL = R038HLO.TIPCOL) AND
       (TABELA001.NUMCAD = R038HLO.NUMCAD))
       AND (R038HFI.DATALT = (SELECT MAX (DATALT) FROM [SQLAZGERAL].[VETORRH].[dbo].R038HFI TABELA002 WHERE
       (TABELA002.NUMEMP = R038HFI.NUMEMP) AND
       (TABELA002.TIPCOL = R038HFI.TIPCOL) AND
       (TABELA002.NUMCAD = R038HFI.NUMCAD)))
       AND (R038HCA.DATALT = (SELECT MAX (DATALT) FROM [SQLAZGERAL].[VETORRH].[dbo].R038HCA TABELA003 WHERE
       (TABELA003.NUMEMP = R038HCA.NUMEMP) AND
       (TABELA003.TIPCOL = R038HCA.TIPCOL) AND
       (TABELA003.NUMCAD = R038HCA.NUMCAD))) 
       AND R034FUN.SITAFA <> 7
	   AND R034FUN.TIPCOL = 1 
	   AND R034FUN.NUMEMP = 1 
	   AND R024CAR.TITCAR NOT LIKE '%APRENDIZ%'