SELECT 
REGIONAL,
ANO,
ROUND(SUM([VOLUME NA ORIGEM]),2) AS [VOLUME NA ORIGEM],
ROUND(SUM([VOLUME NO TRANSITO]),2) AS [VOLUME NA ENTREGA],
ROUND(SUM([VOLUME TRANSBORDO TRANSFERENCIA]),2) AS [VOLUME TRANSBORDO],
ROUND((SUM([VOLUME NA ORIGEM])+SUM([VOLUME NO TRANSITO])+SUM([VOLUME TRANSBORDO TRANSFERENCIA])),2) AS TOTAL,
ROUND(SUM([PESO TOTAL NO TRANSITO]),2) AS [PESO TOTAL NO TRANSITO],
ROUND(SUM([VALOR TOTAL NO TRANSITO]),2) AS [VALOR TOTAL NO TRANSITO],
ROUND(SUM([VALOR NF NO TRANSITO]),2) AS [VALOR NF NO TRANSITO],
ROUND(SUM(QTDDOCSNOTRANSITO),2) AS QTDDOCSNOTRANSITO,
ROUND(SUM([PESO TOTAL TRANSBORDO TRANSFERENCIA]),2) AS [PESO TOTAL TRANSBORDO TRANSFERENCIA],
ROUND(SUM([VALOR TOTAL TRANSBORDO TRANSFERENCIA]),2) AS [VALOR TOTAL TRANSBORDO TRANSFERENCIA],
ROUND(SUM([VALOR NF TRANSBORDO TRANSFERENCIA]),2) AS [VALOR NF TRANSBORDO TRANSFERENCIA],
ROUND(SUM(QTDDOCSTRANSBORDOTRANSFERENCIA),2) AS QTDDOCSTRANSBORDOTRANSFERENCIA,
ROUND(SUM([PESO TOTAL NA ORIGEM]),2) AS [PESO TOTAL NA ORIGEM],
ROUND(SUM([VALOR TOTAL NA ORIGEM]),2) AS [VALOR TOTAL NA ORIGEM],
ROUND(SUM([VALOR NF NA ORIGEM]),2) AS [VALOR NF NA ORIGEM],
ROUND(SUM(QTDDOCSNAORIGEM),2) AS QTDDOCSNAORIGEM


FROM (

SELECT 
YEAR(DL.DATAENTREGA) AS ANO,
CASE WHEN F.ESTADO = 18 THEN 'REGIONAL MG' ELSE '' END AS REGIONAL,
0 AS [VOLUME NA ORIGEM],
SUM(DL.DOCCLIATUALVOLUME) [VOLUME NO TRANSITO],
0 [VOLUME TRANSBORDO TRANSFERENCIA],
SUM(DL.DOCCLIPESOTOTAL) [PESO TOTAL NO TRANSITO],
SUM(DL.DOCCLIVALORTOTAL) [VALOR TOTAL NO TRANSITO],
SUM(DL.VALORCONTABIL) [VALOR NF NO TRANSITO],
COUNT(DISTINCT DL.NUMERO) AS QTDDOCSNOTRANSITO,
0 [PESO TOTAL TRANSBORDO TRANSFERENCIA],
0 [VALOR TOTAL TRANSBORDO TRANSFERENCIA],
0 [VALOR NF TRANSBORDO TRANSFERENCIA],
0 AS QTDDOCSTRANSBORDOTRANSFERENCIA,
0 [PESO TOTAL NA ORIGEM],
0 [VALOR TOTAL NA ORIGEM],
0 [VALOR NF NA ORIGEM],
0 AS QTDDOCSNAORIGEM


FROM  GLGL_DOCUMENTOS DL
INNER JOIN FILIAIS F ON DL.FILIALENTREGA = F.HANDLE

WHERE 1 = 1
AND DL.DATAENTREGA BETWEEN '2015-01-01 00:00:00' AND GETDATE()
AND F.ESTADO = 18
AND DL.FILIAL <> DL.FILIALENTREGA
--AND DL.FILIAL <> 2
--AND VD.FILIALORIGEM = 2
AND DL.TIPODOCUMENTO IN (2,1,6) 
AND((DL.TIPORPS In (322,323))
	  Or (DL.TIPODOCUMENTOFRETE In (153)))

GROUP BY YEAR(DL.DATAENTREGA), CASE WHEN F.ESTADO = 18 THEN 'REGIONAL MG' ELSE '' END

UNION ALL

SELECT 
YEAR(V.INICIOEFETIVO) AS ANO,
CASE WHEN F.ESTADO = 18 THEN 'REGIONAL MG' ELSE '' END AS REGIONAL,
0 AS [VOLUME NA ORIGEM],
0 [VOLUME NO TRANSITO],
SUM(IIf(V.TIPOVIAGEM = 172, DL.DOCCLIATUALVOLUME, 0)) [VOLUME TRANSBORDO TRANSFERENCIA],
0 [PESO TOTAL NO TRANSITO],
0 [VALOR TOTAL NO TRANSITO],
0 [VALOR NF NO TRANSITO],
0 AS QTDDOCSNOTRANSITO,
SUM(DL.DOCCLIPESOTOTAL) [PESO TOTAL TRANSBORDO TRANSFERENCIA],
SUM(DL.DOCCLIVALORTOTAL) [VALOR TOTAL TRANSBORDO TRANSFERENCIA],
SUM(DL.VALORCONTABIL) [VALOR NF TRANSBORDO TRANSFERENCIA],
COUNT(DISTINCT DL.NUMERO) AS QTDDOCSTRANSBORDOTRANSFERENCIA,
0 [PESO TOTAL NA ORIGEM],
0 [VALOR TOTAL NA ORIGEM],
0 [VALOR NF NA ORIGEM],
0 AS QTDDOCSNAORIGEM

FROM GLOP_VIAGEMDOCUMENTOS VD
INNER JOIN GLGL_DOCUMENTOS DL ON DL.HANDLE = VD.DOCUMENTOLOGISTICA AND DL.FILIAL <> VD.FILIALORIGEM
LEFT JOIN GLOP_VIAGENS V ON V.HANDLE = VD.VIAGEM
INNER JOIN FILIAIS F ON VD.FILIALORIGEM = F.HANDLE

WHERE 1 = 1
AND V.INICIOEFETIVO BETWEEN '2015-01-01 00:00:00' AND GETDATE()
AND F.ESTADO = 18
--AND DL.FILIAL <> 2
--AND VD.FILIALORIGEM = 2
AND DL.TIPODOCUMENTO IN (2,1,6) 
AND(((DL.TIPORPS In (322,323)))
	  Or (DL.TIPODOCUMENTOFRETE In (153,156)))

GROUP BY YEAR(V.INICIOEFETIVO), CASE WHEN F.ESTADO = 18 THEN 'REGIONAL MG' ELSE '' END

UNION ALL

SELECT 
YEAR(DL.DATAEMISSAO) AS ANO,
CASE WHEN F.ESTADO = 18 THEN 'REGIONAL MG' ELSE '' END AS REGIONAL,
SUM(DL.DOCCLIVOLUME)  AS [VOLUME NA ORIGEM],
0 AS [VOLUME NO TRANSITO],
0 AS [VOLUME TRANSBORDO TRANSFERENCIA],
0 [PESO TOTAL NO TRANSITO],
0 [VALOR TOTAL NO TRANSITO],
0 [VALOR NF NO TRANSITO],
0 AS QTDDOCSNOTRANSITO,
0 [PESO TOTAL TRANSBORDO TRANSFERENCIA],
0 [VALOR TOTAL TRANSBORDO TRANSFERENCIA],
0 [VALOR NF TRANSBORDO TRANSFERENCIA],
0 AS QTDDOCSTRANSBORDOTRANSFERENCIA,
SUM(DL.DOCCLIPESOTOTAL) [PESO TOTAL NA ORIGEM],
SUM(DL.DOCCLIVALORTOTAL) [VALOR TOTAL NA ORIGEM],
SUM(DL.VALORCONTABIL) [VALOR NF NA ORIGEM],
COUNT(DISTINCT DL.NUMERO) AS QTDDOCSNAORIGEM

FROM GLGL_DOCUMENTOS DL
INNER JOIN FILIAIS F ON DL.FILIAL = F.HANDLE

WHERE 1=1
AND F.ESTADO = 18
AND (DL.DATAEMISSAO BETWEEN '2015-01-01 00:00:00' AND GETDATE())
AND DL.STATUS NOT IN (220, 223, 224, 236, 237, 404, 417)
AND ((DL.TIPODOCUMENTO IN (1, 2, 17, 22) AND DL.FRETECORTESIA = 'N')                                             
	  OR (                                                                         
             DL.TIPODOCUMENTO IN (6)                                                                
       AND DL.TIPORPS <> 323                                                                        
       AND NOT EXISTS                                                                        

       (                                                                                     
             SELECT 1                                                                            
             FROM GLGL_DOCLOGASSOCIADOS DLA                                                  
                  INNER JOIN GLGL_DOCUMENTOS NFS ON (DLA.DOCUMENTOLOGISTICAPAI = NFS.HANDLE) 
            WHERE DLA.DOCUMENTOLOGISTICAFILHO = DL.HANDLE                                    
              AND NFS.TIPODOCUMENTO IN (17, 22,2,1)                                          
              AND NFS.FRETECORTESIA = 'N'                                                           
              AND NFS.STATUS NOT IN (224,404,220,223,236,237,417)                            

       )))

GROUP BY YEAR(DL.DATAEMISSAO), CASE WHEN F.ESTADO = 18 THEN 'REGIONAL MG' ELSE '' END
) AS T1

GROUP BY ANO,REGIONAL