--select * from INFORMATION_SCHEMA.TABLES
--WHERE TABLE_NAME LIKE '%inventario%'

--order by TABLE_NAME



SELECT 
	F.NOME AS NOMEFILIAL
	,TIE.NOME AS NOMEEQUIPAMENTO
	,K_LATITUDE
	,K_LONGITUDE
	,COUNT(*) AS QTD
	

FROM K_GLOP_INVENTARIOEQUIPAMENTOS IVE
INNER JOIN K_GLOP_TIPOINVENTARIOEQUIPTOS TIE
	ON IVE.TIPO = TIE.HANDLE 
	--AND TIE.HANDLE = 2
INNER JOIN GLGL_ENUMERACAOITEMS EI
	ON IVE.STATUS = EI.CODIGO
INNER JOIN FILIAIS F
	ON IVE.FILIAL = F.HANDLE

GROUP BY F.NOME
		,TIE.NOME
      ,K_LATITUDE
      ,K_LONGITUDE

--SELECT * FROM K_GLOP_INVENTARIOEQUIPITENS

--SELECT * FROM K_GLOP_INVENTARIOEQUIPAMENTOS