--SELECT TOP(10) * FROM GLGL_DOCUMENTOS D WITH(NOLOCK)
--LEFT JOIN GLOP_SERVICOREALIZADORPS SERVICORPS WITH(NOLOCK) ON SERVICORPS.DOCUMENTOLOGISTICA = D.HANDLE
--LEFT JOIN GLOP_SERVICOSREALIZADOS SERVICO WITH(NOLOCK) ON SERVICO.HANDLE = SERVICORPS.SERVICOREALIZADO
--LEFT JOIN K9_GLGL_SERVICOSREALIZADOS SERVICOREALIZADOAUTO WITH(NOLOCK) ON SERVICOREALIZADOAUTO.SERVICOREALIZADO = SERVICO.HANDLE
--LEFT JOIN K9_GLCM_CONFSERVICOSAUTOMATICO CONFSERVICOAUTO WITH(NOLOCK) ON CONFSERVICOAUTO.HANDLE = SERVICOREALIZADOAUTO.CONFSERVICOAUTOMATICO
--LEFT JOIN GLOP_OCORRENCIAS OCORRENCIA WITH(NOLOCK) ON SERVICOREALIZADOAUTO.AGRUPADOROCORRENCIA = OCORRENCIA.AGRUPADOR
--LEFT JOIN GLOP_MOTIVOOCORRENCIAS MOTIVOOCORRENCIA WITH(NOLOCK) ON MOTIVOOCORRENCIA.HANDLE = OCORRENCIA.OCORRENCIA

--WHERE MOTIVOOCORRENCIA.DESCRICAO IN ('Aguardando Agendamento','Encaminhado ao Porta Paletes')




--SELECT D.DATAEMISSAO, * FROM GLOP_OCORRENCIAS O
--LEFT JOIN GLGL_DOCUMENTOCLIENTES DC ON O.DOCUMENTO = DC.HANDLE
--LEFT JOIN GLGL_DOCUMENTOS D ON DC.DOCUMENTOLOGISTICA = D.HANDLE
--LEFT JOIN GLOP_MOTIVOOCORRENCIAS MOTIVOOCORRENCIA WITH(NOLOCK) ON MOTIVOOCORRENCIA.HANDLE = O.OCORRENCIA
--WHERE MOTIVOOCORRENCIA.DESCRICAO IN ('Aguardando Agendamento','Encaminhado ao Porta Paletes')
--AND D.DATAEMISSAO >= DATEADD(DD, -90, GETDATE())



SELECT
		FILIAL AS IDFILIAL
		,F.NOME AS NOMEFILIAL
		,[DATA]
		,DOC
		,SUM(TOTENDERECO) AS TOTENDERECO
		,SUM(TOTOCUPADO) AS TOTOCUPADO
		,ROUND(((CAST(SUM(NULLIF(TOTOCUPADO,0)) AS DECIMAL)*100)/(CAST(SUM(NULLIF(TOTENDERECO,0)) AS DECIMAL))),2) AS TOTALPERCOCUPADO
		,SUM(TOTLIVRE) AS TOTLIVRE
		,ROUND(((CAST(SUM(NULLIF(TOTLIVRE,0)) AS DECIMAL)*100)/(CAST(SUM(NULLIF(TOTENDERECO,0)) AS DECIMAL))),2) AS TOTALPERCLIVRE
		,SUM(TOT_DOC) AS TOT_DOC
		,SUM(TOT_VOL) AS TOT_VOL
		,ROUND(SUM(TOT_PESO),2) AS TOT_PESO
		,ROUND(SUM(TOT_VAL),2) AS TOT_VAL

FROM (


SELECT 
	FILIAL
	,CAST(GETDATE() AS DATE) AS [DATA]
	,'' AS DOC
	,COUNT(1) TOTENDERECO
	,0 AS TOTOCUPADO
	,0 AS TOTLIVRE
	,0 AS TOT_DOC
	,0 AS TOT_VOL
	,0 AS TOT_PESO
	,0 AS TOT_VAL 
FROM [dbo].K_PORTAPALETEENDERECOS A 
WHERE NOT EXISTS (SELECT 1 FROM [dbo].K_PORTAPALETEENDERECOS B WHERE A.HANDLE = B.NIVELSUPERIOR)
--AND  FILIAL = 2 
AND A.ATIVO = 'S'

GROUP BY FILIAL

UNION ALL

SELECT 
	FILIAL
	,CAST(GETDATE() AS DATE) AS [DATA]
	,'' AS DOC
	,0 AS TOTENDERECO
	,COUNT(1) TOTOCUPADO 
	,0 AS TOTLIVRE
	,0 AS TOT_DOC
	,0 AS TOT_VOL
	,0 AS TOT_PESO
	,0 AS TOT_VAL


	
FROM [dbo].K_PORTAPALETEENDERECOS A 
WHERE NOT EXISTS (SELECT 1 FROM [dbo].K_PORTAPALETEENDERECOS B WHERE A.HANDLE = B.NIVELSUPERIOR)
AND EXISTS (SELECT 1 FROM [dbo].K_PORTAPALETEDOCUMENTOS B WHERE A.HANDLE = B.ENDERECOATIVO) 
--AND  FILIAL = 2 
AND A.ATIVO = 'S'

GROUP BY FILIAL

UNION ALL

SELECT 
	FILIAL
	,CAST(GETDATE() AS DATE) AS [DATA]
	,'' AS DOC
	,0 AS TOTENDERECO
	,0 AS TOTOCUPADO 
	,COUNT(1) TOTLIVRE 
	,0 AS TOT_DOC
	,0 AS TOT_VOL
	,0 AS TOT_PESO
	,0 AS TOT_VAL

FROM [dbo].K_PORTAPALETEENDERECOS A 
WHERE NOT EXISTS (SELECT 1 FROM [dbo].K_PORTAPALETEENDERECOS B WHERE A.HANDLE = B.NIVELSUPERIOR)
AND NOT EXISTS (SELECT 1 FROM [dbo].K_PORTAPALETEDOCUMENTOS B WHERE A.HANDLE = B.ENDERECOATIVO)
--AND  FILIAL = 2 
AND A.ATIVO = 'S'

GROUP BY FILIAL 

UNION ALL

SELECT 
	FILIAL
	,CAST(GETDATE() AS DATE) AS [DATA]
	,DOC
	,0 AS TOTENDERECO
	,0 AS TOTOCUPADO 
	,0 AS TOTLIVRE
	,SUM(TOT_DOC) TOT_DOC
	,SUM(TOT_VOL) TOT_VOL
	,SUM(TOT_PESO) TOT_PESO
	,SUM(TOT_VAL) TOT_VAL                                               

FROM (                                                              
SELECT 1 TOT_DOC,(C.DOCCLIVOLUME) TOT_VOL                           
,(C.DOCCLIPESOCONSIDERADO) TOT_PESO,(C.DOCCLIVALORTOTAL) TOT_VAL, A.FILIAL, C.NUMERO AS DOC   
FROM [dbo].K_PORTAPALETEENDERECOS A                                       
INNER JOIN [dbo].K_PORTAPALETEDOCUMENTOS B ON (A.HANDLE = B.ENDERECOATIVO)
INNER JOIN [dbo].GLGL_DOCUMENTOS C ON (C.HANDLE = B.DOCUMENTOLOGISTICA)   
WHERE 1=1
--AND A.FILIAL = 2 

AND A.ATIVO = 'S'

GROUP BY C.DOCCLIVOLUME,C.DOCCLIPESOCONSIDERADO,C.HANDLE  ,C.DOCCLIVALORTOTAL, A.FILIAL,C.NUMERO
) AS T

GROUP BY FILIAL, DOC

) AS TABELAFINAL
INNER JOIN [dbo].FILIAIS F 
	ON FILIAL = F.HANDLE

GROUP BY FILIAL
		,F.NOME
		,[DATA]
		,DOC