SELECT  
	DISTINCT 
	GLOP_VIAGENS.NUMEROVIAGEM
	,MA_RECURSOS.PLACANUMERO
	,ISNULL(RGT.DESCRICAO
	,(select TOP 1 RAR2.DESCRICAO FROM GLOP_ROTALOCALIDADES RL2
				INNER JOIN GLOP_REGIAOATENDIMENTOROTAS RAR2 ON RL2.ROTA = RAR2.HANDLE
				WHERE RAR2.ATIVO = 'S'
				AND E.CEPDESTINO >= RL2.CEPINICIO AND E.CEPDESTINO <= RL2.CEPFIM )) AS [Rota Entrega]
	,E.CEPDESTINO
	,FILO.NOME AS FILIALORIGEM
	,FILO.K_LONGITUDE AS LONGITUDEORIGEM
	,FILO.K_LATITUDE AS LATITUDEORIGEM
	,FILD.NOME AS FILIALDESTINO
	,FILD.K_LONGITUDE AS LONGITUDEDESTINO
	,FILD.K_LATITUDE AS LATITUDEDESTINO
	,GLGL_DOCUMENTOS.NUMERO AS [Número Documento]
	,EI.NOME AS [Status]
	,GLGL_DOCUMENTOS.DTPREVISAOENTREGAEMISSAO AS [Previsão Entrega]
	,CONVERT(SMALLDATETIME, CONVERT(VARCHAR(13), GLGL_DOCUMENTOS.DTPREVISAOENTREGAEMISSAO, 120)+ ':00:00.000') AS [Previsão Entrega Horas]
	,GLGL_DOCUMENTOS.DOCCLIPESOTOTAL AS [Peso Real]
	,GLGL_DOCUMENTOS.DOCCLIVOLUME AS [Qtd. Volumes]
	,GLGL_DOCUMENTOS.VALORFRETEVALOR AS [Frete]
	,DateAdd(Hour, ((Select Count(1) 
					     From GLOP_VIAGEMPARADAS X
					    Where X.VIAGEM					= GLOP_VIAGENS.HANDLE
					      And Not X.FILIAL				= GLOP_VIAGENS.FILIALORIGEM
					      And Not X.FILIAL				= GLOP_VIAGENS.FILIALDESTINO
					      And X.PARADAEFETUADA			= 'N') * 2),
	   IsNull(DateAdd(Second, ((Cast(((((Round((DBO.FN_CALCULADISTANCIA(K_GLOP_VEICULOPOSICOES.LATITUDE,	K_GLOP_VEICULOPOSICOES.LONGITUDE, FILIAIS.K_LATITUDE, FILIAIS.K_LONGITUDE) / 55),4) - Cast(Round((DBO.FN_CALCULADISTANCIA(K_GLOP_VEICULOPOSICOES.LATITUDE,	K_GLOP_VEICULOPOSICOES.LONGITUDE, FILIAIS.K_LATITUDE, FILIAIS.K_LONGITUDE) / 55),4) As Int)) * 100) - Cast(((Round((DBO.FN_CALCULADISTANCIA(K_GLOP_VEICULOPOSICOES.LATITUDE,	K_GLOP_VEICULOPOSICOES.LONGITUDE, FILIAIS.K_LATITUDE, FILIAIS.K_LONGITUDE) / 55),4) - Cast(Round((DBO.FN_CALCULADISTANCIA(K_GLOP_VEICULOPOSICOES.LATITUDE,	K_GLOP_VEICULOPOSICOES.LONGITUDE, FILIAIS.K_LATITUDE, FILIAIS.K_LONGITUDE) / 55),4) As Int)) * 100) As Int)) * 100) As Int) * 0.6)), 
					  DateAdd(Minute, (Cast(((Round((DBO.FN_CALCULADISTANCIA(K_GLOP_VEICULOPOSICOES.LATITUDE,	K_GLOP_VEICULOPOSICOES.LONGITUDE, FILIAIS.K_LATITUDE, FILIAIS.K_LONGITUDE) / 55),4) - Cast(Round((DBO.FN_CALCULADISTANCIA(K_GLOP_VEICULOPOSICOES.LATITUDE,	K_GLOP_VEICULOPOSICOES.LONGITUDE, FILIAIS.K_LATITUDE, FILIAIS.K_LONGITUDE) / 55),4) As Int)) * 100) As Int) * 0.6), 
							  DateAdd(Hour, Cast(Round((DBO.FN_CALCULADISTANCIA(K_GLOP_VEICULOPOSICOES.LATITUDE,	K_GLOP_VEICULOPOSICOES.LONGITUDE, FILIAIS.K_LATITUDE, FILIAIS.K_LONGITUDE) / 55),4) As Int), GetDate()))),
			  GLOP_VIAGENS.PREVISAOCHEGADA))								[Previsao Chegada]
	,CONVERT(SMALLDATETIME, CONVERT(VARCHAR(13), DateAdd(Hour, ((Select Count(1) 
					     From GLOP_VIAGEMPARADAS X
					    Where X.VIAGEM					= GLOP_VIAGENS.HANDLE
					      And Not X.FILIAL				= GLOP_VIAGENS.FILIALORIGEM
					      And Not X.FILIAL				= GLOP_VIAGENS.FILIALDESTINO
					      And X.PARADAEFETUADA			= 'N') * 2),
	   IsNull(DateAdd(Second, ((Cast(((((Round((DBO.FN_CALCULADISTANCIA(K_GLOP_VEICULOPOSICOES.LATITUDE,	K_GLOP_VEICULOPOSICOES.LONGITUDE, FILIAIS.K_LATITUDE, FILIAIS.K_LONGITUDE) / 55),4) - Cast(Round((DBO.FN_CALCULADISTANCIA(K_GLOP_VEICULOPOSICOES.LATITUDE,	K_GLOP_VEICULOPOSICOES.LONGITUDE, FILIAIS.K_LATITUDE, FILIAIS.K_LONGITUDE) / 55),4) As Int)) * 100) - Cast(((Round((DBO.FN_CALCULADISTANCIA(K_GLOP_VEICULOPOSICOES.LATITUDE,	K_GLOP_VEICULOPOSICOES.LONGITUDE, FILIAIS.K_LATITUDE, FILIAIS.K_LONGITUDE) / 55),4) - Cast(Round((DBO.FN_CALCULADISTANCIA(K_GLOP_VEICULOPOSICOES.LATITUDE,	K_GLOP_VEICULOPOSICOES.LONGITUDE, FILIAIS.K_LATITUDE, FILIAIS.K_LONGITUDE) / 55),4) As Int)) * 100) As Int)) * 100) As Int) * 0.6)), 
					  DateAdd(Minute, (Cast(((Round((DBO.FN_CALCULADISTANCIA(K_GLOP_VEICULOPOSICOES.LATITUDE,	K_GLOP_VEICULOPOSICOES.LONGITUDE, FILIAIS.K_LATITUDE, FILIAIS.K_LONGITUDE) / 55),4) - Cast(Round((DBO.FN_CALCULADISTANCIA(K_GLOP_VEICULOPOSICOES.LATITUDE,	K_GLOP_VEICULOPOSICOES.LONGITUDE, FILIAIS.K_LATITUDE, FILIAIS.K_LONGITUDE) / 55),4) As Int)) * 100) As Int) * 0.6), 
							  DateAdd(Hour, Cast(Round((DBO.FN_CALCULADISTANCIA(K_GLOP_VEICULOPOSICOES.LATITUDE,	K_GLOP_VEICULOPOSICOES.LONGITUDE, FILIAIS.K_LATITUDE, FILIAIS.K_LONGITUDE) / 55),4) As Int), GetDate()))),
			  GLOP_VIAGENS.PREVISAOCHEGADA)), 120)+ ':00:00.000') AS [Previsao Chegada Hora]
	 ,'' AS NOMEFILIAL
	 ,CONVERT(SMALLDATETIME, CONVERT(VARCHAR(13), GETDATE(), 120)+ ':00:00.000') AS DATAHORAPORTAPALLET
	 ,0 AS TOTENDERECO
	 ,0 AS TOTOCUPADO
	 ,0 AS TOTALPERCOCUPADO
	 ,0 AS TOTLIVRE
	 ,0 AS TOTALPERCLIVRE
	 ,0 AS TOT_DOC
	 ,0 AS TOT_VOL
	 ,0 AS TOT_PESO
	 ,0 AS TOT_VAL


FROM GLOP_VIAGENS
LEFT JOIN GLOP_LINHAVIAGENS					On GLOP_LINHAVIAGENS.HANDLE						= GLOP_VIAGENS.LINHAVIAGEM
Inner Join GLGV_PLANOCARGADESCARGAS			    On GLGV_PLANOCARGADESCARGAS.VIAGEM				= GLOP_VIAGENS.HANDLE
Inner Join MA_RECURSOS							On MA_RECURSOS.HANDLE							= GLGV_PLANOCARGADESCARGAS.VEICULO 
Inner Join GLOP_VIAGEMPARADAS					On GLOP_VIAGEMPARADAS.HANDLE					= GLGV_PLANOCARGADESCARGAS.PARADA
Inner Join GLGL_FILIAIS						    On GLGL_FILIAIS.HANDLE							= GLGV_PLANOCARGADESCARGAS.FILIAL
Inner Join FILIAIS								On FILIAIS.HANDLE								= GLGL_FILIAIS.FILIAL
Inner Join FILIAIS FILO							On FILO.HANDLE								    = GLOP_VIAGENS.FILIALORIGEM
Inner Join GLGV_PROCESSOS						On GLGV_PROCESSOS.PLANOCARGADESCARGA			= GLGV_PLANOCARGADESCARGAS.HANDLE
LEFT JOIN GLOP_VIAGEMDOCUMENTOS                 On GLOP_VIAGEMDOCUMENTOS.VIAGEM		= GLOP_VIAGEMPARADAS.VIAGEM
												   And GLOP_VIAGEMDOCUMENTOS.PARADA		= GLOP_VIAGEMPARADAS.HANDLE
LEFT JOIN GLGL_DOCUMENTOS						On GLGL_DOCUMENTOS.HANDLE						= GLOP_VIAGEMDOCUMENTOS.DOCUMENTOLOGISTICA
Inner Join FILIAIS FILD							On FILD.HANDLE								    = GLGL_DOCUMENTOS.FILIALENTREGA
LEFT JOIN GLGL_PESSOAS P ON GLGL_DOCUMENTOS.DESTINATARIO = P.PESSOA
LEFT JOIN GLGL_PESSOACONFIGURACOES PC ON P.HANDLE = PC.PESSOALOGISTICA
LEFT JOIN K_GLOP_VEICULOPOSICOES				On K_GLOP_VEICULOPOSICOES.HANDLE	= (Select Max(X.HANDLE)
																				 From K_GLOP_VEICULOPOSICOES X
																				Where X.VEICULO		= GLOP_VIAGENS.VEICULO1
																				  And X.DATAHORA	= (Select Max(Y.DATAHORA) 
																										 From K_GLOP_VEICULOPOSICOES Y
																										Where Y.VEICULO		= X.VEICULO))
LEFT JOIN GLGL_ENUMERACAOITEMS EI ON EI.CODIGO = GLOP_VIAGEMDOCUMENTOS.SITUACAO
LEFT JOIN GLGL_DOCUMENTOASSOCIADOS DCA ON DCA.DOCUMENTOLOGISTICA = GLGL_DOCUMENTOS.HANDLE
LEFT JOIN GLGL_DOCUMENTOCLIENTES DC ON DCA.DOCUMENTOCLIENTE = DC.HANDLE
LEFT JOIN GLGV_ETIQUETAS E ON DC.HANDLE = E.DOCUMENTOCLIENTE
LEFT JOIN GLOP_REGIAOATENDIMENTOROTAS RGT ON E.ROTA = RGT.HANDLE

WHERE 1=1
And Cast(GLGV_PLANOCARGADESCARGAS.DATAABERTURA	As Date)	Between dateadd(dd,-3, getdate())
And getdate()
And GLOP_VIAGENS.FILIALDESTINO =2
AND PC.K_MENSAGEMCLIENTEAGENDADO = 'S'
AND GLGL_DOCUMENTOS.FILIALENTREGA = 2

UNION ALL

SELECT
	'' AS UMEROVIAGEM
	,'' AS PLACANUMERO
	,'' AS [Rota Entrega]
	,'' AS CEPDESTINO
	,'' AS FILIALORIGEM
	,'' AS LONGITUDEORIGEM
	,'' AS LATITUDEORIGEM
	,'' AS FILIALDESTINO
	,'' AS LONGITUDEDESTINO
	,'' AS LATITUDEDESTINO
	,'' AS [Número Documento]
	,'' AS [Status]
	,'' AS [Previsão Entrega]
	,'' AS [Previsão Entrega Horas]
	,'' AS [Peso Real]
	,'' AS [Qtd. Volumes]
	,'' AS [Frete]
	,'' AS [Previsao Chegada]
	,'' AS [Previsao Chegada Hora]
	,F.NOME AS NOMEFILIAL
	,CONVERT(SMALLDATETIME, CONVERT(VARCHAR(13), GETDATE(), 120)+ ':00:00.000') AS DATAHORAPOERTAPALLET
	,SUM(TOTENDERECO) AS TOTENDERECO
	,SUM(TOTOCUPADO) AS TOTOCUPADO
	,ROUND(((CAST(SUM(NULLIF(TOTOCUPADO,0)) AS DECIMAL)*100)/(CAST(SUM(NULLIF(TOTENDERECO,0)) AS DECIMAL))),2) AS TOTALPERCOCUPADO
	,SUM(TOTLIVRE) AS TOTLIVRE
	,ROUND(((CAST(SUM(NULLIF(TOTLIVRE,0)) AS DECIMAL)*100)/(CAST(SUM(NULLIF(TOTENDERECO,0)) AS DECIMAL))),2) AS TOTALPERCLIVRE
	,SUM(TOT_DOC) AS TOT_DOC
	,SUM(TOT_VOL) AS TOT_VOL
	,ROUND(SUM(TOT_PESO),2) AS TOT_PESO
	,ROUND(SUM(TOT_VAL),2) AS TOT_VAL

FROM (


SELECT 
	FILIAL
	,CAST(GETDATE() AS DATE) AS [DATA]
	,'' AS DOC
	,COUNT(1) TOTENDERECO
	,0 AS TOTOCUPADO
	,0 AS TOTLIVRE
	,0 AS TOT_DOC
	,0 AS TOT_VOL
	,0 AS TOT_PESO
	,0 AS TOT_VAL 
FROM [dbo].K_PORTAPALETEENDERECOS A 
WHERE NOT EXISTS (SELECT 1 FROM [dbo].K_PORTAPALETEENDERECOS B WHERE A.HANDLE = B.NIVELSUPERIOR)
--AND  FILIAL = 2 
AND A.ATIVO = 'S'

GROUP BY FILIAL

UNION ALL

SELECT 
	FILIAL
	,CAST(GETDATE() AS DATE) AS [DATA]
	,'' AS DOC
	,0 AS TOTENDERECO
	,COUNT(1) TOTOCUPADO 
	,0 AS TOTLIVRE
	,0 AS TOT_DOC
	,0 AS TOT_VOL
	,0 AS TOT_PESO
	,0 AS TOT_VAL


	
FROM [dbo].K_PORTAPALETEENDERECOS A 
WHERE NOT EXISTS (SELECT 1 FROM [dbo].K_PORTAPALETEENDERECOS B WHERE A.HANDLE = B.NIVELSUPERIOR)
AND EXISTS (SELECT 1 FROM [dbo].K_PORTAPALETEDOCUMENTOS B WHERE A.HANDLE = B.ENDERECOATIVO) 
--AND  FILIAL = 2 
AND A.ATIVO = 'S'

GROUP BY FILIAL

UNION ALL

SELECT 
	FILIAL
	,CAST(GETDATE() AS DATE) AS [DATA]
	,'' AS DOC
	,0 AS TOTENDERECO
	,0 AS TOTOCUPADO 
	,COUNT(1) TOTLIVRE 
	,0 AS TOT_DOC
	,0 AS TOT_VOL
	,0 AS TOT_PESO
	,0 AS TOT_VAL

FROM [dbo].K_PORTAPALETEENDERECOS A 
WHERE NOT EXISTS (SELECT 1 FROM [dbo].K_PORTAPALETEENDERECOS B WHERE A.HANDLE = B.NIVELSUPERIOR)
AND NOT EXISTS (SELECT 1 FROM [dbo].K_PORTAPALETEDOCUMENTOS B WHERE A.HANDLE = B.ENDERECOATIVO)
--AND  FILIAL = 2 
AND A.ATIVO = 'S'

GROUP BY FILIAL 

UNION ALL

SELECT 
	FILIAL
	,CAST(GETDATE() AS DATE) AS [DATA]
	,DOC
	,0 AS TOTENDERECO
	,0 AS TOTOCUPADO 
	,0 AS TOTLIVRE
	,SUM(TOT_DOC) TOT_DOC
	,SUM(TOT_VOL) TOT_VOL
	,SUM(TOT_PESO) TOT_PESO
	,SUM(TOT_VAL) TOT_VAL                                               

FROM (                                                              
SELECT 1 TOT_DOC,(C.DOCCLIVOLUME) TOT_VOL                           
,(C.DOCCLIPESOCONSIDERADO) TOT_PESO,(C.DOCCLIVALORTOTAL) TOT_VAL, A.FILIAL, C.NUMERO AS DOC   
FROM [dbo].K_PORTAPALETEENDERECOS A                                       
INNER JOIN [dbo].K_PORTAPALETEDOCUMENTOS B ON (A.HANDLE = B.ENDERECOATIVO)
INNER JOIN [dbo].GLGL_DOCUMENTOS C ON (C.HANDLE = B.DOCUMENTOLOGISTICA)   
WHERE 1=1
--AND A.FILIAL = 2 

AND A.ATIVO = 'S'

GROUP BY C.DOCCLIVOLUME,C.DOCCLIPESOCONSIDERADO,C.HANDLE  ,C.DOCCLIVALORTOTAL, A.FILIAL,C.NUMERO
) AS T

GROUP BY FILIAL, DOC

) AS TABELAFINAL
INNER JOIN [dbo].FILIAIS F 
	ON FILIAL = F.HANDLE
WHERE F.HANDLE = 2

GROUP BY FILIAL
		,F.NOME