DECLARE @CONTRATOFRETE INT = 1336854

SELECT DISTINCT 
	ISNULL(D2.HANDLE,D.HANDLE) HANDLE
	,ISNULL(D.NUMERO, CP.NUMERO) AS 'NUMERO/COLETA'
	,PREM.NOME AS 'REMETENTE'
	,BREM.NOME AS BAIRROREMETENTE
	,CONCAT(MUREM.NOME,'-',ESREM.SIGLA) AS MUNICIPIO
	,PDES.NOME AS DESTINATARIO
	,BDES.NOME AS BAIRRODEST
	,CONCAT(MUDES.NOME,'-',ESDES.SIGLA) AS MUNICIPIODEST
	,D.DOCCLIVOLUME AS VOLUME
	,CASE WHEN D.DOCCLIPESOCUBADOTOTAL > D.DOCCLIPESOTOTAL THEN D.DOCCLIPESOCUBADOTOTAL ELSE D.DOCCLIPESOTOTAL END PESO
	,D.VALORCONTABIL FRETEBRUTO
	,CASE WHEN TRIB.VALORICMS > 0 THEN TRIB.VALORICMS ELSE
           CASE WHEN TRIB.VALORICMSST > 0 THEN TRIB.VALORICMSST ELSE
             CASE WHEN TRIB.VALORICMSOUTRAUF > 0 THEN TRIB.VALORICMSOUTRAUF
             END
             END
             END ICMS
	,CASE WHEN TRIB.VALORICMS > 0 THEN D.VALORCONTABIL-TRIB.VALORICMS ELSE
           CASE WHEN TRIB.VALORICMSST > 0 THEN D.VALORCONTABIL-TRIB.VALORICMSST ELSE
             CASE WHEN TRIB.VALORICMSOUTRAUF > 0 THEN D.VALORCONTABIL-TRIB.VALORICMSOUTRAUF ELSE
               D.VALORCONTABIL
             END
             END
             END FRETELIQUIDO
	,CASE
		WHEN CONTRATOCALC.CLASSIFICACAO IN (9) THEN CONTRATOCALC.VALORFINALICMS
	ELSE 0
	END AS PRODUTIVIDADEKG
	,CASE
		WHEN CONTRATOCALC.COMPONENTETARIFA IN(65759,69589,68804,68808) 
			THEN (
					CASE WHEN TRIB.VALORICMS > 0 THEN TRIB.VALORICMS ELSE
					   CASE WHEN TRIB.VALORICMSST > 0 THEN TRIB.VALORICMSST ELSE
						 CASE WHEN TRIB.VALORICMSOUTRAUF > 0 THEN TRIB.VALORICMSOUTRAUF
						 END
						 END
						 END
				 )
	ELSE 0
	END AS PRODUTIVIDADEPERC
	,TAF.NOME TARIFA
	,C.DOCUMENTOLOGISTICA
	,MO.CODIGO
	,MO.DESCRICAO
	,MO.PADRAO
	,MO.PAGARFORNECEDOR 
	,MO.DESCONTOFORNECEDOR
	,ISNULL(TP.NOME, 'COLETA') AS 'TIPO DOCUMENTO'
	
FROM GLOP_CONTRATOFRETES CONTRATO
INNER JOIN GLOP_CONTRFRETDOCCALCULOS CONTRATOCALC ON CONTRATO.HANDLE = CONTRATOCALC.CONTRATOFRETE 
	AND ((CONTRATOCALC.CLASSIFICACAO IN (9)) OR (CONTRATOCALC.COMPONENTETARIFA IN (64034,64404,69589,68804,68808)))
INNER JOIN GLGL_DOCUMENTOS D ON CONTRATOCALC.DOCUMENTOLOGISTICA = D.HANDLE
LEFT JOIN GLOP_COLETAPEDIDOS CP ON CONTRATOCALC.PEDIDOCOLETA = CP.HANDLE
LEFT JOIN GLGL_TIPODOCUMENTOS TP ON TP.HANDLE = D.TIPODOCUMENTO
LEFT JOIN GLGL_DOCUMENTOASSOCIADOS DA ON D.HANDLE = DA.DOCUMENTOLOGISTICA
LEFT JOIN GN_PESSOAS PREM ON D.REMETENTE = PREM.HANDLE
LEFT JOIN GLGL_PESSOAENDERECOS EREM ON EREM.HANDLE = D.ORIGEMENDERECO
LEFT JOIN BAIRROS BREM ON BREM.HANDLE = EREM.BAIRRO
LEFT JOIN MUNICIPIOS MUREM ON MUREM.HANDLE = EREM.MUNICIPIO
LEFT JOIN ESTADOS ESREM ON ESREM.HANDLE = MUREM.ESTADO
LEFT JOIN GN_PESSOAS PDES ON D.DESTINATARIO = PDES.HANDLE
LEFT JOIN GLGL_PESSOAENDERECOS EDES ON EDES.HANDLE = D.DESTINATARIOENDERECO
LEFT JOIN BAIRROS BDES ON BDES.HANDLE = EDES.BAIRRO
LEFT JOIN MUNICIPIOS MUDES ON MUDES.HANDLE = EDES.MUNICIPIO
LEFT JOIN ESTADOS ESDES ON ESDES.HANDLE = MUDES.ESTADO
LEFT  JOIN GLCM_LEIAUTETARIFAS TAF ON TAF.HANDLE = CONTRATOCALC.LEIAUTETARIFA
LEFT  JOIN GLGL_DOCUMENTOS D2 ON D2.HANDLE = D.DOCUMENTOLOGISTICA AND (D2.TIPODOCUMENTO = 2 OR (D2.TIPODOCUMENTO = 6 AND D2.TIPORPS = 322))
LEFT JOIN GLGL_DOCUMENTOTRIBUTOS TRIB ON TRIB.DOCUMENTO = ISNULL(D2.HANDLE,D.HANDLE)
LEFT JOIN GLOP_VIAGEMDOCUMENTOS C ON C.DOCUMENTOLOGISTICA = D.HANDLE 
LEFT JOIN GLOP_MOTIVOOCORRENCIAS MO ON C.MOTIVOOCORRENCIA = MO.HANDLE




WHERE CONTRATO.HANDLE = @CONTRATOFRETE
AND MO.CODIGO IS NOT NULL

--AND CONTRATOCALC.CLASSIFICACAO IN (9)
--AND CONTRATOCALC.COMPONENTETARIFA IN (64034,64404,69589,68804,68808)

ORDER BY 1
