--=============================================================================================================================
-- Drop de tabelas
--=============================================================================================================================
DROP TABLE IF EXISTS #TempDados
DROP TABLE IF EXISTS #TempDadosAVG


--=============================================================================================================================
-- Valores TempDados D-10
--=============================================================================================================================
SELECT 
	   --colaborador_NAME,
	   REPLACE(REPLACE(colaborador_identification,'.',''),'-','') AS colaborador_identification,
	   [Indicador que ele será avalidado(ID)] AS indicador_identification,
	   ROUND(SUM(resultado),2) AS resultado,
	   ROUND(SUM(ISNULL(fator_0,0)),2) AS fator_0,
	   fator_1 AS fator_1,
	   fator_2 AS fator_2,
	   fator_3 AS fator_3,
	   fator_4 AS fator_4,
	   fator_5 AS fator_5,
	   fator_6 AS fator_6,
	   fator_7 AS fator_7,
	   fator_8 AS fator_8,
	   fator_9 AS fator_9,
	   fator_10 AS fator_10,
	   [DATA]
INTO #TempDados
FROM (
	SELECT DISTINCT 
		   P5.NOME AS colaborador_NAME,
		   CPF.CGCCPF AS colaborador_identification,
		   101 AS [Indicador que ele será avalidado(ID)],
		   CFS.VALORFRETE AS resultado,
		   '' AS fator_0,
		   '' AS fator_1,
		   '' AS fator_2,
		   '' AS fator_3,
		   '' AS fator_4,
		   '' AS fator_5,
		   '' AS fator_6,
		   '' AS fator_7,
		   '' AS fator_8,
		   '' AS fator_9,
		   '' AS fator_10,
		   CAST(CF.DATAINCLUSAO AS DATE) AS [DATA]

	FROM GLCM_COTACOES CF
	LEFT JOIN GLCM_COTACAOSERVICOS CFS ON CFS.COTACAO = CF.HANDLE
	LEFT JOIN GLCR_CLIENTEPOTENCIAL CP ON CP.HANDLE = CF.CLIENTEPOTENCIAL
	LEFT JOIN GN_PESSOAS C ON C.HANDLE = CF.PESSOA
	LEFT JOIN GLGL_ENUMERACAOITEMS TOMADORSERVICO ON TOMADORSERVICO.HANDLE = CF.TOMADORSERVICO
	LEFT JOIN GN_PESSOAS P1 ON P1.HANDLE = CF.PARTICIPANTECLIENTE1
	LEFT JOIN GLGL_ENUMERACAOITEMS PARTICIPANTE1 ON PARTICIPANTE1.HANDLE = CF.PARTICIPANTETIPO1
	LEFT JOIN GN_PESSOAS P2 ON P2.HANDLE = CF.PARTICIPANTECLIENTE2
	LEFT JOIN GLGL_ENUMERACAOITEMS PARTICIPANTE2 ON PARTICIPANTE2.HANDLE = CF.PARTICIPANTETIPO2
	LEFT JOIN GN_PESSOAS P3 ON P3.HANDLE = CF.PARTICIPANTECLIENTE3
	LEFT JOIN GLGL_ENUMERACAOITEMS PARTICIPANTE3 ON PARTICIPANTE3.HANDLE = CF.PARTICIPANTETIPO3
	LEFT JOIN GLGL_LOCALIDADES LO ON LO.HANDLE = CF.ORIGEM
	LEFT JOIN MUNICIPIOS MUNO ON MUNO.HANDLE = LO.MUNICIPIO
	LEFT JOIN GLGL_ENUMERACAOITEMS TIPOLO ON TIPOLO.HANDLE = LO.TIPO
	LEFT JOIN GLGL_LOCALIDADES LD ON LD.HANDLE = CF.DESTINO
	LEFT JOIN MUNICIPIOS MUND ON MUND.HANDLE = LD.MUNICIPIO
	LEFT JOIN GLGL_ENUMERACAOITEMS TIPOLD ON TIPOLD.HANDLE = LD.TIPO
	LEFT JOIN Z_GRUPOUSUARIOS U ON U.HANDLE = CF.USUARIOINCLUIU
	LEFT JOIN FILIAIS FINCLUSAO ON FINCLUSAO.HANDLE = CF.FILIAL
	LEFT JOIN FILIAIS FCOTACAO ON FCOTACAO.HANDLE = CF.FILIALCOTACAO
	LEFT JOIN FILIAIS FENTREGA ON FENTREGA.HANDLE = CF.FILIALENTREGA
	LEFT JOIN GLGL_DOCUMENTOS ON GLGL_DOCUMENTOS.COTACAO = CF.HANDLE
	LEFT JOIN GN_PESSOAS P4 ON P4.HANDLE = C.AGENTEVENDAS AND P4.EHAGENTEVENDAS = 'S'
	LEFT JOIN Z_GRUPOUSUARIOS P5 ON CF.USUARIOINCLUIU = P5.HANDLE
	LEFT JOIN GN_PESSOAS CPF ON P5.PESSOA = CPF.HANDLE
	WHERE CF.DATAINCLUSAO >= DATEADD(DD, -10,CAST(GETDATE() AS DATE))
	AND CF.DATAINCLUSAO < DATEADD(DD, -9,CAST(GETDATE() AS DATE))
	AND CF.STATUS in (6,7) --cotacoes finalizadas / Cotacao vinculada

	UNION ALL

	SELECT DISTINCT 
		   P5.NOME AS colaborador_NAME,
		   CPF.CGCCPF AS colaborador_identification,
		   101 AS [Indicador que ele será avalidado(ID)],
		   0 AS resultado,
		   CFS.VALORFRETE AS fator_0,
		   '' AS fator_1,
		   '' AS fator_2,
		   '' AS fator_3,
		   '' AS fator_4,
		   '' AS fator_5,
		   '' AS fator_6,
		   '' AS fator_7,
		   '' AS fator_8,
		   '' AS fator_9,
		   '' AS fator_10,
		   CAST(CF.DATAINCLUSAO AS DATE) AS [DATA]

	FROM GLCM_COTACOES CF
	LEFT JOIN GLCM_COTACAOSERVICOS CFS ON CFS.COTACAO = CF.HANDLE
	LEFT JOIN GLCR_CLIENTEPOTENCIAL CP ON CP.HANDLE = CF.CLIENTEPOTENCIAL
	LEFT JOIN GN_PESSOAS C ON C.HANDLE = CF.PESSOA
	LEFT JOIN GLGL_ENUMERACAOITEMS TOMADORSERVICO ON TOMADORSERVICO.HANDLE = CF.TOMADORSERVICO
	LEFT JOIN GN_PESSOAS P1 ON P1.HANDLE = CF.PARTICIPANTECLIENTE1
	LEFT JOIN GLGL_ENUMERACAOITEMS PARTICIPANTE1 ON PARTICIPANTE1.HANDLE = CF.PARTICIPANTETIPO1
	LEFT JOIN GN_PESSOAS P2 ON P2.HANDLE = CF.PARTICIPANTECLIENTE2
	LEFT JOIN GLGL_ENUMERACAOITEMS PARTICIPANTE2 ON PARTICIPANTE2.HANDLE = CF.PARTICIPANTETIPO2
	LEFT JOIN GN_PESSOAS P3 ON P3.HANDLE = CF.PARTICIPANTECLIENTE3
	LEFT JOIN GLGL_ENUMERACAOITEMS PARTICIPANTE3 ON PARTICIPANTE3.HANDLE = CF.PARTICIPANTETIPO3
	LEFT JOIN GLGL_LOCALIDADES LO ON LO.HANDLE = CF.ORIGEM
	LEFT JOIN MUNICIPIOS MUNO ON MUNO.HANDLE = LO.MUNICIPIO
	LEFT JOIN GLGL_ENUMERACAOITEMS TIPOLO ON TIPOLO.HANDLE = LO.TIPO
	LEFT JOIN GLGL_LOCALIDADES LD ON LD.HANDLE = CF.DESTINO
	LEFT JOIN MUNICIPIOS MUND ON MUND.HANDLE = LD.MUNICIPIO
	LEFT JOIN GLGL_ENUMERACAOITEMS TIPOLD ON TIPOLD.HANDLE = LD.TIPO
	LEFT JOIN Z_GRUPOUSUARIOS U ON U.HANDLE = CF.USUARIOINCLUIU
	LEFT JOIN FILIAIS FINCLUSAO ON FINCLUSAO.HANDLE = CF.FILIAL
	LEFT JOIN FILIAIS FCOTACAO ON FCOTACAO.HANDLE = CF.FILIALCOTACAO
	LEFT JOIN FILIAIS FENTREGA ON FENTREGA.HANDLE = CF.FILIALENTREGA
	LEFT JOIN GLGL_DOCUMENTOS ON GLGL_DOCUMENTOS.COTACAO = CF.HANDLE
	LEFT JOIN GN_PESSOAS P4 ON P4.HANDLE = C.AGENTEVENDAS AND P4.EHAGENTEVENDAS = 'S'
	LEFT JOIN Z_GRUPOUSUARIOS P5 ON CF.USUARIOINCLUIU = P5.HANDLE
	LEFT JOIN GN_PESSOAS CPF ON P5.PESSOA = CPF.HANDLE
	WHERE CF.DATAINCLUSAO >= DATEADD(DD, -10,CAST(GETDATE() AS DATE))
	AND CF.DATAINCLUSAO < DATEADD(DD, -9,CAST(GETDATE() AS DATE))

) AS TEMP


WHERE REPLACE(REPLACE(colaborador_identification,'.',''),'-','') IN (
'90941420582'
,'31978702809'
,'10393367606'
,'05189394646'
,'10885833694'
,'01625270208'
,'03346435547'
,'38388819828'
,'07680142980'
,'16033860764'
,'05942288674'
,'13642347851'
,'14024970755'
,'01997107678'
,'09937947936'
,'11012152677'
,'04179896524'
,'10548782695'
,'08514862901'
,'12872134646'
,'11329465652'
,'43259828842'
,'04319181638'
,'13121760670'
,'08969107681'
,'02962035051'
,'03119563781'
,'15178961773'
,'33738337873'
,'01468024701'
,'41696008867'
,'47773997888'
,'33635494828'
,'04419709588'
,'31109001819'
,'05853762710'
,'12158808713'
,'03294646631'
,'98010271691'
)

GROUP BY --colaborador_NAME,
	   REPLACE(REPLACE(colaborador_identification,'.',''),'-',''),
	   fator_1,
	   fator_2,
	   fator_3,
	   fator_4,
	   fator_5,
	   fator_6,
	   fator_7,
	   fator_8,
	   fator_9,
	   fator_10,
	   [Indicador que ele será avalidado(ID)],
	   [DATA]


--=============================================================================================================================
-- Valores TempDadosAVG
--=============================================================================================================================
SELECT DISTINCT 
	
		   REPLACE(REPLACE(colaborador_identification,'.',''),'-','') AS colaborador_identification,
		   [Indicador que ele será avalidado(ID)],
		   resultado,
		   fator_0,
		   ROUND(SUM(distinct fator_1)/COUNT(DISTINCT [DATA]),2) AS fator_1,
		   fator_2,
		   fator_3,
		   fator_4,
		   fator_5,
		   fator_6,
		   fator_7,
		   fator_8,
		   fator_9,
		   fator_10,
		   '' AS [DATA]
INTO #TempDadosAVG	
FROM (

SELECT DISTINCT 
		   P5.NOME AS colaborador_NAME,
		   CPF.CGCCPF AS colaborador_identification,
		   101 AS [Indicador que ele será avalidado(ID)],
		   '' AS resultado,
		   '' AS fator_0,
		   ROUND(SUM(CFS.VALORFRETE),2) AS fator_1,
		   '' AS fator_2,
		   '' AS fator_3,
		   '' AS fator_4,
		   '' AS fator_5,
		   '' AS fator_6,
		   '' AS fator_7,
		   '' AS fator_8,
		   '' AS fator_9,
		   '' AS fator_10,
		   MONTH(CF.DATAINCLUSAO) AS [DATA]

	FROM GLCM_COTACOES CF
	LEFT JOIN GLCM_COTACAOSERVICOS CFS ON CFS.COTACAO = CF.HANDLE
	LEFT JOIN GLCR_CLIENTEPOTENCIAL CP ON CP.HANDLE = CF.CLIENTEPOTENCIAL
	LEFT JOIN GN_PESSOAS C ON C.HANDLE = CF.PESSOA
	LEFT JOIN GLGL_ENUMERACAOITEMS TOMADORSERVICO ON TOMADORSERVICO.HANDLE = CF.TOMADORSERVICO
	LEFT JOIN GN_PESSOAS P1 ON P1.HANDLE = CF.PARTICIPANTECLIENTE1
	LEFT JOIN GLGL_ENUMERACAOITEMS PARTICIPANTE1 ON PARTICIPANTE1.HANDLE = CF.PARTICIPANTETIPO1
	LEFT JOIN GN_PESSOAS P2 ON P2.HANDLE = CF.PARTICIPANTECLIENTE2
	LEFT JOIN GLGL_ENUMERACAOITEMS PARTICIPANTE2 ON PARTICIPANTE2.HANDLE = CF.PARTICIPANTETIPO2
	LEFT JOIN GN_PESSOAS P3 ON P3.HANDLE = CF.PARTICIPANTECLIENTE3
	LEFT JOIN GLGL_ENUMERACAOITEMS PARTICIPANTE3 ON PARTICIPANTE3.HANDLE = CF.PARTICIPANTETIPO3
	LEFT JOIN GLGL_LOCALIDADES LO ON LO.HANDLE = CF.ORIGEM
	LEFT JOIN MUNICIPIOS MUNO ON MUNO.HANDLE = LO.MUNICIPIO
	LEFT JOIN GLGL_ENUMERACAOITEMS TIPOLO ON TIPOLO.HANDLE = LO.TIPO
	LEFT JOIN GLGL_LOCALIDADES LD ON LD.HANDLE = CF.DESTINO
	LEFT JOIN MUNICIPIOS MUND ON MUND.HANDLE = LD.MUNICIPIO
	LEFT JOIN GLGL_ENUMERACAOITEMS TIPOLD ON TIPOLD.HANDLE = LD.TIPO
	LEFT JOIN Z_GRUPOUSUARIOS U ON U.HANDLE = CF.USUARIOINCLUIU
	LEFT JOIN FILIAIS FINCLUSAO ON FINCLUSAO.HANDLE = CF.FILIAL
	LEFT JOIN FILIAIS FCOTACAO ON FCOTACAO.HANDLE = CF.FILIALCOTACAO
	LEFT JOIN FILIAIS FENTREGA ON FENTREGA.HANDLE = CF.FILIALENTREGA
	LEFT JOIN GLGL_DOCUMENTOS ON GLGL_DOCUMENTOS.COTACAO = CF.HANDLE
	LEFT JOIN GN_PESSOAS P4 ON P4.HANDLE = C.AGENTEVENDAS AND P4.EHAGENTEVENDAS = 'S'
	LEFT JOIN Z_GRUPOUSUARIOS P5 ON CF.USUARIOINCLUIU = P5.HANDLE
	LEFT JOIN GN_PESSOAS CPF ON P5.PESSOA = CPF.HANDLE
	WHERE CF.DATAINCLUSAO >= '2020-01-01'
	AND CF.DATAINCLUSAO < '2020-03-01'
	AND CF.STATUS in (6,7)

	GROUP BY P5.NOME,
		   CPF.CGCCPF,
		   MONTH(CF.DATAINCLUSAO)

	UNION ALL

	SELECT DISTINCT 
		   P5.NOME AS colaborador_NAME,
		   CPF.CGCCPF AS colaborador_identification,
		   101 AS [Indicador que ele será avalidado(ID)],
		   '' AS resultado,
		   '' AS fator_0,
		   ROUND(SUM(CFS.VALORFRETE),2) AS fator_1,
		   '' AS fator_2,
		   '' AS fator_3,
		   '' AS fator_4,
		   '' AS fator_5,
		   '' AS fator_6,
		   '' AS fator_7,
		   '' AS fator_8,
		   '' AS fator_9,
		   '' AS fator_10,
		   MONTH(CF.DATAINCLUSAO) AS [DATA]

	FROM GLCM_COTACOES CF
	LEFT JOIN GLCM_COTACAOSERVICOS CFS ON CFS.COTACAO = CF.HANDLE
	LEFT JOIN GLCR_CLIENTEPOTENCIAL CP ON CP.HANDLE = CF.CLIENTEPOTENCIAL
	LEFT JOIN GN_PESSOAS C ON C.HANDLE = CF.PESSOA
	LEFT JOIN GLGL_ENUMERACAOITEMS TOMADORSERVICO ON TOMADORSERVICO.HANDLE = CF.TOMADORSERVICO
	LEFT JOIN GN_PESSOAS P1 ON P1.HANDLE = CF.PARTICIPANTECLIENTE1
	LEFT JOIN GLGL_ENUMERACAOITEMS PARTICIPANTE1 ON PARTICIPANTE1.HANDLE = CF.PARTICIPANTETIPO1
	LEFT JOIN GN_PESSOAS P2 ON P2.HANDLE = CF.PARTICIPANTECLIENTE2
	LEFT JOIN GLGL_ENUMERACAOITEMS PARTICIPANTE2 ON PARTICIPANTE2.HANDLE = CF.PARTICIPANTETIPO2
	LEFT JOIN GN_PESSOAS P3 ON P3.HANDLE = CF.PARTICIPANTECLIENTE3
	LEFT JOIN GLGL_ENUMERACAOITEMS PARTICIPANTE3 ON PARTICIPANTE3.HANDLE = CF.PARTICIPANTETIPO3
	LEFT JOIN GLGL_LOCALIDADES LO ON LO.HANDLE = CF.ORIGEM
	LEFT JOIN MUNICIPIOS MUNO ON MUNO.HANDLE = LO.MUNICIPIO
	LEFT JOIN GLGL_ENUMERACAOITEMS TIPOLO ON TIPOLO.HANDLE = LO.TIPO
	LEFT JOIN GLGL_LOCALIDADES LD ON LD.HANDLE = CF.DESTINO
	LEFT JOIN MUNICIPIOS MUND ON MUND.HANDLE = LD.MUNICIPIO
	LEFT JOIN GLGL_ENUMERACAOITEMS TIPOLD ON TIPOLD.HANDLE = LD.TIPO
	LEFT JOIN Z_GRUPOUSUARIOS U ON U.HANDLE = CF.USUARIOINCLUIU
	LEFT JOIN FILIAIS FINCLUSAO ON FINCLUSAO.HANDLE = CF.FILIAL
	LEFT JOIN FILIAIS FCOTACAO ON FCOTACAO.HANDLE = CF.FILIALCOTACAO
	LEFT JOIN FILIAIS FENTREGA ON FENTREGA.HANDLE = CF.FILIALENTREGA
	LEFT JOIN GLGL_DOCUMENTOS ON GLGL_DOCUMENTOS.COTACAO = CF.HANDLE
	LEFT JOIN GN_PESSOAS P4 ON P4.HANDLE = C.AGENTEVENDAS AND P4.EHAGENTEVENDAS = 'S'
	LEFT JOIN Z_GRUPOUSUARIOS P5 ON CF.USUARIOINCLUIU = P5.HANDLE
	LEFT JOIN GN_PESSOAS CPF ON P5.PESSOA = CPF.HANDLE
	WHERE CF.DATAINCLUSAO >= '2020-01-01'
	AND CF.DATAINCLUSAO < '2020-03-01'


	GROUP BY P5.NOME,
		   CPF.CGCCPF,
		   MONTH(CF.DATAINCLUSAO)
) AS T

WHERE REPLACE(REPLACE(colaborador_identification,'.',''),'-','') IN (
'90941420582'
,'31978702809'
,'10393367606'
,'05189394646'
,'10885833694'
,'01625270208'
,'03346435547'
,'38388819828'
,'07680142980'
,'16033860764'
,'05942288674'
,'13642347851'
,'14024970755'
,'01997107678'
,'09937947936'
,'11012152677'
,'04179896524'
,'10548782695'
,'08514862901'
,'12872134646'
,'11329465652'
,'43259828842'
,'04319181638'
,'13121760670'
,'08969107681'
,'02962035051'
,'03119563781'
,'15178961773'
,'33738337873'
,'01468024701'
,'41696008867'
,'47773997888'
,'33635494828'
,'04419709588'
,'31109001819'
,'05853762710'
,'12158808713'
,'03294646631'
,'98010271691'

--'03294646631'

)

GROUP BY 
		 colaborador_identification,
		   [Indicador que ele será avalidado(ID)],
		   resultado,
		   fator_0,
		   fator_2,
		   fator_3,
		   fator_4,
		   fator_5,
		   fator_6,
		   fator_7,
		   fator_8,
		   fator_9,
		   fator_10

--==========================================================================================================================================================================
-- Consulta dos Resultados.
--==========================================================================================================================================================================
SELECT 

	A.colaborador_identification,
	A.[indicador_identification],
	A.resultado,
	A.fator_0,
	B.fator_1,
	A.fator_2,
	A.fator_3,
	A.fator_4,
	A.fator_5,
	A.fator_6,
	A.fator_7,
	A.fator_8,
	A.fator_9,
	A.fator_10,
	A.[DATA]

FROM #TempDados A
INNER JOIN #TempDadosAVG B ON A.colaborador_identification = B.colaborador_identification

