Private Function ObterValorFreteMinimo(handleViagem As Long) As Double
	Dim vEntity As Variant

	Dim bs As CSBusinessComponent

	Set bs = BusinessComponent.CreateInstance("Patrus.Logistica.GL.Operacional.LimiteViagem.Services.ViagemLimiteService,Patrus.Logistica.GL")

	bs.AddParameter(pdtInteger,handleViagem)

	Set vEntity = bs.Execute("ObterSituacaoPelaViagemProxy").CurrentEntityProxy

	ObterValorFreteMinimo = vEntity.GetDecimal("VALORMINIMO")
End Function

' Usar ValorCampo("CAMPO") para ler o valor do registro atual.
' Usar CampoNulo("CAMPO") para saber se o campo é nulo ou não
' Usar ValorFiltro("CAMPO") para ler os valores dos filtros ou valores de parâmetros informados por outra consulta.

Public Sub OnSelectRecord
       ' Implementar o que deve ser feito quando a linha for selecionada com <ENTER> ou <duplo-clique>
End Sub

Public Sub CreateData
       ' Evento para criar Query de Dados, etc. 
End Sub

Public Sub DestroyData
       ' Evento para Destruir os dados criados pelo evento CreateData 
End Sub

Public Sub OnCalcFields
       ' Este evento permite calcular o valor de campos não físicos. 
       ' Sua execução ocorre uma vez para cada linha de resultado.
	ValorCampo("FRETEMINIMO") = ObterValorFreteMinimo(ValorCampo("HANDLE"))
	ValorCampo("DIFERENCAFRETE") = CDbl(ValorCampo("FRETEMINIMO")) - CDbl(ValorCampo("TOTALFRETE"))

	If(CDbl(ValorCampo("TOTALFRETE")) > 0) Then
		ValorCampo("DIFERENCAFRETEPERCENT") = (CDbl(ValorCampo("FRETEMINIMO")) / CDbl(ValorCampo("TOTALFRETE"))) * 100
	End If
End Sub

Public Function CheckFilter As String
       ' Utilizar este campo para validar os parâmetros 
       ' Se existir alguma exceção, utilizar o resultado com a mensagem de crítica.
       ' Ex: CheckFilter = "A data final deve ser menor que a data final!"
       ' Caso contrário manter o resultado em branco para não gerar exceção.
If ValorFiltro("DATAI") = "" And ValorFiltro("DATAF") = "" And ValorFiltro("DATACFI") = "" And ValorFiltro("DATACFF") = "" Then
	CheckFilter = "Preencha ao menos um dos períodos."
End If

End Function

Public Sub SetParameters
       ' Este evento é executado se algum parâmetro da query não for preenchido 
       ' pelos parâmetros ou filtros. Para ajustar o valor de um parâmetros, utilizar: 
       ' ValorParametro("PARAMETRO") = Valor
End Sub

Public Function GetSQLCommand As String
       ' O objetivo deste evento é construir o comando SQL que será usado 
       ' na consulta. Os campos deverão estar definidos na consulta, mesmo 
       ' que em determinada situação um campo não seja utilizado. 
       ' Retornar o valor na própria função: GetSQLCommand = "SELECT * FROM TABELA" 
       ' Obs: Só será executado caso o Comando não esteja definido na consulta.

Dim qSql As BPesquisa
Set qSql = NewQuery

qSql.Add("SELECT DISTINCT																																																					")																										
qSql.Add("--SUBSELECT PARA COMAR TUDO 																																																		")
qSql.Add("		[NUMEROVIAGEM] AS [Número Viagem],																																															")
qSql.Add("        [INICIOEFETIVO] AS [Início Efetivo],																																														")
qSql.Add("        [STATUSVIAGEM] AS [Status Viagem],																																														")
qSql.Add("        [TIPOVIAGEM] AS [Tipo viagem],                                                        																																	")
qSql.Add("        [NUMEROCONTRATOFRETE] AS [Número Contrato de Frete],																																										")
qSql.Add("        [DATACONTRATOFRETE] AS [Data Contrato de Frete],																																											")
qSql.Add("        [STATUSCONTRATOFRETE] AS [Status Contrato de Frete],                                                           																											")
qSql.Add("        [ORIGEM] AS [Origem],                                                                               																														")
qSql.Add("        [DESTINO] AS [Destino],                                                                              																														")
qSql.Add("        [BENEFICIARIO] AS [Beneficiário],                                                                        																													")
qSql.Add("        [MOTORISTA] AS [Motorista],  																																																")
qSql.Add("		[TIPOFROTA] AS [Tipo Frota],                                                                  																																")
qSql.Add("        ISNULL([LINHA],'') AS [Linha],                                                                               																												")
qSql.Add("        [FRETEMINIMO] AS [Frete Mínimo], 																																															")
qSql.Add("		SUM(ISNULL([TOTALFRETET2],TOTALFRETED)) AS [Total Frete],  																																									")
qSql.Add("		(SUM(ISNULL([TOTALFRETET2],TOTALFRETED))-SUM(ISNULL([FRETEMINIMO],0))) AS [Diferença Frete],																																")
qSql.Add("		ISNULL((SUM(ISNULL([TOTALFRETET2],TOTALFRETED))/SUM(NULLIF([FRETEMINIMO],0))),0) AS [Diferença Frete %],																													")
qSql.Add("        ISNULL([VEICULOPUXADOR],'') AS [Veículo Puxador],																																											")
qSql.Add("        ISNULL([REBOQUE1],'') AS [Reboque 01],																																													")
qSql.Add("        ISNULL([REBOQUE2],'') AS [Reboque 02],																																													")
qSql.Add("        ISNULL([TIPOCLASSIFICACAOROTA],'') AS [Tipo Classificação Rota],																																							")
qSql.Add("		[KMCONSIDERADO] AS [KM Considerado],																																														")
qSql.Add("		ROUND(CASE																																																					")
qSql.Add("			WHEN (SUM(ISNULL([RECEITACOLETA],0)) + ISNULL([RECEITAENTREGA],0)) = 0 THEN SUM(ISNULL([TOTALFRETET2],TOTALFRETED))																										")
qSql.Add("		ELSE (SUM(ISNULL([RECEITACOLETA],0)) + ISNULL([RECEITAENTREGA],0))																																							")
qSql.Add("		END,2) AS [Total Receita], 																																																	")
qSql.Add("		SUM(ISNULL([RECEITACOLETA],0)) AS [Receita Coleta],																																											")
qSql.Add("		CAST([RECEITAENTREGA] AS NUMERIC(10,2)) AS [Receita Entrega],																																								")
qSql.Add("		ROUND(SUM(ISNULL([PESOREAL],0)),2) AS [Peso Real],																																											")
qSql.Add("		ROUND(SUM(ISNULL([PESOCUBADO],0)),2) AS [Peso Cubado],																																										")
qSql.Add("		IIF(ISNULL(PESOCONSIDERADOT4,0) + ROUND(SUM(ISNULL([PESOCOLETAREALIZADO],0)),2) = 0,SUM(ISNULL([PESOREAL],0)), ISNULL(PESOCONSIDERADOT4,0) + ROUND(SUM(ISNULL([PESOCOLETAREALIZADO],0)),2))  AS PESOCONSIDERADO,			")
qSql.Add("		--ROUND(IIF(SUM([PESOCONSIDERADO]) = 0, SUM(ISNULL([PESOREAL],0)),SUM([PESOCONSIDERADO])),2) AS [Peso Considerado],																											")
qSql.Add("		SUM(ISNULL([QUANTIDADECOLETA],0)) AS [Quantidade Coleta],																																									")
qSql.Add("		ISNULL([QUANTIDADEENTREGA],0) AS [Quantidade de Entrega],																																									")
qSql.Add("		ROUND(SUM([PESOCONSIDERADOENTREGA]),2) AS [Peso Considerado Entrega],																																						")
qSql.Add("		SUM(ISNULL([QUANTIDADECOLETAREALIZADA],0)) AS [Quantidade de Coleta Realizada],																																				")
qSql.Add("		ISNULL([QUANTIDADEENTREGAREALIZADA],0) AS [Quantidade de Entrega Realizada],																																				")
qSql.Add("		ROUND(SUM(ISNULL([PESOCOLETAREALIZADO],0)),2) AS [Peso Coleta Realizada],																																					")
qSql.Add("		ROUND(SUM(ISNULL([PESOENTREGAREALIZADO],0)),2) AS [Peso Entrega Realizada],																																					")
qSql.Add("		[CAPACIDADE] AS [Capacidade],																																																")
qSql.Add("		--Ocupação % (formula:  Peso coleta realizada + peso entrega realizada)/capacidade) e 																																		")
qSql.Add("		ROUND(((ROUND(SUM(ISNULL([PESOCOLETAREALIZADO],0)),2) + ROUND(SUM(ISNULL([PESOENTREGAREALIZADO],0)),2))/NULLIF([CAPACIDADE],0)),2) AS [Ocupação %],																			")
qSql.Add("		[VALORCONTRATOFRETE] AS [Valor Contrato Frete],																																												")
qSql.Add("		ROUND(((NULLIF(ISNULL(VALORCONTRATOFRETE,0),0)/NULLIF(SUM(ISNULL(PESOCOLETAREALIZADO,0)) + SUM(ISNULL([PESOENTREGAREALIZADO],0)),0))*SUM(ISNULL(PESOCOLETAREALIZADO,0))),2) AS [Custo Coleta],								")
qSql.Add("		ROUND(((NULLIF(ISNULL(VALORCONTRATOFRETE,0),0)/NULLIF(SUM(ISNULL(PESOCOLETAREALIZADO,0)) + SUM(ISNULL([PESOENTREGAREALIZADO],0)),0))*SUM(ISNULL([PESOENTREGAREALIZADO],0))),2) AS [Custo Entrega],							")
qSql.Add("		--“Custo Total por Receita %” (formula: valor contrato frete/Total frete) tabela abaixo com valores calculados 																												")
qSql.Add("		ROUND((ISNULL(VALORCONTRATOFRETE,0)/SUM(ISNULL(NULLIF([TOTALFRETET2],0),NULLIF(TOTALFRETED,0)))),2) AS [Custo Total por Receita %],																							")
qSql.Add("		--SUM(ISNULL([TOTALFRETET2],TOTALFRETED))),2) AS [Custo Total por Receita %],																																				")
qSql.Add("		--SUM(ISNULL([TOTALFRETET2],TOTALFRETED))),2) AS [Custo Total por Receita %],																																				")
qSql.Add("		(SUM(ISNULL(VOLUME, 0))+ ISNULL([VOLUMEENTREGA],0)) AS [Volume realizado],																																					")
qSql.Add("		SUM(ISNULL([VOLUMECOLETA],0)) AS [Volume Coleta Realizada],																																									")
qSql.Add("		ISNULL([VOLUMEENTREGA],0) AS [Volume Entrega Realizada],																																									")
qSql.Add("		ISNULL(SUM([VOLUMECARREGADO]),0) AS [Volume Carregado Sem Coleta],																																							")
qSql.Add("		[BLOQUEADA] AS [Bloqueada],																																																	")
qSql.Add("		SUM(ISNULL(VALORMERCADORIA,0)) AS [Valor Mercadoria],																																										")
qSql.Add("		VALORBLOQUEIO AS [Valor Bloqueio],		                                                                                                                                                                                    ")                              
qSql.Add("        [MOTIVO] AS [Motivo],																																																		")
qSql.Add("        [OBSERVACAO] AS [Observação],																																																")
qSql.Add("        [USUARIO] AS [Usuário],																																																	")
qSql.Add("        ISNULL([SUBTIPOVIAGEM],'') AS [SubTipo],																																													")
qSql.Add("        ISNULL([TIPOVEICULO],'') AS [Tipo Veículo],																																												")
qSql.Add("		[ITINERANTE] AS [Itinerante],																																																")
qSql.Add("		[VALORKM] AS [CF KM],																																																		")
qSql.Add("		GENERALIDADES AS [CF Generalidades],																																														")
qSql.Add("		DIARIA AS [CF Diaria],																																																		")
qSql.Add("		PRODUTIVIDADE AS [CF Produtividade],																																														")
qSql.Add("		TARIFAADD AS [CF Tarifa ADD],																																																")
qSql.Add("		FRETEVEICULO AS [CF Frete Veiculo],																																															")
qSql.Add("		DESCONTOS AS [CF Desconto],																																																	")
qSql.Add("		ISNULL(OBSERVACAOCONTRATOFRETE,'') AS [CF Observação Tarifa ADD]																																							")
qSql.Add("																																																									")
qSql.Add("FROM (																																																							")
qSql.Add("																																																									")
qSql.Add("SELECT  DISTINCT 																																																					")
qSql.Add("		V.NUMEROVIAGEM AS [NUMEROVIAGEM],                                                                        																													")
qSql.Add("        V.INICIOEFETIVO AS [INICIOEFETIVO],                                                                																														")
qSql.Add("        STATUSVIAGEM.NOME AS [STATUSVIAGEM],																																														")
qSql.Add("        TPV.NOME AS [TIPOVIAGEM],  																																																")
qSql.Add("		T5.OBSERVACAO AS OBSERVACAOCONTRATOFRETE,                                                                  																													")
qSql.Add("        FRETE.NUMERO AS [NUMEROCONTRATOFRETE],                                                           																															")
qSql.Add("        FRETE.DATAEMISSAO AS [DATACONTRATOFRETE],                                                      																															")
qSql.Add("        STFRETE.NOME AS [STATUSCONTRATOFRETE],                                                           																															")
qSql.Add("        FO.SIGLA AS [ORIGEM],                                                                               																														")
qSql.Add("        FD.SIGLA AS [DESTINO],                                                                              																														")
qSql.Add("        BENEFICIARIO.NOME AS [BENEFICIARIO],                                                                        																												")
qSql.Add("        VMOT.NOME AS [MOTORISTA],                                                                    																																")
qSql.Add("        CASE VEICULO01.ORIGEM                                                                                                                                                                                                     ")        
qSql.Add("                    WHEN 1 Then 'Próprio'                                                                                                                                                                                         ")                
qSql.Add("                    WHEN 2 Then 'Terceiro/Agregado'                                                                                                                                                                               ")         
qSql.Add("                    WHEN 3 Then 'Não integra frota'                                                                                                                                                                               ")         
qSql.Add("        END AS [TIPOFROTA],                                                                     																																	")
qSql.Add("        LINHA.NOME AS [LINHA],                                                                               																														")
qSql.Add("        ISNULL(V.K_VALORMINIMOFRETE,0) AS [FRETEMINIMO], 																																											")
qSql.Add("		T2.VALORFRETE  as [TOTALFRETET2],																																															")
qSql.Add("		SUM(D.VALORCONTABIL) AS [TOTALFRETED],																																														")
qSql.Add("        VEICULO01.PLACANUMERO AS [VEICULOPUXADOR],																																												")
qSql.Add("        VEICULO02.PLACANUMERO AS [REBOQUE1],																																														")
qSql.Add("        VEICULO03.PLACANUMERO AS [REBOQUE2],																																														")
qSql.Add("        CLASSFROTA.NOME AS [TIPOCLASSIFICACAOROTA],																																												")
qSql.Add("		ISNULL(V.DISTANCIACONSIDERADA, V.DISTANCIATOTAL) AS [KMCONSIDERADO],																																						")
qSql.Add("		(ISNULL(T2.VALORFRETE, 0) + ISNULL(SUM(DISTINCT T3.VALORTOTALRECEBER),0)) AS [TOTALRECEITA],																																")
qSql.Add("		SUM(T2.VALORFRETE) AS [RECEITACOLETA],																																														")
qSql.Add("		SUM(DISTINCT ISNULL(T3.VALORTOTALRECEBER,0)) AS [RECEITAENTREGA],																																							")
qSql.Add("		(SUM(ISNULL(D.DOCCLIPESOTOTAL,0)) + SUM(ISNULL(T2.PESO,0))) AS [PESOREAL],																																					")
qSql.Add("		(SUM(ISNULL(D.DOCCLIPESOCUBADOTOTAL,0)) + SUM(ISNULL(T2.PESOCUBADO,0))) AS [PESOCUBADO],																																	")
qSql.Add("		CAST((IsNull(T3.TOTAL, 0) + SUM(ISNULL(T2.PESOCONSIDERADO,0))) AS DECIMAL(10,3)) AS [PESOCONSIDERADO], 																														")
qSql.Add("		ISNULL(T4.TOTALPESOCONSIDERADOT4,0) AS PESOCONSIDERADOT4,																																									")
qSql.Add("		SUM(T2.QUANTIDADECOLETA) AS [QUANTIDADECOLETA],																																												")
qSql.Add("		T3.HANDLE  AS [QUANTIDADEENTREGAREALIZADA],																																													")
qSql.Add("		IsNull(SUM(IIF(D.DOCCLIPESOCUBADOTOTAL > D.DOCCLIPESOTOTAL, D.DOCCLIPESOCUBADOTOTAL, D.DOCCLIPESOTOTAL)), 0) AS [PESOCONSIDERADOENTREGA],																					")
qSql.Add("		COUNT(DISTINCT T2.COLETA) AS [QUANTIDADECOLETAREALIZADA],																																									")
qSql.Add("		T4.QUANTIDADEDEENTREGA AS [QUANTIDADEENTREGA],																																												")
qSql.Add("		SUM(T2.PESOCONSIDERADO) AS [PESOCOLETAREALIZADO],																																											")
qSql.Add("		CASE																																																						")
qSql.Add("			WHEN DV.SITUACAO = 209 THEN IsNull(SUM(IIF(D.DOCCLIPESOCUBADOTOTAL > D.DOCCLIPESOTOTAL, D.DOCCLIPESOCUBADOTOTAL, D.DOCCLIPESOTOTAL)), 0)																				")
qSql.Add("		ELSE 0																																																						")
qSql.Add("		END AS [PESOENTREGAREALIZADO],																																																")
qSql.Add("		VEICULO01.CAPACIDADE AS [CAPACIDADE],																																														")
qSql.Add("		CONVERT(DECIMAL(14,2),(ISNULL(SUM(D.DOCCLIPESOCONSIDERADO),0) / ISNULL(VEICULO01.CAPACIDADE, 0))*100) AS [OCUPACAOPESOCONSIDERADOPERCENT],																					")
qSql.Add("		FRETE.VALORTOTAL AS [VALORCONTRATOFRETE],																																													")
qSql.Add("		SUM(T10.VOLUMECOLETA) AS [VOLUME],																																															")
qSql.Add("		SUM(T10.VOLUMECOLETA) AS [VOLUMECOLETA],																																													")
qSql.Add("		T11.VOLUMEENTREGA AS [VOLUMEENTREGA],																																														")
qSql.Add("																																																									")
qSql.Add("		--ISNULL(T4.VOLUMECARREGADOS,0) AS [VOLUMECARREGADO],																																										")
qSql.Add("		(SUM(ISNULL(T2.VOLUME,0)) + SUM(ISNULL(D.DOCCLIVOLUME,0))) AS [VOLUMECARREGADO],																																			")
qSql.Add("																																																									")
qSql.Add("		IIF(VB.HANDLE Is Null, 'Não', 'Sim') AS [BLOQUEADA],																																										")
qSql.Add("		(SUM(ISNULL(D.DOCCLIVALORTOTAL,0))+SUM(ISNULL(T2.VALORMERCADORIA,0))) AS VALORMERCADORIA,																																	")
qSql.Add("		ISNULL(VB.VALORBLOQUEIO,0) AS VALORBLOQUEIO,		                                                                                                                                                                        ")                                          
qSql.Add("        ISNULL(VCM.DESCRICAO,'') AS [MOTIVO],																																														")
qSql.Add("        ISNULL(VB.OBSERVACAOAUTORIZACAO,'') AS [OBSERVACAO],																																										")
qSql.Add("        ISNULL(USUARIO.NOME,'') AS [USUARIO],																																														")
qSql.Add("        SBV.NOME AS [SUBTIPOVIAGEM],																																																")
qSql.Add("        VEICTIPO.NOME AS [TIPOVEICULO],																																															")
qSql.Add("		IIF(CALC.QUILOMETRAGEM>0, 'Sim', 'Não') [ITINERANTE],																																										")
qSql.Add("		CALC.QUILOMETRAGEM AS [VALORKM],																																															")
qSql.Add("		CALC.GENERALIDADES AS GENERALIDADES,																																														")
qSql.Add("		CALC.DIARIA AS DIARIA,																																																		")
qSql.Add("		CALC.PRODUTIVIDADE AS PRODUTIVIDADE,																																														")
qSql.Add("		CALC.QUILOMETRAGEM AS QUILOMETRAGEM,																																														")
qSql.Add("		CALC.TARIFAADD AS TARIFAADD,																																																")
qSql.Add("		CALC.FRETEVEICULO AS FRETEVEICULO,																																															")
qSql.Add("		CALC.DESCONTOS AS DESCONTOS																																																	")
qSql.Add("																																																									")
qSql.Add("FROM GLOP_VIAGENS V                                                                                                                                                                                     							")
qSql.Add("LEFT JOIN GLGL_SUBTIPOVIAGENS SBV																																																	")
qSql.Add("	ON SBV.HANDLE = V.SUBTIPOVIAGEM  																																																")
qSql.Add("																																																									")
qSql.Add("INNER JOIN GLOP_VIAGEMDOCUMENTOS DV																																																")
qSql.Add("	ON DV.VIAGEM = V.HANDLE																																																			")
qSql.Add("																																																									")
qSql.Add("LEFT JOIN GLGL_DOCUMENTOS D																																																		")
qSql.Add("	ON DV.DOCUMENTOLOGISTICA = D.HANDLE																																																")
qSql.Add("	                                                                                  																																				")
qSql.Add("JOIN GLGL_ENUMERACAOITEMS TPV																																																		")
qSql.Add("	ON TPV.HANDLE = V.TIPOVIAGEM                                                                                             																										")
qSql.Add("																																																									")
qSql.Add("JOIN GLGL_ENUMERACAOITEMS STATUSVIAGEM    																																														")
qSql.Add("	ON STATUSVIAGEM.HANDLE = V.STATUS																																																")
qSql.Add("																																																									")
qSql.Add("JOIN GN_PESSOAS VMOT                																																																")
qSql.Add("	ON VMOT.HANDLE = V.MOTORISTA 																																																	")
qSql.Add("	                                                                                       																																			")
qSql.Add("LEFT JOIN GLOP_CONTRATOFRETEVIAGENS VFRETE       																																													")
qSql.Add("	ON VFRETE.VIAGEM = V.Handle																																																		")
qSql.Add("                                                                                                                                                                    																")
qSql.Add("INNER JOIN GLOP_CONTRATOFRETES FRETE               																																												")
qSql.Add("	ON FRETE.HANDLE = VFRETE.CONTRATOFRETE                                                                               																											")
qSql.Add("    AND FRETE.Status Not In (262, 433, 731)   																																													")
qSql.Add("                                                                                                                                                                                                               					")
qSql.Add("LEFT JOIN 																																																						")
qSql.Add("	(																																																								")
qSql.Add("			SELECT 																																																					")
qSql.Add("					CONTRATOFRETE,																																																	")
qSql.Add("					SUM(GENERALIDADES) AS GENERALIDADES,																																											")
qSql.Add("					SUM(DIARIA) AS DIARIA,																																															")
qSql.Add("					SUM(PRODUTIVIDADE) AS PRODUTIVIDADE,																																											")
qSql.Add("					SUM(QUILOMETRAGEM) AS QUILOMETRAGEM,																																											")
qSql.Add("					SUM(TARIFAADD) AS TARIFAADD,																																													")
qSql.Add("					SUM(FRETEVEICULO) AS FRETEVEICULO,																																												")
qSql.Add("					SUM(DESCONTOS) AS DESCONTOS																																														")
qSql.Add("			FROM (																																																					")
qSql.Add("			SELECT DISTINCT 																																																		")
qSql.Add("					CONTRATOFRETE,																																																	")
qSql.Add("					CASE																																																			")
qSql.Add("						WHEN CLASSIFICACAO = 7 THEN SUM(VALORFINAL)																																									")
qSql.Add("					ELSE 0																																																			")
qSql.Add("					END AS GENERALIDADES,																																															")
qSql.Add("					CASE																																																			")
qSql.Add("						WHEN CLASSIFICACAO = 8 THEN SUM(VALORFINAL)																																									")
qSql.Add("					ELSE 0																																																			")
qSql.Add("					END AS DIARIA,																																																	")
qSql.Add("					CASE																																																			")
qSql.Add("						WHEN CLASSIFICACAO = 9 THEN SUM(VALORFINAL)																																									")
qSql.Add("					ELSE 0																																																			")
qSql.Add("					END AS PRODUTIVIDADE,																																															")
qSql.Add("					CASE																																																			")
qSql.Add("						WHEN CLASSIFICACAO = 10 THEN SUM(ISNULL(VALORFINAL,0))																																						")
qSql.Add("					ELSE 0																																																			")
qSql.Add("					END AS QUILOMETRAGEM,																																															")
qSql.Add("					CASE																																																			")
qSql.Add("						WHEN CLASSIFICACAO = 13 THEN SUM(VALORFINAL)																																								")
qSql.Add("					ELSE 0																																																			")
qSql.Add("					END AS TARIFAADD,																																																")
qSql.Add("					CASE																																																			")
qSql.Add("						WHEN CLASSIFICACAO = 14 THEN SUM(VALORFINAL)																																								")
qSql.Add("					ELSE 0																																																			")
qSql.Add("					END AS FRETEVEICULO,																																															")
qSql.Add("					CASE																																																			")
qSql.Add("						WHEN CLASSIFICACAO = 15 THEN SUM(VALORFINAL)																																								")
qSql.Add("					ELSE 0																																																			")
qSql.Add("					END AS DESCONTOS																																																")
qSql.Add("																																																									")
qSql.Add("																																																									")
qSql.Add("			FROM GLOP_CONTRATOFRETCALCULOS																																															")
qSql.Add("																																																									")
qSql.Add("			GROUP BY CONTRATOFRETE, CLASSIFICACAO																																													")
qSql.Add("			) AS T1																																																					")
qSql.Add("																																																									")
qSql.Add("			GROUP BY CONTRATOFRETE																																																	")
qSql.Add("	)AS CALC						 																																																")
qSql.Add("	ON CALC.CONTRATOFRETE = FRETE.HANDLE																																															")
qSql.Add("																																																									")
qSql.Add("																																																									")
qSql.Add("																																																									")
qSql.Add("LEFT JOIN GLGL_ENUMERACAOITEMS STFRETE                    																																										")
qSql.Add("	ON STFRETE.HANDLE = FRETE.STATUS  																																																")
qSql.Add("	                                                                                            																																	")
qSql.Add("JOIN GLGL_FILIAIS FO                         																																														")
qSql.Add("	ON FO.HANDLE = V.FILIALORIGEM   																																																")
qSql.Add("	                                                                                  																																				")
qSql.Add("JOIN GLGL_FILIAIS FD                         																																														")
qSql.Add("	ON FD.HANDLE = V.FILIALDESTINO   																																																")
qSql.Add("	                                                                                 																																				")
qSql.Add("JOIN MA_RECURSOS VEICULO01           																																																")
qSql.Add("	ON VEICULO01.HANDLE = V.VEICULO1                                                                                         																										")
qSql.Add("																																																									")
qSql.Add("LEFT JOIN MF_VEICULOTIPOS VEICTIPO            																																													")
qSql.Add("	ON VEICTIPO.HANDLE = VEICULO01.TIPOVEICULO                                                                              																										")
qSql.Add("																																																									")
qSql.Add("LEFT JOIN K_MF_TIPOCLASSIFICACAOFROTA CLASSFROTA																																													")
qSql.Add("	ON CLASSFROTA.HANDLE = VEICULO01.K_TIPOCLASSIFICACAO																																											")
qSql.Add("	                                                               																																									")
qSql.Add("LEFT JOIN MA_RECURSOS VEICULO02           																																														")
qSql.Add("	ON VEICULO02.HANDLE           = V.VEICULO2                                                                                         																								")
qSql.Add("																																																									")
qSql.Add("LEFT JOIN MA_RECURSOS VEICULO03           																																														")
qSql.Add("	ON VEICULO03.HANDLE = V.VEICULO3   																																																")
qSql.Add("	                                                                                      																																			")
qSql.Add("JOIN GN_PESSOAS BENEFICIARIO  																																																	")
qSql.Add("	ON BENEFICIARIO.HANDLE = FRETE.BENEFICIARIO 																																													")
qSql.Add("	                                                                   																																								")
qSql.Add("LEFT JOIN GLOP_LINHAVIAGENS LINHA               																																													")
qSql.Add("	ON LINHA.HANDLE = V.LINHAVIAGEM   																																																")
qSql.Add("	                                                                                          																																		")
qSql.Add("LEFT JOIN K_GLOP_LINHAVIAGEMLIMITES LVL                        																																									")
qSql.Add("	ON LVL.LINHAVIAGEM            = LINHA.HANDLE                                                                                              																						")
qSql.Add("	AND LVL.TIPOTERCEIRO = VEICULO01.TIPOFROTAAGREGADA                                                                  																											")
qSql.Add("	AND LVL.TIPOVEICULO = VEICULO01.TIPOVEICULO																																														")
qSql.Add("                                                                              																																					")
qSql.Add("LEFT JOIN K_GLOP_VIAGEMBLOQUEIOS VB 																																																")
qSql.Add("	ON VB.VIAGEM = V.HANDLE                                                                                                  																										")
qSql.Add("	AND NOT VB.STATUS = 61                                                                                                       																									")
qSql.Add("																																																									")
qSql.Add("LEFT JOIN K_GLOP_VIAGEMCUSTOMOTIVOS VCM                        																																									")
qSql.Add("	ON VCM.HANDLE = VB.MOTIVOLIBERACAO																																																")
qSql.Add("	                                                                        																																						")
qSql.Add("LEFT JOIN Z_GRUPOUSUARIOS USUARIO 																																																")
qSql.Add("	ON USUARIO.HANDLE = VB.USUARIOAPROVACAO 																																														")
qSql.Add("																																																									")
qSql.Add("LEFT JOIN (																																																						")
qSql.Add("																																																									")
qSql.Add("				SELECT																																																				")
qSql.Add("					 COLETA,  																																																		")
qSql.Add("					 SUM(VALORFRETE) AS VALORFRETE,																																													")
qSql.Add("					 SUM(PESO) AS PESO,																																																")
qSql.Add("					 SUM(PESOCUBADO) AS PESOCUBADO, 																																												")
qSql.Add("					 SUM(PESOCONSIDERADO) AS PESOCONSIDERADO,																																										")
qSql.Add("					 SUM(QUANTIDADECOLETA) AS QUANTIDADECOLETA,																																										")
qSql.Add("					 SUM(PESOCOLETAREALIZADO) AS PESOCOLETAREALIZADO,																																								")
qSql.Add("					 SUM([VOLUME]) AS [VOLUME],																																														")
qSql.Add("					 SUM([VALORMERCADORIA]) AS [VALORMERCADORIA]																																									")
qSql.Add("																																																									")
qSql.Add("				FROM(																																																				")
qSql.Add("																																																									")
qSql.Add("				SELECT		CP.HANDLE COLETA,  																																														")
qSql.Add("											DL.NUMERO,                                                                                                                                                 								")
qSql.Add("											DL.VALORTOTALRECEBER           VALORFRETE,																																				")
qSql.Add("											DL.DOCCLIPESOTOTAL AS PESO,																																								")
qSql.Add("											DL.DOCCLIPESOCUBADOTOTAL AS PESOCUBADO, 																																				")
qSql.Add("											DL.DOCCLIPESOCONSIDERADO AS PESOCONSIDERADO,																																			")
qSql.Add("											COUNT(DISTINCT CP.HANDLE) AS QUANTIDADECOLETA,																																			")
qSql.Add("											DL.DOCCLIPESOCONSIDERADO AS PESOCOLETAREALIZADO,																																		")
qSql.Add("											DL.DOCCLIVOLUME AS [VOLUME],																																							")
qSql.Add("											DL.DOCCLIVALORTOTAL AS [VALORMERCADORIA]                                                                                                                  								")
qSql.Add("								FROM GLGL_DOCUMENTOASSOCIADOS DA   																																									")
qSql.Add("                                                                                                                                                                   																")
qSql.Add("								INNER JOIN GLGL_DOCUMENTOCLIENTES DC 																																								")
qSql.Add("									ON DC.HANDLE = DA.DOCUMENTOCLIENTE																																								")
qSql.Add("	                                                                                       																																			")
qSql.Add("								INNER JOIN GLGL_DOCUMENTOS DL 																																										")
qSql.Add("									ON DA.DOCUMENTOLOGISTICA = DL.HANDLE 																																							")
qSql.Add("	                                                                                                     																															")
qSql.Add("								INNER JOIN GLOP_COLETAPEDIDOS CP 																																									")
qSql.Add("									ON CP.HANDLE = DC.PEDIDOCOLETA     																																								")
qSql.Add("	                                                                                     																																			")
qSql.Add("	                                                                                                       																															")
qSql.Add("								WHERE  1=1                                                                                                                                                                                          ")                  
qSql.Add("									And ((DL.TIPODOCUMENTO In (1, 2)                                                                                                         														")
qSql.Add("									And   DL.TIPODOCUMENTOFRETE = 153)                                                                                                            													")
qSql.Add("									Or  (DL.TIPODOCUMENTO In (6)                                                                                                            														")
qSql.Add("									And   DL.TIPORPS <> 324))   																																									")
qSql.Add("									AND DL.STATUS <> 236																																											")
qSql.Add("									--AND CP.HANDLE = 2177518																																										")
qSql.Add("					                                                                                                      																											")
qSql.Add("								GROUP BY CP.HANDLE,  																																												")
qSql.Add("										 DL.NUMERO,                                                                                                                                                                                 ")    
qSql.Add("										 DL.VALORTOTALRECEBER,																																										")
qSql.Add("										 DL.DOCCLIPESOTOTAL,																																										")
qSql.Add("										 DL.DOCCLIPESOCUBADOTOTAL, 																																									")
qSql.Add("										 DL.DOCCLIPESOCONSIDERADO,																																									")
qSql.Add("										 DL.DOCCLIPESOCONSIDERADO,																																									")
qSql.Add("										 DL.DOCCLIVOLUME,																																											")
qSql.Add("										 DL.DOCCLIVALORTOTAL																																										")
qSql.Add("				) T																																																					")
qSql.Add("																																																									")
qSql.Add("				GROUP BY COLETA																																																		")
qSql.Add("																																																									")
qSql.Add("		  ) AS T2 ON T2.COLETA = DV.DOCUMENTOCOLETA																																													")
qSql.Add("		  AND DV.SITUACAO = 209																																																		")
qSql.Add("																																																									")
qSql.Add("																																																									")
qSql.Add("LEFT JOIN (																																																						")
qSql.Add("			SELECT 																																																					")
qSql.Add("					VD.VIAGEM,																																																		")
qSql.Add("					SUM(CONVERT(DECIMAL(14,3),DL.VALORTOTALRECEBER)) AS VALORTOTALRECEBER,																																			")
qSql.Add("					SUM(CONVERT(DECIMAL(14,3),DL.DOCCLIPESOTOTAL)) AS DOCCLIPESOTOTAL,                                                                                                                                              ")                                             
qSql.Add("                    SUM(CONVERT(DECIMAL(14,3),DL.DOCCLIPESOCUBADOTOTAL)) AS DOCCLIPESOCUBADOTOTAL,																																")
qSql.Add("					SUM(CONVERT(DECIMAL(14,3),DL.DOCCLIPESOCONSIDERADO)) AS PESOTOTALCONSIDERADO,																																	")
qSql.Add("					--SUM(DL.DOCCLIVOLUME) AS VOLUMEENTREGA,																																										")
qSql.Add("					SUM(IIF(DOCCLIPESOCUBADOTOTAL > DOCCLIPESOTOTAL, DOCCLIPESOCUBADOTOTAL, DOCCLIPESOTOTAL))  AS TOTAL,																											")
qSql.Add("					COUNT(DL.HANDLE) AS HANDLE																																														")
qSql.Add("			--INTO #TESTE																																																			")
qSql.Add("			FROM GLOP_VIAGEMDOCUMENTOS VD																																															")
qSql.Add("																																																									")
qSql.Add("			INNER JOIN GLOP_OCORRENCIAS OC     																																														")
qSql.Add("				ON OC.HANDLE = VD.OCORRENCIA 																																														")
qSql.Add("																																																									")
qSql.Add("			INNER JOIN GLOP_MOTIVOOCORRENCIAS MOC 																																													")
qSql.Add("				ON MOC.HANDLE = OC.OCORRENCIA                                                                                                          																				")
qSql.Add("				AND PAGARFORNECEDOR = 'S'  																																															")
qSql.Add("				                                                                                                                  																									")
qSql.Add("			INNER JOIN GLGL_DOCUMENTOS DL     																																														")
qSql.Add("				ON DL.HANDLE = VD.DOCUMENTOLOGISTICA                                                                                            																					")
qSql.Add("																																																									")
qSql.Add("			WHERE VD.TIPOSERVICO = 197       																																														")
qSql.Add("																																																									")
qSql.Add("			GROUP BY VD.VIAGEM																																																		")
qSql.Add("		  ) AS T3 ON T3.VIAGEM = V.HANDLE																																															")
qSql.Add("LEFT JOIN 																																																						")
qSql.Add("		(																																																							")
qSql.Add("			SELECT 																																																					")
qSql.Add("					VD.VIAGEM,																																																		")
qSql.Add("					COUNT(DISTINCT DL.HANDLE) AS QUANTIDADEDEENTREGA,																																								")
qSql.Add("					SUM(DL.DOCCLIVOLUME) AS VOLUMECARREGADOS,																																										")
qSql.Add("					SUM(DL.DOCCLIVALORTOTAL) AS [VALORMERCADORIAENTREGA],																																							")
qSql.Add("					SUM(IIF(DOCCLIPESOCUBADOTOTAL > DOCCLIPESOTOTAL, DOCCLIPESOCUBADOTOTAL, DOCCLIPESOTOTAL))  AS TOTALPESOCONSIDERADOT4																							")
qSql.Add("			FROM GLOP_VIAGEMDOCUMENTOS VD																																															")
qSql.Add("																																																									")
qSql.Add("			INNER JOIN GLOP_OCORRENCIAS OC     																																														")
qSql.Add("				ON OC.HANDLE = VD.OCORRENCIA 																																														")
qSql.Add("																																																									")
qSql.Add("			INNER JOIN GLOP_MOTIVOOCORRENCIAS MOC 																																													")
qSql.Add("				ON MOC.HANDLE = OC.OCORRENCIA                                                                                                          																				")
qSql.Add("				--AND PAGARFORNECEDOR = 'S'  																																														")
qSql.Add("				                                                                                                                  																									")
qSql.Add("			INNER JOIN GLGL_DOCUMENTOS DL     																																														")
qSql.Add("				ON DL.HANDLE = VD.DOCUMENTOLOGISTICA                                                                                            																					")
qSql.Add("																																																									")
qSql.Add("			WHERE VD.TIPOSERVICO = 197     																																															")
qSql.Add("																																																									")
qSql.Add("			GROUP BY VD.VIAGEM																																																		")
qSql.Add("		) AS T4 ON T4.VIAGEM = V.HANDLE																																																")
qSql.Add("LEFT JOIN 																																																						")
qSql.Add("		(																																																							")
qSql.Add("			SELECT  																																																				")
qSql.Add("				MAX(HANDLE) AS HANDLE																																																")
qSql.Add("				,CONTRATOFRETE																																																		")
qSql.Add("				--,OBSERVACAO																																																		")
qSql.Add("				,MAX(DATAHORA) AS [DATA] 																																															")
qSql.Add("																																																									")
qSql.Add("			FROM GLOP_FRETECOMBINADOLOGS T																																															")
qSql.Add("			GROUP BY CONTRATOFRETE																																																	")
qSql.Add("		) AS FRETECOMBINADOLOGS																																																		")
qSql.Add("	ON FRETE.HANDLE = FRETECOMBINADOLOGS.CONTRATOFRETE																																												")
qSql.Add("																																																									")
qSql.Add("LEFT JOIN GLOP_FRETECOMBINADOLOGS T5																																																")
qSql.Add("	ON FRETECOMBINADOLOGS.CONTRATOFRETE = T5.CONTRATOFRETE																																											")
qSql.Add("	AND FRETECOMBINADOLOGS.HANDLE = T5.HANDLE																																														")
qSql.Add("																																																									")
qSql.Add("LEFT JOIN																																																							")
qSql.Add("		(																																																							")
qSql.Add("			SELECT																																																					")
qSql.Add("				 COLETA,  																																																			")
qSql.Add("				 SUM([VOLUME]) AS [VOLUMECOLETA]																																													")
qSql.Add("																																																									")
qSql.Add("			FROM(																																																					")
qSql.Add("																																																									")
qSql.Add("			SELECT		CP.HANDLE COLETA,  																																															")
qSql.Add("																																																									")
qSql.Add("										DL.DOCCLIVOLUME AS [VOLUME]                                                                                                               													")
qSql.Add("							FROM GLGL_DOCUMENTOASSOCIADOS DA   																																										")
qSql.Add("                                                                                                                                                                   																")
qSql.Add("							INNER JOIN GLGL_DOCUMENTOCLIENTES DC 																																									")
qSql.Add("								ON DC.HANDLE = DA.DOCUMENTOCLIENTE																																									")
qSql.Add("	                                                                                       																																			")
qSql.Add("							INNER JOIN GLGL_DOCUMENTOS DL 																																											")
qSql.Add("								ON DA.DOCUMENTOLOGISTICA = DL.HANDLE 																																								")
qSql.Add("	                                                                                                     																															")
qSql.Add("							INNER JOIN GLOP_COLETAPEDIDOS CP 																																										")
qSql.Add("								ON CP.HANDLE = DC.PEDIDOCOLETA     																																									")
qSql.Add("	                                                                                     																																			")
qSql.Add("	                                                                                                       																															")
qSql.Add("							WHERE  1=1                                                                                                                                                                                              ")              
qSql.Add("								And ((DL.TIPODOCUMENTO In (1, 2)                                                                                                         															")
qSql.Add("								And   DL.TIPODOCUMENTOFRETE = 153)                                                                                                            														")
qSql.Add("								Or  (DL.TIPODOCUMENTO In (6)                                                                                                            															")
qSql.Add("								And   DL.TIPORPS <> 324))   																																										")
qSql.Add("								AND DL.STATUS <> 236																																												")
qSql.Add("																																																									")
qSql.Add("					                                                                                                      																											")
qSql.Add("							GROUP BY CP.HANDLE,  																																													")
qSql.Add("									 DL.NUMERO,                                                                                                                                                                                     ")
qSql.Add("									 DL.VALORTOTALRECEBER,																																											")
qSql.Add("									 DL.DOCCLIPESOTOTAL,																																											")
qSql.Add("									 DL.DOCCLIPESOCUBADOTOTAL, 																																										")
qSql.Add("									 DL.DOCCLIPESOCONSIDERADO,																																										")
qSql.Add("									 DL.DOCCLIPESOCONSIDERADO,																																										")
qSql.Add("									 DL.DOCCLIVOLUME,																																												")
qSql.Add("									 DL.DOCCLIVALORTOTAL																																											")
qSql.Add("			) T																																																						")
qSql.Add("																																																									")
qSql.Add("			GROUP BY COLETA																																																			")
qSql.Add("		) AS T10																																																					")
qSql.Add("	ON T10.COLETA = DV.DOCUMENTOCOLETA																																																")
qSql.Add("																																																									")
qSql.Add("LEFT JOIN (																																																						")
qSql.Add("			SELECT  																																																				")
qSql.Add("						VIAGEM																																																		")
qSql.Add("						,SUM(VOLUMEENTREGA) AS VOLUMEENTREGA																																										")
qSql.Add("																																																									")
qSql.Add("				FROM (																																																				")
qSql.Add("					SELECT 																																																			")
qSql.Add("										VD.VIAGEM,																																													")
qSql.Add("										DL.DOCCLIVOLUME AS VOLUMEENTREGA																																							")
qSql.Add("																																																									")
qSql.Add("								FROM GLOP_VIAGEMDOCUMENTOS VD																																										")
qSql.Add("																																																									")
qSql.Add("								INNER JOIN GLOP_OCORRENCIAS OC     																																									")
qSql.Add("									ON OC.HANDLE = VD.OCORRENCIA 																																									")
qSql.Add("																																																									")
qSql.Add("								INNER JOIN GLOP_MOTIVOOCORRENCIAS MOC 																																								")
qSql.Add("									ON MOC.HANDLE = OC.OCORRENCIA                                                                                                          															")
qSql.Add("									AND PAGARFORNECEDOR = 'S'  																																										")
qSql.Add("				                                                                                                                  																									")
qSql.Add("								INNER JOIN GLGL_DOCUMENTOS DL     																																									")
qSql.Add("									ON DL.HANDLE = VD.DOCUMENTOLOGISTICA   																																							")
qSql.Add("																																																									")
qSql.Add("								WHERE VD.TIPOSERVICO = 197     																																										")
qSql.Add("						) AS T																																																		")
qSql.Add("																																																									")
qSql.Add("					GROUP BY VIAGEM																																																	")
qSql.Add("		   ) AS T11																																																					")
qSql.Add("	ON T11.VIAGEM = V.HANDLE 																																																		")
qSql.Add("																																																									")
qSql.Add("WHERE 1 = 1                                                                                                                                                                                                                       ")                
qSql.Add("--And Convert(Date, v.INICIOEFETIVO) >= '2019-07-03' 																																												")
qSql.Add("--And Convert(Date, v.INICIOEFETIVO) < '2019-07-04'																																												")
qSql.Add("--AND V.NUMEROVIAGEM IN 																																																			")
qSql.Add("--													(																																											")
qSql.Add("--													'2019/159690-27'																																							")
qSql.Add("--													,'2019/204046-363'																																							")
qSql.Add("--													,'2019/205100-2'																																							")
qSql.Add("--													,'2019/207382-7'																																							")
qSql.Add("--													,'2019/208659-7'																																							")
qSql.Add("--													,'2019/209934-38'																																							")
qSql.Add("--													)																																											")
qSql.Add("GROUP BY 																																																							")
qSql.Add("		V.NUMEROVIAGEM,                                                                        																																		")
qSql.Add("		V.INICIOEFETIVO,                                                                																																			")
qSql.Add("		STATUSVIAGEM.NOME,																																																			")
qSql.Add("		TPV.NOME,																																																					")
qSql.Add("		T5.OBSERVACAO,                                                                    																																			")
qSql.Add("		FRETE.NUMERO,                                                           																																					")
qSql.Add("		FRETE.DATAEMISSAO,                                                      																																					")
qSql.Add("		STFRETE.NOME,                                                           																																					")
qSql.Add("		FO.SIGLA,                                                                               																																	")
qSql.Add("		FD.SIGLA,                                                                              																																		")
qSql.Add("		BENEFICIARIO.NOME,                                                                        																																	")
qSql.Add("		VMOT.NOME,                                                                    																																				")
qSql.Add("		CASE VEICULO01.ORIGEM                                                                                                                                                                                                       ")      
qSql.Add("					WHEN 1 Then 'Próprio'                                                                                                                                                                                           ")              
qSql.Add("					WHEN 2 Then 'Terceiro/Agregado'                                                                                                                                                                                 ")       
qSql.Add("					WHEN 3 Then 'Não integra frota'                                                                                                                                                                                 ")       
qSql.Add("		END,                                                                     																																					")
qSql.Add("		LINHA.NOME,          																																																		")
qSql.Add("		LVL.VALOR,                                                                     																																				")
qSql.Add("		ISNULL(V.K_VALORMINIMOFRETE,0), 																																															")
qSql.Add("		VEICULO01.PLACANUMERO,																																																		")
qSql.Add("		VEICULO02.PLACANUMERO,																																																		")
qSql.Add("		VEICULO03.PLACANUMERO,																																																		")
qSql.Add("		CLASSFROTA.NOME,																																																			")
qSql.Add("		ISNULL(V.DISTANCIACONSIDERADA, V.DISTANCIATOTAL),																																											")
qSql.Add("		DV.SITUACAO,																																																				")
qSql.Add("		VEICULO01.CAPACIDADE,																																																		")
qSql.Add("		FRETE.VALORTOTAL,																																																			")
qSql.Add("		T3.TOTAL,																																																					")
qSql.Add("		T3.HANDLE,																																																					")
qSql.Add("		V.TIPOVIAGEM,																																																				")
qSql.Add("		T3.PESOTOTALCONSIDERADO,																																																	")
qSql.Add("		T3.VALORTOTALRECEBER,																																																		")
qSql.Add("		IIF(VB.HANDLE Is Null, 'Não', 'Sim'),																																														")
qSql.Add("		 VB.VALORBLOQUEIO,                                                                                                                                                                                                          ")  
qSql.Add("         VCM.DESCRICAO,																																																			")
qSql.Add("         VB.OBSERVACAOAUTORIZACAO,																																																")
qSql.Add("         USUARIO.NOME,																																																			")
qSql.Add("         SBV.NOME,																																																				")
qSql.Add("         VEICTIPO.NOME,																																																			")
qSql.Add("		 CALC.QUILOMETRAGEM,																																																		")
qSql.Add("		 CALC.GENERALIDADES,																																																		")
qSql.Add("		 CALC.DIARIA,																																																				")
qSql.Add("		 CALC.PRODUTIVIDADE,																																																		")
qSql.Add("		 CALC.QUILOMETRAGEM,																																																		")
qSql.Add("		 CALC.TARIFAADD,																																																			")
qSql.Add("		 CALC.FRETEVEICULO,																																																			")
qSql.Add("		 CALC.DESCONTOS,																																																			")
qSql.Add("		 V.HANDLE,																																																					")
qSql.Add("		 T2.VALORFRETE,																																																				")
qSql.Add("		 T4.QUANTIDADEDEENTREGA,																																																	")
qSql.Add("		 T4.VALORMERCADORIAENTREGA,																																																	")
qSql.Add("		 T11.VOLUMEENTREGA,																																																			")
qSql.Add("		 ISNULL(T4.VOLUMECARREGADOS,0),																																																")
qSql.Add("		 ISNULL(T4.TOTALPESOCONSIDERADOT4,0)																																														")
qSql.Add(") AS T1																																																							")
qSql.Add("																																																									")
qSql.Add("GROUP BY																																																							")
qSql.Add("[NUMEROVIAGEM],                                                                        																																			")
qSql.Add("        [INICIOEFETIVO],                                                                																																			")
qSql.Add("        [STATUSVIAGEM],																																																			")
qSql.Add("        [TIPOVIAGEM],																																																				")
qSql.Add("		OBSERVACAOCONTRATOFRETE,                                                                   																																	")
qSql.Add("        [NUMEROCONTRATOFRETE],                                                           																																			")
qSql.Add("        [DATACONTRATOFRETE],                                                      																																				")
qSql.Add("        [STATUSCONTRATOFRETE],                                                           																																			")
qSql.Add("        [ORIGEM],                                                                               																																	")
qSql.Add("        [DESTINO],                                                                              																																	")
qSql.Add("        [BENEFICIARIO],                                                                        																																	")
qSql.Add("        [MOTORISTA], 																																																				")
qSql.Add("		[TIPOFROTA],                                                                   																																				")
qSql.Add("        [LINHA],                                                                               																																	")
qSql.Add("        [FRETEMINIMO], 																																																			")
qSql.Add("        [VEICULOPUXADOR],																																																			")
qSql.Add("        [REBOQUE1],																																																				")
qSql.Add("        [REBOQUE2],																																																				")
qSql.Add("        [TIPOCLASSIFICACAOROTA],																																																	")
qSql.Add("		[KMCONSIDERADO],																																																			")
qSql.Add("		[RECEITAENTREGA],																																																			")
qSql.Add("		[QUANTIDADEENTREGAREALIZADA],																																																")
qSql.Add("		[CAPACIDADE],																																																				")
qSql.Add("		[VALORCONTRATOFRETE],																																																		")
qSql.Add("		[BLOQUEADA],																																																				")
qSql.Add("		VALORBLOQUEIO,                                                                                                                                                                                                              ")    
qSql.Add("        [MOTIVO],																																																					")
qSql.Add("        [OBSERVACAO],																																																				")
qSql.Add("        [USUARIO],																																																				")
qSql.Add("        [SUBTIPOVIAGEM],																																																			")
qSql.Add("        [TIPOVEICULO],																																																			")
qSql.Add("		[ITINERANTE],																																																				")
qSql.Add("		[VALORKM],																																																					")
qSql.Add("		GENERALIDADES,																																																				")
qSql.Add("		DIARIA,																																																						")
qSql.Add("		PRODUTIVIDADE,																																																				")
qSql.Add("		TARIFAADD,																																																					")
qSql.Add("		FRETEVEICULO,																																																				")
qSql.Add("		DESCONTOS,																																																					")
qSql.Add("		ISNULL([QUANTIDADEENTREGA],0),																																																")
qSql.Add("		[VOLUMEENTREGA],																																																			")
qSql.Add("		ISNULL(PESOCONSIDERADOT4,0)																																																	")


If ValorFiltro("DATAI") <> "" Or ValorFiltro("DATAF") <> "" Then
	qSql.Add("	   And Convert(Date, V.INICIOEFETIVO)												Between '" & FormatDateTime2("yyyy-mm-dd",ValorFiltro("DATAI")) & "'	")
	qSql.Add("																							And '" & FormatDateTime2("yyyy-mm-dd",ValorFiltro("DATAF")) & "'	")
End If

If ValorFiltro("DATACFI") <> "" Or ValorFiltro("DATACFF") <> "" Then
	qSql.Add("	   And Convert(Date, FRETE.DATAEMISSAO)												Between '" & FormatDateTime2("yyyy-mm-dd",ValorFiltro("DATACFI")) & "'	")
	qSql.Add("																							And '" & FormatDateTime2("yyyy-mm-dd",ValorFiltro("DATACFF")) & "'	")
End If

If ValorFiltro("STATUSVG") <> "" Then
	qSql.Add("	   And V.STATUS																		In ("+ValorFiltro("STATUSVG")+")				")
End If

If ValorFiltro("STATUSCF") <> "" Then
	qSql.Add("	   And FRETE.STATUS																	In ("+ValorFiltro("STATUSCF")+")				")
End If

If ValorFiltro("TPVIAGEM") <> "" Then
	qSql.Add("	   And V.TIPOVIAGEM																	In ("+ValorFiltro("TPVIAGEM")+")				")
End If

If ValorFiltro("FILIALO") <> "" Then
	qSql.Add("	   And FO.HANDLE																	In ("+ValorFiltro("FILIALO") +")				")
End If

If ValorFiltro("FILIALD") <> "" Then
	qSql.Add("	   And FD.HANDLE																	In ("+ValorFiltro("FILIALD") +")				")
End If

qSql.Active = True

GetSQLCommand = qSql.Text

qSql.Active = False
Set qSql = Nothing

End Function

Public Function GetContainerXMLData As String
       ' O objetivo deste evento é permitir que os dados da consulta sejam gerados a partir 
       ' de um Container. Neste caso esta função deve retornar o XML do container que contém 
       ' os dados da Consulta. 
       ' Retornar o valor na própria função: GetContainerXMLData = container.GetXML()
       ' Obs: Só será executado caso o Comando não esteja definido na consulta e o evento GetSQLCommand não retorne nada .
End Function

Public Sub DataPrepared

End Sub

Public Function GetStatusDescription As String

End Function

Public Sub OnButtonClick

End Sub