--Select *
--  Into #TMETA
--  From OPENROWSET('Microsoft.ACE.OLEDB.12.0', 'Excel 12.0; Database=\\fileserverazure\marcusoliveira$\ETM.xlsx', [DESTINO_ORIGEM$]) TB
-- Where TB.[CODIGO FILIAL DESTINO]	= @Filial

Select ORIGEM,
	   HDLDESTINO																[FILIAL],
	   STATUS,
	   PLACA,
	   DATACHEGADA																[CHEGADA],
	   (Select Sum(GLOP_VIAGEMDOCUMENTOS.VOLUMES)
	      From GLOP_VIAGEMDOCUMENTOS
		 Where GLOP_VIAGEMDOCUMENTOS.VIAGEM			= HDLVIAGEM
		   And GLOP_VIAGEMDOCUMENTOS.PARADA			= HDLPARADA
		   And GLOP_VIAGEMDOCUMENTOS.SITUACAO		<> 210)						[VOLUME],
	   Sum(IIF(LIDO = 'S', VOLUME, 0))											[VOLLIDO],
	   Sum(VOLUME)																[VOLTOTAL],
	   INICIOLEITURA															[INICIODESCARGA],
	   FIMLEITURA																[FIMDESCARGA],
	   CONFERENTE,	   
	   NUMEROVIAGEM,
	   [LinhaViagem],
	   [CodFilialEntrega],
	   [FilialEntrega],
	   --ETM.[TEMPO MEDIO]														[META],
	   IsNull((Select Sum(DateDiff(Minute, GLGV_PROCESSOPAUSAS.DATAHORAPAUSA, 
										   IsNull(GLGV_PROCESSOPAUSAS.DATAHORAREINICIO, GetDate())))
		 	     From GLGV_PROCESSOPAUSAS
		 	    Where GLGV_PROCESSOPAUSAS.PROCESSO		= TB.PROCESSO), 0)		[PAUSA],
	   Sum(PESOTOTAL)															[PESO]
  From (Select GLGL_FILIAIS.SIGLA						[ORIGEM],
			   GLGL_FILIAIS.HANDLE						[HDLORIGEM],
			   FILIAIS.HANDLE							[HDLDESTINO],
			   Case GLGV_PLANOCARGADESCARGAS.STATUS
					When 1329 Then Case IsNull(GLGV_PROCESSOS.STATUS, 0)
										When 0	  Then 'Aguardando Descarga'
										When 1332 Then 'Aguardando Descarga'
										When 1333 Then 'Descarregando'
										When 1334 Then 'Parado'
										When 1337 Then 'Descarregando'
										Else 'Descarregando'
									End
					When 1330 Then 'Finalizado'
					When 1340 Then 'Ag. Processos de Coleta'
					Else 'Descarregando'
			   End										[STATUS],
			   MA_RECURSOS.CODIGO						[PLACA],
			   GLOP_VIAGEMPARADAS.CHEGADA				[DATACHEGADA],
			   Case GLGV_ETIQUETAS.PALETIZADA
					When 'N' Then IIF(Not IsNull(GLGL_DOCUMENTOS.DOCCLIVOLUME, GLGL_DOCUMENTOCLIENTES.VOLUME) Is Null, IsNull(GLGL_DOCUMENTOS.DOCCLIVOLUME, GLGL_DOCUMENTOCLIENTES.VOLUME),  Count(Distinct GLGV_PROCESSOITENS.HANDLE))
					When 'S' Then IsNull(GLGL_DOCUMENTOS.DOCCLIVOLUME, GLGL_DOCUMENTOCLIENTES.VOLUME)
					Else Count(Distinct GLGV_PROCESSOITENS.HANDLE)
			   End										[VOLUME],
			   IsNull(GLGL_DOCUMENTOS.DOCCLIPESOTOTAL, GLGL_DOCUMENTOCLIENTES.PESOTOTAL)			[PESOTOTAL],
			   GLGV_PROCESSOITENS.LIDO					[LIDO],
			   GLGV_PROCESSOS.HANDLE					[PROCESSO],
			   GLGV_PROCESSOS.DATAABERTURA				[INICIOLEITURA]												,
			   GLGV_PROCESSOS.DATAENCERRAMENTOLEITURAS	[FIMLEITURA],
			   GN_PESSOAS.NOME							[CONFERENTE],
			   GLOP_VIAGENS.NUMEROVIAGEM,
			   GLOP_VIAGENS.HANDLE						[HDLVIAGEM],
			   GLOP_VIAGEMPARADAS.HANDLE				[HDLPARADA],
			   GLOP_LINHAVIAGENS.NOME                   [LinhaViagem],
			   GLENTREGA.HANDLE							[CodFilialEntrega],
			   GLENTREGA.SIGLA							[FilialEntrega]

		  From GLOP_VIAGENS
		 Inner Join GLGV_PLANOCARGADESCARGAS			On GLGV_PLANOCARGADESCARGAS.VIAGEM				= GLOP_VIAGENS.HANDLE
		 Inner Join MA_RECURSOS							On MA_RECURSOS.HANDLE							= GLGV_PLANOCARGADESCARGAS.VEICULO 

		 Inner Join GLOP_VIAGEMPARADAS					On GLOP_VIAGEMPARADAS.HANDLE					= GLGV_PLANOCARGADESCARGAS.PARADA
		 Inner Join FILIAIS								On FILIAIS.HANDLE								= GLOP_VIAGEMPARADAS.FILIAL
		 Inner Join GLGL_FILIAIS						On GLGL_FILIAIS.HANDLE							= GLOP_VIAGENS.FILIALORIGEM

		 Inner Join GLGV_PROCESSOS						On GLGV_PROCESSOS.PLANOCARGADESCARGA			= GLGV_PLANOCARGADESCARGAS.HANDLE
		 Inner Join GLGV_PROCESSOITENS					On GLGV_PROCESSOITENS.PROCESSO					= GLGV_PROCESSOS.HANDLE
													   And GLGV_PROCESSOITENS.RETIRADO					= 'N'
		 Inner Join GLGV_ETIQUETAVOLUMES				On GLGV_ETIQUETAVOLUMES.HANDLE					= GLGV_PROCESSOITENS.VOLUME
		 Inner Join GLGV_ETIQUETAS						On GLGV_ETIQUETAS.HANDLE						= GLGV_ETIQUETAVOLUMES.ETIQUETA
			
		  Left Join GLGV_PROCESSOS			GVPUNIT		On GVPUNIT.UNITIZADOR							= GLGV_ETIQUETAS.UNITIZADOR
													   And GVPUNIT.STATUS								<> 1336
		  Left Join GLGV_PROCESSOITENS		GVPIUNIT	On GVPIUNIT.PROCESSO							= GVPUNIT.HANDLE
													   And GVPIUNIT.RETIRADO							= 'N'
		  Left Join GLGV_ETIQUETAVOLUMES	GVEVUNIT	On GVEVUNIT.HANDLE								= GVPIUNIT.VOLUME
		  Left Join GLGV_ETIQUETAS			GVEUNIT		On GVEUNIT.HANDLE								= GVEVUNIT.ETIQUETA
		
		  Left Join GLGL_DOCUMENTOCLIENTES				On GLGL_DOCUMENTOCLIENTES.HANDLE				= IsNull(GVEUNIT.DOCUMENTOCLIENTE, GLGV_ETIQUETAS.DOCUMENTOCLIENTE)
		  Left Join GLGL_DOCUMENTOS						On GLGL_DOCUMENTOS.HANDLE						= IsNull(GVEUNIT.MINUTA , GLGV_ETIQUETAS.MINUTA)
		  
		  Left Join GLGV_PROCESSOPARTICIPANTES			
		 Inner Join GN_PESSOAS							On GN_PESSOAS.HANDLE							= GLGV_PROCESSOPARTICIPANTES.PESSOA
														On GLGV_PROCESSOPARTICIPANTES.PROCESSO			= GLGV_PROCESSOS.HANDLE
													   And GLGV_PROCESSOPARTICIPANTES.TIPOPARTICIPANTE	= 511
		Inner Join GLGL_FILIAIS GLENTREGA		On GLENTREGA.HANDLE					= GLOP_VIAGEMPARADAS.FILIAL
		Inner Join GLOP_LINHAVIAGENS			On GLOP_LINHAVIAGENS.HANDLE			= GLOP_VIAGENS.LINHAVIAGEM
		 Where GLOP_VIAGENS.TIPOVIAGEM																	= 172
		   And GLGV_PLANOCARGADESCARGAS.TIPO															= 'D'
		   And GLGV_PROCESSOS.STATUS																	<> 1336
		   And GLGV_PROCESSOS.TIPO																		In (2)
		   And GLGV_PROCESSOS.SUBTIPO																	In (1)
		   And ((Cast(GLOP_VIAGEMPARADAS.CHEGADA	As Date)											= Cast(GetDate() As Date))
			Or  (Cast(GLOP_VIAGEMPARADAS.CHEGADA	As Date)											>= DateAdd(Month, -1, Cast(GetDate() As Date))
		   And   (GLGV_PLANOCARGADESCARGAS.STATUS														= 1329
		    Or    Cast(GLGV_PROCESSOS.DATAENCERRAMENTO	As Date)										= Cast(GetDate() As Date))))
		 Group By GLGV_ETIQUETAS.DOCUMENTOCLIENTE,
				  FILIAIS.NOME,								
				  GLGL_FILIAIS.SIGLA,
				  GLOP_VIAGEMPARADAS.CHEGADA,	
				  GLGL_DOCUMENTOCLIENTES.VOLUME,
				  GLGL_DOCUMENTOCLIENTES.PESOTOTAL,
				  GLGV_PROCESSOITENS.LIDO,
				  GLGV_PROCESSOS.HANDLE,
				  GLGV_PROCESSOS.DATAABERTURA,
				  GLGV_PROCESSOS.DATAENCERRAMENTOLEITURAS,
				  GN_PESSOAS.NOME,
				  GLOP_VIAGENS.NUMEROVIAGEM,
				  GLGV_ETIQUETAS.PALETIZADA,
				  GVEUNIT.DOCUMENTOCLIENTE,
				  GLGV_PLANOCARGADESCARGAS.STATUS,
				  GLGV_PROCESSOS.STATUS,
				  MA_RECURSOS.CODIGO,
				  GLGL_FILIAIS.HANDLE,
				  FILIAIS.HANDLE,
				  GLGL_DOCUMENTOS.DOCCLIVOLUME,
				  GLGL_DOCUMENTOS.DOCCLIPESOTOTAL,
				  GLOP_VIAGENS.HANDLE,
				  GLOP_VIAGEMPARADAS.HANDLE,
				  GLOP_LINHAVIAGENS.NOME,
				  GLENTREGA.SIGLA,
				  GLENTREGA.HANDLE
				  
				  
				  ) TB

  --Left Join #TMETA ETM							On ETM.[CODIGO FILIAL DESTINO]						= HDLDESTINO
		--									   And ETM.[CODIGO FILIAL ORIGEM]						= HDLORIGEM
 Group By ORIGEM,
		  STATUS,
		  PLACA,
		  DATACHEGADA,
		  INICIOLEITURA,
		  FIMLEITURA,
		  PROCESSO,
		  CONFERENTE,
		  NUMEROVIAGEM,
		  HDLORIGEM,
		  HDLDESTINO,
		  --ETM.[TEMPO MEDIO],
		  NUMEROVIAGEM,
		  HDLVIAGEM,
		  HDLPARADA,
		  [LinhaViagem],
	      [FilialEntrega],
		  [CodFilialEntrega]

--Drop Table #TMETA