--Indicar documentos que possuem comprovante de entrega integrado, porém sem integração com o cliente
SELECT 1 ORDEM,
        DOC.HANDLE,
	FILIAIS.NOME,
	CAST(DOC.NUMEROSDOCUMENTOS AS VARCHAR(100))NUMEROSDOCUMENTOS,
	DOC.NUMERO DOCUMENTO,
	DOC.DATAENTREGA,
	ANEXO.K_INTEGRADOCLIENTE INTEGRADO,
	ANEXO.K_DTINTEGRACAOCLIENTE DATAINTEGRACAO,
	ANEXO.ARQUIVO Arquivo,
	ANEXO.DESCRICAO,
	CASE
		WHEN ANEXO.K_INTEGRADOCLIENTE = 'S' THEN 'INTEGRADO'
	ELSE 'NÃO INTEGRADO'
	END AS TIPO
FROM GLGL_DOCUMENTOS DOC
INNER JOIN GLGL_DOCUMENTOANEXOS ANEXO ON ANEXO.DOCUMENTO = DOC.HANDLE and ANEXO.CLASSIFICACAO IN(497,1281) --COMPROVANTE DE ENTREGA E COMPROVANTE DE ENTREGA MOBILE
INNER JOIN FILIAIS ON FILIAIS.HANDLE = DOC.FILIAL
INNER JOIN GLCM_REGOPERACIONAIS REG ON DOC.REGOPERACIONAL = REG.HANDLE
INNER JOIN GN_PESSOAS P ON DOC.REMETENTE = P.HANDLE 
WHERE 1=1
AND ((DOC.TIPODOCUMENTO IN (2)) OR ((DOC.TIPODOCUMENTO = 6 AND DOC.TIPORPS IN (322))))
AND ANEXO.K_INTEGRADOCLIENTE = 'N'
AND REG.K_ARQUIVAMENTODIGITAL = 'S'
AND DOC.DATAENTREGA >= '2019-11-25'
AND DOC.DATAENTREGA < '2019-12-13'
AND P.CGCCPF LIKE '%71.673.990%'
AND NOT EXISTS (Select 1
					From GLGL_DOCUMENTOANEXOS DLA
				Where 1=1 
				AND DLA.K_INTEGRADOCLIENTE = 'S'
				--AND DLA.DOCUMENTO = 41218891
				AND DLA.DOCUMENTO = DOC.HANDLE 
				AND DLA.CLASSIFICACAO IN(497,1281))
