DECLARE @CONTRATOFRETE INT = 1336854

SELECT DISTINCT 

	ISNULL(ISNULL(DA.HANDLE, CP.NUMERO), D.NUMERO) AS 'NUMERO/COLETA'
	,ISNULL(TP.NOME, 'COLETA') AS 'TIPO DOCUMENTO'
	,PREM.NOME AS 'REMETENTE'
	,BREM.NOME AS BAIRROREMETENTE
	,CONCAT(MUREM.NOME,'-',ESREM.SIGLA) AS MUNICIPIO
	,PDES.NOME AS DESTINATARIO
	,BDES.NOME AS BAIRRODEST
	,CONCAT(MUDES.NOME,'-',ESDES.SIGLA) AS MUNICIPIODEST


	,CONTRATO.FILIAL
	,CONTRATO.NUMERO AS NUMEROCONTRATO
	
	,CONTRATOCALC.DOCUMENTOLOGISTICA
	,CONTRATOCALC.CLASSIFICACAO
	,CONTRATOCALC.COMPONENTETARIFA
	,CASE
		WHEN CONTRATOCALC.CLASSIFICACAO IN (9) THEN CONTRATOCALC.VALORFINALICMS
	ELSE 0
	END AS PRODUTIVIDADEKG
	

FROM GLOP_CONTRATOFRETES CONTRATO
INNER JOIN GLOP_CONTRFRETDOCCALCULOS CONTRATOCALC ON CONTRATO.HANDLE = CONTRATOCALC.CONTRATOFRETE
INNER JOIN GLGL_DOCUMENTOS D ON CONTRATOCALC.DOCUMENTOLOGISTICA = D.HANDLE
LEFT JOIN GLOP_COLETAPEDIDOS CP ON CONTRATOCALC.PEDIDOCOLETA = CP.HANDLE
LEFT JOIN GLGL_TIPODOCUMENTOS TP ON TP.HANDLE = D.TIPODOCUMENTO
LEFT JOIN GLGL_DOCUMENTOASSOCIADOS DA ON D.HANDLE = DA.DOCUMENTOLOGISTICA
LEFT JOIN GN_PESSOAS PREM ON D.REMETENTE = PREM.HANDLE
LEFT JOIN GLGL_PESSOAENDERECOS EREM ON EREM.HANDLE = D.ORIGEMENDERECO
LEFT JOIN BAIRROS BREM ON BREM.HANDLE = EREM.BAIRRO
LEFT JOIN MUNICIPIOS MUREM ON MUREM.HANDLE = EREM.MUNICIPIO
LEFT JOIN ESTADOS ESREM ON ESREM.HANDLE = MUREM.ESTADO
LEFT JOIN GN_PESSOAS PDES ON D.DESTINATARIO = PDES.HANDLE

LEFT JOIN GLGL_PESSOAENDERECOS EDES ON EDES.HANDLE = D.DESTINATARIOENDERECO
LEFT JOIN BAIRROS BDES ON BDES.HANDLE = EDES.BAIRRO
LEFT JOIN MUNICIPIOS MUDES ON MUDES.HANDLE = EDES.MUNICIPIO
LEFT JOIN ESTADOS ESDES ON ESDES.HANDLE = MUDES.ESTADO




WHERE CONTRATO.HANDLE = @CONTRATOFRETE
AND CONTRATOCALC.CLASSIFICACAO IN (9)
--AND CONTRATOCALC.COMPONENTETARIFA IN (64034,64404,69589,68804,68808)
