DROP TABLE IF EXISTS #TempInventario

SELECT 
		EQUIP.EQUIPAMENTO
		, MAX(EQUIP.DATAHORA) AS DATAHORA 

INTO #TempInventario
FROM K_GLOP_INVENTARIOEQUIPITENS EQUIP
--INNER JOIN MA_RECURSOS REC ON EQUIP.EQUIPAMENTO = REC.HANDLE
--INNER JOIN K_GLOP_INVENTARIOEQUIPAMENTOS INVENTARIO ON EQUIP.INVENTARIO = INVENTARIO.HANDLE
--INNER JOIN Z_GRUPOUSUARIOS USU ON EQUIP.USUARIO = USU.HANDLE
--INNER JOIN FILIAIS FI ON INVENTARIO.FILIAL = FI.HANDLE

GROUP BY EQUIP.EQUIPAMENTO

SELECT 

	REC.NOME AS CODIGO 
	,FI.NOME AS FILIAL
	,USU.NOME
	,TI.DATAHORA


FROM #TempInventario TI
INNER JOIN K_GLOP_INVENTARIOEQUIPITENS EQUIP
	ON EQUIP.EQUIPAMENTO = TI.EQUIPAMENTO
	AND EQUIP.DATAHORA = TI.DATAHORA 
INNER JOIN Z_GRUPOUSUARIOS USU 
	ON EQUIP.USUARIO = USU.HANDLE
INNER JOIN MA_RECURSOS REC 
	ON EQUIP.EQUIPAMENTO = REC.HANDLE

INNER JOIN K_GLOP_INVENTARIOEQUIPAMENTOS INVENTARIO 
	ON EQUIP.INVENTARIO = INVENTARIO.HANDLE
INNER JOIN FILIAIS FI 
	ON INVENTARIO.FILIAL = FI.HANDLE

ORDER BY 1