--Indicar documentos que possuem comprovante de entrega integrado, porém sem integração com o cliente
SELECT 1 ORDEM,
        DOC.HANDLE,
	FILIAIS.NOME,
	CAST(DOC.NUMEROSDOCUMENTOS AS VARCHAR(100))NUMEROSDOCUMENTOS,
	DOC.NUMERO DOCUMENTO,
	DOC.DATAENTREGA,
	ANEXO.K_INTEGRADOCLIENTE INTEGRADO,
	ANEXO.K_DTINTEGRACAOCLIENTE DATAINTEGRACAO,
	ANEXO.ARQUIVO Arquivo,
	ANEXO.DESCRICAO,
	CASE
		WHEN ANEXO.K_INTEGRADOCLIENTE = 'S' THEN 'INTEGRADO'
	ELSE 'NÃO INTEGRADO'
	END AS TIPO
FROM GLGL_DOCUMENTOS DOC
INNER JOIN GLGL_DOCUMENTOANEXOS ANEXO ON ANEXO.DOCUMENTO = DOC.HANDLE and ANEXO.CLASSIFICACAO IN(497,1281) --COMPROVANTE DE ENTREGA E COMPROVANTE DE ENTREGA MOBILE
INNER JOIN FILIAIS ON FILIAIS.HANDLE = DOC.FILIAL
INNER JOIN GLCM_REGOPERACIONAIS REG ON DOC.REGOPERACIONAL = REG.HANDLE
INNER JOIN GN_PESSOAS P ON DOC.REMETENTE = P.HANDLE 
WHERE 1=1
AND ((DOC.TIPODOCUMENTO IN (2)) OR ((DOC.TIPODOCUMENTO = 6 AND DOC.TIPORPS IN (322))))
AND ANEXO.K_INTEGRADOCLIENTE = 'N'
AND REG.K_ARQUIVAMENTODIGITAL = 'S'
AND DOC.DATAENTREGA >= '2019-11-25'
AND DOC.DATAENTREGA < '2019-12-13'
AND P.CGCCPF LIKE '%71.673.990%'
AND NOT EXISTS (Select 1
					From GLGL_DOCUMENTOANEXOS DLA
				Where 1=1 
				AND DLA.K_INTEGRADOCLIENTE = 'S'
				--AND DLA.DOCUMENTO = 41218891
				AND DLA.DOCUMENTO = DOC.HANDLE 
				AND DLA.CLASSIFICACAO IN(497,1281))
UNION ALL
--* Alerta de arquivos recusados
SELECT 2 ORDEM,
        DOC.HANDLE,
	FILIAIS.NOME,
	CAST(DOC.NUMEROSDOCUMENTOS AS VARCHAR(100))NUMEROSDOCUMENTOS,
	DOC.NUMERO DOCUMENTO,
	DOC.DATAENTREGA,
	'' AS INTEGRADO,
	'' AS DATAINTEGRACAO,
	'' AS Arquivo,
	'' AS DESCRICAO,
	'RECUSADOS' AS TIPO
FROM GLGL_DOCUMENTOS DOC
--INNER JOIN GLGL_DOCUMENTOANEXOS ANEXO ON ANEXO.DOCUMENTO = DOC.HANDLE and ANEXO.CLASSIFICACAO IN(497,1281) --COMPROVANTE DE ENTREGA E COMPROVANTE DE ENTREGA MOBILE
INNER JOIN FILIAIS ON FILIAIS.HANDLE = DOC.FILIAL
INNER JOIN GLCM_REGOPERACIONAIS REG ON DOC.REGOPERACIONAL = REG.HANDLE
INNER JOIN GN_PESSOAS P ON DOC.REMETENTE = P.HANDLE 
WHERE 1=1
AND ((DOC.TIPODOCUMENTO IN (2)) OR ((DOC.TIPODOCUMENTO = 6 AND DOC.TIPORPS IN (322))))
--AND ANEXO.K_INTEGRADOCLIENTE = 'N'
AND REG.K_ARQUIVAMENTODIGITAL = 'S'
AND DOC.DATAENTREGA >= '2019-11-25'
AND DOC.DATAENTREGA < '2019-12-13'
--AND P.CGCCPF LIKE '%71.673.990%'
AND NOT EXISTS (Select 1
					From GLGL_DOCUMENTOANEXOS DLA
				Where 1=1 
				--AND DLA.K_INTEGRADOCLIENTE = 'S'
				AND DLA.DOCUMENTO = DOC.HANDLE 
				AND DLA.CLASSIFICACAO IN(497,1281))
AND DOC.DEVOLUCAO = 'N'

--* Documentos finalizados sem comprovante de entrega
SELECT 3 ORDEM,
        DOC.HANDLE,
	FILIAIS.NOME,
	CAST(DOC.NUMEROSDOCUMENTOS AS VARCHAR(100))NUMEROSDOCUMENTOS,
	DOC.NUMERO DOCUMENTO,
	DOC.DATAENTREGA,
	ANEXO.K_INTEGRADOCLIENTE INTEGRADO,
	ANEXO.K_DTINTEGRACAOCLIENTE DATAINTEGRACAO,
	ANEXO.ARQUIVO Arquivo,
	ANEXO.DESCRICAO,
	'DOC. ENTREGUE, SEM COMPROVANTE' AS TIPO
FROM GLGL_DOCUMENTOS DOC
INNER JOIN GLGL_DOCUMENTOANEXOS ANEXO ON ANEXO.DOCUMENTO = DOC.HANDLE 
INNER JOIN FILIAIS ON FILIAIS.HANDLE = DOC.FILIAL
INNER JOIN GLCM_REGOPERACIONAIS REG ON DOC.REGOPERACIONAL = REG.HANDLE
INNER JOIN GN_PESSOAS P ON DOC.REMETENTE = P.HANDLE 
WHERE 1=1
AND ((DOC.TIPODOCUMENTO IN (2)) OR ((DOC.TIPODOCUMENTO = 6 AND DOC.TIPORPS IN (322))))
--AND ANEXO.K_INTEGRADOCLIENTE = 'N'
--AND REG.K_ARQUIVAMENTODIGITAL = 'S'
AND DOC.DATAENTREGA >= '2019-11-25'
AND DOC.DATAENTREGA < '2019-12-13'
AND P.CGCCPF LIKE '%71.673.990%'
AND ANEXO.CLASSIFICACAO NOT IN(497,1281) --COMPROVANTE DE ENTREGA E COMPROVANTE DE ENTREGA MOBILE


--------------------------------------------------------------------------------------------------------------------------------------

declare @BeginDate DATE = '2019-12-01'
declare @EndDate DATE = '2019-12-11'

--SET ANSI_NULLS ON

declare @BeginDate DATE = DateAdd(mm, DateDiff(mm,0,GetDate()) + 0, 0)
declare @EndDate DATE = GETDATE()

DROP TABLE IF EXISTS #TEMPOCC

SELECT 
	OCORREN.HANDLE
	,K_DATAALTERACAO
	,EDIDATAHORAENVIO
	,ENVIAEDIMANUAL
	,DATAENVIOEDIMANUAL
	,ESTORNADO
	,DOCUMENTO
	,NOTAFISCAL
	,ENVIAEDI
	,OCORREN.FILIAL
	,OCORREN.OCORRENCIA
	,1 AS TIPO 
INTO #TEMPOCC
FROM GLOP_OCORRENCIAS OCORREN  
INNER JOIN GLOP_MOTIVOOCORRENCIAS MOTIV ON MOTIV.HANDLE = OCORREN.OCORRENCIA   
LEFT JOIN GLOP_OCORRENCIALOGS LOG ON LOG.OCORRENCIA = OCORREN.HANDLE AND LOG.DESCRICAO = 'Inclusão'            
WHERE  (((MOTIV.ENVIAEDI = 'S' AND OCORREN.ENVIAEDIMANUAL = 'S') 
AND OCORREN.ESTORNADO = 'N'                                              
AND (CAST(OCORREN.K_DATAALTERACAO AS DATE) BETWEEN '2019-12-11' AND '2019-12-11'))                               
--OR ((OCORREN.ENVIAEDIMANUAL = 'S')                                                                             
--AND (CAST(OCORREN.DATAENVIOEDIMANUAL AS DATE) BETWEEN '2019-12-11' AND '2019-12-11')))  
AND OCORREN.EDIDATAHORAENVIO IS NULL)

UNION ALL

SELECT 
	OCORREN.HANDLE
	,K_DATAALTERACAO
	,EDIDATAHORAENVIO
	,ENVIAEDIMANUAL
	,DATAENVIOEDIMANUAL
	,ESTORNADO
	,DOCUMENTO
	,NOTAFISCAL
	,ENVIAEDI
	,OCORREN.FILIAL
	,OCORREN.OCORRENCIA
	,2 AS TIPO
FROM GLOP_OCORRENCIAS OCORREN  
INNER JOIN GLOP_MOTIVOOCORRENCIAS MOTIV ON MOTIV.HANDLE = OCORREN.OCORRENCIA   
LEFT JOIN GLOP_OCORRENCIALOGS LOG ON LOG.OCORRENCIA = OCORREN.HANDLE AND LOG.DESCRICAO = 'Inclusão'            
WHERE  (((OCORREN.ENVIAEDIMANUAL = 'S')                                                                             
    AND (CAST(OCORREN.DATAENVIOEDIMANUAL AS DATE) BETWEEN '2019-12-11' AND '2019-12-11')))  
AND OCORREN.EDIDATAHORAENVIO IS NULL 
AND OCORREN.ESTORNADO = 'N'  

--select * from (

SELECT   
	    DOCCLI.NUMERO NUMERONF                                                     
	   ,DOCCLI.PEDIDO                                                              
	   ,DOCCLI.SERIE                        
	   ,CASE DOC.TIPODOCUMENTO          
					WHEN 1 THEN 'CTRC'    
					WHEN 2 THEN 'CT-e'  
					WHEN 6 THEN 'RPS' 
		END as TIPODOC
		,DATEDIFF(MINUTE,K_DATAALTERACAO,GETDATE()) DIFERENCA
	  ,FLOCORRENCIA.NOME FILIALOCORREN 
	  ,#TEMPOCC.EDIDATAHORAENVIO
	  ,#TEMPOCC.ENVIAEDI
	  ,#TEMPOCC.ENVIAEDIMANUAL
	  ,#TEMPOCC.DATAENVIOEDIMANUAL
	  ,DOC.STATUS
	  ,#TEMPOCC.ESTORNADO
	  --,CASE 
			--WHEN DATEDIFF(MINUTE,K_DATAALTERACAO,GETDATE()) <= CONVERT(INT, CAST(TB3.VALOR AS VARCHAR(50))) THEN TB3.NOME
			--WHEN DATEDIFF(MINUTE,K_DATAALTERACAO,GETDATE()) >= CONVERT(INT, CAST(TB3.VALOR AS VARCHAR(50))) THEN TB3.NOME
	  -- ELSE 'AZUL'
	  -- END AS TEST
	  ,(SELECT TOP 1 TB3.NOME
			FROM Z_AGENDAMENTOPARAMETROS TB3 
				 WHERE TB2.HANDLE = TB3.AGENDAMENTO
				 AND TB3.NOME IN('ALERTAAMARELO','ALERTAVERMELHO')
				 AND DATEDIFF(MINUTE,K_DATAALTERACAO,GETDATE()) > CONVERT(INT, CAST(TB3.VALOR AS VARCHAR(50))) 
		    ORDER BY CONVERT(INT, CAST(TB3.VALOR AS VARCHAR(50))) DESC
		) AS TEST
	  ,TB2.NOME
 
FROM #TEMPOCC                                                                               
LEFT  JOIN GLGL_DOCUMENTOS DOC ON DOC.HANDLE = #TEMPOCC.DOCUMENTO                                               
LEFT JOIN GLGL_DOCUMENTOASSOCIADOS DA ON DA.DOCUMENTOLOGISTICA = DOC.HANDLE                                    
left JOIN GLGL_DOCUMENTOCLIENTES DOCCLI ON DOCCLI.HANDLE = #TEMPOCC.NOTAFISCAL                                  
INNER JOIN GN_PESSOAS PESSOA ON PESSOA.HANDLE = DOCCLI.REMETENTE                                               
INNER JOIN GLCM_REGOPERACIONAIS REGOP ON REGOP.CONTRATO = DOCCLI.CONTRATO                                      
INNER JOIN FILIAIS FL ON FL.HANDLE = DOCCLI.FILIAL
INNER JOIN FILIAIS FLOCORRENCIA ON FLOCORRENCIA.HANDLE = #TEMPOCC.FILIAL                                                             
LEFT JOIN GLCM_REGOPEDI TB1 ON REGOP.HANDLE = TB1.REGOPERACIONAL AND TB1.GRUPOEMPRESARIALPESSOA = DOCCLI.REMETENTE
LEFT JOIN Z_AGENDAMENTOS TB2 ON TB1.OEAGENDAMENTO = TB2.HANDLE

WHERE DOC.STATUS NOT IN (236,237)                                                                                
AND DOCCLI.PEDIDO IS NOT NULL                                                                                  
AND PESSOA.HANDLE in (83768345,295201,523309,308986,83831491,77164697,451280,480985,82480219,5829821)                                                                                        
AND #TEMPOCC.EDIDATAHORAENVIO IS NULL                                                                        
--AND DOCCLI.NUMERO = 22685110
--AND dbo.BL_EDIDevolvidoOrigem(DOCCLI.HANDLE,#TEMPOCC.OCORRENCIA) = 1                                                  

--) AS T1

--PIVOT(
--    COUNT(VALOR) 
--    FOR PARAMETRO IN (
--        [ALERTAAMARELO]
--		,[ALERTAVERMELHO])
--) AS pivot_table;


