SELECT 
	--R.HANDLE
	R.FILIAL AS FILIALCONTABIL
	,F.NOME AS NOMEFILIALCONTABIL
	,R.LOCALFILIAL AS FILIALLOCALIZACAO
	,FO.NOME AS NOMEFILIALLOCALIZACAO
	,R.DATAINCLUSAO
	,R.DATAALTERACAO	
	,R.CODIGO
	,R.TIPOVEICULO
	,VT.NOME
	,R.GLSUBTIPO
	,VST.NOME
--*

FROM MA_RECURSOS R
INNER JOIN MF_VEICULOTIPOS VT 
	ON R.TIPOVEICULO = VT.HANDLE
LEFT JOIN FILIAIS F
	ON R.FILIAL = F.HANDLE
LEFT JOIN FILIAIS FO
	ON R.LOCALFILIAL = FO.HANDLE
LEFT JOIN GLMF_VEICULOSUBTIPOS VST
	ON R.GLSUBTIPO = VST.HANDLE

WHERE 1=1
--AND R.CODIGO LIKE '%03240%' 
AND VT.NOME IN ('Unitizador')

--IN ('01374-GLA','03240-GLA','00003-GLA') --01374-GLA NUMERO QUE IDENTIFICA UMA GAIOLA (EXEMPLO DE NUMERO)

--GROUP BY R.CODIGO
--HAVING COUNT(*) > 1