--DECLARE @DATA DATETIME = GETDATE()
 
--DROP TABLE IF EXISTS #TempServicoLogistica
SELECT * FROM (
  SELECT DISTINCT 
		 DF2.NOME AS [Filial Porta Pallet]
		 ,CASE WHEN EXISTS(SELECT 1 FROM K_PORTAPALETEDOCUMENTOS AA WITH(NOLOCK)                                                        
							  INNER JOIN K_PORTAPALETEENDERECOS BB WITH(NOLOCK) ON (AA.ENDERECO=BB.HANDLE)                                      
							  WHERE AA.DOCUMENTOLOGISTICA=D.HANDLE AND AA.DATAENTRADA = PD.DATAENTRADA AND AA.ENDERECOATIVO IS NOT NULL)  THEN 'Armazenado' 
		  ELSE 'Liberado' END AS [Situação]
		  ,CAST( STUFF((SELECT ' / ' + BB.ENDERECOCOMPLETO FROM K_PORTAPALETEDOCUMENTOS AA WITH(NOLOCK)          
														 INNER JOIN K_PORTAPALETEENDERECOS BB WITH(NOLOCK) ON (AA.ENDERECO=BB.HANDLE)  
														 WHERE AA.DOCUMENTOLOGISTICA=D.HANDLE AND AA.DATAENTRADA = PD.DATAENTRADA FOR XML PATH('')),2,1,'') AS VARCHAR(200)) AS ENDERECO_COMPLETO  

		,DF.NOME AS [Filial Emissão]
		,ISNULL(REM.CGCCPF,REM2.CGCCPF) [CNPJ Remetente]
		,ISNULL(REM.NOME,REM2.NOME) AS [Remetente]
		,ISNULL(DST.CGCCPF,REM2.CGCCPF) [CNPJ Destinatario]
		,ISNULL(DST.NOME,DST2.NOME) AS [Destinatario]
		,TOMADOR.NOME AS [Nome Tomador Serviço]
		--,D.HANDLE
		,D.NUMERO AS [Número Documento]
		,DT.NOME AS [Tipo Documento]
		,CAST(D.DATAEMISSAO AS DATE) AS [Data Emissão]
		,D.DOCCLIVALORTOTAL AS [Valor Mercadoria]
		,D.VALORCONTABIL AS [Valor Frete]
		,D.DOCCLIPESOCONSIDERADO AS [Peso Total]
		,D.DOCCLIVOLUME AS [Volumes]
		,CAST(PD.DATAENTRADA AS DATE) AS [Data Entrou]
		,CAST(PD.DATASAIDA AS DATE) AS [Data Saiu]
		,DATEDIFF(DAY,PD.DATAENTRADA,ISNULL(PD.DATASAIDA,GETDATE())) AS [Total Dias]
		,CAST( STUFF((SELECT ' / ' + CAST(INF.NUMERO AS VARCHAR(10)) FROM GLGL_DOCUMENTOCLIENTES INF(NOLOCK)          
																INNER JOIN GLGL_DOCUMENTOASSOCIADOS IDOCASSOC(NOLOCK) ON (IDOCASSOC.DOCUMENTOCLIENTE=INF.HANDLE)  
																WHERE IDOCASSOC.DOCUMENTOLOGISTICA=D.HANDLE FOR XML PATH('')),2,1,'') AS VARCHAR(200)) AS [Notas Fiscais]
		
		
		,RPS.NUMERO AS [RPS Cobrança]
		,CAST(RPS.DATAEMISSAO AS DATE) AS DATAEMISSAO
		,RPS.VALORCONTABIL
		,RPS.VALORTOTALRECEBER
		,MOTIVOOCORRENCIA.DESCRICAO
		,CAST(OCORRENCIA.INCLUIDOEM AS DATE) DATAINCLUSAOOCORRENCIA
		,CAST(OCORRENCIA.CONCLUIDOEM AS DATE) DATACONCLUSAOOCORRENCIA
		

		,CASE 
			WHEN OCORRENCIA.CONCLUIDOEM IS NOT NULL	THEN DATEDIFF(DAY,OCORRENCIA.INCLUIDOEM,OCORRENCIA.CONCLUIDOEM )
		ELSE DATEDIFF(DAY,OCORRENCIA.INCLUIDOEM,GETDATE() )
		END AS [Dias em Aberto]
		,CAST(SERVICO.DATAINICIO AS DATE) AS [Data Inicial Servico]
		,CAST(SERVICO.DATATERMINO AS DATE) [Data Final Servico]
		,SERVICOLOGISTICA.HANDLE AS [Id Servico Logistica]
		,SERVICOLOGISTICA.DESCRICAO [Servico Logística]
		,RPS.VALORTOTALRECEBER [Valor Total Receber Original]
		,RPS.VALORTOTAL AS [Valor Total Original]
		,NFSE.NUMERO AS [Numero NFSe]
		,FILIALNFSE.NOME AS [Filial NFSe]   
		,CASE
			WHEN  SR.HANDLE IS NOT NULL THEN 'SIM'
		ELSE 'NÃO'
		END AS CONFIGURADO                   
		                                                                                                      
		                                                                                                                                                                            
   --INTO #TempServicoLogistica                                                               
   FROM (SELECT PD.DATAENTRADA,PD.DATASAIDA,PD.PESSOARETIROU,PD.PESSOAINCLUIU,PD.DOCUMENTOLOGISTICA,PP.FILIAL       
        FROM K_PORTAPALETEDOCUMENTOS PD WITH(NOLOCK) INNER JOIN K_PORTAPALETEENDERECOS PP WITH(NOLOCK) ON (PD.ENDERECO = PP.HANDLE)          
        GROUP BY PD.DATAENTRADA,PD.DATASAIDA,PD.PESSOARETIROU,PD.PESSOAINCLUIU,PD.DOCUMENTOLOGISTICA,PP.FILIAL) PD 

   INNER JOIN GLGL_DOCUMENTOS D WITH(NOLOCK) ON (D.HANDLE = PD.DOCUMENTOLOGISTICA)    
   LEFT JOIN GLOP_SERVICOREALIZADORPS SERVICORPS WITH(NOLOCK) ON SERVICORPS.DOCUMENTOLOGISTICA = D.HANDLE
   LEFT JOIN GLGL_DOCUMENTOS RPS WITH(NOLOCK) ON RPS.HANDLE = SERVICORPS.DOCUMENTOLOGISTICARPS  
                                                
   INNER JOIN FILIAIS DF WITH(NOLOCK) ON (DF.HANDLE = D.FILIAL)    
   INNER JOIN FILIAIS DF2 WITH(NOLOCK) ON (DF2.HANDLE = PD.FILIAL)                                                                        
   LEFT JOIN ED_PESSOAS REM WITH(NOLOCK) ON (REM.HANDLE = D.REMETENTESPED)                                                               
   LEFT JOIN GN_PESSOAS REM2 WITH(NOLOCK) ON (REM2.HANDLE = D.REMETENTE)                                                                  
   INNER JOIN GLGL_TIPODOCUMENTOS DT WITH(NOLOCK) ON(DT.HANDLE = D.TIPODOCUMENTO)                                                          
   INNER JOIN GLGL_ENUMERACAOITEMS DSTATUS WITH(NOLOCK) ON (DSTATUS.CODIGO = D.STATUS)                                                     
   LEFT JOIN Z_GRUPOUSUARIOS USU WITH(NOLOCK) ON (USU.HANDLE = PD.PESSOAINCLUIU)                                                          
   LEFT JOIN Z_GRUPOUSUARIOS USURET WITH(NOLOCK) ON (USURET.HANDLE = PD.PESSOARETIROU)                                                    
   LEFT JOIN ED_PESSOAS DST WITH(NOLOCK) ON (DST.HANDLE = D.DESTINATARIOSPED)                                                            
   LEFT JOIN GN_PESSOAS DST2 WITH(NOLOCK) ON (DST2.HANDLE = D.DESTINATARIO) 
   LEFT JOIN GN_PESSOAS TOMADOR WITH(NOLOCK) ON (D.TOMADORSERVICOPESSOA = TOMADOR.HANDLE)

   LEFT JOIN GLOP_SERVICOSREALIZADOS SERVICO WITH(NOLOCK) ON SERVICO.HANDLE = SERVICORPS.SERVICOREALIZADO
   LEFT JOIN GLGL_SERVICOLOGISTICA SERVICOLOGISTICA WITH(NOLOCK) ON SERVICOLOGISTICA.HANDLE = SERVICO.SERVICO  --AND SERVICOLOGISTICA.HANDLE IN (56,58)

   LEFT JOIN K9_GLGL_SERVICOSREALIZADOS SERVICOREALIZADOAUTO WITH(NOLOCK) ON SERVICOREALIZADOAUTO.SERVICOREALIZADO = SERVICO.HANDLE
   LEFT JOIN K9_GLCM_CONFSERVICOSAUTOMATICO CONFSERVICOAUTO WITH(NOLOCK) ON CONFSERVICOAUTO.HANDLE = SERVICOREALIZADOAUTO.CONFSERVICOAUTOMATICO
   LEFT JOIN ( 
				SELECT 
					AGRUPADOR
					,MAX(CONCLUIDOEM) AS CONCLUIDOEM
					,MAX(INCLUIDOEM) AS INCLUIDOEM
					,OCORRENCIA

				FROM GLOP_OCORRENCIAS

				WHERE AGRUPADOR IS NOT NULL
				AND ESTORNADO = 'N'

				GROUP BY AGRUPADOR
					,OCORRENCIA
			 ) AS OCORRENCIA
				ON SERVICOREALIZADOAUTO.AGRUPADOROCORRENCIA = OCORRENCIA.AGRUPADOR
   LEFT JOIN GLOP_MOTIVOOCORRENCIAS MOTIVOOCORRENCIA WITH(NOLOCK) ON MOTIVOOCORRENCIA.HANDLE = OCORRENCIA.OCORRENCIA
   LEFT  JOIN GLGL_DOCLOGASSOCIADOS DOCUMENTOASSOCIADOLOG WITH(NOLOCK)
   LEFT JOIN GLGL_DOCUMENTOS NFSE WITH(NOLOCK)
		ON NFSE.HANDLE = DOCUMENTOASSOCIADOLOG.DOCUMENTOLOGISTICAPAI 
		--AND (NFSE.STATUS <> (236) OR NFSE.STATUS <> (237))
		ON DOCUMENTOASSOCIADOLOG.DOCUMENTOLOGISTICAFILHO = RPS.HANDLE
   LEFT JOIN FILIAIS FILIALNFSE WITH(NOLOCK) ON (FILIALNFSE.HANDLE = NFSE.FILIAL)
   LEFT JOIN K9_GLGL_SERVICOSREALIZADOS SR
		ON OCORRENCIA.AGRUPADOR = SR.AGRUPADOROCORRENCIA

                                                               
 WHERE 1=1
 --AND PD.FILIAL = 2 
 AND DATEPART(YY,PD.DATAENTRADA) = DATEPART(YY, GETDATE())
 AND PD.DATAENTRADA >= DateAdd(yyyy, DateDiff(yyyy,0,GetDate()), 0)
 AND PD.DATAENTRADA < GETDATE()
-- AND RPS.NUMERO = 67819
 --AND PD.DATAENTRADA < DATEADD(DD, -1,GETDATE())
 --AND D.NUMERO = 5354814
 ) AS T1

 WHERE ([Id Servico Logistica] IS NULL OR [Id Servico Logistica] IN (56,58,22))