	
--Motivo	
--Plano de Ação	
--Diferença da Entrega	
--Status da entrega	
--Lead Time TDB	
--Observação

SELECT DISTINCT
	D.NUMERO AS [Nº CT-E]
	,D.DATAEMISSAO AS [Data Emissão CT-E]
	,DC.NUMERO AS [Número NF]
	,DC.DATAEMISSAO AS [Data Emissão de NF]
	,'' [DATA DE LIBERAÇÃO PIN]
	,REM.NOME AS [Cliente Remetente]
	,REM.CGCCPF AS [CNPJ (Remetente)]
	,MUNREM.NOME AS [Cidade (Remetente)]
	,ESTREM.SIGLA AS [UF (Remetente)]
	,DEST.HANDLE AS [Cod. Destinatário]
	,DEST.NOME AS [Destinatário]
	,DEST.CGCCPF AS [CNPJ (Destinatário)]
	,MUN.NOME AS [Cidade destinatário]
	,EST.SIGLA AS [UF (Destinatário)]
	,D.DOCCLIVOLUME AS [Qtd. De Volumes]
	,ISNULL(D.DOCCLIPESOTOTAL, 0) AS [Peso real em Kgs]
	,'' AS [Tamanho real em M3]
	,ISNULL(D.DOCCLIPESOCONSIDERADO,0) AS [Peso Cobrado]
	,D.DTPREVISAOENTREGA AS [Data Prevista de Entrega]
	,D.DATAENTREGA AS [Data Real da Entrega]
	,'' AS STATUS
	


	,D.VALORTOTAL AS [Valor NF]
	
	,ISNULL(D.DOCCLIPESOCUBADOTOTAL, 0) AS [Peso cubado]
	,ISNULL(D.DOCCLIPESOCONSIDERADO,0) AS [Peso Considerado]
	,D.VALORFRETEPESO  AS [Frete peso]
	,D.VALORGRIS AS [GRIS]
	,D.VALORPEDAGIO AS [Pedágio]
	,D.VALORFRETEVALOR AS [ADV] --(Frete Valor)
	,DT.ALIQUOTAICMS AS [Aliquita de ICMS]
	,DT.VALORICMS AS [ICMS]
	,D.VALORCONTABIL AS [Frete Total]
	
	,DC.PEDIDO AS [Pedido]
	,CHAVECTE AS [Chave CTe]
	,EI.NOME AS [Tipo Entrega]
	,CASE
		WHEN D.TIPODOCUMENTO = 2 THEN 'CT-e'
		WHEN D.TIPODOCUMENTO = 6 THEN 'RPS'
	ELSE ''
	END AS TIPO

FROM GLGL_DOCUMENTOS D

INNER JOIN GN_PESSOAS REM 
	ON D.REMETENTE = REM.HANDLE

INNER JOIN GN_PESSOAS DEST
	ON D.DESTINATARIO = DEST.HANDLE

INNER JOIN MUNICIPIOS MUN
	ON DEST.MUNICIPIO = MUN.HANDLE

INNER JOIN MUNICIPIOS MUNREM
	ON REM.MUNICIPIO = MUNREM.HANDLE

INNER JOIN ESTADOS EST
	ON DEST.ESTADO = EST.HANDLE

INNER JOIN ESTADOS ESTREM
	ON REM.ESTADO = ESTREM.HANDLE

INNER JOIN GLGL_DOCUMENTOTRIBUTOS DT
	ON DT.DOCUMENTO = D.HANDLE

LEFT JOIN GLGL_DOCUMENTOASSOCIADOS DA
	ON DA.DOCUMENTOLOGISTICA = D.HANDLE

LEFT JOIN GLGL_DOCUMENTOCLIENTES DC 
	ON DC.HANDLE = DA.DOCUMENTOCLIENTE

INNER JOIN GLGL_ENUMERACAOITEMS EI
	ON EI.CODIGO = D.TIPOSERVICOFRETE

INNER JOIN FILIAIS FENT
	ON D.FILIALENTREGA = FENT.HANDLE


WHERE D.DATAEMISSAO >= '2019-11-01'
AND D.DATAEMISSAO < '2019-11-02'
AND D.TIPODOCUMENTO IN (2,6)
AND REM.CGCCPF IN (
					'59.104.760/0010-82'
					,'59.104.760/0005-15'
					,'59.104.760/0007-87'
					,'59.104.760/0003-53'
					,'59.104.760/0009-49'
					,'59.104.760/0001-91'
					,'59.104.760/0012-44'
					,'59.104.760/0004-34'
					,'59.104.760/0006-04'
				  )