DROP TABLE IF EXISTS #TempOcorrencias

SELECT DISTINCT

G.NUMERO AS [Número da NF],
H.NUMERO AS [Número do Conhecimento],
G.VALORTOTAL AS [Valor total NF],
G.VOLUME,
E.CODIGOBARRAS,
K.NOME AS FILIALENTREGA,
H.DTPREVISAOENTREGAEMISSAO,
--I.HANDLE,
--CAST(I.OBSERVACAO AS NVARCHAR(MAX)) AS OBSERVACAO,
L.NOME AS CLIENTE 

into #TempOcorrencias
FROM GLGV_OCORRENCIAITENS A
LEFT JOIN GLGV_OCORRENCIAS B ON A.OCORRENCIA = B.HANDLE
LEFT JOIN GLGV_PROCESSOITENS C ON A.ITEM = C.HANDLE
LEFT JOIN GLGV_PROCESSOS D ON C.PROCESSO = D.HANDLE
LEFT JOIN GLGV_ETIQUETAVOLUMES E ON C.VOLUME = E.HANDLE
LEFT JOIN GLGV_ETIQUETAS F ON E.ETIQUETA = F.HANDLE
LEFT JOIN GLGL_DOCUMENTOCLIENTES G ON F.DOCUMENTOCLIENTE = G.HANDLE
LEFT JOIN GLGL_DOCUMENTOS H ON G.DOCUMENTOLOGISTICA = H.HANDLE
LEFT JOIN GLOP_OCORRENCIAS I ON H.HANDLE = I.DOCUMENTO AND I.PENDENCIA = 'S'
LEFT JOIN GLOP_MOTIVOOCORRENCIAS J ON J.HANDLE = I.OCORRENCIA
LEFT JOIN FILIAIS K ON H.FILIALENTREGA = K.HANDLE
LEFT JOIN GN_PESSOAS L ON G.REMETENTE = L.HANDLE 

WHERE 1=1
--AND D.NUMERO = '2020/012418-2'
AND J.DESCRICAO = 'Falta com Busca/Reconferência'
AND G.DATAINCLUSAO >= DateAdd(yyyy, DateDiff(yyyy,0,GetDate()), 0)
AND G.DATAINCLUSAO < DATEADD(yyyy, DATEDIFF(yyyy, 0, GETDATE()) + 1, -1)
AND H.FILIALENTREGA IN (2)
AND H.STATUS = 232
--AND G.DATAINCLUSAO >= @BeginDate
--AND G.DATAINCLUSAO < @EndDate
--AND H.FILIALENTREGA IN (@filial)


SELECT DISTINCT
	[Número da NF],
    [Número do Conhecimento],
	FILIALENTREGA,
	CLIENTE,
	DTPREVISAOENTREGAEMISSAO,
	--RTRIM(LTRIM(OBSERVACAO)) AS OBSERVACAO,
    [Valor total NF],
	NULLIF(VOLUME,0) AS TOTALVOLUMES,
	ROUND(([Valor total NF]/NULLIF(VOLUME,0)),2) AS [Valor médio por volume],
	COUNT(CODIGOBARRAS) AS QTDFALTANTE,
	ROUND((([Valor total NF]/NULLIF(VOLUME,0))*COUNT(CODIGOBARRAS)),2) AS [Valor faltante]

FROM #TempOcorrencias

GROUP BY [Número da NF],
    [Número do Conhecimento],
	FILIALENTREGA,
	CLIENTE,
	DTPREVISAOENTREGAEMISSAO,
	--RTRIM(LTRIM(OBSERVACAO)),
    [Valor total NF],
	NULLIF(VOLUME,0),
	ROUND(([Valor total NF]/NULLIF(VOLUME,0)),2)