--DROP TABLE IF EXISTS #TESTE

SELECT
		FILIAL AS IDFILIAL
		,F.NOME AS NOMEFILIAL
		,[DATA]
		,SUM(TOTENDERECO) AS TOTENDERECO
		,SUM(TOTOCUPADO) AS TOTOCUPADO
		,SUM(TOTLIVRE) AS TOTLIVRE
		,SUM(TOT_DOC) AS TOT_DOC
		,SUM(TOT_VOL) AS TOT_VOL
		,ROUND(SUM(TOT_PESO),2) AS TOT_PESO
		,ROUND(SUM(TOT_VAL),2) AS TOT_VAL

--INTO #TESTE

FROM (


SELECT 
	FILIAL
	,CAST(GETDATE() AS DATE) AS [DATA]
	,COUNT(1) TOTENDERECO
	,0 AS TOTOCUPADO
	,0 AS TOTLIVRE
	,0 AS TOT_DOC
	,0 AS TOT_VOL
	,0 AS TOT_PESO
	,0 AS TOT_VAL 
FROM K_PORTAPALETEENDERECOS A 
WHERE NOT EXISTS (SELECT 1 FROM K_PORTAPALETEENDERECOS B WHERE A.HANDLE = B.NIVELSUPERIOR)
--AND  FILIAL = 2 
AND A.ATIVO = 'S'

GROUP BY FILIAL

UNION ALL

SELECT 
	FILIAL
	,CAST(GETDATE() AS DATE) AS [DATA]
	,0 AS TOTENDERECO
	,COUNT(1) TOTOCUPADO 
	,0 AS TOTLIVRE
	,0 AS TOT_DOC
	,0 AS TOT_VOL
	,0 AS TOT_PESO
	,0 AS TOT_VAL


	
FROM K_PORTAPALETEENDERECOS A 
WHERE NOT EXISTS (SELECT 1 FROM K_PORTAPALETEENDERECOS B WHERE A.HANDLE = B.NIVELSUPERIOR)
AND EXISTS (SELECT 1 FROM K_PORTAPALETEDOCUMENTOS B WHERE A.HANDLE = B.ENDERECOATIVO) 
--AND  FILIAL = 2 
AND A.ATIVO = 'S'

GROUP BY FILIAL

UNION ALL

SELECT 
	FILIAL
	,CAST(GETDATE() AS DATE) AS [DATA]
	,0 AS TOTENDERECO
	,0 AS TOTOCUPADO 
	,COUNT(1) TOTLIVRE 
	,0 AS TOT_DOC
	,0 AS TOT_VOL
	,0 AS TOT_PESO
	,0 AS TOT_VAL

FROM K_PORTAPALETEENDERECOS A 
WHERE NOT EXISTS (SELECT 1 FROM K_PORTAPALETEENDERECOS B WHERE A.HANDLE = B.NIVELSUPERIOR)
AND NOT EXISTS (SELECT 1 FROM K_PORTAPALETEDOCUMENTOS B WHERE A.HANDLE = B.ENDERECOATIVO)
--AND  FILIAL = 2 
AND A.ATIVO = 'S'

GROUP BY FILIAL 

UNION ALL

SELECT 
	FILIAL
	,CAST(GETDATE() AS DATE) AS [DATA]
	,0 AS TOTENDERECO
	,0 AS TOTOCUPADO 
	,0 AS TOTLIVRE
	,SUM(TOT_DOC) TOT_DOC
	,SUM(TOT_VOL) TOT_VOL
	,SUM(TOT_PESO) TOT_PESO
	,SUM(TOT_VAL) TOT_VAL                                               

FROM (                                                              
SELECT 1 TOT_DOC,(C.DOCCLIVOLUME) TOT_VOL                           
,(C.DOCCLIPESOCONSIDERADO) TOT_PESO,(C.DOCCLIVALORTOTAL) TOT_VAL, A.FILIAL    
FROM K_PORTAPALETEENDERECOS A                                       
INNER JOIN K_PORTAPALETEDOCUMENTOS B ON (A.HANDLE = B.ENDERECOATIVO)
INNER JOIN GLGL_DOCUMENTOS C ON (C.HANDLE = B.DOCUMENTOLOGISTICA)   
WHERE 1=1
--AND A.FILIAL = 2 

AND A.ATIVO = 'S'

GROUP BY C.DOCCLIVOLUME,C.DOCCLIPESOCONSIDERADO,C.HANDLE  ,C.DOCCLIVALORTOTAL, A.FILIAL
) AS T

GROUP BY FILIAL

) AS TABELAFINAL
INNER JOIN FILIAIS F 
	ON FILIAL = F.HANDLE

GROUP BY FILIAL
		,F.NOME
		,[DATA]


--SELECT * FROM #TESTE