DROP TABLE IF EXISTS #TempHostasMotorista
SELECT 
		MOTORISTA.CGCCPF AS colaborador_identification
		,203 AS indicador_identification
		,Cast((ISNULL(ISNULL(V.K_DATACHEGADAOMINILINK,V.K_DATACHEGADADIGITADA),V.CHEGADAEFETIVA) - ISNULL(ISNULL(V.K_DATASAIDAOMNILINK,V.K_DATASAIDADIGITADA),V.INICIOEFETIVO)) as Float) * 24.0 AS resultado
		,(SUM(DIAS)*1440) 
		+(SUM(CONVERT(INT,cast(substring(CONVERT(VARCHAR(8),CAST(TEMPOOPERACAOESTIMADO AS TIME)),1,2) AS int)*60+
		   cast(substring(CONVERT(VARCHAR(8),CAST(TEMPOOPERACAOESTIMADO AS TIME)),4,2) AS int)+ 
		   cast(substring(CONVERT(VARCHAR(8),CAST(TEMPOOPERACAOESTIMADO AS TIME)),7,2) AS int)/60.0)))

		+(SUM(CONVERT(INT,cast(substring(CONVERT(VARCHAR(8),CAST(HORAS AS TIME)),1,2) AS int)*60+
		   cast(substring(CONVERT(VARCHAR(8),CAST(HORAS AS TIME)),4,2) AS int)+ 
		   cast(substring(CONVERT(VARCHAR(8),CAST(HORAS AS TIME)),7,2) AS int)/60.0))) AS fator_0
		,V.NUMEROVIAGEM AS fator_1
		,0 AS fator_2
		,0 AS fator_3
		,0 AS fator_4
		,0 AS fator_5
		,0 AS fator_6
		,0 AS fator_7
		,0 AS fator_8
		,0 AS fator_9
		,0 AS fator_10
		,CAST(ISNULL(ISNULL(V.K_DATACHEGADAOMINILINK,V.K_DATACHEGADADIGITADA),V.CHEGADAEFETIVA) AS DATE) AS [DATA]
		,LVF.LINHAVIAGEM
		,LINHA.NOME

		


into #TempHostasMotorista
FROM GLOP_VIAGENS V
LEFT JOIN GLOP_LINHAVIAGENS LINHA ON LINHA.HANDLE = V.LINHAVIAGEM
LEFT JOIN GN_PESSOAS MOTORISTA ON V.MOTORISTA = MOTORISTA.HANDLE
LEFT JOIN GLOP_LINHAVIAGEMFILIAIS LVF ON LVF.LINHAVIAGEM = LINHA.HANDLE
--LEFT JOIN GLOP_VIAGEMDOCUMENTOS DV ON DV.VIAGEM = V.HANDLE --AND VP.HANDLE = DV.PARADA
--LEFT JOIN GLOP_VIAGEMPARADAS VP ON V.HANDLE = VP.VIAGEM  AND VP.HANDLE = DV.PARADA  

WHERE 1=1
AND ISNULL(ISNULL(V.K_DATACHEGADAOMINILINK,V.K_DATACHEGADADIGITADA),V.CHEGADAEFETIVA) >= DATEADD(DAY, -1, GETDATE())
AND ISNULL(ISNULL(V.K_DATACHEGADAOMINILINK,V.K_DATACHEGADADIGITADA),V.CHEGADAEFETIVA) < GETDATE()
--AND V.NUMEROVIAGEM = '2019/362030-2'
AND V.TIPOVIAGEM = 172
AND V.STATUS IN (194, 180, 293, 181)

GROUP BY 
	MOTORISTA.CGCCPF
		,Cast((ISNULL(ISNULL(V.K_DATACHEGADAOMINILINK,V.K_DATACHEGADADIGITADA),V.CHEGADAEFETIVA) - ISNULL(ISNULL(V.K_DATASAIDAOMNILINK,V.K_DATASAIDADIGITADA),V.INICIOEFETIVO)) as Float) * 24.0
		,V.NUMEROVIAGEM
		,CAST(ISNULL(ISNULL(V.K_DATACHEGADAOMINILINK,V.K_DATACHEGADADIGITADA),V.CHEGADAEFETIVA) AS DATE)
		,LVF.LINHAVIAGEM
		,LINHA.NOME


SELECT 
		colaborador_identification
		,indicador_identification
		,FORMAT(FLOOR(resultado)*100 + (resultado-FLOOR(resultado))*60,'00:00') as resultado
		,convert(varchar, fator_0 / 60) + ':' + right('00'+convert(varchar, fator_0 % 60), 2) as fator_0
		,fator_1
		,fator_2
		,fator_3
		,fator_4
		,fator_5
		,fator_6
		,fator_7
		,fator_8
		,fator_9
		,fator_10
		,[DATA]
		,LINHAVIAGEM
		,NOME



from #TempHostasMotorista
