SELECT A.AP
	   ,A.PARCELADIGITADA
	   ,A.DATAVENCIMENTO
	   ,A.VCTOPRORROGADO
	   ,A.DATALIQUIDACAO
	   ,A.VALOR
	   ,A.VALORESBAIXADOS
	   ,A.HISTORICO
	   ,A.MOEDA
	   ,A.VALORMOEDA
	   ,A.NUMDOCBANCO
	   ,B.HANDLE
	   ,B.DOCUMENTODIGITADO
	   ,B.DATAEMISSAO
	   ,C.NOME
	   ,D.NOME NOMEMOEDA
	   ,B.DATAREALIZACAO DATAREALIZACAO   

FROM FN_PARCELAS A, FN_DOCUMENTOS B, GN_PESSOAS C, GN_MOEDAS D  

WHERE A.DOCUMENTO = B.HANDLE 
AND B.PESSOA = C.HANDLE 
AND A.MOEDA = D.HANDLE 
AND  A.DOCUMENTO IN (SELECT DOCS.HANDLE FROM FN_DOCUMENTOS DOCS WHERE (DOCS.EMPRESA = 1) AND (A.VALOR > 0) 
AND (DOCS.ENTRADASAIDA IN ('E', 'I') AND (DOCS.ABRANGENCIA <> 'R')  
AND DOCS.TIPODEMOVIMENTO IN(1))  
AND ((DOCS.DATACANCELAMENTO IS NULL) )  
AND DOCS.DATAEMISSAO BETWEEN CONVERT(DATETIME, '01/01/2019' ,103) AND CONVERT(DATETIME, '01/01/2019' ,103)  
AND ( A.FILIAL IN  ( 2 ) ) )

ORDER BY C.NOME