SELECT 
	V.NUMEROVIAGEM
	,V.CHEGADAEFETIVA
	,EI.NOME AS TIPOVIAGEM
	,EIS.NOME AS STATUSVIAGEM

FROM GLOP_VIAGENS V
INNER JOIN GLGL_ENUMERACAOITEMS EI ON V.TIPOVIAGEM = EI.HANDLE
INNER JOIN GLGL_ENUMERACAOITEMS EIS ON V.STATUS = EIS.HANDLE
WHERE EI.CODIGO IN (169, 170, 173)
AND EIS.NOME LIKE '%Aguardando Finalização%'
AND V.CHEGADAEFETIVA >= DATEADD(DD,-3, GETDATE())
AND V.CHEGADAEFETIVA < GETDATE()

--AND K_DATACHEGADADIGITADA


