  SELECT DISTINCT 
		 DF2.NOME AS [Filial Porta Pallet]
		 ,CASE WHEN EXISTS(SELECT 1 FROM K_PORTAPALETEDOCUMENTOS AA                                                         
							  INNER JOIN K_PORTAPALETEENDERECOS BB ON (AA.ENDERECO=BB.HANDLE)                                      
							  WHERE AA.DOCUMENTOLOGISTICA=D.HANDLE AND AA.DATAENTRADA = PD.DATAENTRADA AND AA.ENDERECOATIVO IS NOT NULL)  THEN 'Armazenado' 
		  ELSE 'Liberado' END AS [Situação]
		  ,CAST( STUFF((SELECT ' / ' + BB.ENDERECOCOMPLETO FROM K_PORTAPALETEDOCUMENTOS AA          
														 INNER JOIN K_PORTAPALETEENDERECOS BB ON (AA.ENDERECO=BB.HANDLE)  
														 WHERE AA.DOCUMENTOLOGISTICA=D.HANDLE AND AA.DATAENTRADA = PD.DATAENTRADA FOR XML PATH('')),2,1,'') AS VARCHAR(200)) AS ENDERECO_COMPLETO  

		,DF.NOME AS [Filial Emissão]
		,ISNULL(REM.CGCCPF,REM2.CGCCPF) [CNPJ Remetente]
		,ISNULL(REM.NOME,REM2.NOME) AS [Remetente]
		,ISNULL(DST.CGCCPF,REM2.CGCCPF) [CNPJ Destinatario]
		,ISNULL(DST.NOME,DST2.NOME) AS [Destinatario]
		,TOMADOR.NOME AS [Nome Tomador Serviço]
		--,D.HANDLE
		,D.NUMERO AS [Número Documento]
		,DT.NOME AS [Tipo Documento]
		,D.DATAEMISSAO AS [Data Emissão]
		,D.DOCCLIVALORTOTAL AS [Valor Mercadoria]
		,D.VALORCONTABIL AS [Valor Frete]
		,D.DOCCLIPESOCONSIDERADO AS [Peso Total]
		,D.DOCCLIVOLUME AS [Volumes]
		,PD.DATAENTRADA AS [Data Entrou]
		,PD.DATASAIDA AS [Data Saiu]
		,DATEDIFF(DAY,PD.DATAENTRADA,ISNULL(PD.DATASAIDA,GETDATE())) AS [Total Dias]
		,CAST( STUFF((SELECT ' / ' + CAST(INF.NUMERO AS VARCHAR(10)) FROM GLGL_DOCUMENTOCLIENTES INF(NOLOCK)          
																INNER JOIN GLGL_DOCUMENTOASSOCIADOS IDOCASSOC(NOLOCK) ON (IDOCASSOC.DOCUMENTOCLIENTE=INF.HANDLE)  
																WHERE IDOCASSOC.DOCUMENTOLOGISTICA=D.HANDLE FOR XML PATH('')),2,1,'') AS VARCHAR(200)) AS [Notas Fiscais]
		
		
		,RPS.NUMERO AS [RPS Cobrança]
		,RPS.DATAEMISSAO
		,RPS.VALORCONTABIL
		,RPS.VALORTOTALRECEBER
		,MOTIVOOCORRENCIA.DESCRICAO
		,OCORRENCIA.INCLUIDOEM DATAINCLUSAOOCORRENCIA
		,OCORRENCIA.CONCLUIDOEM DATACONCLUSAOOCORRENCIA
		

		,CASE 
			WHEN OCORRENCIA.CONCLUIDOEM IS NOT NULL	THEN DATEDIFF(DAY,OCORRENCIA.INCLUIDOEM,OCORRENCIA.CONCLUIDOEM )
		ELSE DATEDIFF(DAY,OCORRENCIA.INCLUIDOEM,GETDATE() )
		END AS [Dias em Aberto]
		,SERVICO.DATAINICIO AS [Data Inicial Servico]
		,SERVICO.DATATERMINO [Data Final Servico]
		,SERVICOLOGISTICA.DESCRICAO [Servico Logística]
		,RPS.VALORTOTALRECEBER [Valor Total Receber Original]
		,RPS.VALORTOTAL AS [Valor Total Original]
		,NFSE.NUMERO AS [Numero NFSe]
		,FILIALNFSE.NOME AS [Filial NFSe]                         
		                                                                                                      
		                                                                                                                                                                            
                                                                  
  FROM (SELECT PD.DATAENTRADA,PD.DATASAIDA,PD.PESSOARETIROU,PD.PESSOAINCLUIU,PD.DOCUMENTOLOGISTICA,PP.FILIAL       
        FROM K_PORTAPALETEDOCUMENTOS PD INNER JOIN K_PORTAPALETEENDERECOS PP ON (PD.ENDERECO = PP.HANDLE)          
        GROUP BY PD.DATAENTRADA,PD.DATASAIDA,PD.PESSOARETIROU,PD.PESSOAINCLUIU,PD.DOCUMENTOLOGISTICA,PP.FILIAL) PD 

  INNER JOIN GLGL_DOCUMENTOS D ON (D.HANDLE = PD.DOCUMENTOLOGISTICA)    
  LEFT JOIN GLOP_SERVICOREALIZADORPS SERVICORPS ON SERVICORPS.DOCUMENTOLOGISTICA = D.HANDLE
  LEFT JOIN GLGL_DOCUMENTOS RPS ON RPS.HANDLE = SERVICORPS.DOCUMENTOLOGISTICARPS  
                                                
  INNER JOIN FILIAIS DF ON (DF.HANDLE = D.FILIAL)    
  INNER JOIN FILIAIS DF2 ON (DF2.HANDLE = PD.FILIAL)                                                                        
  LEFT JOIN ED_PESSOAS REM  ON (REM.HANDLE = D.REMETENTESPED)                                                               
  LEFT JOIN GN_PESSOAS REM2 ON (REM2.HANDLE = D.REMETENTE)                                                                  
  INNER JOIN GLGL_TIPODOCUMENTOS DT ON(DT.HANDLE = D.TIPODOCUMENTO)                                                          
  INNER JOIN GLGL_ENUMERACAOITEMS DSTATUS ON (DSTATUS.CODIGO = D.STATUS)                                                     
  LEFT JOIN Z_GRUPOUSUARIOS USU ON (USU.HANDLE = PD.PESSOAINCLUIU)                                                          
  LEFT JOIN Z_GRUPOUSUARIOS USURET ON (USURET.HANDLE = PD.PESSOARETIROU)                                                    
  LEFT JOIN ED_PESSOAS DST  ON (DST.HANDLE = D.DESTINATARIOSPED)                                                            
  LEFT JOIN GN_PESSOAS DST2 ON (DST2.HANDLE = D.DESTINATARIO) 
  LEFT JOIN GN_PESSOAS TOMADOR ON (D.TOMADORSERVICOPESSOA = TOMADOR.HANDLE)

  LEFT JOIN GLOP_SERVICOSREALIZADOS SERVICO ON SERVICO.HANDLE = SERVICORPS.SERVICOREALIZADO
  LEFT JOIN GLGL_SERVICOLOGISTICA SERVICOLOGISTICA ON SERVICOLOGISTICA.HANDLE = SERVICO.SERVICO AND SERVICOLOGISTICA.HANDLE IN (56,58)

   LEFT JOIN K9_GLGL_SERVICOSREALIZADOS SERVICOREALIZADOAUTO ON SERVICOREALIZADOAUTO.SERVICOREALIZADO = SERVICO.HANDLE
   LEFT JOIN K9_GLCM_CONFSERVICOSAUTOMATICO CONFSERVICOAUTO ON CONFSERVICOAUTO.HANDLE = SERVICOREALIZADOAUTO.CONFSERVICOAUTOMATICO
   LEFT JOIN GLOP_OCORRENCIAS OCORRENCIA ON SERVICOREALIZADOAUTO.AGRUPADOROCORRENCIA = OCORRENCIA.AGRUPADOR
   LEFT JOIN GLOP_MOTIVOOCORRENCIAS MOTIVOOCORRENCIA ON MOTIVOOCORRENCIA.HANDLE = OCORRENCIA.OCORRENCIA
   LEFT  JOIN GLGL_DOCLOGASSOCIADOS DOCUMENTOASSOCIADOLOG
   INNER JOIN GLGL_DOCUMENTOS NFSE 
		ON NFSE.HANDLE = DOCUMENTOASSOCIADOLOG.DOCUMENTOLOGISTICAPAI AND NFSE.STATUS NOT IN (236,237) 
		ON DOCUMENTOASSOCIADOLOG.DOCUMENTOLOGISTICAFILHO = RPS.HANDLE
   LEFT JOIN FILIAIS FILIALNFSE ON (FILIALNFSE.HANDLE = NFSE.FILIAL)

                                                               
 WHERE 1=1
 AND PD.FILIAL = 2   
 AND PD.DATAENTRADA >= DATEADD(DD, -1,GETDATE())
 --AND PD.DATAENTRADA < DATEADD(DD, -1,GETDATE())
 --AND D.NUMERO = 351867 