DECLARE @BeginDate Datetime = '2019-12-01'
DECLARE @EndDate Datetime = '2019-12-02'

DROP TABLE IF EXISTS #TempFracionadoEPP

SELECT 
		 VIAGEM.NUMEROVIAGEM,
		 VIAGEM.INICIOEFETIVO																				As INICIOEFETIVO,
		 IIF(DOCORIGINAL.HANDLE Is Null, IIF(DOC.HANDLE Is Null, COLETA.DATAFIM, ISNULL(DOC.DTPREVISAOENTREGAEDI,DOC.DTPREVISAOENTREGAEMISSAO)), ISNULL(DOCORIGINAL.DTPREVISAOENTREGAEDI,DOCORIGINAL.DTPREVISAOENTREGAEMISSAO))		As PREVISAOENTREGA,
		 GNPES.NOME																						AS MOTORISTA,
		 PLACA.CODIGO																						AS VEICULO,
		 CASE
			WHEN PC.CLIENTEEPP = 'N' THEN 'FRACIONADO'
		ELSE 'EPP'
	   END AS TIPOCLIENTE,
	    CASE
			WHEN DOC.TIPODOCUMENTO	= 6
			 AND DOC.TIPORPS		= 324	THEN Cast(DOCORIGINAL.NUMERO As VarChar(Max))
			ELSE IsNull(Cast(DOC.NUMERO As VarChar(Max)), COLETA.NUMERO)
	   END																								AS DOCUMENTO, 
	   COLETA.HANDLE AS COLETA,
	   (SELECT SUM(QTDADE_ENTREGA)
		  FROM (SELECT COUNT(1)										QTDADE_ENTREGA
				  FROM GLOP_VIAGEMDOCUMENTOS VIADOC
				 INNER JOIN GLOP_SERVICOREALIZADORPS SRPS
					ON SRPS.DOCUMENTOLOGISTICARPS					= VIADOC.DOCUMENTOLOGISTICA
				 INNER JOIN GLOP_VIAGENS VIA
					ON VIA.HANDLE									= VIADOC.VIAGEM
				 WHERE SRPS.DOCUMENTOLOGISTICA						= DOC.HANDLE
				   AND VIA.TIPOVIAGEM								IN (169,170,173,175)
				   AND DOC.TIPODOCUMENTO							= 2
			       And VIA.DATACANCELAMENTO							Is Null
				   And Cast(VIA.INICIOEFETIVO As Date)				<= Cast(VIAGEM.INICIOEFETIVO As Date)
				 UNION ALL
				SELECT COUNT(1)										QTDADE_ENTREGA
				  FROM GLOP_VIAGEMDOCUMENTOS VIADOC
				 INNER JOIN GLOP_SERVICOREALIZADORPS SRPS
					ON SRPS.DOCUMENTOLOGISTICARPS					= VIADOC.DOCUMENTOLOGISTICA
				 INNER JOIN GLOP_SERVICOREALIZADORPS DOCORIGINAL
					ON DOCORIGINAL.DOCUMENTOLOGISTICA				= SRPS.DOCUMENTOLOGISTICA
				 INNER JOIN GLOP_VIAGENS VIA
					ON VIA.HANDLE									= VIADOC.VIAGEM
				 WHERE DOCORIGINAL.DOCUMENTOLOGISTICARPS			=  DOC.HANDLE
				   AND VIA.TIPOVIAGEM								IN (169,170,173,175)
				   AND DOC.TIPODOCUMENTO							= 6
				   AND DOC.TIPORPS									= 324
			       And VIA.DATACANCELAMENTO							Is Null
				   And Cast(VIA.INICIOEFETIVO As Date)				<= Cast(VIAGEM.INICIOEFETIVO As Date)
				 UNION ALL
				SELECT COUNT(1)										QTDADE_ENTREGA
				  FROM GLOP_VIAGEMDOCUMENTOS
				 INNER JOIN GLOP_VIAGENS VIA
					ON GLOP_VIAGEMDOCUMENTOS.VIAGEM					= VIA.HANDLE
				 WHERE GLOP_VIAGEMDOCUMENTOS.DOCUMENTOLOGISTICA		= DOC.HANDLE
				   AND TIPOVIAGEM									IN (169,170,173,175)
			       And VIA.DATACANCELAMENTO							Is Null
				   And Cast(VIA.INICIOEFETIVO As Date)				<= Cast(VIAGEM.INICIOEFETIVO As Date)
				 UNION ALL
				SELECT COUNT(1) QTDADE_ENTREGA
				  FROM GLOP_VIAGEMDOCUMENTOS
				 Inner Join GLOP_VIAGENS VIA
					On VIA.HANDLE									= GLOP_VIAGEMDOCUMENTOS.VIAGEM
				 WHERE DOCUMENTOCOLETA								= COLETA.HANDLE
			       And VIA.DATACANCELAMENTO							Is Null
				   And Cast(VIA.INICIOEFETIVO As Date)				<= Cast(VIAGEM.INICIOEFETIVO As Date) )	AS T1 )			AS QTDADE_ENTREGAS
				   --T3.HANDLE
				,CASE
					WHEN DOC.STATUS = 227 THEN 'RETORNOS'
					WHEN DOC.STATUS IN (234, 625) THEN 'REALIZADOS'
				ELSE 'PENDENTES'
				END AS STATUSDOC


INTO #TempFracionadoEPP
  FROM GLOP_VIAGENS									AS VIAGEM
 INNER JOIN FILIAIS									AS FILIAISVG
	ON FILIAISVG.HANDLE							= VIAGEM.FILIALORIGEM
 INNER JOIN	MA_RECURSOS								AS PLACA
	ON PLACA.HANDLE								= VIAGEM.VEICULO1
 INNER JOIN	GN_PESSOAS								AS GNPES
	ON	GNPES.HANDLE							= VIAGEM.MOTORISTA
 INNER JOIN	GLOP_VIAGEMDOCUMENTOS					AS VIADOC
	ON VIAGEM.HANDLE							= VIADOC.VIAGEM
  LEFT JOIN	GLGL_DOCUMENTOS							AS DOC
	ON DOC.HANDLE								= VIADOC.DOCUMENTOLOGISTICA
  LEFT JOIN	GLGL_TIPODOCUMENTOS						AS TIPO
	ON TIPO.HANDLE								= DOC.TIPODOCUMENTO
  LEFT JOIN	GLOP_COLETAPEDIDOS						AS COLETA
	ON COLETA.HANDLE							= VIADOC.DOCUMENTOCOLETA
 INNER JOIN	GLOP_OCORRENCIAS						AS OC
	ON OC.HANDLE								= VIADOC.OCORRENCIA
 INNER JOIN	GLOP_MOTIVOOCORRENCIAS					AS MO
	ON MO.HANDLE								= OC.OCORRENCIA
 INNER JOIN	FILIAIS									AS FI
	ON FI.HANDLE								= IsNull(DOC.FILIAL, COLETA.COLETAFILIAL)
  LEFT JOIN	GLOP_SERVICOREALIZADORPS				AS SRPS
	ON SRPS.DOCUMENTOLOGISTICARPS				= VIADOC.DOCUMENTOLOGISTICA
  LEFT JOIN	GLGL_DOCUMENTOS							AS DOCORIGINAL
	ON DOCORIGINAL.HANDLE						= SRPS.DOCUMENTOLOGISTICA
  LEFT JOIN	FILIAIS									AS FILIALORIGINAL
	ON FILIALORIGINAL.HANDLE					= DOCORIGINAL.FILIAL
  LEFT JOIN GLGL_PESSOACONFIGURACOES PC 
	ON GNPES.CODIGO								= PC.HANDLE

 
 WHERE VIADOC.SITUACAO							= 216
   AND VIAGEM.TIPOVIAGEM						IN (169, 170, 173, 175)
   AND VIAGEM.INICIOEFETIVO >= @BeginDate
   AND VIAGEM.INICIOEFETIVO < @EndDate


ORDER BY IsNull(IsNull(DOCORIGINAL.HANDLE, DOC.HANDLE), COLETA.HANDLE)



DROP TABLE IF EXISTS #TempPivotFracionadoEpp

SELECT *
INTO #TempPivotFracionadoEpp
FROM   
(
    SELECT 
        *
    FROM 
        #TempFracionadoEPP
) t 
PIVOT(
    SUM(QTDADE_ENTREGAS) 
    FOR STATUSDOC IN (
        [REALIZADOS], 
        [RETORNOS], 
        [PENDENTES])
) AS pivot_table


DROP TABLE IF EXISTS #TempPivotFracionadoEppFinal

SELECT * 

INTO #TempPivotFracionadoEppFinal
FROM   
(
    SELECT 
        *
    FROM 
        #TempPivotFracionadoEpp
) t 
PIVOT(
    COUNT(DOCUMENTO) 
    FOR TIPOCLIENTE IN (
        [EPP], 
        [FRACIONADO])
) AS pivot_table;

--QTDE DOCUMENTOS	EPP	FRACIONADO	COLETAS	REALIZADO	RETORNOS

SELECT 
	NUMEROVIAGEM
	,INICIOEFETIVO
	,PREVISAOENTREGA
	,MOTORISTA
	,VEICULO
	,(ISNULL(EPP,0) + ISNULL(FRACIONADO,0)) AS [QTDE DOCUMENTOS]
	,ISNULL(EPP,0) AS EPP
	,ISNULL(FRACIONADO,0) AS FRACIONADO
	,SUM(CASE	
		WHEN COLETA IS NULL THEN 0 
	ELSE 1
	END) AS [COLETA]
	,ISNULL(REALIZADOS,0) AS REALIZADO
	,ISNULL(RETORNOS,0) AS RETORNOS

FROM #TempPivotFracionadoEppFinal

GROUP BY 
		NUMEROVIAGEM
	,INICIOEFETIVO
	,PREVISAOENTREGA
	,MOTORISTA
	,VEICULO
	,(ISNULL(EPP,0) + ISNULL(FRACIONADO,0))
	,ISNULL(EPP,0) 
	,ISNULL(FRACIONADO,0) 
	,ISNULL(REALIZADOS,0)
	,ISNULL(RETORNOS,0) 