SELECT top(10) 
		 CF.NUMERO,
		 CF.HANDLE,
         CF.DATAINCLUSAO,
         REPLACE(ISNULL(CP.NOME,C.NOME),'&','e') TOMADORSERVICO,
         TOMADORSERVICO.NOME PARTICIPANTETOMADORSERVICO,
         REPLACE(P1.NOME,'&','e') PARTICIPANTE1,
         PARTICIPANTE1.NOME TIPOPARTICIPANTE1,
         REPLACE(P2.NOME,'&','e') PARTICIPANTE2,
         PARTICIPANTE2.NOME TIPOPARTICIPANTE2,
         REPLACE(P3.NOME,'&','e') PARTICIPANTE3,
         PARTICIPANTE3.NOME TIPOPARTICIPANTE3,
		 LO.NOME LOCORIGEM,
	   TIPOLO.NOME TIPOLOCORIGEM,
	   MUNO.NOME MUNORIGEM,
	   LD.NOME LOCDESTINO,
	   TIPOLD.NOME TIPOLOCDESTINO,
	   MUND.NOME MUNDESTINO,
	   CF.QUANTIDADEVOLUMES,
	   CF.PESOTOTAL,
	   CF.PESOCUBADO,
	   CF.VALORTOTAL,
	   CFS.VALORTOTALRECEBER,
	   U.APELIDO DIGITADOR,
	   FINCLUSAO.NOME				[FILIALINCLUSAO],
	   FCOTACAO.NOME				[FILIALCOTACAO],
	   FENTREGA.NOME				[FILIALENTREGA],
	   ISNULL(GLGL_DOCUMENTOS.NUMERO,T1.DOCNUMERO)		[DOCUMENTO],
	   Case CF.STATUS
			When 1 Then 'Em Elaboração'
			When 2 Then 'Em Aprovação'
			When 3 Then 'Aprovada'
			When 4 Then 'Reprovada'
			When 5 Then 'Cancelada'
			When 6 Then 'Finalizada'
			When 7 Then 'Coleta Vinculada'
			When 8 Then 'Bloqueada'
	   End							[STATUS],
	   CF.DATAVALIDADE				[VALIDADE],
	   P4.NOME                      [AGENTEVENDAS]
FROM GLCM_COTACOES CF
LEFT JOIN GLCM_COTACAOSERVICOS CFS ON CFS.COTACAO = CF.HANDLE
LEFT JOIN GLCR_CLIENTEPOTENCIAL CP ON CP.HANDLE = CF.CLIENTEPOTENCIAL
LEFT JOIN GN_PESSOAS C ON C.HANDLE = CF.PESSOA
LEFT JOIN GLGL_ENUMERACAOITEMS TOMADORSERVICO ON TOMADORSERVICO.HANDLE = CF.TOMADORSERVICO
LEFT JOIN GN_PESSOAS P1 ON P1.HANDLE = CF.PARTICIPANTECLIENTE1
LEFT JOIN GLGL_ENUMERACAOITEMS PARTICIPANTE1 ON PARTICIPANTE1.HANDLE = CF.PARTICIPANTETIPO1
LEFT JOIN GN_PESSOAS P2 ON P2.HANDLE = CF.PARTICIPANTECLIENTE2
LEFT JOIN GLGL_ENUMERACAOITEMS PARTICIPANTE2 ON PARTICIPANTE2.HANDLE = CF.PARTICIPANTETIPO2
LEFT JOIN GN_PESSOAS P3 ON P3.HANDLE = CF.PARTICIPANTECLIENTE3
LEFT JOIN GLGL_ENUMERACAOITEMS PARTICIPANTE3 ON PARTICIPANTE3.HANDLE = CF.PARTICIPANTETIPO3
LEFT JOIN GLGL_LOCALIDADES LO ON LO.HANDLE = CF.ORIGEM
LEFT JOIN MUNICIPIOS MUNO ON MUNO.HANDLE = LO.MUNICIPIO
LEFT JOIN GLGL_ENUMERACAOITEMS TIPOLO ON TIPOLO.HANDLE = LO.TIPO
LEFT JOIN GLGL_LOCALIDADES LD ON LD.HANDLE = CF.DESTINO
LEFT JOIN MUNICIPIOS MUND ON MUND.HANDLE = LD.MUNICIPIO
LEFT JOIN GLGL_ENUMERACAOITEMS TIPOLD ON TIPOLD.HANDLE = LD.TIPO
LEFT JOIN Z_GRUPOUSUARIOS U ON U.HANDLE = CF.USUARIOINCLUIU
LEFT JOIN FILIAIS FINCLUSAO ON FINCLUSAO.HANDLE = CF.FILIAL
LEFT JOIN FILIAIS FCOTACAO ON FCOTACAO.HANDLE = CF.FILIALCOTACAO
LEFT JOIN FILIAIS FENTREGA ON FENTREGA.HANDLE = CF.FILIALENTREGA
LEFT JOIN GLGL_DOCUMENTOS ON GLGL_DOCUMENTOS.COTACAO = CF.HANDLE
LEFT JOIN GN_PESSOAS P4 ON P4.HANDLE = C.AGENTEVENDAS AND P4.EHAGENTEVENDAS = 'S'
LEFT JOIN (
			SELECT DOC.NUMERO AS DOCNUMERO, DOC.DATAEMISSAO , CC.NUMERO
				FROM GLCM_COTACOES CC
				INNER JOIN GLOP_COLETAPEDIDOCOTACOES CPC ON CPC.COTACAO = CC.HANDLE
				INNER JOIN GLOP_COLETAPEDIDOS CP ON CP.HANDLE = CPC.PEDIDOCOLETA
				INNER JOIN GLGL_DOCUMENTOCLIENTES DOCCLI ON DOCCLI.PEDIDOCOLETA = CP.HANDLE AND DOCCLI.COTACAO = CC.HANDLE
				INNER JOIN GLGL_DOCUMENTOS DOC ON DOCCLI.DOCUMENTOLOGISTICA = DOC.HANDLE
		   ) AS T1 ON T1.NUMERO = CF.NUMERO 
------------------------------------------------------------------------------------------------------------------------------------------------
WHERE (CF.NUMERO IS NOT NULL AND CF.SIMULACAO = 'N')
      {IF([FILIAL] <> '', " AND CF.FILIAL IN ("+ [FILIAL] +")", "")}
  AND ((CF.PESSOA = CASE WHEN ISNULL(:TOMADORSERVICO1,'') <> '' THEN :TOMADORSERVICO1 END) OR
	  (CF.CLIENTEPOTENCIAL = CASE WHEN ISNULL(:TOMADORSERVICO2,'') <> '' THEN :TOMADORSERVICO2 END) OR
	  (ISNULL(:TOMADORSERVICO1,'') = '' AND ISNULL(:TOMADORSERVICO2,'') = ''))
  AND (CF.DATAINCLUSAO BETWEEN :DATAINICIO AND DATEADD(HOUR,23,DATEADD(MINUTE,59,DATEADD(SECOND,59,:DATAFIM))))
ORDER BY CF.DATAINCLUSAO, CF.NUMERO
