DECLARE @BeginDate Datetime = '2019-11-01'
DECLARE @EndDate Datetime = '2019-11-02'

SELECT 
	   IsNull(IsNull(DOCORIGINAL.HANDLE, DOC.HANDLE), COLETA.HANDLE)									As HANDLEDOC,
	   IIF(DOCORIGINAL.HANDLE Is Null, IIF(DOC.HANDLE Is Null, 'COLETA', 'LOGISTICA'), 'LOGISTICA')		AS TPTABELA,
       PLACA.CODIGO																						AS VEICULO,
	   GNPES.NOME																						AS MOTORISTA,
	   CASE
			WHEN DOC.TIPODOCUMENTO	= 6
			 AND DOC.TIPORPS		= 324	THEN FILIALORIGINAL.NOME
			ELSE FI.NOME
	   END																								AS FILIAL_ORIGEM,
       FILIAISVG.NOME                                                                                                                                                                                   AS FILIALVIAGEM,
	   CASE
			WHEN DOC.TIPODOCUMENTO	= 6
			 AND DOC.TIPORPS		= 324	THEN Cast(DOCORIGINAL.NUMERO As VarChar(Max))
			ELSE IsNull(Cast(DOC.NUMERO As VarChar(Max)), COLETA.NUMERO)
	   END																								AS DOCUMENTO,
	   MO.DESCRICAO																						AS OCORRENCIA,
	   VIAGEM.NUMEROVIAGEM,
	   VIAGEM.INICIOEFETIVO																				As INICIOEFETIVO,
	   IIF(DOCORIGINAL.HANDLE Is Null, IIF(DOC.HANDLE Is Null, COLETA.DATAFIM, ISNULL(DOC.DTPREVISAOENTREGAEDI,DOC.DTPREVISAOENTREGAEMISSAO)), ISNULL(DOCORIGINAL.DTPREVISAOENTREGAEDI,DOCORIGINAL.DTPREVISAOENTREGAEMISSAO))		As PREVISAOENTREGA,
	   CASE
			WHEN PC.CLIENTEEPP = 'N' THEN 'FRACIONADO'
		ELSE 'EPP'
	   END AS TIPOCLIENTE,
	   (SELECT SUM(QTDADE_ENTREGA)
		  FROM (SELECT COUNT(1)										QTDADE_ENTREGA
				  FROM GLOP_VIAGEMDOCUMENTOS VIADOC
				 INNER JOIN GLOP_SERVICOREALIZADORPS SRPS
					ON SRPS.DOCUMENTOLOGISTICARPS					= VIADOC.DOCUMENTOLOGISTICA
				 INNER JOIN GLOP_VIAGENS VIA
					ON VIA.HANDLE									= VIADOC.VIAGEM
				 WHERE SRPS.DOCUMENTOLOGISTICA						= DOC.HANDLE
				   AND VIA.TIPOVIAGEM								IN (169,170,173,175)
				   AND DOC.TIPODOCUMENTO							= 2
			       And VIA.DATACANCELAMENTO							Is Null
				   And Cast(VIA.INICIOEFETIVO As Date)				<= Cast(VIAGEM.INICIOEFETIVO As Date)
				 UNION ALL
				SELECT COUNT(1)										QTDADE_ENTREGA
				  FROM GLOP_VIAGEMDOCUMENTOS VIADOC
				 INNER JOIN GLOP_SERVICOREALIZADORPS SRPS
					ON SRPS.DOCUMENTOLOGISTICARPS					= VIADOC.DOCUMENTOLOGISTICA
				 INNER JOIN GLOP_SERVICOREALIZADORPS DOCORIGINAL
					ON DOCORIGINAL.DOCUMENTOLOGISTICA				= SRPS.DOCUMENTOLOGISTICA
				 INNER JOIN GLOP_VIAGENS VIA
					ON VIA.HANDLE									= VIADOC.VIAGEM
				 WHERE DOCORIGINAL.DOCUMENTOLOGISTICARPS			=  DOC.HANDLE
				   AND VIA.TIPOVIAGEM								IN (169,170,173,175)
				   AND DOC.TIPODOCUMENTO							= 6
				   AND DOC.TIPORPS									= 324
			       And VIA.DATACANCELAMENTO							Is Null
				   And Cast(VIA.INICIOEFETIVO As Date)				<= Cast(VIAGEM.INICIOEFETIVO As Date)
				 UNION ALL
				SELECT COUNT(1)										QTDADE_ENTREGA
				  FROM GLOP_VIAGEMDOCUMENTOS
				 INNER JOIN GLOP_VIAGENS VIA
					ON GLOP_VIAGEMDOCUMENTOS.VIAGEM					= VIA.HANDLE
				 WHERE GLOP_VIAGEMDOCUMENTOS.DOCUMENTOLOGISTICA		= DOC.HANDLE
				   AND TIPOVIAGEM									IN (169,170,173,175)
			       And VIA.DATACANCELAMENTO							Is Null
				   And Cast(VIA.INICIOEFETIVO As Date)				<= Cast(VIAGEM.INICIOEFETIVO As Date)
				 UNION ALL
				SELECT COUNT(1) QTDADE_ENTREGA
				  FROM GLOP_VIAGEMDOCUMENTOS
				 Inner Join GLOP_VIAGENS VIA
					On VIA.HANDLE									= GLOP_VIAGEMDOCUMENTOS.VIAGEM
				 WHERE DOCUMENTOCOLETA								= COLETA.HANDLE
			       And VIA.DATACANCELAMENTO							Is Null
				   And Cast(VIA.INICIOEFETIVO As Date)				<= Cast(VIAGEM.INICIOEFETIVO As Date) )	AS T1 )			AS QTDADE_ENTREGAS
  FROM GLOP_VIAGENS									AS VIAGEM
 INNER JOIN FILIAIS									AS FILIAISVG
	ON FILIAISVG.HANDLE							= VIAGEM.FILIALORIGEM
 INNER JOIN	MA_RECURSOS								AS PLACA
	ON PLACA.HANDLE								= VIAGEM.VEICULO1
 INNER JOIN	GN_PESSOAS								AS GNPES
	ON	GNPES.HANDLE							= VIAGEM.MOTORISTA
 INNER JOIN	GLOP_VIAGEMDOCUMENTOS					AS VIADOC
	ON VIAGEM.HANDLE							= VIADOC.VIAGEM
  LEFT JOIN	GLGL_DOCUMENTOS							AS DOC
	ON DOC.HANDLE								= VIADOC.DOCUMENTOLOGISTICA
  LEFT JOIN	GLGL_TIPODOCUMENTOS						AS TIPO
	ON TIPO.HANDLE								= DOC.TIPODOCUMENTO
  LEFT JOIN	GLOP_COLETAPEDIDOS						AS COLETA
	ON COLETA.HANDLE							= VIADOC.DOCUMENTOCOLETA
 INNER JOIN	GLOP_OCORRENCIAS						AS OC
	ON OC.HANDLE								= VIADOC.OCORRENCIA
 INNER JOIN	GLOP_MOTIVOOCORRENCIAS					AS MO
	ON MO.HANDLE								= OC.OCORRENCIA
 INNER JOIN	FILIAIS									AS FI
	ON FI.HANDLE								= IsNull(DOC.FILIAL, COLETA.COLETAFILIAL)
  LEFT JOIN	GLOP_SERVICOREALIZADORPS				AS SRPS
	ON SRPS.DOCUMENTOLOGISTICARPS				= VIADOC.DOCUMENTOLOGISTICA
  LEFT JOIN	GLGL_DOCUMENTOS							AS DOCORIGINAL
	ON DOCORIGINAL.HANDLE						= SRPS.DOCUMENTOLOGISTICA
  LEFT JOIN	FILIAIS									AS FILIALORIGINAL
	ON FILIALORIGINAL.HANDLE					= DOCORIGINAL.FILIAL
  LEFT JOIN GLGL_PESSOACONFIGURACOES PC 
	ON GNPES.CODIGO								= PC.HANDLE
 
 WHERE VIADOC.SITUACAO							= 216
   AND VIAGEM.TIPOVIAGEM						IN (169, 170, 173, 175)
   AND VIAGEM.INICIOEFETIVO >= @BeginDate
   AND VIAGEM.INICIOEFETIVO < @EndDate


   --{IF([MOTORISTA] <> '', "AND VIAGEM.MOTORISTA	In ("+[MOTORISTA]+")", "")}
   --{IF([FILIAL] <> '', "And FILIAISVG.HANDLE In ("+[FILIAL]+")", "")}
   --{IF([PLACAS] <> '', "AND PLACA.HANDLE	In ("+[PLACAS]+")", "")}
   --AND CAST(VIAGEM.INICIOEFETIVO	AS DATE)		BETWEEN :DATAINICIAL
			--										AND :DATAFINAL

  --GROUP BY  IsNull(IsNull(DOCORIGINAL.HANDLE, DOC.HANDLE), COLETA.HANDLE),
	 --  IIF(DOCORIGINAL.HANDLE Is Null, IIF(DOC.HANDLE Is Null, 'COLETA', 'LOGISTICA'), 'LOGISTICA'),
  --     PLACA.CODIGO,
	 --  GNPES.NOME,
	 --  CASE
		--	WHEN DOC.TIPODOCUMENTO	= 6
		--	 AND DOC.TIPORPS		= 324	THEN FILIALORIGINAL.NOME
		--	ELSE FI.NOME
	 --  END,
  --     FILIAISVG.NOME,
	 --  CASE
		--	WHEN DOC.TIPODOCUMENTO	= 6
		--	 AND DOC.TIPORPS		= 324	THEN Cast(DOCORIGINAL.NUMERO As VarChar(Max))
		--	ELSE IsNull(Cast(DOC.NUMERO As VarChar(Max)), COLETA.NUMERO)
	 --  END,
	 --  MO.DESCRICAO,
	 --  VIAGEM.NUMEROVIAGEM,
	 --  VIAGEM.INICIOEFETIVO,
	 --  IIF(DOCORIGINAL.HANDLE Is Null, IIF(DOC.HANDLE Is Null, COLETA.DATAFIM, ISNULL(DOC.DTPREVISAOENTREGAEDI,DOC.DTPREVISAOENTREGAEMISSAO)), ISNULL(DOCORIGINAL.DTPREVISAOENTREGAEDI,DOCORIGINAL.DTPREVISAOENTREGAEMISSAO)),
	 --  CASE
		--	WHEN PC.CLIENTEEPP = 'N' THEN 'FRACIONADO'
		--ELSE 'EPP'
	 --  END,
	 --  DOC.TIPODOCUMENTO
	 --  ,DOC.TIPORPS
	 --  ,VIAGEM.TIPOVIAGEM 



 ORDER BY IsNull(IsNull(DOCORIGINAL.HANDLE, DOC.HANDLE), COLETA.HANDLE)