
SELECT DISTINCT 
	V.NUMEROVIAGEM 
	,TPV.NOME AS TIPOVIAGEM
	,GNPR.CGCCPF
	,CASE
		WHEN VP.ORDEM = 1 THEN 'HUB1'
		WHEN VP.ORDEM = 2 THEN 'HUB2'
		WHEN VP.ORDEM = 3 THEN 'HUB3'
		WHEN VP.ORDEM = 4 THEN 'HUB4'
		WHEN VP.ORDEM = 5 THEN 'HUB5'
		WHEN VP.ORDEM = 6 THEN 'HUB6'
		WHEN VP.ORDEM = 7 THEN 'HUB7'
		WHEN VP.ORDEM = 8 THEN 'HUB8'
		WHEN VP.ORDEM = 9 THEN 'HUB9'
	 ELSE ''
	 END AS HUB

	,(SELECT FILIAL.SIGLA FROM GLOP_VIAGEMPARADAS INNER JOIN GLGL_FILIAIS FILIAL ON FILIAL.FILIAL = GLOP_VIAGEMPARADAS.FILIAL
		WHERE V.HANDLE = VIAGEM AND ORDEM = VP.ORDEM -1) ORIGEM
	,FD.SIGLA AS DESTINO
	,LINHAVIAGENS.NOME AS LINHAVIAGEM
	 ,(SELECT INICIOVIAGEM FROM GLOP_VIAGEMPARADAS 
	 WHERE VP.VIAGEM = GLOP_VIAGEMPARADAS.VIAGEM AND GLOP_VIAGEMPARADAS.ORDEM = VP.ORDEM -1 ) AS INICIOEFETIVO
	,VP.CHEGADA
	,SUM(D.DOCCLIVOLUME) AS TOTAL

FROM GLOP_VIAGENS V 
LEFT JOIN GLGL_FILIAIS FO                         
	ON FO.HANDLE = V.FILIALORIGEM
	
LEFT JOIN GLGL_SUBTIPOVIAGENS SBV
	ON SBV.HANDLE = V.SUBTIPOVIAGEM  

LEFT JOIN GLOP_VIAGEMDOCUMENTOS DV
	ON DV.VIAGEM = V.HANDLE --AND VP.HANDLE = DV.PARADA

LEFT JOIN GLOP_VIAGEMPARADAS VP
	ON V.HANDLE = VP.VIAGEM  AND VP.HANDLE = DV.PARADA   

LEFT JOIN GLGL_DOCUMENTOS D
	ON DV.DOCUMENTOLOGISTICA = D.HANDLE

INNER JOIN GLOP_LINHAVIAGENS LINHAVIAGENS 
	ON LINHAVIAGENS.HANDLE = V.LINHAVIAGEM

LEFT JOIN [DBRodo].[dbo].[GN_PESSOAS] GNPR WITH(NOLOCK)
	ON D.TOMADORSERVICOPESSOA = GNPR.HANDLE 

JOIN GLGL_ENUMERACAOITEMS TPV
	ON TPV.HANDLE = V.TIPOVIAGEM 

JOIN GLGL_FILIAIS FD                         
	ON FD.HANDLE = VP.FILIAL 

INNER JOIN GLGL_ENUMERACAOITEMS TIPOTRANSFERENCIA 
	ON TIPOTRANSFERENCIA.HANDLE = V.TIPOVIAGEM
	AND TIPOTRANSFERENCIA.HANDLE = 172

WHERE 0=0 
--AND NUMEROVIAGEM = '2019/331888-3'
AND GNPR.CGCCPF IN (
'20.121.850/0001-55'
,'20.121.850/0003-17'
,'20.121.850/0009-02'
,'20.121.850/0008-21'
,'20.121.850/0007-40'
,'20.121.850/0010-46'
					)
AND V.INICIOEFETIVO >= @BeginDate
AND V.INICIOEFETIVO < @EndDate


GROUP BY 
		V.NUMEROVIAGEM 
	,TPV.NOME
	,GNPR.CGCCPF
    ,VP.ORDEM
	,FO.SIGLA 
	,FD.SIGLA 
	,LINHAVIAGENS.NOME
	,V.INICIOEFETIVO
	--,V.CHEGADAEFETIVA
	,V.HANDLE
	,VP.CHEGADA
	,VP.INICIOVIAGEM
	,VP.FILIAL
	,VP.VIAGEM

--------------------------------------------------------------------------------------------------------------------------------------------
--Com Pivot
--------------------------------------------------------------------------------------------------------------------------------------------

SELECT 
	NUMEROVIAGEM 
	,TIPOVIAGEM
	,CGCCPF
	,ORIGEM
	,DESTINO
	,LINHAVIAGEM
	,INICIOEFETIVO
	,CHEGADA
	,ISNULL(HUB1,0) AS HUB1
    ,ISNULL(HUB2,0) AS HUB2 
    ,ISNULL(HUB3,0) AS HUB3 
    ,ISNULL(HUB4,0) AS HUB4 
    ,ISNULL(HUB5,0) AS HUB5 
    ,ISNULL(HUB6,0) AS HUB6 
    ,ISNULL(HUB7,0) AS HUB7
	,ISNULL(HUB8,0) AS HUB8
	,ISNULL(HUB9,0) AS HUB9

FROM (
SELECT DISTINCT 
	V.NUMEROVIAGEM 
	,TPV.NOME AS TIPOVIAGEM
	,GNPR.CGCCPF
	,CASE
		WHEN VP.ORDEM = 1 THEN 'HUB1'
		WHEN VP.ORDEM = 2 THEN 'HUB2'
		WHEN VP.ORDEM = 3 THEN 'HUB3'
		WHEN VP.ORDEM = 4 THEN 'HUB4'
		WHEN VP.ORDEM = 5 THEN 'HUB5'
		WHEN VP.ORDEM = 6 THEN 'HUB6'
		WHEN VP.ORDEM = 7 THEN 'HUB7'
		WHEN VP.ORDEM = 8 THEN 'HUB8'
		WHEN VP.ORDEM = 9 THEN 'HUB9'
	 ELSE ''
	 END AS HUB

	,(SELECT FILIAL.SIGLA FROM GLOP_VIAGEMPARADAS INNER JOIN GLGL_FILIAIS FILIAL ON FILIAL.FILIAL = GLOP_VIAGEMPARADAS.FILIAL
		WHERE V.HANDLE = VIAGEM AND ORDEM = VP.ORDEM -1) ORIGEM
	,FD.SIGLA AS DESTINO
	,LINHAVIAGENS.NOME AS LINHAVIAGEM
	 ,(SELECT INICIOVIAGEM FROM GLOP_VIAGEMPARADAS 
	 WHERE VP.VIAGEM = GLOP_VIAGEMPARADAS.VIAGEM AND GLOP_VIAGEMPARADAS.ORDEM = VP.ORDEM -1 ) AS INICIOEFETIVO
	,ISNULL(VP.CHEGADA, V.CHEGADAEFETIVA) AS CHEGADA
	,SUM(D.DOCCLIVOLUME) AS TOTAL

FROM GLOP_VIAGENS V 
LEFT JOIN GLGL_FILIAIS FO                         
	ON FO.HANDLE = V.FILIALORIGEM
	
LEFT JOIN GLGL_SUBTIPOVIAGENS SBV
	ON SBV.HANDLE = V.SUBTIPOVIAGEM  

LEFT JOIN GLOP_VIAGEMDOCUMENTOS DV
	ON DV.VIAGEM = V.HANDLE --AND VP.HANDLE = DV.PARADA

LEFT JOIN GLOP_VIAGEMPARADAS VP
	ON V.HANDLE = VP.VIAGEM  AND VP.HANDLE = DV.PARADA   

LEFT JOIN GLGL_DOCUMENTOS D
	ON DV.DOCUMENTOLOGISTICA = D.HANDLE

INNER JOIN GLOP_LINHAVIAGENS LINHAVIAGENS 
	ON LINHAVIAGENS.HANDLE = V.LINHAVIAGEM

LEFT JOIN [DBRodo].[dbo].[GN_PESSOAS] GNPR WITH(NOLOCK)
	ON D.TOMADORSERVICOPESSOA = GNPR.HANDLE 

JOIN GLGL_ENUMERACAOITEMS TPV
	ON TPV.HANDLE = V.TIPOVIAGEM 

JOIN GLGL_FILIAIS FD                         
	ON FD.HANDLE = VP.FILIAL 

INNER JOIN GLGL_ENUMERACAOITEMS TIPOTRANSFERENCIA 
	ON TIPOTRANSFERENCIA.HANDLE = V.TIPOVIAGEM
	AND TIPOTRANSFERENCIA.HANDLE = 172

WHERE 0=0 
--AND NUMEROVIAGEM = '2019/331888-3'
AND GNPR.CGCCPF IN (
'20.121.850/0001-55'
,'20.121.850/0003-17'
,'20.121.850/0009-02'
,'20.121.850/0008-21'
,'20.121.850/0007-40'
,'20.121.850/0010-46'
					)
AND V.INICIOEFETIVO >= '2019-10-01'
AND V.INICIOEFETIVO < '2019-10-15'
AND TIPOTRANSFERENCIA.HANDLE = 172

GROUP BY 
		V.NUMEROVIAGEM 
	,TPV.NOME
	,GNPR.CGCCPF
    ,VP.ORDEM
	,FO.SIGLA 
	,FD.SIGLA 
	,LINHAVIAGENS.NOME
	,V.INICIOEFETIVO
	--,V.CHEGADAEFETIVA
	,V.HANDLE
	,ISNULL(VP.CHEGADA, V.CHEGADAEFETIVA)
	,VP.INICIOVIAGEM
	,VP.FILIAL
	,VP.VIAGEM
) AS T1
PIVOT(
    SUM(T1.TOTAL) 
    FOR HUB IN (
        HUB1, 
        HUB2, 
        HUB3, 
        HUB4, 
        HUB5, 
        HUB6, 
        HUB7,
		HUB8,
		HUB9)
) AS pivot_table;