SELECT	CT_LANCAMENTOS.DATA,
        FILIAIS.NOME 'NOME_DA_FILIAL',
        CT_CC.ESTRUTURA 'ESTRUTURA_CENTRO_DE_CUSTO',
        CT_CC.NOME 'NOME_DO_CENTRO_DE_CUSTO',
        GN_PROJETOS.ESTRUTURA 'ESTUTURA_DO_PROJETO',
        GN_PROJETOS.NOME 'NOME_DO_PROJETO',
        CT_CONTAS.ESTRUTURA 'ESTRUTURA_CONTA_CONTABIL',
        CT_CONTAS.NOME 'NOME_DA_CONTA_CONTABIL',
        CT_LANCAMENTOS.DOCUMENTOCONTABIL,
        CONCAT(CT_HISTORICOSPADROES.NOME,' ',CT_LANCAMENTOS.COMPLEMENTO) 'HISTORICO_CONTABIL',
        CASE WHEN A.NATUREZA='D' THEN A.VALOR
        END  'DEBITO',
        CASE WHEN A.NATUREZA='C' THEN A.VALOR
        END  'CREDITO',
	CASE WHEN CT_LANCAMENTOS.ORIGEM=1 THEN  'DIGITADO CONTABIL'
	     WHEN CT_LANCAMENTOS.ORIGEM=2 THEN  'LANCAMENTO TESOURARIA'
             WHEN CT_LANCAMENTOS.ORIGEM=3 THEN  UPPER(GN_PESSOAS.NOME)
	     WHEN CT_LANCAMENTOS.ORIGEM=4 THEN  UPPER(GN_PESSOAS.NOME)
	     WHEN CT_LANCAMENTOS.ORIGEM=7 THEN  UPPER(GN_PESSOAS.NOME)
             WHEN CT_LANCAMENTOS.ORIGEM=10 THEN 'FOLHA DE PAGAMENTO'
	     WHEN CT_LANCAMENTOS.ORIGEM=11 THEN UPPER(GN_PESSOAS.NOME)
	     WHEN CT_LANCAMENTOS.ORIGEM=12 THEN 'ALOCACOES CONTABEIS'
	     WHEN CT_LANCAMENTOS.ORIGEM=22 THEN 'MOVIMENTACOES DE ESTOQUE'
		 ELSE 'DIVERSOS'
	END 'FORNECEDOR_CLIENTE',
	CASE WHEN FN_DOCUMENTOS.DOCUMENTODIGITADO<>'' THEN FN_DOCUMENTOS.DOCUMENTODIGITADO
	     WHEN FN_DOCUMENTOS4.DOCUMENTODIGITADO<>'' THEN FN_DOCUMENTOS4.DOCUMENTODIGITADO
	     WHEN FN_DOCUMENTOS5.DOCUMENTODIGITADO<>'' THEN FN_DOCUMENTOS5.DOCUMENTODIGITADO
	     WHEN FN_DOCUMENTOS6.DOCUMENTODIGITADO<>'' THEN FN_DOCUMENTOS6.DOCUMENTODIGITADO
		ELSE PD_TANQUECONTABILVARIACOES.DOCTOCONTABIL
	END DOCUMENTO,
        CASE WHEN FN_DOCUMENTOS.ENTRADASAIDA='I' THEN Z_GRUPOUSUARIOS1.NOME
	     WHEN FN_DOCUMENTOS.ENTRADASAIDA='E' THEN Z_GRUPOUSUARIOS.NOME
	     WHEN (FN_DOCUMENTOS4.ENTRADASAIDA='E' AND FN_DOCUMENTOS4.ABRANGENCIA IN ('N','T')) THEN Z_GRUPOUSUARIOS8.NOME
	     WHEN FN_DOCUMENTOS5.ENTRADASAIDA='S' AND FN_DOCUMENTOS5.ABRANGENCIA='A' THEN Z_GRUPOUSUARIOS7.NOME
	     WHEN FN_DOCUMENTOS6.ENTRADASAIDA='S' AND FN_DOCUMENTOS5.ABRANGENCIA='T' THEN Z_GRUPOUSUARIOS6.NOME
		ELSE CASE WHEN ISNULL(Z_GRUPOUSUARIOS2.NOME,Z_GRUPOUSUARIOS3.NOME)<>''
	                  THEN ISNULL(Z_GRUPOUSUARIOS2.NOME,Z_GRUPOUSUARIOS3.NOME)
		ELSE CASE WHEN ISNULL(Z_GRUPOUSUARIOS4.NOME,Z_GRUPOUSUARIOS5.NOME)<>''
    	                  THEN  ISNULL(Z_GRUPOUSUARIOS4.NOME,Z_GRUPOUSUARIOS5.NOME)
        END END END  USUARIOINCLUIU,
	CASE WHEN FN_DOCUMENTOS.HISTORICO <>'' THEN FN_DOCUMENTOS.HISTORICO
	     WHEN FN_DOCUMENTOS4.HISTORICO <>'' THEN FN_DOCUMENTOS4.HISTORICO
	     WHEN FN_DOCUMENTOS5.HISTORICO <>'' THEN FN_DOCUMENTOS5.HISTORICO
	     WHEN FN_DOCUMENTOS6.HISTORICO <>'' THEN FN_DOCUMENTOS6.HISTORICO
                ELSE FN_DOCUMENTOS3.HISTORICO
        END 'HISTORICO_DOCUMENTO',
	ISNULL (PD_PRODUTOS.NOME,PD_PRODUTOS2.NOME) PRODUTO,
	ISNULL (CM_ITENS.QUANTIDADE,PD_MOVIMENTACAOVARIACAO.QUANTIDADE) QUANTIDADE,
	ISNULL (CM_ITENS.VALORUNITARIO,PD_MOVIMENTACAOVARIACAO.VALORUNITARIO) VALORUNITARIO,
        ISNULL (CM_ITENS.DESCONTOSVALOR,'0') AS DESCONTO,
        CASE WHEN A.NATUREZA='C' THEN
	     ISNULL (((CM_ITENS.VALORTOTAL+CM_ITENS.OUTROS)*-1),((PD_MOVIMENTACAOVARIACAO.VALORTOTAL)*-1))
        ELSE
             ISNULL (CM_ITENS.VALORTOTAL+CM_ITENS.OUTROS,PD_MOVIMENTACAOVARIACAO.VALORTOTAL)
        END TOTALGERAL,
        ISNULL (PD_FAMILIASPRODUTOS.NOME,PD_FAMILIASPRODUTOS2.NOME) 'NOME_DA_FAMILIA',
		FILIAIS2.NOME 'FILIAL_DO_CENTRO_DE_CUSTO',
		DATEPART(YEAR,CT_LANCAMENTOS.DATA) ANO,
        DATEPART(MONTH,CT_LANCAMENTOS.DATA) MES,
		CASE
			WHEN PC.CLIENTEEPP = 'N' THEN 'FRACIONADO'
		ELSE 'EPP'
		END AS TIPOCLIENTE
  FROM CT_LANCAMENTOCC A
       LEFT OUTER JOIN CT_CC CT_CC ON (CT_CC.HANDLE = A.CENTROCUSTO)
       JOIN CT_LANCAMENTOS CT_LANCAMENTOS ON (CT_LANCAMENTOS.HANDLE = A.LANCAMENTO)
       LEFT OUTER JOIN CT_CONTAS CT_CONTAS ON (CT_CONTAS.HANDLE = CT_LANCAMENTOS.CONTA)
       LEFT OUTER JOIN GN_PESSOAS GN_PESSOAS ON (GN_PESSOAS.HANDLE=CT_LANCAMENTOS.K_PESSOA)
       LEFT OUTER JOIN GN_PROJETOS GN_PROJETOS ON (GN_PROJETOS.HANDLE=A.PROJETO)
       LEFT OUTER JOIN CT_DOCUMENTOS CT_DOCUMENTOS ON (CT_DOCUMENTOS.HANDLE = A.DOCUMENTO)
       LEFT OUTER JOIN FILIAIS FILIAIS ON (FILIAIS.HANDLE = CT_LANCAMENTOS.FILIAL)
       LEFT OUTER JOIN FILIAIS FILIAIS2 ON (FILIAIS2.HANDLE = CT_CC.K_FILIALCC)
       LEFT OUTER JOIN CT_HISTORICOSPADROES CT_HISTORICOSPADROES ON (CT_HISTORICOSPADROES.HANDLE = CT_LANCAMENTOS.HISTORICO)
       LEFT OUTER JOIN FN_DOCUMENTOS FN_DOCUMENTOS ON (FN_DOCUMENTOS.DOCUMENTOORIGEM=CT_LANCAMENTOS.LANCAMENTOFINANCEIRO AND FN_DOCUMENTOS.ENTRADASAIDA='I')
       LEFT OUTER JOIN Z_GRUPOUSUARIOS Z_GRUPOUSUARIOS1 ON (FN_DOCUMENTOS.USUARIOINCLUIU=Z_GRUPOUSUARIOS1.HANDLE)
       LEFT OUTER JOIN FN_DOCUMENTOS FN_DOCUMENTOS2 ON (FN_DOCUMENTOS2.DOCUMENTOORIGEM=FN_DOCUMENTOS.HANDLE AND FN_DOCUMENTOS.ENTRADASAIDA='E')
       LEFT OUTER JOIN Z_GRUPOUSUARIOS Z_GRUPOUSUARIOS ON (FN_DOCUMENTOS2.USUARIOINCLUIU=Z_GRUPOUSUARIOS.HANDLE)
       LEFT OUTER JOIN FN_DOCUMENTOS FN_DOCUMENTOS4 ON (FN_DOCUMENTOS4.HANDLE=CT_LANCAMENTOS.LANCAMENTOFINANCEIRO AND FN_DOCUMENTOS4.ENTRADASAIDA='E' AND FN_DOCUMENTOS4.ABRANGENCIA IN ('N','T'))
       LEFT OUTER JOIN Z_GRUPOUSUARIOS Z_GRUPOUSUARIOS8 ON (FN_DOCUMENTOS4.USUARIOINCLUIU=Z_GRUPOUSUARIOS8.HANDLE)
       LEFT OUTER JOIN FN_MOVIMENTACOES FN_MOVIMENTACOES ON (FN_MOVIMENTACOES.HANDLE=CT_LANCAMENTOS.LANCAMENTOMOVIMENTACAO)
       LEFT OUTER JOIN FN_DOCUMENTOS FN_DOCUMENTOS3 ON (FN_DOCUMENTOS3.HANDLE=FN_MOVIMENTACOES.DOCUMENTO)
       LEFT OUTER JOIN Z_GRUPOUSUARIOS Z_GRUPOUSUARIOS3 ON (FN_DOCUMENTOS3.USUARIOINCLUIU=Z_GRUPOUSUARIOS3.HANDLE)
       LEFT OUTER JOIN Z_GRUPOUSUARIOS Z_GRUPOUSUARIOS4 ON (CT_LANCAMENTOS.USUARIOINCLUIU=Z_GRUPOUSUARIOS4.HANDLE AND CT_LANCAMENTOS.ORIGEM=1)
       LEFT OUTER JOIN TS_LANCAMENTOS TS_LANCAMENTOS ON (TS_LANCAMENTOS.HANDLE=CT_LANCAMENTOS.LANCAMENTOTESOURARIA)
       LEFT OUTER JOIN Z_GRUPOUSUARIOS Z_GRUPOUSUARIOS5 ON (TS_LANCAMENTOS.USUARIOINCLUIU=Z_GRUPOUSUARIOS5.HANDLE)
       LEFT OUTER JOIN FN_DOCUMENTOS FN_DOCUMENTOS5 ON (FN_DOCUMENTOS5.DOCUMENTOORIGEM=CT_LANCAMENTOS.LANCAMENTOFINANCEIRO AND FN_DOCUMENTOS5.ENTRADASAIDA='S' AND FN_DOCUMENTOS5.ABRANGENCIA='A' )
       LEFT OUTER JOIN Z_GRUPOUSUARIOS Z_GRUPOUSUARIOS7 ON (FN_DOCUMENTOS5.USUARIOINCLUIU=Z_GRUPOUSUARIOS7.HANDLE)
       LEFT OUTER JOIN FN_DOCUMENTOS FN_DOCUMENTOS6 ON (FN_DOCUMENTOS6.DOCUMENTOORIGEM=FN_DOCUMENTOS5.HANDLE  AND FN_DOCUMENTOS5.ENTRADASAIDA='S' AND FN_DOCUMENTOS5.ABRANGENCIA='T'  )
       LEFT OUTER JOIN Z_GRUPOUSUARIOS Z_GRUPOUSUARIOS6 ON (FN_DOCUMENTOS6.USUARIOINCLUIU=Z_GRUPOUSUARIOS6.HANDLE)
       LEFT OUTER JOIN CM_ITENS CM_ITENS ON (CM_ITENS.HANDLE=CT_LANCAMENTOS.LANCAMENTOFINANCEIROITEM)
       LEFT OUTER JOIN PD_PRODUTOS PD_PRODUTOS ON (PD_PRODUTOS.HANDLE=CM_ITENS.PRODUTO)
       LEFT OUTER JOIN PD_FAMILIASPRODUTOS PD_FAMILIASPRODUTOS ON (PD_FAMILIASPRODUTOS.HANDLE=CM_ITENS.FAMILIA)
       LEFT OUTER JOIN PD_TANQUECONTABILVARIACOES PD_TANQUECONTABILVARIACOES ON (PD_TANQUECONTABILVARIACOES.HANDLE=CT_LANCAMENTOS.LANCAMENTOMOVVARIACAOESTOQUE)
       LEFT OUTER JOIN PD_MOVIMENTACAOVARIACAO PD_MOVIMENTACAOVARIACAO ON (PD_MOVIMENTACAOVARIACAO.TANQUECONTABILMOVVARIACAO=PD_TANQUECONTABILVARIACOES.HANDLE)
       LEFT OUTER JOIN Z_GRUPOUSUARIOS Z_GRUPOUSUARIOS2 ON (PD_MOVIMENTACAOVARIACAO.USUARIO=Z_GRUPOUSUARIOS2.HANDLE)
       LEFT OUTER JOIN PD_PRODUTOS PD_PRODUTOS2 ON (PD_PRODUTOS2.HANDLE=PD_MOVIMENTACAOVARIACAO.PRODUTO)
       LEFT OUTER JOIN PD_FAMILIASPRODUTOS PD_FAMILIASPRODUTOS2 ON (PD_FAMILIASPRODUTOS2.HANDLE=PD_MOVIMENTACAOVARIACAO.FAMILIA)
	   LEFT JOIN GLGL_PESSOACONFIGURACOES PC ON GN_PESSOAS.CODIGO = PC.HANDLE
WHERE
	CT_LANCAMENTOS.DATA >= '2019-10-01'
	AND CT_LANCAMENTOS.DATA < '2019-10-02'
  --CT_LANCAMENTOS.DATA >= :EMISSAOINICIAL   AND CT_LANCAMENTOS.DATA <= :EMISSAOFINAL
  --    {IF([FILIAL]<> '', "AND CT_LANCAMENTOS.FILIAL IN ("+ [FILIAL] +")", "")}
  --      {IF  (([CONTAINICIAL]  <> '') AND ([CONTAFINAL]  <> ''), " AND CT_LANCAMENTOS.CONTA IN
  --             ( SELECT HANDLE FROM CT_CONTAS  WHERE EMPRESA = 1 AND INDICADORNATUREZASPED=4 AND VERSAO =[VERSAO] AND ESTRUTURA >=
  --                 (SELECT ESTRUTURA FROM CT_CONTAS WHERE EMPRESA = 1 AND INDICADORNATUREZASPED=4 AND VERSAO =[VERSAO] AND HANDLE = [CONTAINICIAL])
  --                       AND ESTRUTURA <=  (SELECT ESTRUTURA FROM CT_CONTAS WHERE EMPRESA=1 AND INDICADORNATUREZASPED=4 AND VERSAO=[VERSAO] AND HANDLE= [CONTAFINAL])  )", "")}
  --      {IF  (([CONTAUNICA]  <> ''), " AND CT_LANCAMENTOS.CONTA IN
  --       ( SELECT HANDLE FROM CT_CONTAS  WHERE EMPRESA = 1 AND INDICADORNATUREZASPED=4 AND VERSAO =[VERSAO] AND ESTRUTURA =
  --         (SELECT ESTRUTURA FROM CT_CONTAS WHERE EMPRESA = 1 AND VERSAO =[VERSAO] AND HANDLE = [CONTAUNICA]))", "")}
  --      {IF  (([CONTAALTERNADA]  <> ''), " AND CT_LANCAMENTOS.CONTA IN
  --       ( SELECT HANDLE FROM CT_CONTAS  WHERE EMPRESA = 1 AND INDICADORNATUREZASPED=4 AND VERSAO =[VERSAO] AND ESTRUTURA IN
  --         (SELECT ESTRUTURA FROM CT_CONTAS WHERE EMPRESA = 1 AND INDICADORNATUREZASPED=4 AND VERSAO =[VERSAO] AND HANDLE IN ("+ [CONTAALTERNADA] +")))", "")}
  --      {IF  (([CENTROCUSTOUNICO]  <> ''), " AND A.CENTROCUSTO IN
  --         (SELECT HANDLE FROM CT_CC  WHERE CT_CC.ESTRUTURA IN(SELECT ESTRUTURA FROM CT_CC  WHERE HANDLE = [CENTROCUSTOUNICO]))", "")}
  --      {IF  (([CENTROCUSTOALTERNADO]  <> ''), " AND A.CENTROCUSTO IN
  --         (SELECT HANDLE FROM CT_CC  WHERE CT_CC.ESTRUTURA IN(SELECT ESTRUTURA FROM CT_CC  WHERE HANDLE IN ("+ [CENTROCUSTOALTERNADO] +")))", "")}
  --      {IF  (([CENTROCUSTOINICIAL]  <> '') AND ([CENTROCUSTOFINAL]  <> ''), " AND A.CENTROCUSTO IN
  --             ( SELECT HANDLE FROM CT_CC  WHERE ESTRUTURA >=
  --                 (SELECT ESTRUTURA FROM CT_CC WHERE EMPRESA = 1 AND HANDLE = [CENTROCUSTOINICIAL])
  --                      AND ESTRUTURA <=  (SELECT ESTRUTURA FROM CT_CC WHERE HANDLE= [CENTROCUSTOFINAL])  )", "")}
  --      {IF([PROJETOUNICO]  <> '', "AND A.PROJETO IN ("+ [PROJETOUNICO] +")", "")}
  --      {IF (([PROJETOALTERNADO]  <> ''), "AND A.PROJETO IN
  --         (SELECT HANDLE FROM GN_PROJETOS WHERE GN_PROJETOS.ESTRUTURA IN(SELECT ESTRUTURA FROM GN_PROJETOS  WHERE HANDLE IN ("+ [PROJETOALTERNADO] +")))", "")}
  --      {IF ((([PROJETOINICIAL]  <> '') AND ([PROJETOFINAL]  <> '')), "AND A.PROJETO IN
  --             (SELECT HANDLE FROM GN_PROJETOS  WHERE ESTRUTURA >=
  --                 (SELECT ESTRUTURA FROM GN_PROJETOS WHERE EMPRESA = 1 AND HANDLE = [PROJETOINICIAL])
  --                      AND ESTRUTURA <=  (SELECT ESTRUTURA FROM GN_PROJETOS WHERE HANDLE= [PROJETOFINAL])  )", "")}
      AND CT_LANCAMENTOS.EMPRESA = 1 AND CT_LANCAMENTOS.LANCAMENTOGERADO='N' AND CT_CONTAS.INDICADORNATUREZASPED=4
UNION ALL
SELECT  K_RECLASSIFICACAOTM1.DATA,
        FILIAIS.NOME 'NOME_DA_FILIAL',
        CT_CC.ESTRUTURA 'ESTRUTURA_CENTRO_DE_CUSTO',
	CT_CC.NOME 'NOME_DO_CENTRO_DE_CUSTO',
        GN_PROJETOS.ESTRUTURA 'ESTRUTURA_PROJETO',
	GN_PROJETOS.NOME 'NOME_DO_PROJETO',
        CT_CONTAS.ESTRUTURA 'ESTRUTURA_CONTA_CONTABIL',
	CT_CONTAS.NOME 'NOME_DA_CONTA_CONTABIL',
        K_RECLASSIFICACAOTM1.DOCUMENTOCONTABIL 'DOCUMENTOCONTABIL',
        K_RECLASSIFICACAOTM1.HISTORICO  'HISTORICO_CONTABIL',
        K_RECLASSIFICACAOTM1.DEBITO  'DEBITO',
        K_RECLASSIFICACAOTM1.CREDITO 'CREDITO',
        GN_PESSOAS.NOME 'FORNECEDOR_CLIENTE',
	NULL  AS DOCUMENTO,
	Z_GRUPOUSUARIOS.NOME 'USUARIOINCLUIU',
	NULL AS 'HISTORICO_DOCUMENTO',
	NULL AS PRODUTO,
	NULL AS QUANTIDADE,
	NULL AS VALORUNITARIO,
	NULL AS DESCONTO,
	NULL AS TOTALGERAL,
	NULL AS 'NOME_DA_FAMILIA',
	FILIAIS2.NOME 'FILIAL_DO_CENTRO_DE_CUSTO',
	DATEPART(YEAR,K_RECLASSIFICACAOTM1.DATA) ANO,
	DATEPART(MONTH,K_RECLASSIFICACAOTM1.DATA) MES,
	CASE
		WHEN PC.CLIENTEEPP = 'N' THEN 'FRACIONADO'
	ELSE 'EPP'
	END AS TIPOCLIENTE
FROM K_RECLASSIFICACAOTM1
LEFT OUTER JOIN FILIAIS FILIAIS ON (FILIAIS.HANDLE=K_RECLASSIFICACAOTM1.FILIALLANCAMENTO)
LEFT OUTER JOIN CT_CC CT_CC ON (CT_CC.HANDLE=K_RECLASSIFICACAOTM1.CENTROCUSTO)
LEFT OUTER JOIN FILIAIS FILIAIS2 ON (FILIAIS2.HANDLE=CT_CC.K_FILIALCC)
LEFT OUTER JOIN GN_PROJETOS GN_PROJETOS ON (GN_PROJETOS.HANDLE=K_RECLASSIFICACAOTM1.PROJETO)
LEFT OUTER JOIN CT_CONTAS CT_CONTAS ON (CT_CONTAS.HANDLE=K_RECLASSIFICACAOTM1.CONTACONTABIL)
LEFT OUTER JOIN GN_PESSOAS GN_PESSOAS ON (GN_PESSOAS.HANDLE=K_RECLASSIFICACAOTM1.PESSOA)
LEFT OUTER JOIN Z_GRUPOUSUARIOS Z_GRUPOUSUARIOS ON (Z_GRUPOUSUARIOS.HANDLE=K_RECLASSIFICACAOTM1.USUARIOINCLUIU)
LEFT JOIN GLGL_PESSOACONFIGURACOES PC ON GN_PESSOAS.CODIGO = PC.HANDLE

WHERE  K_RECLASSIFICACAOTM1.DATA >= '2019-10-01'
	AND K_RECLASSIFICACAOTM1.DATA < '2019-10-02'

	--K_RECLASSIFICACAOTM1.DATA >= :EMISSAOINICIAL   AND K_RECLASSIFICACAOTM1.DATA <= :EMISSAOFINAL
     --{IF([FILIAL]  <> '', "AND K_RECLASSIFICACAOTM1.FILIALLANCAMENTO IN ("+ [FILIAL]       +")", "")}
     --{IF  (([CONTAINICIAL]  <> '') AND ([CONTAFINAL]  <> ''), " AND K_RECLASSIFICACAOTM1.CONTACONTABIL IN
     --          ( SELECT HANDLE FROM CT_CONTAS  WHERE EMPRESA = 1 AND VERSAO =[VERSAO] AND ESTRUTURA >=
     --              (SELECT ESTRUTURA FROM CT_CONTAS WHERE EMPRESA = 1 AND INDICADORNATUREZASPED=4 AND VERSAO =[VERSAO] AND HANDLE = [CONTAINICIAL])
     --                   AND ESTRUTURA <=  (SELECT ESTRUTURA FROM CT_CONTAS WHERE EMPRESA=1 AND VERSAO=[VERSAO] AND HANDLE= [CONTAFINAL])  )", "")}
     --{IF  (([CONTAUNICA]  <> ''), " AND K_RECLASSIFICACAOTM1.CONTACONTABIL IN
     --  ( SELECT HANDLE FROM CT_CONTAS  WHERE EMPRESA = 1 AND VERSAO =[VERSAO] AND ESTRUTURA =
     --     (SELECT ESTRUTURA FROM CT_CONTAS WHERE EMPRESA = 1 AND INDICADORNATUREZASPED=4 AND VERSAO =[VERSAO] AND HANDLE = [CONTAUNICA]))", "")}
     --{IF  (([CONTAALTERNADA]  <> ''), " AND K_RECLASSIFICACAOTM1.CONTACONTABIL IN
     --    ( SELECT HANDLE FROM CT_CONTAS  WHERE EMPRESA = 1 AND VERSAO =[VERSAO] AND ESTRUTURA IN
     --      (SELECT ESTRUTURA FROM CT_CONTAS WHERE EMPRESA = 1 AND INDICADORNATUREZASPED=4 AND VERSAO =[VERSAO] AND HANDLE IN ("+ [CONTAALTERNADA] +")))", "")}
     --{IF  (([CENTROCUSTOUNICO]  <> ''), " AND K_RECLASSIFICACAOTM1.CENTROCUSTO IN
     --      (SELECT HANDLE FROM CT_CC  WHERE CT_CC.ESTRUTURA IN(SELECT ESTRUTURA FROM CT_CC  WHERE HANDLE = [CENTROCUSTOUNICO]))", "")}
     --{IF  (([CENTROCUSTOALTERNADO]  <> ''), " AND K_RECLASSIFICACAOTM1.CENTROCUSTO IN
     --      (SELECT HANDLE FROM CT_CC  WHERE CT_CC.ESTRUTURA IN(SELECT ESTRUTURA FROM CT_CC  WHERE HANDLE IN ("+ [CENTROCUSTOALTERNADO] +")))", "")}
     --{IF  (([CENTROCUSTOINICIAL]  <> '') AND ([CENTROCUSTOFINAL]  <> ''), " AND K_RECLASSIFICACAOTM1.CENTROCUSTO IN
     --         ( SELECT HANDLE FROM CT_CC  WHERE ESTRUTURA >=
     --              (SELECT ESTRUTURA FROM CT_CC WHERE EMPRESA = 1 AND HANDLE = [CENTROCUSTOINICIAL])
     --                    AND ESTRUTURA <=  (SELECT ESTRUTURA FROM CT_CC WHERE HANDLE= [CENTROCUSTOFINAL])  )", "")}
     --{IF([PROJETOUNICO]  <> '', "AND K_RECLASSIFICACAOTM1.PROJETO IN ("+ [PROJETOUNICO] +")", "")}
     --{IF (([PROJETOALTERNADO]  <> ''), "AND K_RECLASSIFICACAOTM1.PROJETO IN
     --    (SELECT HANDLE FROM GN_PROJETOS WHERE GN_PROJETOS.ESTRUTURA IN(SELECT ESTRUTURA FROM GN_PROJETOS  WHERE HANDLE IN ("+ [PROJETOALTERNADO] +")))", "")}
     --{IF ((([PROJETOINICIAL]  <> '') AND ([PROJETOFINAL]  <> '')), "AND K_RECLASSIFICACAOTM1.PROJETO IN
     --        (SELECT HANDLE FROM GN_PROJETOS  WHERE ESTRUTURA >=
     --             (SELECT ESTRUTURA FROM GN_PROJETOS WHERE EMPRESA = 1 AND HANDLE = [PROJETOINICIAL])
     --                  AND ESTRUTURA <=  (SELECT ESTRUTURA FROM GN_PROJETOS WHERE HANDLE= [PROJETOFINAL])  )", "")}
ORDER BY CT_LANCAMENTOS.DATA
