 SELECT 
		   --'RECEITA' AS TIPO,
		   --'' AS TIPOMOTORISTA,
		   --VIAGENS.NUMEROVIAGEM  AS Manifesto,
           --FILIALORIGEM.NOME     AS FILIAL,
           --FILIALDESTINO.NOME    AS FILIALDESTINO,
		   VEICULO1.CODIGO AS Cavalo,
           VEICULO2.CODIGO AS Carreta,
           VEICULO3.CODIGO AS Carreta2,
		   ISNULL(LINHAVIAGENS2.NOME, LINHAVIAGENS.NOME)     AS LINHAVIAGEM,
		   BENEFICIARIO.NOME     AS BENEFICIARIO,
		   MOTORISTA.NOME        AS MOTORISTA, 
           --VIAGENS.INICIOEFETIVO AS DATAINICIO,
		   VIAGENS.PREVISAOSAIDA AS [DATA],
		   (SELECT SUM(VIAGEMDOCUMENTOS.PESO)
              FROM GLOP_VIAGEMDOCUMENTOS VIAGEMDOCUMENTOS
             WHERE VIAGEMDOCUMENTOS.VIAGEM = VIAGENS.HANDLE) AS PESOREAL,

           (SELECT SUM(VIAGEMDOCUMENTOS.PESOCUBADO)
              FROM GLOP_VIAGEMDOCUMENTOS VIAGEMDOCUMENTOS
             WHERE VIAGEMDOCUMENTOS.VIAGEM = VIAGENS.HANDLE) AS PESOCUBADO,

		   SUM(DOC.PESOCONSIDERADO) PESOCONSIDERADO,

		   --((SELECT SUM(VIAGEMDOCUMENTOS.VALORFRETE)
     --          FROM GLOP_VIAGEMDOCUMENTOS VIAGEMDOCUMENTOS WITH(NOLOCK)
     --         WHERE VIAGEMDOCUMENTOS.VIAGEM = VIAGENS.HANDLE) / NULLIF((SELECT SUM(VIAGEMDOCUMENTOS.PESO)
     --                                                              FROM GLOP_VIAGEMDOCUMENTOS VIAGEMDOCUMENTOS WITH(NOLOCK)
     --                                                             WHERE VIAGEMDOCUMENTOS.VIAGEM = VIAGENS.HANDLE AND VIAGEMDOCUMENTOS.PESO > 0.0), 0)) 
																  
																  
			(SELECT SUM(CASE WHEN CONTRATOFRETES.VALORTOTAL IS NULL THEN 0 ELSE CONTRATOFRETES.VALORTOTAL END)
            FROM GLOP_CONTRATOFRETEVIAGENS CONTRATOFRETEVIAGENS INNER
		    JOIN GLOP_CONTRATOFRETES CONTRATOFRETES ON (CONTRATOFRETEVIAGENS.CONTRATOFRETE = CONTRATOFRETES.HANDLE)
			WHERE CONTRATOFRETEVIAGENS.VIAGEM = VIAGENS.HANDLE
			AND CONTRATOFRETES.STATUS NOT IN(433,262)) AS [Total NF],

		   ((SELECT SUM(CASE WHEN CONTRATOFRETES.VALORTOTAL IS NULL THEN 0 ELSE CONTRATOFRETES.VALORTOTAL END)
               FROM GLOP_CONTRATOFRETEVIAGENS CONTRATOFRETEVIAGENS INNER
                    JOIN GLOP_CONTRATOFRETES CONTRATOFRETES ON (CONTRATOFRETEVIAGENS.CONTRATOFRETE = CONTRATOFRETES.HANDLE)
              WHERE CONTRATOFRETEVIAGENS.VIAGEM = VIAGENS.HANDLE
                    AND CONTRATOFRETES.STATUS NOT IN(433,262)) / NULLIF((SELECT SUM(CASE WHEN P.DISTANCIAPREVISTA IS NULL THEN 0 ELSE P.DISTANCIAPREVISTA END)
                                                                    FROM GLOP_VIAGEMPARADAS P
                                                                   WHERE P.VIAGEM = VIAGENS.HANDLE), 0)) AS VALORPORKMLV,

		   (SELECT SUM(CASE WHEN VIAGEMPARADAS.DISTANCIAPREVISTA IS NULL
                            THEN 0
                            ELSE VIAGEMPARADAS.DISTANCIAPREVISTA END)
              FROM GLOP_VIAGEMPARADAS VIAGEMPARADAS
             WHERE VIAGEMPARADAS.VIAGEM = VIAGENS.HANDLE) AS KMTOTAL,

   --        (SELECT SUM(CASE WHEN CONTRATOFRETES.VALORTOTAL IS NULL THEN 0 ELSE CONTRATOFRETES.VALORTOTAL END)
   --         FROM GLOP_CONTRATOFRETEVIAGENS CONTRATOFRETEVIAGENS INNER
		 --   JOIN GLOP_CONTRATOFRETES CONTRATOFRETES ON (CONTRATOFRETEVIAGENS.CONTRATOFRETE = CONTRATOFRETES.HANDLE)
			--WHERE CONTRATOFRETEVIAGENS.VIAGEM = VIAGENS.HANDLE
			--AND CONTRATOFRETES.STATUS NOT IN(433,262))  AS [Valor Bruto],


			 (SELECT SUM(VIAGEMDOCUMENTOS.VALORTOTAL)
              FROM GLOP_VIAGEMDOCUMENTOS VIAGEMDOCUMENTOS
             WHERE VIAGEMDOCUMENTOS.VIAGEM = VIAGENS.HANDLE) AS VALORTOTALMERCADORIA,

			 isnull(SUM(CALC.TARIFAADD),0) AS [Tarifas adicionais],
			 --'' AS OBSERVACOES
			 '' AS TIPODESPESAS,
			 '' AS TIPOOS


INTO #TempReceita
FROM GLOP_VIAGENS VIAGENS
           INNER JOIN FILIAIS FILIALORIGEM ON FILIALORIGEM.HANDLE = VIAGENS.FILIALORIGEM
           INNER JOIN FILIAIS FILIALDESTINO ON FILIALDESTINO.HANDLE = VIAGENS.FILIALDESTINO
           LEFT JOIN GN_PESSOAS MOTORISTA ON MOTORISTA.HANDLE = VIAGENS.MOTORISTA
           INNER JOIN MA_RECURSOS VEICULO1 ON VEICULO1.HANDLE = VIAGENS.VEICULO1
           INNER JOIN MF_VEICULOTIPOS VEICULOTIPO ON VEICULOTIPO.HANDLE = VEICULO1.TIPOVEICULO
           LEFT JOIN GN_PESSOAS BENEFICIARIO ON BENEFICIARIO.HANDLE = VEICULO1.PROPRIETARIO
           INNER JOIN GLOP_LINHAVIAGENS LINHAVIAGENS ON LINHAVIAGENS.HANDLE = VIAGENS.LINHAVIAGEM
           LEFT JOIN MA_RECURSOS VEICULO2 ON VEICULO2.HANDLE = VIAGENS.VEICULO2
           LEFT JOIN MA_RECURSOS VEICULO3 ON VEICULO3.HANDLE = VIAGENS.VEICULO3
           INNER JOIN GLGL_ENUMERACAOITEMS TIPOTRANSFERENCIA ON TIPOTRANSFERENCIA.HANDLE = VIAGENS.TIPOVIAGEM
           INNER JOIN GLOP_VIAGEMDOCUMENTOS VDOC ON (VDOC.VIAGEM = VIAGENS.HANDLE)
		   LEFT JOIN GLOP_CONTRATOFRETEVIAGENS VFRETE WITH(NOLOCK) ON VFRETE.VIAGEM = VIAGENS.Handle
		   INNER JOIN  (
							SELECT 186 AS TIPO,HANDLE, DOCCLIATUALPESOCONSIDERADO PESOCONSIDERADO 
							FROM GLGL_DOCUMENTOS
							WHERE TIPODOCUMENTO = 6

							UNION ALL

                            SELECT 188 AS TIPO,HANDLE, DOCCLIATUALPESOCONSIDERADO PESOCONSIDERADO 
							FROM GLGL_DOCUMENTOS
							WHERE TIPODOCUMENTO = 2

                        ) DOC ON VDOC.DOCUMENTOLOGISTICA = DOC.HANDLE AND DOC.TIPO = VDOC.TIPODOCUMENTO
			LEFT JOIN GLOP_LINHAVIAGENS LINHAVIAGENS2 WITH(NOLOCK) ON LINHAVIAGENS2.HANDLE = VIAGENS.LINHAVIAGEMBASECALCULO
			INNER JOIN GLOP_CONTRATOFRETES FRETE WITH(NOLOCK)            
			ON FRETE.HANDLE = VFRETE.CONTRATOFRETE                                                                               
			AND FRETE.Status Not In (262, 433, 731)

			LEFT JOIN 
			(
					SELECT 
							CONTRATOFRETE,
							SUM(GENERALIDADES) AS GENERALIDADES,
							SUM(DIARIA) AS DIARIA,
							SUM(PRODUTIVIDADE) AS PRODUTIVIDADE,
							SUM(QUILOMETRAGEM) AS QUILOMETRAGEM,
							SUM(TARIFAADD) AS TARIFAADD,
							SUM(FRETEVEICULO) AS FRETEVEICULO,
							SUM(DESCONTOS) AS DESCONTOS
					FROM (
					SELECT DISTINCT 
							CONTRATOFRETE,
							CASE
								WHEN CLASSIFICACAO = 7 THEN SUM(VALORFINAL)
							ELSE 0
							END AS GENERALIDADES,
							CASE
								WHEN CLASSIFICACAO = 8 THEN SUM(VALORFINAL)
							ELSE 0
							END AS DIARIA,
							CASE
								WHEN CLASSIFICACAO = 9 THEN SUM(VALORFINAL)
							ELSE 0
							END AS PRODUTIVIDADE,
							CASE
								WHEN CLASSIFICACAO = 10 THEN SUM(ISNULL(VALORFINAL,0))
							ELSE 0
							END AS QUILOMETRAGEM,
							CASE
								WHEN CLASSIFICACAO = 13 THEN SUM(VALORFINAL)
							ELSE 0
							END AS TARIFAADD,
							CASE
								WHEN CLASSIFICACAO = 14 THEN SUM(VALORFINAL)
							ELSE 0
							END AS FRETEVEICULO,
							CASE
								WHEN CLASSIFICACAO = 15 THEN SUM(VALORFINAL)
							ELSE 0
							END AS DESCONTOS


					FROM GLOP_CONTRATOFRETCALCULOS WITH(NOLOCK)

					GROUP BY CONTRATOFRETE, CLASSIFICACAO
					) AS T1

					GROUP BY CONTRATOFRETE
			)AS CALC						 
			ON CALC.CONTRATOFRETE = FRETE.HANDLE

			LEFT JOIN 
			(
				SELECT  
					MAX(HANDLE) AS HANDLE
					,CONTRATOFRETE
					--,OBSERVACAO
					,MAX(DATAHORA) AS [DATA] 
	
				FROM GLOP_FRETECOMBINADOLOGS T WITH(NOLOCK)
				GROUP BY CONTRATOFRETE
			) AS FRETECOMBINADOLOGS
			ON FRETE.HANDLE = FRETECOMBINADOLOGS.CONTRATOFRETE
			LEFT JOIN GLOP_FRETECOMBINADOLOGS T5 WITH(NOLOCK)
					ON FRETECOMBINADOLOGS.CONTRATOFRETE = T5.CONTRATOFRETE
					AND FRETECOMBINADOLOGS.HANDLE = T5.HANDLE

     WHERE TIPOTRANSFERENCIA.HANDLE = 172
       AND VIAGENS.STATUS           <> 179
       And VIAGENS.PREVIAGEM        = 'N'
       And VIAGENS.PREVISAOSAIDA >= @BeginDate
	   And VIAGENS.PREVISAOSAIDA < @EndDate

  GROUP BY  VIAGENS.NUMEROVIAGEM,
		   VEICULO1.CODIGO,
           VEICULO2.CODIGO,
           VEICULO3.CODIGO,
		   ISNULL(LINHAVIAGENS2.NOME, LINHAVIAGENS.NOME),
		   BENEFICIARIO.NOME,
		   MOTORISTA.NOME, 
           --VIAGENS.INICIOEFETIVO,
		   VIAGENS.PREVISAOSAIDA,
		   VIAGENS.HANDLE