--DECLARE @tomador VARCHAR (MAX) = ''
--DECLARE @BeginDate DATETIME = '2020-01-15'
--DECLARE @EndDate DATETIME = '2020-01-21'

--filtrar o campo status da glid_impdoclotes (não processados)
--xml é o tipo do documento

SELECT DISTINCT 
	    D.NUMERO AS [Nº CT-E]
       ,D.DATAEMISSAO AS [Data Emissão CT-E]
       ,REM.NOME AS [Cliente Remetente]
	   ,DEST.NOME AS [Cliente Destinatario]
       ,DC.NUMERO AS [Número NF]
	   ,FENT.NOME AS [Filial Entrega]
       ,ISNULL(D.DOCCLIPESOTOTAL, 0) AS [Peso real]
	   ,CASE
			WHEN D.DOCCLIPESOCUBADOTOTAL IS NULL OR D.DOCCLIPESOCUBADOTOTAL = 0 THEN D.DOCCLIPESOTOTAL
		ELSE D.DOCCLIPESOCUBADOTOTAL
		END AS [Peso cubado]
       ,ISNULL(D.DOCCLIVOLUME, D.DOCCLIATUALVOLUME) AS [Vol.]
       ,CASE
             WHEN D.TIPODOCUMENTO = 2 THEN 'CT-e'
             WHEN D.TIPODOCUMENTO = 6 THEN 'RPS'
       ELSE ''
       END AS TIPO
       ,TOMADOR.NOME


FROM GLGL_DOCUMENTOS D

LEFT JOIN GN_PESSOAS REM 
       ON D.REMETENTE = REM.HANDLE

LEFT JOIN GN_PESSOAS DEST
       ON D.DESTINATARIO = DEST.HANDLE

LEFT JOIN MUNICIPIOS MUN
       ON DEST.MUNICIPIO = MUN.HANDLE

LEFT JOIN ESTADOS EST
       ON DEST.ESTADO = EST.HANDLE

LEFT JOIN GLGL_DOCUMENTOTRIBUTOS DT
       ON DT.DOCUMENTO = D.HANDLE

LEFT JOIN GLGL_DOCUMENTOASSOCIADOS DA
       ON DA.DOCUMENTOLOGISTICA = D.HANDLE

LEFT JOIN GLGL_DOCUMENTOCLIENTES DC 
       ON DC.HANDLE = DA.DOCUMENTOCLIENTE

LEFT JOIN GLGL_ENUMERACAOITEMS EI
       ON EI.CODIGO = D.TIPOSERVICOFRETE

LEFT JOIN GLGL_ENUMERACAOITEMS EI2
       ON EI.CODIGO = D.TIPODOCUMENTOFRETE

LEFT JOIN FILIAIS FENT
       ON D.FILIALENTREGA = FENT.HANDLE

LEFT JOIN GN_PESSOAS TOMADOR
       ON D.TOMADORSERVICOPESSOA = TOMADOR.HANDLE

INNER JOIN GLID_IMPDOCCLIS
	   ON DC.HANDLE	= GLID_IMPDOCCLIS.DOCUMENTOCLIENTE

INNER JOIN GLID_IMPLOTES 
	   ON GLID_IMPDOCCLIS.EDILOTE = GLID_IMPLOTES.HANDLE
          

WHERE 1=1
AND D.VALORCONTABIL > 0
AND D.TIPODOCUMENTO IN (2,6)
AND D.DATAEMISSAO >= @BeginDate
AND D.DATAEMISSAO < DATEADD(DD, 1, @EndDate)
AND (TOMADOR.NOME LIKE '%' + @tomador + '%' OR REM.NOME is NULL)
