SELECT
    T.name AS Tabela,
    C.name AS Coluna
FROM
    sys.sysobjects    AS T (NOLOCK)
INNER JOIN sys.all_columns AS C (NOLOCK) ON T.id = C.object_id AND T.XTYPE = 'U'
WHERE
    C.NAME LIKE '%DATA%'
	and T.name in (
'GLOP_SERVICOREALIZADORPS'
,'GLGL_DOCUMENTOS'
,'GLGL_TIPODOCUMENTOS'
,'GLOP_SERVICOSREALIZADOS'
,'GLGL_SERVICOLOGISTICA'
,'FILIAIS'
,'GN_PESSOAS'
,'GN_PESSOAS'
,'GN_PESSOAS'
,'K9_GLGL_SERVICOSREALIZADOS'
,'K9_GLCM_CONFSERVICOSAUTOMATICO'
,'GLOP_OCORRENCIAS'
,'GLOP_MOTIVOOCORRENCIAS'
,'GLCM_TABELAPRECOS'
,'GLGL_DOCLOGASSOCIADOS'
,'GLGL_DOCUMENTOS'
,'FILIAIS'
,'GLFT_FATURADOCUMENTOS'
,'GLFT_FATURAS'
,'GLGL_ENUMERACAOITEMS'
)
ORDER BY
    T.name ASC