--declare @DTINICIAL DATETIME = '2019-08-31'
--DECLARE @DTFINAL DATETIME = '2019-08-31'
--DECLARE @FILIAL INT = 5


Select TBBase.CGCCPF,
	   TBBase.NOME,
	   TBBase.BASECALCULO					[BaseCalculo],
	   IIF(Sum(TBBase.VALORCUBADO)			> 0
		Or Sum(TBBase.VALORCUBADOMANUAL)	> 0
		Or Sum(TBBase.VALORCUBADOEDI)		> 0,
		'S', 'N')							[Cubagem],
	   TBBase.DESCRICAO						[Descricao],
	   TBBase.NUMERODOCUMENTO				[NumeroDoc],
	   CASE 
		   WHEN TBBase.DESCRICAO = 'Valor Cubado Cargo Scan' THEN 'Cliente c/ mercadoria cubada CargoScan'
		   WHEN TBBase.DESCRICAO = 'Valor Cubado Manual' THEN 'Cliente c/ mercadoria cubada Manual'
		   WHEN TBBase.DESCRICAO = 'Valor Cubado EDI' THEN 'Cliente c/ mercadoria cubada EDI'
		   WHEN TBBase.DESCRICAO = 'Valor Sem Cubagem' THEN 'Cliente s/ mercadoria cubada'
	   ELSE ''
	   END AS TIPODESCRICAO,
	   CAST(DATAEMISSAO AS DATE)            [DataEmissao],
	   DATEPART(DD, CAST(DATAEMISSAO AS DATE)) AS DIADATA,
	   CASE	
			WHEN DATEPART(DW, CAST(DATAEMISSAO AS DATE)) = 1 THEN 'Domingo'
			WHEN DATEPART(DW, CAST(DATAEMISSAO AS DATE)) = 2 THEN 'Segunda'
			WHEN DATEPART(DW, CAST(DATAEMISSAO AS DATE)) = 3 THEN 'Terça'
			WHEN DATEPART(DW, CAST(DATAEMISSAO AS DATE)) = 4 THEN 'Quarta'
			WHEN DATEPART(DW, CAST(DATAEMISSAO AS DATE)) = 5 THEN 'Quinta'
			WHEN DATEPART(DW, CAST(DATAEMISSAO AS DATE)) = 6 THEN 'Sexta'
			WHEN DATEPART(DW, CAST(DATAEMISSAO AS DATE)) = 7 THEN 'Sabado'
	   ELSE ''
	   END AS DIASEMANA,
	   Sum(TBBase.Qntde)					[Qntde],
	   Sum(TBBase.DOCCLIVOLUME)				[Volume],
	   Sum(DOCCLIPESOTOTAL)					[PesoNF],
	   Sum(TBBase.VALORCUBADO) 				[ValorCubado],
	   Sum(TBBase.DIFCALCULO)				[DifFrete],
	   Sum(TBBase.VALORSEMCARGOSCAN)		[ValorSemCubagem],
	   Sum(TBBase.DIFCALCULOMANUAL)			[DifFreteManual],
	   Sum(TBBase.VALORCUBADOMANUAL)		[ValorCubadoManual],
	   Sum(TBBase.DIFCALCULOEDI)			[DifFreteEDI],
	   Sum(TBBase.VALORCUBADOEDI)			[ValorCubadoEDI],
	   Sum(TBBase.VALOR)					[ValorTotal]
  From (SELECT GN_PESSOAS.CGCCPF,
			   GN_PESSOAS.NOME,
			   GLGL_DOCUMENTOS.NUMERO					[NUMERODOCUMENTO],
			   GLGL_DOCUMENTOS.DATAEMISSAO,
			   GLGL_ENUMERACAOITEMS.NOME				[BASECALCULO],
			   GLGL_DOCUMENTOS.VALORCONTABIL			[VALOR],
			   1										[Qntde],
			   GLGL_DOCUMENTOS.DOCCLIVOLUME,
			   GLGL_DOCUMENTOS.DOCCLIPESOTOTAL,
			   Case 
					When IIF(EXISTS(  SELECT 1
										FROM GLGL_DOCUMENTOASSOCIADOS
									   INNER JOIN GLGL_DOCUMENTOCLIENTES
										  ON (GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOCLIENTE		= GLGL_DOCUMENTOCLIENTES.HANDLE)
									   WHERE GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOLOGISTICA	= GLGL_DOCUMENTOS.HANDLE
										 AND ((GLGL_DOCUMENTOCLIENTES.K_AFERIDOCARGOSCAN		= 'S')
										  Or  (GLGL_DOCUMENTOCLIENTES.K_AFERIDOCARGOSCAN		= 'N'
										 AND  (GLGL_DOCUMENTOCLIENTES.CUBAGEM					= 'S'
										  Or  Exists (Select 1
													    From GLGL_DOCCLICUBAGENS
													   Where GLGL_DOCCLICUBAGENS.DOCUMENTOCLIENTE = GLGL_DOCUMENTOCLIENTES.HANDLE))))), 0, GLGL_DOCUMENTOS.VALORCONTABIL) > 0 Then 'Valor Sem Cubagem'
					When IIF(EXISTS(  SELECT 1
										FROM GLGL_DOCUMENTOASSOCIADOS
									   INNER JOIN GLGL_DOCUMENTOCLIENTES
										  ON (GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOCLIENTE		= GLGL_DOCUMENTOCLIENTES.HANDLE)
									   WHERE GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOLOGISTICA	= GLGL_DOCUMENTOS.HANDLE
										 AND GLGL_DOCUMENTOCLIENTES.K_AFERIDOCARGOSCAN		= 'N'
										 AND (GLGL_DOCUMENTOCLIENTES.CUBAGEM				= 'S'
										  Or Exists (Select 1
													   From GLGL_DOCCLICUBAGENS
													  Where GLGL_DOCCLICUBAGENS.DOCUMENTOCLIENTE = GLGL_DOCUMENTOCLIENTES.HANDLE))
										And Not Exists (Select 1
														  From GLID_IMPDOCCLIS 
														 Where GLID_IMPDOCCLIS.DOCUMENTOCLIENTE  = GLGL_DOCUMENTOCLIENTES.HANDLE 
														   And GLID_IMPDOCCLIS.EDIPESOCUBADO	 > 0)), GLGL_DOCUMENTOS.VALORCONTABIL, 0) > 0 Then 'Valor Cubado Manual'
					When IIF(EXISTS(  SELECT 1	
										FROM GLGL_DOCUMENTOASSOCIADOS
									   INNER JOIN GLGL_DOCUMENTOCLIENTES
										  ON (GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOCLIENTE		= GLGL_DOCUMENTOCLIENTES.HANDLE)
									   WHERE GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOLOGISTICA	= GLGL_DOCUMENTOS.HANDLE
										 AND GLGL_DOCUMENTOCLIENTES.K_AFERIDOCARGOSCAN		= 'N'
										 AND (GLGL_DOCUMENTOCLIENTES.CUBAGEM				= 'S'
										  Or Exists (Select 1
													   From GLGL_DOCCLICUBAGENS
													  Where GLGL_DOCCLICUBAGENS.DOCUMENTOCLIENTE = GLGL_DOCUMENTOCLIENTES.HANDLE))
										And Exists (Select 1
													  From GLID_IMPDOCCLIS 
													 Where GLID_IMPDOCCLIS.DOCUMENTOCLIENTE		 = GLGL_DOCUMENTOCLIENTES.HANDLE 
													   And GLID_IMPDOCCLIS.EDIPESOCUBADO		 > 0)), GLGL_DOCUMENTOS.VALORCONTABIL, 0) > 0 Then 'Valor Cubado EDI'

					Else 'Valor Cubado Cargo Scan'
			   End																																					[DESCRICAO],
			   IIF(EXISTS(SELECT 1
							FROM GLGL_DOCUMENTOASSOCIADOS
						   INNER JOIN GLGL_DOCUMENTOCLIENTES
							  ON (GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOCLIENTE		= GLGL_DOCUMENTOCLIENTES.HANDLE)
						   WHERE GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOLOGISTICA	= GLGL_DOCUMENTOS.HANDLE
							 AND GLGL_DOCUMENTOCLIENTES.K_AFERIDOCARGOSCAN		= 'S')
			   AND NOT EXISTS(SELECT 1
								FROM GLGL_DOCUMENTOASSOCIADOS
							   INNER JOIN GLGL_DOCUMENTOCLIENTES
								  ON (GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOCLIENTE		= GLGL_DOCUMENTOCLIENTES.HANDLE)
							   WHERE GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOLOGISTICA	= GLGL_DOCUMENTOS.HANDLE
								 AND GLGL_DOCUMENTOCLIENTES.K_AFERIDOCARGOSCAN		= 'N'
								 AND (GLGL_DOCUMENTOCLIENTES.CUBAGEM				= 'S'
								  Or Exists (Select 1
											   From GLGL_DOCCLICUBAGENS
											  Where GLGL_DOCCLICUBAGENS.DOCUMENTOCLIENTE = GLGL_DOCUMENTOCLIENTES.HANDLE))
								And Not Exists (Select 1
												  From GLID_IMPDOCCLIS 
												 Where GLID_IMPDOCCLIS.DOCUMENTOCLIENTE  = GLGL_DOCUMENTOCLIENTES.HANDLE 
												   And GLID_IMPDOCCLIS.EDIPESOCUBADO	 > 0)), CASE
																									 WHEN GLGL_DOCUMENTOS.K_VALORRECALCULADOPESO IS NOT NULL
																									 THEN (GLGL_DOCUMENTOS.VALORCONTABIL - GLGL_DOCUMENTOS.K_VALORRECALCULADOPESO)
																									 ELSE 0
																							    END, 0)																[DIFCALCULO],
			   IIF(EXISTS(SELECT 1
							FROM GLGL_DOCUMENTOASSOCIADOS
						   INNER JOIN GLGL_DOCUMENTOCLIENTES
							  ON (GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOCLIENTE		= GLGL_DOCUMENTOCLIENTES.HANDLE)
						   WHERE GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOLOGISTICA	= GLGL_DOCUMENTOS.HANDLE
							 AND ((GLGL_DOCUMENTOCLIENTES.K_AFERIDOCARGOSCAN		= 'S')
							  Or  (GLGL_DOCUMENTOCLIENTES.K_AFERIDOCARGOSCAN		= 'N'
							 AND  (GLGL_DOCUMENTOCLIENTES.CUBAGEM					= 'S'
							  Or  Exists (Select 1
										    From GLGL_DOCCLICUBAGENS
										   Where GLGL_DOCCLICUBAGENS.DOCUMENTOCLIENTE = GLGL_DOCUMENTOCLIENTES.HANDLE))))), 0, GLGL_DOCUMENTOS.VALORCONTABIL)		[VALORSEMCARGOSCAN],
			   IIF(EXISTS(SELECT 1
							FROM GLGL_DOCUMENTOASSOCIADOS
						   INNER JOIN GLGL_DOCUMENTOCLIENTES
							  ON (GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOCLIENTE		= GLGL_DOCUMENTOCLIENTES.HANDLE)
						   WHERE GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOLOGISTICA	= GLGL_DOCUMENTOS.HANDLE
							 AND GLGL_DOCUMENTOCLIENTES.K_AFERIDOCARGOSCAN		= 'S')
			   AND NOT EXISTS(SELECT 1
								FROM GLGL_DOCUMENTOASSOCIADOS
							   INNER JOIN GLGL_DOCUMENTOCLIENTES
								  ON (GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOCLIENTE		= GLGL_DOCUMENTOCLIENTES.HANDLE)
							   WHERE GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOLOGISTICA	= GLGL_DOCUMENTOS.HANDLE
								 AND GLGL_DOCUMENTOCLIENTES.K_AFERIDOCARGOSCAN		= 'N'
								 AND (GLGL_DOCUMENTOCLIENTES.CUBAGEM				= 'S'
								  Or Exists (Select 1
											   From GLGL_DOCCLICUBAGENS
											  Where GLGL_DOCCLICUBAGENS.DOCUMENTOCLIENTE = GLGL_DOCUMENTOCLIENTES.HANDLE))
								And Not Exists (Select 1
												  From GLID_IMPDOCCLIS 
												 Where GLID_IMPDOCCLIS.DOCUMENTOCLIENTE  = GLGL_DOCUMENTOCLIENTES.HANDLE 
												   And GLID_IMPDOCCLIS.EDIPESOCUBADO	 > 0)), GLGL_DOCUMENTOS.VALORCONTABIL, 0)									[VALORCUBADO],
			   IIF(EXISTS(SELECT 1
							FROM GLGL_DOCUMENTOASSOCIADOS
						   INNER JOIN GLGL_DOCUMENTOCLIENTES
							  ON (GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOCLIENTE		= GLGL_DOCUMENTOCLIENTES.HANDLE)
						   WHERE GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOLOGISTICA	= GLGL_DOCUMENTOS.HANDLE
							 AND GLGL_DOCUMENTOCLIENTES.K_AFERIDOCARGOSCAN		= 'N'
							 AND (GLGL_DOCUMENTOCLIENTES.CUBAGEM				= 'S'
							  Or Exists (Select 1
										   From GLGL_DOCCLICUBAGENS
										  Where GLGL_DOCCLICUBAGENS.DOCUMENTOCLIENTE = GLGL_DOCUMENTOCLIENTES.HANDLE))
							And Not Exists (Select 1
											  From GLID_IMPDOCCLIS 
											 Where GLID_IMPDOCCLIS.DOCUMENTOCLIENTE  = GLGL_DOCUMENTOCLIENTES.HANDLE 
											   And GLID_IMPDOCCLIS.EDIPESOCUBADO	 > 0)),	CASE
																								 WHEN GLGL_DOCUMENTOS.K_VALORRECALCULADOPESO IS NOT NULL
																								 THEN (GLGL_DOCUMENTOS.VALORCONTABIL - GLGL_DOCUMENTOS.K_VALORRECALCULADOPESO)
																								 ELSE 0
																							END, 0)										[DIFCALCULOMANUAL],
			   --IIF(EXISTS(SELECT 1
						--	FROM GLGL_DOCUMENTOASSOCIADOS
						--   INNER JOIN GLGL_DOCUMENTOCLIENTES
						--	  ON (GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOCLIENTE		= GLGL_DOCUMENTOCLIENTES.HANDLE)
						--   WHERE GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOLOGISTICA	= GLGL_DOCUMENTOS.HANDLE
						--	 AND GLGL_DOCUMENTOCLIENTES.K_AFERIDOCARGOSCAN		= 'N'
						--	 AND (GLGL_DOCUMENTOCLIENTES.CUBAGEM				= 'S'
						--	  Or Exists (Select 1
						--				   From GLGL_DOCCLICUBAGENS
						--				  Where GLGL_DOCCLICUBAGENS.DOCUMENTOCLIENTE = GLGL_DOCUMENTOCLIENTES.HANDLE))
						--	And Not Exists (Select 1
						--					  From GLID_IMPDOCCLIS 
						--					 Where GLID_IMPDOCCLIS.DOCUMENTOCLIENTE  = GLGL_DOCUMENTOCLIENTES.HANDLE 
						--					   And GLID_IMPDOCCLIS.EDIPESOCUBADO	 > 0)), GLGL_DOCUMENTOS.VALORCONTABIL, 0)			[VALORCUBADOMANUAL],

			   IIF(EXISTS(SELECT 1
			FROM GLGL_DOCUMENTOASSOCIADOS
			INNER JOIN GLGL_DOCUMENTOCLIENTES
				ON (GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOCLIENTE		= GLGL_DOCUMENTOCLIENTES.HANDLE)
			WHERE GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOLOGISTICA	= GLGL_DOCUMENTOS.HANDLE
				AND GLGL_DOCUMENTOCLIENTES.K_AFERIDOCARGOSCAN		= 'N'
				AND (GLGL_DOCUMENTOCLIENTES.CUBAGEM				= 'S'
				Or Exists (Select 1
							From GLGL_DOCCLICUBAGENS
							Where GLGL_DOCCLICUBAGENS.DOCUMENTOCLIENTE = GLGL_DOCUMENTOCLIENTES.HANDLE))
			And Not Exists (Select 1
								From GLID_IMPDOCCLIS 
								Where GLID_IMPDOCCLIS.DOCUMENTOCLIENTE  = GLGL_DOCUMENTOCLIENTES.HANDLE 
								And isnull(GLID_IMPDOCCLIS.EDIPESOCUBADO,0)	 > 0
								and isnull(GLID_IMPDOCCLIS.EDIM3,0)    > 0)), GLGL_DOCUMENTOS.VALORCONTABIL, 0)			[VALORCUBADOMANUAL],

			   IIF(EXISTS(SELECT 1
							FROM GLGL_DOCUMENTOASSOCIADOS
						   INNER JOIN GLGL_DOCUMENTOCLIENTES
							  ON (GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOCLIENTE		= GLGL_DOCUMENTOCLIENTES.HANDLE)
						   WHERE GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOLOGISTICA	= GLGL_DOCUMENTOS.HANDLE
							 AND GLGL_DOCUMENTOCLIENTES.K_AFERIDOCARGOSCAN		= 'N'
							 AND (GLGL_DOCUMENTOCLIENTES.CUBAGEM				= 'S'
							  Or Exists (Select 1
										   From GLGL_DOCCLICUBAGENS
										  Where GLGL_DOCCLICUBAGENS.DOCUMENTOCLIENTE = GLGL_DOCUMENTOCLIENTES.HANDLE))
							And Exists (Select 1
										  From GLID_IMPDOCCLIS 
										 Where GLID_IMPDOCCLIS.DOCUMENTOCLIENTE		 = GLGL_DOCUMENTOCLIENTES.HANDLE 
										   And GLID_IMPDOCCLIS.EDIPESOCUBADO		 > 0)), CASE
																							    WHEN GLGL_DOCUMENTOS.K_VALORRECALCULADOPESO IS NOT NULL
																							    THEN (GLGL_DOCUMENTOS.VALORCONTABIL - GLGL_DOCUMENTOS.K_VALORRECALCULADOPESO)
																							    ELSE 0
																							END, 0)										[DIFCALCULOEDI],
			   IIF(EXISTS(SELECT 1	
							FROM GLGL_DOCUMENTOASSOCIADOS
						   INNER JOIN GLGL_DOCUMENTOCLIENTES
							  ON (GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOCLIENTE		= GLGL_DOCUMENTOCLIENTES.HANDLE)
						   WHERE GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOLOGISTICA	= GLGL_DOCUMENTOS.HANDLE
							 AND GLGL_DOCUMENTOCLIENTES.K_AFERIDOCARGOSCAN		= 'N'
							 AND (GLGL_DOCUMENTOCLIENTES.CUBAGEM				= 'S'
							  Or Exists (Select 1
										   From GLGL_DOCCLICUBAGENS
										  Where GLGL_DOCCLICUBAGENS.DOCUMENTOCLIENTE = GLGL_DOCUMENTOCLIENTES.HANDLE))
							And Exists (Select 1
										  From GLID_IMPDOCCLIS 
										 Where GLID_IMPDOCCLIS.DOCUMENTOCLIENTE		 = GLGL_DOCUMENTOCLIENTES.HANDLE 
										   And GLID_IMPDOCCLIS.EDIPESOCUBADO		 > 0)), GLGL_DOCUMENTOS.VALORCONTABIL, 0)			[VALORCUBADOEDI]
		  FROM GLGL_DOCUMENTOS
		 Inner Join GLGL_PESSOAS
			On GLGL_PESSOAS.HANDLE							= GLGL_DOCUMENTOS.TOMADORSERVICOPESSOA
		 Inner Join GN_PESSOAS
			On GN_PESSOAS.HANDLE							= GLGL_PESSOAS.PESSOA
		  Left Join GLGL_DOCUMENTOCALCULOS			
		 Inner Join GLGL_ENUMERACAOITEMS
			On GLGL_ENUMERACAOITEMS.HANDLE					= GLGL_DOCUMENTOCALCULOS.PESOBASECALCULO
			On GLGL_DOCUMENTOCALCULOS.DOCUMENTO				= GLGL_DOCUMENTOS.HANDLE
		 WHERE Cast(GLGL_DOCUMENTOS.DATAEMISSAO As Date)	Between @DTINICIAL
																And @DTFINAL
		   AND GLGL_DOCUMENTOS.FILIAL						In (@FILIAL)
		   AND ((GLGL_DOCUMENTOS.STATUSCTE					= 7
		   AND   GLGL_DOCUMENTOS.TIPODOCUMENTO				= 2
		   AND	 GLGL_DOCUMENTOS.TIPODOCUMENTOFRETE			= 153)
			OR (GLGL_DOCUMENTOS.TIPODOCUMENTO				= 6
		   AND  GLGL_DOCUMENTOS.TIPORPS						IN (322, 902)))
		   And (GLGL_ENUMERACAOITEMS.HANDLE					In (385, 387, 1191)
		    Or EXISTS(SELECT 1
							FROM GLGL_DOCUMENTOASSOCIADOS
						   INNER JOIN GLGL_DOCUMENTOCLIENTES
							  ON (GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOCLIENTE		= GLGL_DOCUMENTOCLIENTES.HANDLE)
						   WHERE GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOLOGISTICA	= GLGL_DOCUMENTOS.HANDLE
							 AND GLGL_DOCUMENTOCLIENTES.K_AFERIDOCARGOSCAN		= 'S'))) TBBase

 Group By TBBase.CGCCPF,
	      TBBase.NOME,
		  TBBase.BASECALCULO,
		  TBBase.DESCRICAO,
		  CAST(DATAEMISSAO AS DATE),
		  DATEPART(DD, CAST(DATAEMISSAO AS DATE)),
		  DATEPART(DW, CAST(DATAEMISSAO AS DATE)),
		  TBBase.NUMERODOCUMENTO