SELECT A.PROCESSO
       ,A.PLANOCARGADESCARGA
       ,A.UNITIZADOR
       ,SUM(TOTALVOLUME) TOTALVOLUME
       ,SUM(TOTALLIDO) TOTALLIDO
       ,SUM(PESOTOTAL) PESOTOTAL
       ,SUM(FRETETOTAL) FRETETOTAL
       ,SUM(VALORTOTAL) VALORTOTAL
       ,SUM(TOTALDOCUMENTOS) TOTALDOCUMENTOS
FROM (
       /*================== Minutas de um Processo ================== */ 

       SELECT
             A.PROCESSO
           ,A.PLANOCARGADESCARGA
             ,A.UNITIZADOR
           ,SUM(TOTALVOLUME) TOTALVOLUME
           ,SUM(TOTALLIDO) TOTALLIDO
           ,SUM(PESOTOTAL) PESOTOTAL
           ,SUM(FRETE) FRETETOTAL
           ,SUM(VALORTOTAL) VALORTOTAL
             ,COUNT(1) TOTALDOCUMENTOS
       FROM ( 
                SELECT PROCESSO.HANDLE PROCESSO
                       ,PROCESSO.PLANOCARGADESCARGA
                       ,PROCESSO.UNITIZADOR
                       ,ETIQUETA.VOLUMES TOTALVOLUME
                       ,SUM(IIF(ITEM.LIDO = 'S', 1, 0)) TOTALLIDO
                       ,ISNULL(DL.DOCCLIPESOTOTAL, 0) PESOTOTAL
                       ,0 FRETE
                       ,ISNULL(DL.DOCCLIVALORTOTAL, 0) VALORTOTAL
                FROM GLGV_PROCESSOS PROCESSO(NOLOCK)
                INNER JOIN GLGV_PROCESSOITENS ITEM(NOLOCK) ON ITEM.PROCESSO = PROCESSO.HANDLE
                INNER JOIN GLGV_ETIQUETAVOLUMES VOLUME(NOLOCK) ON VOLUME.HANDLE = ITEM.VOLUME
                INNER JOIN GLGV_ETIQUETAS ETIQUETA (NOLOCK) ON ETIQUETA.HANDLE = VOLUME.ETIQUETA
                INNER JOIN GLGL_DOCUMENTOS DL(NOLOCK) ON DL.HANDLE = ETIQUETA.MINUTA
                WHERE ETIQUETA.TIPO = 2
                       AND ITEM.RETIRADO = 'N'
                GROUP BY PROCESSO.HANDLE
                       ,PROCESSO.PLANOCARGADESCARGA
                       ,PROCESSO.UNITIZADOR
                       ,DL.HANDLE
                       ,ETIQUETA.VOLUMES
                       ,DL.DOCCLIPESOTOTAL
                       ,ISNULL(DL.DOCCLIVALORTOTAL, 0)
     ) AS A
       GROUP BY A.PROCESSO,A.PLANOCARGADESCARGA,A.UNITIZADOR
       
       UNION ALL /*================== Minutas de um Processo considerando Unitizador (Apenas Valores) ================== */
       
       SELECT
             A.PROCESSO
           ,A.PLANOCARGADESCARGA
             ,NULL UNITIZADOR
           ,SUM(TOTALVOLUME) TOTALVOLUME
           ,SUM(TOTALLIDO) TOTALLIDO
           ,SUM(PESOTOTAL) PESOTOTAL
           ,SUM(FRETE) FRETETOTAL
           ,SUM(VALORTOTAL) VALORTOTAL
             ,COUNT(1) TOTALDOCUMENTOS
       FROM (
                SELECT PROCESSO.HANDLE PROCESSO
                       ,PROCESSO.PLANOCARGADESCARGA
                       ,0 TOTALVOLUME
                       ,0 TOTALLIDO
                       ,ISNULL(DL.DOCCLIPESOTOTAL, 0) PESOTOTAL
                       ,0 FRETE
                       ,ISNULL(DL.DOCCLIVALORTOTAL, 0) VALORTOTAL
                FROM GLGV_PROCESSOS PROCESSO(NOLOCK)
                INNER JOIN GLGV_PROCESSOITENS ITEM(NOLOCK) ON ITEM.PROCESSO = PROCESSO.HANDLE
                INNER JOIN GLGV_ETIQUETAVOLUMES VOLUME(NOLOCK) ON VOLUME.HANDLE = ITEM.VOLUME
                INNER JOIN GLGV_ETIQUETAS ETIQUETA(NOLOCK) ON ETIQUETA.HANDLE = VOLUME.ETIQUETA
                INNER JOIN GLGV_PROCESSOS CARGAUNITIZADOR(NOLOCK) ON CARGAUNITIZADOR.UNITIZADOR = ETIQUETA.UNITIZADOR
                INNER JOIN GLGV_PROCESSOITENS ITEMDENTROUNITIZADOR(NOLOCK) ON ITEMDENTROUNITIZADOR.PROCESSO = CARGAUNITIZADOR.HANDLE
                INNER JOIN GLGV_ETIQUETAVOLUMES VOLUMEDENTROUNITIZADOR(NOLOCK) ON VOLUMEDENTROUNITIZADOR.HANDLE = ITEMDENTROUNITIZADOR.VOLUME
                INNER JOIN GLGV_ETIQUETAS ETIQUETADENTROUNITIZADOR (NOLOCK) ON ETIQUETADENTROUNITIZADOR.HANDLE = VOLUMEDENTROUNITIZADOR.ETIQUETA
                INNER JOIN GLGL_DOCUMENTOS DL(NOLOCK) ON DL.HANDLE = ETIQUETADENTROUNITIZADOR.MINUTA
               WHERE CARGAUNITIZADOR.TIPO = 1
                       AND CARGAUNITIZADOR.SUBTIPO = 4
                       AND ETIQUETA.TIPO = 3
                       AND ETIQUETADENTROUNITIZADOR.TIPO = 2
                       AND ITEM.RETIRADO = 'N'
                       AND ITEMDENTROUNITIZADOR.RETIRADO = 'N'
                GROUP BY PROCESSO.HANDLE
                       ,PROCESSO.PLANOCARGADESCARGA
                       ,DL.HANDLE
                       ,DL.DOCCLIPESOTOTAL
                       ,ISNULL(DL.DOCCLIVALORTOTAL, 0)
     ) AS A
       GROUP BY A.PROCESSO,A.PLANOCARGADESCARGA
       
       UNION ALL /*================== Documentos clientes de um Processo ================== */

       SELECT
             A.PROCESSO
           ,A.PLANOCARGADESCARGA
             ,A.UNITIZADOR
           ,SUM(TOTALVOLUME) TOTALVOLUME
           ,SUM(TOTALLIDO) TOTALLIDO
           ,SUM(PESOTOTAL) PESOTOTAL
           ,SUM(FRETE) FRETETOTAL
           ,SUM(VALORTOTAL) VALORTOTAL
             ,0 TOTALDOCUMENTOS
       FROM ( 
                SELECT PROCESSO.HANDLE PROCESSO
                       ,PROCESSO.PLANOCARGADESCARGA
                       ,PROCESSO.UNITIZADOR
                       ,ETIQUETA.VOLUMES TOTALVOLUME
                       ,SUM(IIF(ITEM.LIDO = 'S', 1, 0)) TOTALLIDO
                       ,COALESCE(DC.PESOTOTAL, 0) PESOTOTAL
                       ,0 FRETE
                       ,ISNULL(DC.VALORTOTAL, 0) VALORTOTAL
                FROM GLGV_PROCESSOS PROCESSO(NOLOCK)
                INNER JOIN GLGV_PROCESSOITENS ITEM(NOLOCK) ON ITEM.PROCESSO = PROCESSO.HANDLE
                INNER JOIN GLGV_ETIQUETAVOLUMES VOLUME(NOLOCK) ON VOLUME.HANDLE = ITEM.VOLUME
                INNER JOIN GLGV_ETIQUETAS ETIQUETA (NOLOCK) ON ETIQUETA.HANDLE = VOLUME.ETIQUETA
                INNER JOIN GLGL_DOCUMENTOCLIENTES DC (NOLOCK) ON ETIQUETA.DOCUMENTOCLIENTE = DC.HANDLE
                WHERE ETIQUETA.TIPO = 1
                       AND ITEM.RETIRADO = 'N'
                GROUP BY PROCESSO.HANDLE
                       ,PROCESSO.PLANOCARGADESCARGA
                       ,PROCESSO.UNITIZADOR
                       ,ETIQUETA.HANDLE
                       ,COALESCE(DC.PESOTOTAL, 0)
                       ,ETIQUETA.VOLUMES
                       ,ISNULL(DC.VALORTOTAL, 0)
     ) AS A
       GROUP BY A.PROCESSO,A.PLANOCARGADESCARGA,A.UNITIZADOR
       
       UNION ALL /*================== Documentos clientes de um processo considerando unitizadores ================== */
       
       SELECT
             A.PROCESSO
           ,A.PLANOCARGADESCARGA
             ,NULL UNITIZADOR
           ,SUM(TOTALVOLUME) TOTALVOLUME
           ,SUM(TOTALLIDO) TOTALLIDO
           ,SUM(PESOTOTAL) PESOTOTAL
           ,SUM(FRETE) FRETETOTAL
           ,SUM(VALORTOTAL) VALORTOTAL
             ,0 TOTALDOCUMENTOS
       FROM (
                SELECT PROCESSO.HANDLE PROCESSO
                       ,PROCESSO.PLANOCARGADESCARGA
                       ,0 TOTALVOLUME
                       ,0 TOTALLIDO
                       ,COALESCE(DC.PESOTOTAL, 0) PESOTOTAL
                       ,0 FRETE
                       ,ISNULL(DC.VALORTOTAL, 0) VALORTOTAL
                FROM GLGV_PROCESSOS PROCESSO(NOLOCK)
                INNER JOIN GLGV_PROCESSOITENS ITEM(NOLOCK) ON ITEM.PROCESSO = PROCESSO.HANDLE
                INNER JOIN GLGV_ETIQUETAVOLUMES VOLUME(NOLOCK) ON VOLUME.HANDLE = ITEM.VOLUME
                INNER JOIN GLGV_ETIQUETAS ETIQUETA(NOLOCK) ON ETIQUETA.HANDLE = VOLUME.ETIQUETA
                INNER JOIN GLGV_PROCESSOS CARGAUNITIZADOR(NOLOCK) ON CARGAUNITIZADOR.UNITIZADOR = ETIQUETA.UNITIZADOR
                INNER JOIN GLGV_PROCESSOITENS ITEMDENTROUNITIZADOR(NOLOCK) ON ITEMDENTROUNITIZADOR.PROCESSO = CARGAUNITIZADOR.HANDLE
                INNER JOIN GLGV_ETIQUETAVOLUMES VOLUMEDENTROUNITIZADOR(NOLOCK) ON VOLUMEDENTROUNITIZADOR.HANDLE = ITEMDENTROUNITIZADOR.VOLUME
                INNER JOIN GLGV_ETIQUETAS ETIQUETADENTROUNITIZADOR (NOLOCK) ON ETIQUETADENTROUNITIZADOR.HANDLE = VOLUMEDENTROUNITIZADOR.ETIQUETA
                INNER JOIN GLGL_DOCUMENTOCLIENTES DC(NOLOCK) ON ETIQUETADENTROUNITIZADOR.DOCUMENTOCLIENTE = DC.HANDLE
                WHERE CARGAUNITIZADOR.TIPO = 1
                       AND CARGAUNITIZADOR.SUBTIPO = 4
                       AND ETIQUETA.TIPO = 3
                       AND ETIQUETADENTROUNITIZADOR.TIPO = 1
                       AND ITEM.RETIRADO = 'N'
                       AND ITEMDENTROUNITIZADOR.RETIRADO = 'N'
                GROUP BY PROCESSO.HANDLE
                       ,PROCESSO.PLANOCARGADESCARGA
                       ,ETIQUETADENTROUNITIZADOR.HANDLE
                       ,COALESCE(DC.PESOTOTAL, 0)
                       ,ISNULL(DC.VALORTOTAL, 0)
     ) AS A
       GROUP BY A.PROCESSO,A.PLANOCARGADESCARGA
       
       UNION ALL /*================== Etiqueta de NFe sem documento cliente vinculado (EDI) ================== */
       
       SELECT
             A.PROCESSO
           ,A.PLANOCARGADESCARGA
             ,A.UNITIZADOR
           ,SUM(TOTALVOLUME) TOTALVOLUME
           ,SUM(TOTALLIDO) TOTALLIDO
           ,SUM(PESOTOTAL) PESOTOTAL
           ,SUM(FRETE) FRETETOTAL
           ,SUM(VALORTOTAL) VALORTOTAL
             ,0 TOTALDOCUMENTOS
       FROM (
                SELECT PROCESSO.HANDLE PROCESSO
                       ,PROCESSO.PLANOCARGADESCARGA
                       ,PROCESSO.UNITIZADOR
                       ,ETIQUETA.VOLUMES TOTALVOLUME
                       ,SUM(IIF(ITEM.LIDO = 'S', 1, 0)) TOTALLIDO
                       ,ISNULL(EDC.EDIPESOTOTAL, 0) PESOTOTAL
                       ,0 FRETE
                       ,ISNULL(EDC.EDIVALORTOTAL, 0) VALORTOTAL
                FROM GLGV_PROCESSOS PROCESSO(NOLOCK)
                INNER JOIN GLGV_PROCESSOITENS ITEM(NOLOCK) ON ITEM.PROCESSO = PROCESSO.HANDLE
                INNER JOIN GLGV_ETIQUETAVOLUMES VOLUME(NOLOCK) ON VOLUME.HANDLE = ITEM.VOLUME
                INNER JOIN GLGV_ETIQUETAS ETIQUETA(NOLOCK) ON ETIQUETA.HANDLE = VOLUME.ETIQUETA
                INNER JOIN GN_PESSOAS R(NOLOCK) ON R.HANDLE = ETIQUETA.REMETENTE
                LEFT JOIN GLID_IMPDOCCLIS EDC(NOLOCK) ON EDC.HANDLE = (
                              SELECT MAX(A.HANDLE)
                              FROM GLID_IMPDOCCLIS A (NOLOCK)
                              WHERE (A.EDICHAVENFE = ETIQUETA.CHAVENFE)
                              )
                WHERE ETIQUETA.TIPO = 1
                       AND ETIQUETA.DOCUMENTOCLIENTE IS NULL
                       AND ITEM.RETIRADO = 'N'
                GROUP BY PROCESSO.HANDLE
                       ,PROCESSO.PLANOCARGADESCARGA
                       ,PROCESSO.UNITIZADOR
                       ,ETIQUETA.VOLUMES
                       ,ETIQUETA.HANDLE
                       ,ISNULL(EDC.EDIPESOTOTAL, 0)
                       ,ISNULL(EDC.EDIVALORTOTAL, 0)
     ) AS A
       GROUP BY A.PROCESSO,A.PLANOCARGADESCARGA,A.UNITIZADOR
       
       UNION ALL /*================== Etiqueta de NFe sem documento cliente vinculado (EDI) considerando unitizadores ================== */
       
       SELECT
             A.PROCESSO
           ,A.PLANOCARGADESCARGA
             ,NULL UNITIZADOR
           ,SUM(TOTALVOLUME) TOTALVOLUME
           ,SUM(TOTALLIDO) TOTALLIDO
           ,SUM(PESOTOTAL) PESOTOTAL
           ,SUM(FRETE) FRETETOTAL
           ,SUM(VALORTOTAL) VALORTOTAL
             ,0 TOTALDOCUMENTOS
       FROM (
                SELECT PROCESSO.HANDLE PROCESSO
                       ,PROCESSO.PLANOCARGADESCARGA
                       ,0 TOTALVOLUME
                       ,0 TOTALLIDO
                       ,ISNULL(EDC.EDIPESOTOTAL, 0) PESOTOTAL
                       ,0 FRETE
                       ,ISNULL(EDC.EDIVALORTOTAL, 0) VALORTOTAL
                FROM GLGV_PROCESSOS PROCESSO(NOLOCK)
                INNER JOIN GLGV_PROCESSOITENS ITEM(NOLOCK) ON ITEM.PROCESSO = PROCESSO.HANDLE
                INNER JOIN GLGV_ETIQUETAVOLUMES VOLUME(NOLOCK) ON VOLUME.HANDLE = ITEM.VOLUME
                INNER JOIN GLGV_ETIQUETAS ETIQUETA(NOLOCK) ON ETIQUETA.HANDLE = VOLUME.ETIQUETA
                INNER JOIN GLGV_PROCESSOS CARGAUNITIZADOR(NOLOCK) ON CARGAUNITIZADOR.UNITIZADOR = ETIQUETA.UNITIZADOR
                INNER JOIN GLGV_PROCESSOITENS ITEMDENTROUNITIZADOR(NOLOCK) ON ITEMDENTROUNITIZADOR.PROCESSO = CARGAUNITIZADOR.HANDLE
                INNER JOIN GLGV_ETIQUETAVOLUMES VOLUMEDENTROUNITIZADOR(NOLOCK) ON VOLUMEDENTROUNITIZADOR.HANDLE = ITEMDENTROUNITIZADOR.VOLUME
                INNER JOIN GLGV_ETIQUETAS ETIQUETADENTROUNITIZADOR(NOLOCK) ON ETIQUETADENTROUNITIZADOR.HANDLE = VOLUMEDENTROUNITIZADOR.ETIQUETA
                LEFT JOIN GLID_IMPDOCCLIS EDC(NOLOCK) ON EDC.HANDLE = (
                              SELECT MAX(A.HANDLE)
                              FROM GLID_IMPDOCCLIS A (NOLOCK)
                              WHERE (A.EDICHAVENFE = ETIQUETA.CHAVENFE)
                              )
                WHERE CARGAUNITIZADOR.TIPO = 1
                       AND CARGAUNITIZADOR.SUBTIPO = 4
                       AND ETIQUETA.TIPO = 3
                       AND ETIQUETADENTROUNITIZADOR.TIPO = 1
                       AND ETIQUETADENTROUNITIZADOR.DOCUMENTOCLIENTE IS NULL
                       AND ITEM.RETIRADO = 'N'
                       AND ITEMDENTROUNITIZADOR.RETIRADO = 'N'
                GROUP BY PROCESSO.HANDLE
                       ,PROCESSO.PLANOCARGADESCARGA
                       ,ETIQUETADENTROUNITIZADOR.HANDLE
                       ,ISNULL(EDC.EDIPESOTOTAL, 0)
                       ,ISNULL(EDC.EDIVALORTOTAL, 0)
     ) AS A
       GROUP BY A.PROCESSO,A.PLANOCARGADESCARGA
       
       UNION ALL /*================== Soma de etiquetas de unitizadores lidos (1/1) ================== */

       SELECT
             A.PROCESSO
           ,A.PLANOCARGADESCARGA
             ,NULL UNITIZADOR
           ,SUM(TOTALVOLUME) TOTALVOLUME
           ,SUM(TOTALLIDO) TOTALLIDO
           ,SUM(PESOTOTAL) PESOTOTAL
          ,SUM(FRETE) FRETETOTAL
           ,SUM(VALORTOTAL) VALORTOTAL
             ,0 TOTALDOCUMENTOS
       FROM ( 
                SELECT PROCESSO.HANDLE PROCESSO
                       ,PROCESSO.PLANOCARGADESCARGA
                       ,ETIQUETA.VOLUMES TOTALVOLUME
                       ,SUM(IIF(ITEM.LIDO = 'S', 1, 0)) TOTALLIDO
                       ,0 PESOTOTAL
                       ,0 FRETE
                       ,0 VALORTOTAL
                FROM GLGV_PROCESSOS PROCESSO(NOLOCK)
                INNER JOIN GLGV_PROCESSOITENS ITEM(NOLOCK) ON ITEM.PROCESSO = PROCESSO.HANDLE
                INNER JOIN GLGV_ETIQUETAVOLUMES VOLUME(NOLOCK) ON VOLUME.HANDLE = ITEM.VOLUME
                INNER JOIN GLGV_ETIQUETAS ETIQUETA(NOLOCK) ON ETIQUETA.HANDLE = VOLUME.ETIQUETA
                WHERE ETIQUETA.TIPO = 3
                       AND ITEM.RETIRADO = 'N'
                GROUP BY PROCESSO.HANDLE
                       ,PROCESSO.PLANOCARGADESCARGA
                       ,ETIQUETA.UNITIZADOR
                       ,ETIQUETA.VOLUMES
     ) AS A
       GROUP BY A.PROCESSO,A.PLANOCARGADESCARGA
       
       UNION ALL /*================== Obter Valor do frete dos documentos ================== */

       SELECT
             A.PROCESSO
           ,A.PLANOCARGADESCARGA
             ,A.UNITIZADOR
           ,SUM(TOTALVOLUME) TOTALVOLUME
           ,SUM(TOTALLIDO) TOTALLIDO
           ,SUM(PESOTOTAL) PESOTOTAL
           ,SUM(FRETE) FRETETOTAL
           ,SUM(VALORTOTAL) VALORTOTAL
             ,COUNT(1) TOTALDOCUMENTOS
       FROM (        
                SELECT PROCESSO.HANDLE PROCESSO
                       ,PROCESSO.PLANOCARGADESCARGA
                    ,PROCESSO.UNITIZADOR
                       ,0 TOTALVOLUME
                       ,0 TOTALLIDO
                       ,0 PESOTOTAL
                       ,DL.VALORCONTABIL FRETE
                       ,0 VALORTOTAL
                FROM GLGV_PROCESSOS PROCESSO(NOLOCK)
                INNER JOIN GLGV_PROCESSOITENS ITEM(NOLOCK) ON ITEM.PROCESSO = PROCESSO.HANDLE
                INNER JOIN GLGV_ETIQUETAVOLUMES VOLUME(NOLOCK) ON VOLUME.HANDLE = ITEM.VOLUME
                INNER JOIN GLGV_ETIQUETAS ETIQUETA(NOLOCK) ON ETIQUETA.HANDLE = VOLUME.ETIQUETA
                INNER JOIN GLGL_DOCUMENTOCLIENTES DC(NOLOCK) ON ETIQUETA.DOCUMENTOCLIENTE = DC.HANDLE
                INNER JOIN GLGL_DOCUMENTOASSOCIADOS DA(NOLOCK) ON DA.DOCUMENTOCLIENTE = DC.HANDLE
                INNER JOIN GLGL_DOCUMENTOS DL(NOLOCK) ON DL.HANDLE = DA.DOCUMENTOLOGISTICA
                WHERE ETIQUETA.TIPO = 1
                       AND ITEM.RETIRADO = 'N'
                       AND (
                              DL.TIPODOCUMENTO = 2 OR (DL.TIPODOCUMENTO = 6 AND DL.TIPORPS IN (322,902))
                              )
                       AND DL.STATUS NOT IN (236,237,417)
                GROUP BY PROCESSO.HANDLE
                       ,PROCESSO.PLANOCARGADESCARGA
                       ,PROCESSO.UNITIZADOR
                       ,DL.HANDLE
                       ,DL.VALORCONTABIL
       ) AS A
       GROUP BY A.PROCESSO,A.PLANOCARGADESCARGA,A.UNITIZADOR

       UNION ALL /*================== Obter Valor do frete dos documentos considerando unitizadores ================== */

       SELECT
             A.PROCESSO
           ,A.PLANOCARGADESCARGA
             ,NULL UNITIZADOR
           ,SUM(TOTALVOLUME) TOTALVOLUME
           ,SUM(TOTALLIDO) TOTALLIDO
           ,SUM(PESOTOTAL) PESOTOTAL
           ,SUM(FRETE) FRETETOTAL
           ,SUM(VALORTOTAL) VALORTOTAL
             ,COUNT(1) TOTALDOCUMENTOS
       FROM ( 
                SELECT PROCESSO.HANDLE PROCESSO
                       ,PROCESSO.PLANOCARGADESCARGA
                       ,0 TOTALVOLUME
                       ,0 TOTALLIDO
                       ,0 PESOTOTAL
                       ,DL.VALORCONTABIL FRETE
                       ,0 VALORTOTAL
                FROM GLGV_PROCESSOS PROCESSO(NOLOCK)
                INNER JOIN GLGV_PROCESSOITENS ITEM(NOLOCK) ON ITEM.PROCESSO = PROCESSO.HANDLE
                INNER JOIN GLGV_ETIQUETAVOLUMES VOLUME(NOLOCK) ON VOLUME.HANDLE = ITEM.VOLUME
                INNER JOIN GLGV_ETIQUETAS ETIQUETA(NOLOCK) ON ETIQUETA.HANDLE = VOLUME.ETIQUETA
                INNER JOIN GLGV_PROCESSOS CARGAUNITIZADOR(NOLOCK) ON CARGAUNITIZADOR.UNITIZADOR = ETIQUETA.UNITIZADOR
                INNER JOIN GLGV_PROCESSOITENS ITEMDENTROUNITIZADOR(NOLOCK) ON ITEMDENTROUNITIZADOR.PROCESSO = CARGAUNITIZADOR.HANDLE
                INNER JOIN GLGV_ETIQUETAVOLUMES VOLUMEDENTROUNITIZADOR(NOLOCK) ON VOLUMEDENTROUNITIZADOR.HANDLE = ITEMDENTROUNITIZADOR.VOLUME
                INNER JOIN GLGV_ETIQUETAS ETIQUETADENTROUNITIZADOR(NOLOCK) ON ETIQUETADENTROUNITIZADOR.HANDLE = VOLUMEDENTROUNITIZADOR.ETIQUETA
                INNER JOIN GLGL_DOCUMENTOCLIENTES DC (NOLOCK) ON ETIQUETADENTROUNITIZADOR.DOCUMENTOCLIENTE = DC.HANDLE
                INNER JOIN GLGL_DOCUMENTOASSOCIADOS DA(NOLOCK) ON DA.DOCUMENTOCLIENTE = DC.HANDLE
                INNER JOIN GLGL_DOCUMENTOS DL(NOLOCK) ON DL.HANDLE = DA.DOCUMENTOLOGISTICA
                WHERE CARGAUNITIZADOR.TIPO = 1
                       AND CARGAUNITIZADOR.SUBTIPO = 4
                       AND ETIQUETA.TIPO = 3
                       AND ETIQUETADENTROUNITIZADOR.TIPO = 1
                       AND ITEM.RETIRADO = 'N'
                       AND ITEMDENTROUNITIZADOR.RETIRADO = 'N'
                       AND (
                              DL.TIPODOCUMENTO = 2 OR (DL.TIPODOCUMENTO = 6 AND DL.TIPORPS IN (322,902))
                              )
                       AND DL.STATUS NOT IN (236,237,417)
                GROUP BY PROCESSO.HANDLE
                       ,PROCESSO.PLANOCARGADESCARGA
                       ,DL.HANDLE
                       ,DL.VALORCONTABIL
     ) AS A
       GROUP BY A.PROCESSO,A.PLANOCARGADESCARGA
       
       UNION ALL /*================== Processo sem leituras ================== */
       
       SELECT PROCESSO.HANDLE PROCESSO
             ,PROCESSO.PLANOCARGADESCARGA
             ,PROCESSO.UNITIZADOR
             ,0 TOTALVOLUME
             ,0 TOTALLIDO
             ,0 PESOTOTAL
             ,0 FRETE
             ,0 VALORTOTAL
             ,0 TOTALDOCUMENTOS
       FROM GLGV_PROCESSOS PROCESSO(NOLOCK)
       WHERE NOT EXISTS (
                    SELECT 1
                    FROM GLGV_PROCESSOITENS ITEM(NOLOCK)
                    WHERE ITEM.PROCESSO = PROCESSO.HANDLE
                           AND ITEM.RETIRADO = 'N'
                    )
       ) AS A
GROUP BY A.PROCESSO
       ,A.PLANOCARGADESCARGA
       ,A.UNITIZADOR

