create procedure [dbo].[SP_DOC_TRANS_MAS_RELA_BX] AS

--DOCUMENTOS EM TRANSITO EM RELAçãO DE ENTREGA  E MANIFESTOS Já BAIXADOS

 DECLARE @LNGPOLOCOLETA INT
        , @LNGDOC INT
        
--DECLARE @DATAI DATE = '2020-03-19'
--DECLARE @DATAF DATE = '2020-03-20'

Declare
	@CodigoToyota		TABLE(CODIGOCONCESSIOARIA	VarChar(30),
							TIPO					VarChar(50),
							CONCESSIONARIA			VarChar(250),
							MUNICIPIO				Int,
							ESTADO					Int,
							CGCCPF					VarChar(20))

--Insert Into @CodigoToyota Values ('1095130','3S','TROP (SUAPE)', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('RECIFE')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='PE')), (Select HANDLE From ESTADOS Where SIGLA ='PE'),'' )
--Insert Into @CodigoToyota Values ('1410030','3S','TOYOTA SULPAR LTDA - PSAL', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('CURITIBA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='PR')), (Select HANDLE From ESTADOS Where SIGLA ='PR'),'' )
--Insert Into @CodigoToyota Values ('1410031','3S','TOYOTA SULPAR LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('CURITIBA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='PR')), (Select HANDLE From ESTADOS Where SIGLA ='PR'),'' )
--Insert Into @CodigoToyota Values ('1410050','3S','ESPACO AUTOMOVEIS LTDA - PSAL', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('CURITIBA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='PR')), (Select HANDLE From ESTADOS Where SIGLA ='PR'),'' )
--Insert Into @CodigoToyota Values ('1410068','3S','TOYOPAR COMERCIO DE VEICULOS E PECAS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('SANTO ANTONIO DA PLATINA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='PR')), (Select HANDLE From ESTADOS Where SIGLA ='PR'),'' )
--Insert Into @CodigoToyota Values ('1410365','3S','GERMANO ZENI VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('CASCAVEL')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='PR')), (Select HANDLE From ESTADOS Where SIGLA ='PR'),'' )
--Insert Into @CodigoToyota Values ('1410366','3S','GERMANO ZENI VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('TOLEDO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='PR')), (Select HANDLE From ESTADOS Where SIGLA ='PR'),'' )
--Insert Into @CodigoToyota Values ('1410451','3S','TOYOPAR COMERCIO DE VEICULOS E PECAS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('LONDRINA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='PR')), (Select HANDLE From ESTADOS Where SIGLA ='PR'),'' )
--Insert Into @CodigoToyota Values ('1410511','3S','NOMA VEICULOS AUTOMOTORES LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('MARINGA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='PR')), (Select HANDLE From ESTADOS Where SIGLA ='PR'),'' )
--Insert Into @CodigoToyota Values ('1410521','3S','ESPACO AUTOMOVEIS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('CURITIBA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='PR')), (Select HANDLE From ESTADOS Where SIGLA ='PR'),'' )
--Insert Into @CodigoToyota Values ('1410559','3S','TOYOPABRA VEIC E PECAS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('PATO BRANCO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='PR')), (Select HANDLE From ESTADOS Where SIGLA ='PR'),'' )
--Insert Into @CodigoToyota Values ('1411261','3S','TRACADO VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('UMUARAMA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='PR')), (Select HANDLE From ESTADOS Where SIGLA ='PR'),'' )
--Insert Into @CodigoToyota Values ('1411300','3S','TOYCAS COMERCIAL VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('PONTA GROSSA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='PR')), (Select HANDLE From ESTADOS Where SIGLA ='PR'),'' )
--Insert Into @CodigoToyota Values ('1412725','2S','GERMANO ZENI VEICULOS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('FRANCISCO BELTRAO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='PR')), (Select HANDLE From ESTADOS Where SIGLA ='PR'),'' )
--Insert Into @CodigoToyota Values ('1418711','3S','ESPACO AUTOMOVEIS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('GUARAPUAVA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='PR')), (Select HANDLE From ESTADOS Where SIGLA ='PR'),'' )
--Insert Into @CodigoToyota Values ('1418933','2S','GERMANO ZENI VEICULOS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('FOZ DO IGUACU')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='PR')), (Select HANDLE From ESTADOS Where SIGLA ='PR'),'' )
--Insert Into @CodigoToyota Values ('1419183','2S','TOYOPAR COMERCIO DE VEICULOS E PECAS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('APUCARANA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='PR')), (Select HANDLE From ESTADOS Where SIGLA ='PR'),'' )
--Insert Into @CodigoToyota Values ('1419194','2S','TOYOTA SULPAR LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('PARANAGUA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='PR')), (Select HANDLE From ESTADOS Where SIGLA ='PR'),'' )
--Insert Into @CodigoToyota Values ('1420245','3S','SPERANDIO MOTORS COMERCIO DE VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('CHAPECO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SC')), (Select HANDLE From ESTADOS Where SIGLA ='SC'),'' )
--Insert Into @CodigoToyota Values ('1420355','3S','ZAUTO VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('LAGES')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SC')), (Select HANDLE From ESTADOS Where SIGLA ='SC'),'' )
--Insert Into @CodigoToyota Values ('1420447','3S','HAI AUTOMOVEIS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('FLORIANOPOLIS')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SC')), (Select HANDLE From ESTADOS Where SIGLA ='SC'),'' )
--Insert Into @CodigoToyota Values ('1420448','3S','HAI AUTOMOVEIS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('ITAJAI')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SC')), (Select HANDLE From ESTADOS Where SIGLA ='SC'),'' )
--Insert Into @CodigoToyota Values ('1421016','2S','TOYOVILLE COM.VEIC.PEC.LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('JARAGUA DO SUL')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SC')), (Select HANDLE From ESTADOS Where SIGLA ='SC'),'' )
--Insert Into @CodigoToyota Values ('1421068','3S','MERCOSUL VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('TUBARAO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SC')), (Select HANDLE From ESTADOS Where SIGLA ='SC'),'' )
--Insert Into @CodigoToyota Values ('1421073','3S','TOYOVILLE COM.VEIC.PEC.LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('JOINVILLE')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SC')), (Select HANDLE From ESTADOS Where SIGLA ='SC'),'' )
--Insert Into @CodigoToyota Values ('1421249','3S','TARPAN COM.VEICS.PEC.LTDA.', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('BLUMENAU')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SC')), (Select HANDLE From ESTADOS Where SIGLA ='SC'),'' )
--Insert Into @CodigoToyota Values ('1421420','3S','MOTOLANDIA LAJEADO LTDA.', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('LAJEADO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RS')), (Select HANDLE From ESTADOS Where SIGLA ='RS'),'' )
--Insert Into @CodigoToyota Values ('1425827','2S','MERCOSUL VEICULOS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('CRICIUMA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SC')), (Select HANDLE From ESTADOS Where SIGLA ='SC'),'' )
--Insert Into @CodigoToyota Values ('1425899','3S','COM.VEIC.ARISTIDES MALLON LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('CANOINHAS')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RS')), (Select HANDLE From ESTADOS Where SIGLA ='RS'),'' )
--Insert Into @CodigoToyota Values ('1428878','3S','TERRASOL VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('CAXIAS DO SUL')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RS')), (Select HANDLE From ESTADOS Where SIGLA ='RS'),'' )
--Insert Into @CodigoToyota Values ('1429163','3S','CARHOUSE VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('SANTA MARIA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RS')), (Select HANDLE From ESTADOS Where SIGLA ='RS'),'' )
--Insert Into @CodigoToyota Values ('1429164','3S','CARHOUSE VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('PASSO FUNDO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RS')), (Select HANDLE From ESTADOS Where SIGLA ='RS'),'' )
--Insert Into @CodigoToyota Values ('1429344','2S','HAI AUTOMOVEIS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('BRUSQUE')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SC')), (Select HANDLE From ESTADOS Where SIGLA ='SC'),'' )
--Insert Into @CodigoToyota Values ('1429430','2S','TARPAN COM.VEICS.PEC.LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('RIO DO SUL')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SC')), (Select HANDLE From ESTADOS Where SIGLA ='SC'),'' )
--Insert Into @CodigoToyota Values ('1429562','3S','STRADA MOTORS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('ARARANGUA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SC')), (Select HANDLE From ESTADOS Where SIGLA ='SC'),'' )
--Insert Into @CodigoToyota Values ('1430580','3S','SAVARAUTO 2000 COMERCIO DE VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('PELOTAS')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RS')), (Select HANDLE From ESTADOS Where SIGLA ='RS'),'' )
--Insert Into @CodigoToyota Values ('1431076','2S','TERRASOL VEICULOS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('BENTO GONCALVES')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RS')), (Select HANDLE From ESTADOS Where SIGLA ='RS'),'' )
--Insert Into @CodigoToyota Values ('1431408','3S','CARHOUSE VEICULOS LTDA - PSAL', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('PORTO ALEGRE')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RS')), (Select HANDLE From ESTADOS Where SIGLA ='RS'),'' )
--Insert Into @CodigoToyota Values ('1431500','3S','CARHOUSE VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('NOVO HAMBURGO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RS')), (Select HANDLE From ESTADOS Where SIGLA ='RS'),'' )
--Insert Into @CodigoToyota Values ('1431501','3S','CARHOUSE VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('PORTO ALEGRE')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RS')), (Select HANDLE From ESTADOS Where SIGLA ='RS'),'' )
--Insert Into @CodigoToyota Values ('1435993','2S','SAVARAUTO 2000 COMERCIO DE VEICULOS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('CANOAS')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RS')), (Select HANDLE From ESTADOS Where SIGLA ='RS'),'' )
--Insert Into @CodigoToyota Values ('1437507','3S','SAVARAUTO 2000 COMERCIO DE VEICULOS LTDA-PSAL', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('PORTO ALEGRE')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RS')), (Select HANDLE From ESTADOS Where SIGLA ='RS'),'' )
--Insert Into @CodigoToyota Values ('1439365','3S','CARHOUSE VEICULOS LTDA - 3S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('IJUI')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RS')), (Select HANDLE From ESTADOS Where SIGLA ='RS'),'' )
--Insert Into @CodigoToyota Values ('2114755','2S','KURUMA VEICULOS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('TEOFILO OTONI')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'00.827.783/0026-30' )
--Insert Into @CodigoToyota Values ('2310288','2S','IMPERIAL VEICULOS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('UBA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'64.286.420/0002-40' )
--Insert Into @CodigoToyota Values ('2310649','3S','FUTURA VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('UBERLANDIA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'02.563.250/0001-65' )
--Insert Into @CodigoToyota Values ('2310660','3S','GOVESA MOTORS VEICULOS PECAS E SERVICOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('UBERABA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'07.066.165/0001-05' )
--Insert Into @CodigoToyota Values ('2311320','2S','NIPONICA COMERCIO DE VEICULOS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('POUSO ALEGRE')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'07.215.045/0006-36' )
--Insert Into @CodigoToyota Values ('2311369','3S','IMPERIAL VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('JUIZ DE FORA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'64.286.420/0001-69' )
--Insert Into @CodigoToyota Values ('2311500','3S','AB COMERCIO DE VEICULOS LTDA - PSAL', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('BELO HORIZONTE')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'07.124.577/0001-54' )
--Insert Into @CodigoToyota Values ('2312346','3S','KURUMA VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('IPATINGA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'00.827.783/0009-39' )
--Insert Into @CodigoToyota Values ('2312348','3S','KURUMA VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('MANHUACU')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'00.827.783/0010-72' )
--Insert Into @CodigoToyota Values ('2312350','3S','KURUMA VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('GOVERNADOR VALADARES')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'00.827.783/0008-58' )
--Insert Into @CodigoToyota Values ('2312352','3S','KURUMA VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('MURIAE')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'00.827.783/0011-53' )
--Insert Into @CodigoToyota Values ('2312353','3S','KURUMA VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('VILA VELHA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='ES')), (Select HANDLE From ESTADOS Where SIGLA ='ES'),'' )
--Insert Into @CodigoToyota Values ('2312354','3S','KURUMA VEICULOS LTDA - PSAL', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('RIO DE JANEIRO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RJ')), (Select HANDLE From ESTADOS Where SIGLA ='RJ'),'00.827.783/0015-87' )
--Insert Into @CodigoToyota Values ('2312400','3S','NIPONICA COMERCIO DE VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('VARGINHA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'07.215.045/0001-22' )
--Insert Into @CodigoToyota Values ('2312401','3S','NIPONICA COMERCIO DE VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('LIMEIRA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2312402','3S','NIPONICA COMERCIO DE VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('POCOS DE CALDAS')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'07.215.045/0004-75' )
--Insert Into @CodigoToyota Values ('2315644','3S','GNC COMERCIO DE VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('DIVINOPOLIS')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'09.564.676/0002-63' )
--Insert Into @CodigoToyota Values ('2316719','3S','GNC COMERCIO DE VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('MONTES CLAROS')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'09.564.676/0003-44' )
--Insert Into @CodigoToyota Values ('2318228','3S','AB COMERCIO DE VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('BELO HORIZONTE')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'07.124.577/0002-35' )
--Insert Into @CodigoToyota Values ('2318934','2S','AB COMERCIO DE VEICULOS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('SETE LAGOAS')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'07.124.577/0004-05' )
--Insert Into @CodigoToyota Values ('2319222','2S','FUTURA VEICULOS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('PATOS DE MINAS')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'02.563.250/0004-08' )
--Insert Into @CodigoToyota Values ('2319344','2S','KURUMA VEICULOS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('JOAO MONLEVADE')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'00.827.783/0022-06' )
--Insert Into @CodigoToyota Values ('2320680','3S','KURUMA VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('LINHARES')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='ES')), (Select HANDLE From ESTADOS Where SIGLA ='ES'),'' )
--Insert Into @CodigoToyota Values ('2321437','3S','KURUMA VEICULOS LTDA - PSAL', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('VITORIA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='ES')), (Select HANDLE From ESTADOS Where SIGLA ='ES'),'' )
--Insert Into @CodigoToyota Values ('2326297','2S','KURUMA VEICULOS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('CARIACICA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='ES')), (Select HANDLE From ESTADOS Where SIGLA ='ES'),'' )
--Insert Into @CodigoToyota Values ('2326686','3S','KURUMA VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('CACHOEIRO DE ITAPEMIRIM')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='ES')), (Select HANDLE From ESTADOS Where SIGLA ='ES'),'' )
--Insert Into @CodigoToyota Values ('2328160','2S Fleet','KURUMA VEICULOS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Serra')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='ES')), (Select HANDLE From ESTADOS Where SIGLA ='ES'),'' )
--Insert Into @CodigoToyota Values ('2328885','2S','KURUMA VEICULOS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('SAO MATEUS')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='ES')), (Select HANDLE From ESTADOS Where SIGLA ='ES'),'' )
--Insert Into @CodigoToyota Values ('2328887','2S','KURUMA VEICULOS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('GUARAPARI')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='ES')), (Select HANDLE From ESTADOS Where SIGLA ='ES'),'' )
--Insert Into @CodigoToyota Values ('2329061','2S','KURUMA VEICULOS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('COLATINA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='ES')), (Select HANDLE From ESTADOS Where SIGLA ='ES'),'' )
--Insert Into @CodigoToyota Values ('2330240','3S','TOYOSERRA VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('NOVA FRIBURGO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RJ')), (Select HANDLE From ESTADOS Where SIGLA ='RJ'),'32.565.848/0001-54' )
--Insert Into @CodigoToyota Values ('2331048','3S','MOITINHO AUTOMOVEIS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('RIO DE JANEIRO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RJ')), (Select HANDLE From ESTADOS Where SIGLA ='RJ'),'22.460.858/0001-09' )
--Insert Into @CodigoToyota Values ('2331278','3S','SGA NITEROI VEICULOS E PECAS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('NITEROI')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RJ')), (Select HANDLE From ESTADOS Where SIGLA ='RJ'),'36,152,916/0001-04' )
--Insert Into @CodigoToyota Values ('2331279','3S','SGA NITEROI VEICULOS E PECAS LTDA.', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('NITEROI')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RJ')), (Select HANDLE From ESTADOS Where SIGLA ='RJ'),'36.152.916/0003-76' )
--Insert Into @CodigoToyota Values ('2331281','3S','SGA NITEROI VEICULOS E PECAS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('GOITACAZES - CAMPOS DOS GOYTACAZES')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RJ')), (Select HANDLE From ESTADOS Where SIGLA ='RJ'),'36.152.916/0004-57' )
--Insert Into @CodigoToyota Values ('2334960','2S','KURUMA VEICULOS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('CAMPO GRANDE')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RJ')), (Select HANDLE From ESTADOS Where SIGLA ='RJ'),'' )
--Insert Into @CodigoToyota Values ('2337150','2S','TOYOSERRA VEICULOS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('CABO FRIO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RJ')), (Select HANDLE From ESTADOS Where SIGLA ='RJ'),'32.565.848/0002-35' )
--Insert Into @CodigoToyota Values ('2338194','3S','INTER JAPAN VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('SAO JOAO DE MERITI')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RJ')), (Select HANDLE From ESTADOS Where SIGLA ='RJ'),'05.027.327/0004-13' )
--Insert Into @CodigoToyota Values ('2338233','3S','INTER JAPAN VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('RIO DE JANEIRO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RJ')), (Select HANDLE From ESTADOS Where SIGLA ='RJ'),'05.027.327/0006-85' )
--Insert Into @CodigoToyota Values ('2339696','3S','TOYAMA AUTOMOVEIS LTDA - 3S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('BARRA MANSA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RJ')), (Select HANDLE From ESTADOS Where SIGLA ='RJ'),'21.460.858/0001-09' )
--Insert Into @CodigoToyota Values ('2350219','3S','NIPPOKAR LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('PIRACICABA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2350317','3S','MORI MOTOR S COMERCIO DE VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('BAURU')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2350500','3S','DISTRIBUIDORA DE VEICULOS FREIRE LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('MARILIA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2350612','3S','UNITED AUTO ARICANDUVA COMERCIO DE VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('SAO JOSE DOS CAMPOS')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2350648','3S','MALABAR COML.VEIC.LTDA-EXPOENT', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('JUNDIAI')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2350649','3S','GRAND MOTORS COMERCIO DE VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('SAO PAULO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2350657','3S','DESTAQUE MOTORS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('CAMPINAS')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2350702','3S','VIVIANI MOTORS COMERCIO DE VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('ARACATUBA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2350869','3S','Rodobens Comercio e Locacao de Veiculos Ltda - PSAL', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('SAO JOSE DO RIO PRETO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2350901','2S','RAMIRES MOTORS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('ITAPETININGA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2351008','2S','BACABA VEICULOS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('BOTUCATU')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2351026','2S','MALABAR COML.VEIC.LTDA-EXPOENT - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('BRAGANCA PAULISTA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2351130','3S','INTER JAPAN VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('SAO PAULO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2351132','3S','SORANA VEICULOS E SERVICOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('SAO PAULO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2351135','3S','NIPPOKAR LTDA - PSAL', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('CAMPINAS')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2351137','3S','NIPPOKAR LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('CAMPINAS')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2351458','3S','SANTA EMILIA MOTORS-COMERCIAL DE VEIC E PECAS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('RIBEIRAO PRETO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2351511','3S','COLLECTION MOTORS IMP.COM.LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('SAO PAULO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2351534','3S','COM.VEIC.TOYOTA TSUSHO LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('SAO PAULO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2351535','2S','COMERCIO DE VEICULOS TOYOTA TSUSHO LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('SUZANO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2351546','3S','COLLECTION MOTORS IMP.COM.LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('SANTOS')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2351560','3S','COMERCIO DE VEICULOS TOYOTA TSUSHO LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('MOGI DAS CRUZES')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2351570','3S','T.LINE VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('SAO PAULO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2351934','2S','VIVIANI MOTORS COMERCIO DE VEICULOS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('JALES')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2352568','2S','Rodobens Comercio e Locacao de Veiculos Ltda - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('CATANDUVA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2352577','2S','STEFANI MOTORS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('JABOTICABAL')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2352591','3S','COLLECTION MOTORS IMP COM L BRIGADEIRO', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('SAO PAULO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2352623','3S','MAGGI MOTORS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('ITU')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2352624','3S','MAGGI MOTORS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('AMERICANA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2352625','3S','MAGGI MOTORS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('PIRASSUNUNGA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2352626','3S','MAGGI MOTORS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('INDAIATUBA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2354013','3S','NIPONICA COMERCIO DE VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('RIO CLARO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2354459','3S','CMBERRINI VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('SAO PAULO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2354512','3S','ALPHA TREVO AUTOMOVEIS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('BARUERI')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2354515','3S','COMERCIO DE VEICULOS TOYOTA TSUSHO LTDA - PSAL', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('SAO CAETANO DO SUL')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2354533','3S','SHOGUN VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('SANTO ANDRE')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2354563','3S','SORTE VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('SAO BERNARDO DO CAMPO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2354624','3S','STEFANI MOTORS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('ARARAQUARA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2354627','3S','VIA JAPAN LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('PRESIDENTE PRUDENTE')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2354951','3S','RAMIRES MOTORS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('SOROCABA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2355320','2S','SHOGUN VEICULOS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('MAUA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2355413','2S','BACABA VEICULOS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('OURINHOS')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2355550','TDB','TOYOTA DO BRASIL LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('SAO BERNARDO DO CAMPO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2355697','2S','UNITED AUTO ARICANDUVA COMERCIO DE VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('TAUBATE')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2355923','3S','ELEVIS COMERCIO DE VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('RIBEIRAO PRETO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2355948','2S','DISTRIBUIDORA DE VEICULOS FREIRE LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('ASSIS')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2356195','3S','NOVA QUALITY VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('GUARULHOS')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2356270','3S','CMPAC AUTOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('SAO PAULO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2358212','3S','NIPPOKAR LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('MOGI MIRIM')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2358986','3S','INTER JAPAN VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('SAO PAULO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2359233','2S','NOVA QUALITY VEICULOS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('SAO PAULO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2359536','3S','SANTA EMILIA MOTORS-COMERCIAL DE VEIC E PECAS LTDA - 3S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('FRANCA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2359625','3S','SUN NORTH MOTORS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('SAO PAULO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2359739','2S','VIVIANI MOTORS COMERCIO DE VEICULOS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('LINS')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2359753','2S','STEFANI MOTORS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('SAO CARLOS')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('2359955','3S','UNITED AUTO ARICANDUVA COMERCIO DE VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('SAO PAULO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('3500819','3S','DOURAMOTORS VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('DOURADOS')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MS')), (Select HANDLE From ESTADOS Where SIGLA ='MT'),'' )
--Insert Into @CodigoToyota Values ('3502155','3S','KAMPAI MOTORS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('CAMPO GRANDE')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MS')), (Select HANDLE From ESTADOS Where SIGLA ='MS'),'' )
--Insert Into @CodigoToyota Values ('3509953','2S','DOURAMOTORS VEICULOS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('TRES LAGOAS')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MT')), (Select HANDLE From ESTADOS Where SIGLA ='MT'),'' )
--Insert Into @CodigoToyota Values ('3510247','3S','DISVECO LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('CUIABA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MT')), (Select HANDLE From ESTADOS Where SIGLA ='MT'),'' )
--Insert Into @CodigoToyota Values ('3510704','2S','Rodobens Comercio e Locacao de Veiculos Ltda - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('PRIMAVERA DO LESTE')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MT')), (Select HANDLE From ESTADOS Where SIGLA ='MT'),'' )
--Insert Into @CodigoToyota Values ('3510790','3S','Rodobens Comercio e Locacao de Veiculos Ltda', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('SINOP')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MT')), (Select HANDLE From ESTADOS Where SIGLA ='MT'),'' )
--Insert Into @CodigoToyota Values ('3510920','3S','Rodobens Comercio e Locacao de Veiculos Ltda', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('RONDONOPOLIS')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MT')), (Select HANDLE From ESTADOS Where SIGLA ='MT'),'' )
--Insert Into @CodigoToyota Values ('3511191','2S','Rodobens Comercio e Locacao de Veiculos Ltda - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('LUCAS DO RIO VERDE')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MT')), (Select HANDLE From ESTADOS Where SIGLA ='MT'),'' )
--Insert Into @CodigoToyota Values ('3511922','2S','Rodobens Comercio e Locacao de Veiculos Ltda - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('SORRISO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MT')), (Select HANDLE From ESTADOS Where SIGLA ='MT'),'' )
--Insert Into @CodigoToyota Values ('3514390','2S','DISVECO LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('TANGARA DA SERRA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MT')), (Select HANDLE From ESTADOS Where SIGLA ='MT'),'' )
--Insert Into @CodigoToyota Values ('3518862','2S','Rodobens Comercio e Locacao de Veiculos Ltda - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('AGUA BOA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MT')), (Select HANDLE From ESTADOS Where SIGLA ='MT'),'' )
--Insert Into @CodigoToyota Values ('3521358','3S','UMUARAMA MOTORS COMERCIO E SERVICOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('ITUMBIARA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='GO')), (Select HANDLE From ESTADOS Where SIGLA ='GO'),'' )
--Insert Into @CodigoToyota Values ('3521418','3S','UMUARAMA MOTORS COMERCIO E SERVICOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('RIO VERDE')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='GO')), (Select HANDLE From ESTADOS Where SIGLA ='GO'),'' )
--Insert Into @CodigoToyota Values ('3521451','3S','LINCE MOTORS S.A.', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('GOIANIA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='GO')), (Select HANDLE From ESTADOS Where SIGLA ='GO'),'' )
--Insert Into @CodigoToyota Values ('3521452','B&P','LINCE MOTORS S/A - B&P', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('APARECIDA DE GOIANIA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='GO')), (Select HANDLE From ESTADOS Where SIGLA ='GO'),'' )
--Insert Into @CodigoToyota Values ('3522464','2S','KASA MOTORS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('APARECIDA DE GOIANIA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='GO')), (Select HANDLE From ESTADOS Where SIGLA ='GO'),'' )
--Insert Into @CodigoToyota Values ('3524541','3S','KASA MOTORS LTDA - PSAL', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('GOIANIA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='GO')), (Select HANDLE From ESTADOS Where SIGLA ='GO'),'' )
--Insert Into @CodigoToyota Values ('3524543','3S','KASA MOTORS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('ANAPOLIS')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='GO')), (Select HANDLE From ESTADOS Where SIGLA ='GO'),'' )
--Insert Into @CodigoToyota Values ('3530151','3S','DISVECO LTDA - PSAL', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('BRASILIA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='DF')), (Select HANDLE From ESTADOS Where SIGLA ='DF'),'' )
--Insert Into @CodigoToyota Values ('3539736','3S','KASA MOTORS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('BRASILIA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='DF')), (Select HANDLE From ESTADOS Where SIGLA ='DF'),'' )
--Insert Into @CodigoToyota Values ('3555663','3S','DISVECO LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('MARABA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='PA')), (Select HANDLE From ESTADOS Where SIGLA ='PA'),'' )
--Insert Into @CodigoToyota Values ('3556128','3S','DISVECO LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('CACERES')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MT')), (Select HANDLE From ESTADOS Where SIGLA ='MT'),'' )
--Insert Into @CodigoToyota Values ('3556133','3S','DISVECO LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('VARZEA GRANDE')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MT')), (Select HANDLE From ESTADOS Where SIGLA ='MT'),'' )
--Insert Into @CodigoToyota Values ('3556141','3S','DISVECO LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('BRASILIA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='DF')), (Select HANDLE From ESTADOS Where SIGLA ='DF'),'' )
--Insert Into @CodigoToyota Values ('4114736','2S','BRAZAUTO COMERCIO DE VEICULOS E PECAS - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('PATOS')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='PB')), (Select HANDLE From ESTADOS Where SIGLA ='PB'),'' )
--Insert Into @CodigoToyota Values ('4210083','2S','UMUARAMA MOTORS COMERCIO E SERVICOS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('BALSAS')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MA')), (Select HANDLE From ESTADOS Where SIGLA ='MA'),'' )
--Insert Into @CodigoToyota Values ('4210653','3S','TOYOLEX AUTOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('SAO LUIS')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MA')), (Select HANDLE From ESTADOS Where SIGLA ='MA'),'' )
--Insert Into @CodigoToyota Values ('4219592','2S','UMUARAMA MOTORS COMERCIO E SERVICOS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('BACABAL')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MA')), (Select HANDLE From ESTADOS Where SIGLA ='MA'),'' )
--Insert Into @CodigoToyota Values ('4220302','3S','NEWLAND VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('TERESINA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='PI')), (Select HANDLE From ESTADOS Where SIGLA ='PI'),'' )
--Insert Into @CodigoToyota Values ('4221093','2S','NEWLAND VEICULOS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('TERESINA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='PI')), (Select HANDLE From ESTADOS Where SIGLA ='PI'),'' )
--Insert Into @CodigoToyota Values ('4222916','2S','NEWLAND VEICULOS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('PARNAIBA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='PI')), (Select HANDLE From ESTADOS Where SIGLA ='PI'),'' )
--Insert Into @CodigoToyota Values ('4228884','2S','NEWLAND VEICULOS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('PICOS')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='PI')), (Select HANDLE From ESTADOS Where SIGLA ='PI'),'' )
--Insert Into @CodigoToyota Values ('4231414','3S','NEWLAND VEICULOS LTDA - PSAL', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('FORTALEZA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='CE')), (Select HANDLE From ESTADOS Where SIGLA ='CE'),'' )
--Insert Into @CodigoToyota Values ('4231415','3S','NEWLAND VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('FORTALEZA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='CE')), (Select HANDLE From ESTADOS Where SIGLA ='CE'),'' )
--Insert Into @CodigoToyota Values ('4231416','B&P','NEWLAND VEICULOS LTDA B&P', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('FORTALEZA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='CE')), (Select HANDLE From ESTADOS Where SIGLA ='CE'),'' )
--Insert Into @CodigoToyota Values ('4233615','3S','NEWLAND VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('JUAZEIRO DO NORTE')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='CE')), (Select HANDLE From ESTADOS Where SIGLA ='CE'),'' )
--Insert Into @CodigoToyota Values ('4236784','2S Fleet','NEWLAND VEICULOS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Sobral')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='CE')), (Select HANDLE From ESTADOS Where SIGLA ='CE'),'' )
--Insert Into @CodigoToyota Values ('4240700','3S','TOYOLEX AUTOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('NATAL')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RN')), (Select HANDLE From ESTADOS Where SIGLA ='RN'),'' )
--Insert Into @CodigoToyota Values ('4249504','2S','TOYOLEX AUTOS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('MOSSORO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RN')), (Select HANDLE From ESTADOS Where SIGLA ='RN'),'' )
--Insert Into @CodigoToyota Values ('4251234','3S','UMUARAMA MOTORS COMERCIO E SERVICOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('IMPERATRIZ')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MA')), (Select HANDLE From ESTADOS Where SIGLA ='MA'),'' )
--Insert Into @CodigoToyota Values ('4255933','3S','NEWLAND VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('CABEDELO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='PB')), (Select HANDLE From ESTADOS Where SIGLA ='PB'),'' )
--Insert Into @CodigoToyota Values ('4258073','3S','BRAZAUTO COMERCIO DE VEICULOS E PECAS', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('CAMPINA GRANDE')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='PB')), (Select HANDLE From ESTADOS Where SIGLA ='PB'),'' )
--Insert Into @CodigoToyota Values ('4260036','3S','TOYOLEX CARUARU VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('CARUARU')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='PE')), (Select HANDLE From ESTADOS Where SIGLA ='PE'),'' )
--Insert Into @CodigoToyota Values ('4260081','3S','TOYOLEX VEICULOS LTDA - PSAL', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('RECIFE')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='PE')), (Select HANDLE From ESTADOS Where SIGLA ='PE'),'' )
--Insert Into @CodigoToyota Values ('4260880','3S','TOYOLEX VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('RECIFE')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='PE')), (Select HANDLE From ESTADOS Where SIGLA ='PE'),'' )
--Insert Into @CodigoToyota Values ('4268212','3S','TOYOLEX VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('PETROLINA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='PE')), (Select HANDLE From ESTADOS Where SIGLA ='PE'),'' )
--Insert Into @CodigoToyota Values ('4269212','2S','TOYOLEX AUTOS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('GARANHUNS')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='PE')), (Select HANDLE From ESTADOS Where SIGLA ='PE'),'' )
--Insert Into @CodigoToyota Values ('4270070','3S','AUTOFORTE VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('MACEIO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='AL')), (Select HANDLE From ESTADOS Where SIGLA ='AL'),'' )
--Insert Into @CodigoToyota Values ('4279434','2S','AUTOFORTE VEICULOS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('ARAPIRACA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='AL')), (Select HANDLE From ESTADOS Where SIGLA ='AL'),'' )
--Insert Into @CodigoToyota Values ('4280895','3S','TOYOLEX AUTOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('ARACAJU')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SE')), (Select HANDLE From ESTADOS Where SIGLA ='SE'),'' )
--Insert Into @CodigoToyota Values ('4290112','3S','DIAMANTINA VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('VITORIA DA CONQUISTA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='BA')), (Select HANDLE From ESTADOS Where SIGLA ='BA'),'04.542.610/0001-78' )
--Insert Into @CodigoToyota Values ('4290121','3S','TOPAZIO VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('FEIRA DE SANTANA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='BA')), (Select HANDLE From ESTADOS Where SIGLA ='BA'),'13.398.201/0001-30' )
--Insert Into @CodigoToyota Values ('4290474','3S','GUEBOR-COMERCIAL DISTRIB.LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('SALVADOR')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='BA')), (Select HANDLE From ESTADOS Where SIGLA ='BA'),'15.137.417/0001-78' )
--Insert Into @CodigoToyota Values ('4290475','3S','GUEBOR COMERCIAL DISTRIBUIDORA LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('SALVADOR')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='BA')), (Select HANDLE From ESTADOS Where SIGLA ='BA'),'15.137.417/0013-01' )
--Insert Into @CodigoToyota Values ('4290476','3S','GNC COMERCIO DE VEICULOS LTDA - PSAL', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('SALVADOR')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='BA')), (Select HANDLE From ESTADOS Where SIGLA ='BA'),'09.564.676/0001-82' )
--Insert Into @CodigoToyota Values ('4290477','3S','SA OESTE COMERCIO DE VEICULOS LTDA.', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('BARREIRAS')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='BA')), (Select HANDLE From ESTADOS Where SIGLA ='BA'),'00.583.018/0001-63' )
--Insert Into @CodigoToyota Values ('4290806','2S','TOPAZIO VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('JEQUIE')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='BA')), (Select HANDLE From ESTADOS Where SIGLA ='BA'),'13.398.201/0004-83' )
--Insert Into @CodigoToyota Values ('4295368','2S','GNC COMERCIO DE VEICULOS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('LAURO DE FREITAS')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='BA')), (Select HANDLE From ESTADOS Where SIGLA ='BA'),'09.564.676/0004-25' )
--Insert Into @CodigoToyota Values ('4298176','3S','TOPAZIO VEICULOS LTDA - 3S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('ITABUNA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='BA')), (Select HANDLE From ESTADOS Where SIGLA ='BA'),'13.398.201/0002-11' )
--Insert Into @CodigoToyota Values ('4299170','2S','TOPAZIO VEICULOS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('TEIXEIRA DE FREITAS')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='BA')), (Select HANDLE From ESTADOS Where SIGLA ='BA'),'13.398.201/0003-00' )
--Insert Into @CodigoToyota Values ('4299223','2S','SA OESTE COMERCIO DE VEICULOS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('LUIS EDUARDO MAGALHAES')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='BA')), (Select HANDLE From ESTADOS Where SIGLA ='BA'),'00.583.018/0002-44' )
--Insert Into @CodigoToyota Values ('5110662','3S','APEDIA - VEIC. PECAS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('VILHENA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RO')), (Select HANDLE From ESTADOS Where SIGLA ='RO'),'' )
--Insert Into @CodigoToyota Values ('5112456','3S','NISSEY MOTORS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('PORTO VELHO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RO')), (Select HANDLE From ESTADOS Where SIGLA ='RO'),'' )
--Insert Into @CodigoToyota Values ('5114687','2S','NISSEY MOTORS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('ARIQUEMES')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RO')), (Select HANDLE From ESTADOS Where SIGLA ='RO'),'' )
--Insert Into @CodigoToyota Values ('5115855','3S','NISSEY MOTORS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('JI PARANA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RO')), (Select HANDLE From ESTADOS Where SIGLA ='RO'),'' )
--Insert Into @CodigoToyota Values ('5118972','2S','APEDIA - VEIC. PECAS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('CACOAL')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RO')), (Select HANDLE From ESTADOS Where SIGLA ='RO'),'' )
--Insert Into @CodigoToyota Values ('5120001','3S','ACRE COMERCIO E ADMINISTRACAO LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('RIO BRANCO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='AC')), (Select HANDLE From ESTADOS Where SIGLA ='AC'),'' )
--Insert Into @CodigoToyota Values ('5130108','3S','TOYOLEX AUTOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('MANAUS')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='AM')), (Select HANDLE From ESTADOS Where SIGLA ='AM'),'' )
--Insert Into @CodigoToyota Values ('5130700','3S','BACABA VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('MACAPA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='AP')), (Select HANDLE From ESTADOS Where SIGLA ='AP'),'' )
--Insert Into @CodigoToyota Values ('5130701','3S','BACABA VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('AVARE')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('5140001','3S','TOYOLEX VEICULOS LTDA - 3S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('BOA VISTA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RR')), (Select HANDLE From ESTADOS Where SIGLA ='RR'),'' )
--Insert Into @CodigoToyota Values ('5150175','3S','Rodobens Comercio e Locacao de Veiculos Ltda', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('BELEM')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='PA')), (Select HANDLE From ESTADOS Where SIGLA ='PA'),'' )
--Insert Into @CodigoToyota Values ('5150680','2S','Rodobens Comercio e Locacao de Veiculos Ltda - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('SANTAREM')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='PA')), (Select HANDLE From ESTADOS Where SIGLA ='PA'),'' )
--Insert Into @CodigoToyota Values ('5152126','2S Fleet','DISVECO LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Parauapebas')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='PA')), (Select HANDLE From ESTADOS Where SIGLA ='PA'),'' )
--Insert Into @CodigoToyota Values ('5156415','3S','BACABA VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('ANANINDEUA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='PA')), (Select HANDLE From ESTADOS Where SIGLA ='PA'),'' )
--Insert Into @CodigoToyota Values ('5159430','2S','DISVECO LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('PARAGOMINAS')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='PA')), (Select HANDLE From ESTADOS Where SIGLA ='PA'),'' )
--Insert Into @CodigoToyota Values ('5159439','2S','DISVECO LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('REDENCAO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='PA')), (Select HANDLE From ESTADOS Where SIGLA ='PA'),'' )
--Insert Into @CodigoToyota Values ('5159441','2S','BACABA VEICULOS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('CASTANHAL')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='PA')), (Select HANDLE From ESTADOS Where SIGLA ='PA'),'' )
--Insert Into @CodigoToyota Values ('5170010','3S','ARAGUAIA MOTORS COM.DE VEIC.E PECAS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('PALMAS')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='TO')), (Select HANDLE From ESTADOS Where SIGLA ='TO'),'' )
--Insert Into @CodigoToyota Values ('5170015','3S','UMUARAMA MOTORS COMERCIO E SERVICOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('ARAGUAINA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='TO')), (Select HANDLE From ESTADOS Where SIGLA ='TO'),'' )
--Insert Into @CodigoToyota Values ('5178933','2S','ARAGUAIA MOTORS COM.DE VEIC.E PECAS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('GURUPI')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='TO')), (Select HANDLE From ESTADOS Where SIGLA ='TO'),'' )
--Insert Into @CodigoToyota Values ('5220301','TDB','TOYOTA DO BRASIL LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('VOTORANTIM')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('6960301','TDB','TOYOTA DO BRASIL LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('PORTO FELIZ')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('7016700','TDB','TOYOTA DO BRASIL LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('INDAIATUBA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('7647100','2S','TOYOLEX VEICS LTDA - 2S', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('SAO LUIS')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MA')), (Select HANDLE From ESTADOS Where SIGLA ='MA'),'' )
--Insert Into @CodigoToyota Values ('8918801','3S','TEGMAX', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('CARIACICA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='ES')), (Select HANDLE From ESTADOS Where SIGLA ='ES'),'' )
--Insert Into @CodigoToyota Values ('9438401','3S','P & B COMERCIO E SERVICOS AUTOMOTIVOS LTDA (CHROMA)', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('DIADEMA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='SP')), (Select HANDLE From ESTADOS Where SIGLA ='SP'),'' )
--Insert Into @CodigoToyota Values ('9860701','3S','CISA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('VITORIA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='ES')), (Select HANDLE From ESTADOS Where SIGLA ='ES'),'' )
--Insert Into @CodigoToyota Values ('4290477', '', 'SA Oeste Comercio de Veiculos Ltda.', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Barreiras')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='BA')), (Select HANDLE From ESTADOS Where SIGLA ='BA'),'00.583.018/0001-63' )
--Insert Into @CodigoToyota Values ('4290121', '', 'Topazio Veiculos Ltda', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Feira de Santana')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='BA')), (Select HANDLE From ESTADOS Where SIGLA ='BA'),'13.398.201/0001-30' )
--Insert Into @CodigoToyota Values ('4298176', '', 'Topazio Veiculos Ltda', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Itabuna')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='BA')), (Select HANDLE From ESTADOS Where SIGLA ='BA'),'13.398.201/0002-11' )
--Insert Into @CodigoToyota Values ('4290806', '', 'Topazio Veiculos Ltda', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Jequi�')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='BA')), (Select HANDLE From ESTADOS Where SIGLA ='BA'),'13.398.201/0004-83 ' )
--Insert Into @CodigoToyota Values ('4295368', '', 'GNC Comercio de Veiculos Ltda', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Lauro de Freitas')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='BA')), (Select HANDLE From ESTADOS Where SIGLA ='BA'),'09.564.676/0004-25' )
--Insert Into @CodigoToyota Values ('4299223', '', 'SA Oeste Comercio de Veiculos Ltda.', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Luis Eduardo Magalh�es')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='BA')), (Select HANDLE From ESTADOS Where SIGLA ='BA'),'00.583.018/0002-44' )
--Insert Into @CodigoToyota Values ('4290474', '', 'Guebor Comercial Distribuidora Ltda', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Salvador')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='BA')), (Select HANDLE From ESTADOS Where SIGLA ='BA'),'15.137.417/0001-78' )
--Insert Into @CodigoToyota Values ('4290475', '', 'Guebor Comercial Distribuidora Ltda', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Salvador')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='BA')), (Select HANDLE From ESTADOS Where SIGLA ='BA'),'15.137.417/0013-01' )
--Insert Into @CodigoToyota Values ('4290476', '', 'GNC Comercio de Veiculos Ltda', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Salvador')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='BA')), (Select HANDLE From ESTADOS Where SIGLA ='BA'),'09.564.676/0001-82' )
--Insert Into @CodigoToyota Values ('4299170', '', 'Topazio Veiculos Ltda', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Teixeira de Freitas')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='BA')), (Select HANDLE From ESTADOS Where SIGLA ='BA'),'13.398.201/0003-00' )
--Insert Into @CodigoToyota Values ('4290112', '', 'Diamantina Veiculos Ltda', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Vit�ria da Conquista')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='BA')), (Select HANDLE From ESTADOS Where SIGLA ='BA'),'04.542.610/0001-78' )
--Insert Into @CodigoToyota Values ('2326686', '', 'Kuruma Veiculos S.A', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Cachoeiro de Itapemirim')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='ES')), (Select HANDLE From ESTADOS Where SIGLA ='ES'),'00.827.783/0019-00' )
--Insert Into @CodigoToyota Values ('89188', '', 'TEGMAX COM SERV AUTOM LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Cariacica')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='ES')), (Select HANDLE From ESTADOS Where SIGLA ='ES'),'07.065.830/0006-50' )
--Insert Into @CodigoToyota Values ('2329061', '', 'Kuruma Veiculos S.A', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Colatina')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='ES')), (Select HANDLE From ESTADOS Where SIGLA ='ES'),'00.827.783/0021-25' )
--Insert Into @CodigoToyota Values ('2320680', '', 'Kuruma Veiculos S.A', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Linhares')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='ES')), (Select HANDLE From ESTADOS Where SIGLA ='ES'),'00.827.783/0004-24' )
--Insert Into @CodigoToyota Values ('2328160', '', 'Kuruma Veiculos S.A', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Serra')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='ES')), (Select HANDLE From ESTADOS Where SIGLA ='ES'),'00.827.783/0020-44' )
--Insert Into @CodigoToyota Values ('2312353', '', 'Kuruma Veiculos S.A', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Vila Velha')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='ES')), (Select HANDLE From ESTADOS Where SIGLA ='ES'),'00.827.783/0005-05' )
--Insert Into @CodigoToyota Values ('2321437', '', 'Kuruma Veiculos S.A', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Vit�ria')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='ES')), (Select HANDLE From ESTADOS Where SIGLA ='ES'),'00.827.783/0001-81' )
--Insert Into @CodigoToyota Values ('2310620', '', 'Rodobens Comercio e Locacao de Veiculos Ltda', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Belo Horizonte')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'65.993.453/0037-12' )
--Insert Into @CodigoToyota Values ('2310621', '', 'Rodobens Comercio e Locacao de Veiculos Ltda', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Belo Horizonte')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'65.993.453/0039-84' )
--Insert Into @CodigoToyota Values ('2311500', '', 'AB Comercio de Veiculos Ltda', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Belo Horizonte')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'07.124.577/0001-54' )
--Insert Into @CodigoToyota Values ('2318228', '', 'AB Comercio de Veiculos Ltda', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Belo Horizonte')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'07.124.577/0002-35' )
--Insert Into @CodigoToyota Values ('2315644', '', 'GNC Comercio de Veiculos Ltda', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Divin�polis')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'09.564.676/0002-63' )
--Insert Into @CodigoToyota Values ('2312350', '', 'Kuruma Veiculos S.A', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Governador Valadares')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'00.827.783/0008-58' )
--Insert Into @CodigoToyota Values ('2312346', '', 'Kuruma Veiculos S.A', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Ipatinga')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'00.827.783/0009-39' )
--Insert Into @CodigoToyota Values ('2319344', '', 'Kuruma Veiculos S.A', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Jo�o Monlevade')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'00.827.783/0022-06' )
--Insert Into @CodigoToyota Values ('2311369', '', 'Imperial Veiculos Ltda', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Juiz de Fora')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'64.286.420/0001-69' )
--Insert Into @CodigoToyota Values ('2312348', '', 'Kuruma Veiculos S.A', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Manhua�u')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'00.827.783/0010-72' )
--Insert Into @CodigoToyota Values ('2316719', '', 'GNC Comercio de Veiculos Ltda', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Montes Claros')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'09.564.676/0003-44' )
--Insert Into @CodigoToyota Values ('2312352', '', 'Kuruma Veiculos S.A', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Muria�')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'00.827.783/0011-53' )
--Insert Into @CodigoToyota Values ('2319222', '', 'Futura Veiculos Ltda', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Patos de Minas')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'02.563.250/0004-08' )
--Insert Into @CodigoToyota Values ('2312402', '', 'Niponica Comercio de Veiculos Ltda', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Po�os de Caldas')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'07.215.045/0004-75' )
--Insert Into @CodigoToyota Values ('2311320', '', 'Niponica Comercio de Veiculos Ltda', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Pouso Alegre')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'07.215.045/0006-36' )
--Insert Into @CodigoToyota Values ('2318934', '', 'AB Comercio de Veiculos Ltda', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Sete Lagoas')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'07.124.577/0004-05' )
--Insert Into @CodigoToyota Values ('2114755', '', 'Kuruma Veiculos S.A', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Te�filo Otoni')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'00.827.783/0026-30' )
--Insert Into @CodigoToyota Values ('2310288', '', 'Imperial Veiculos Ltda', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Ub�')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'64.286.420/0002-40' )
--Insert Into @CodigoToyota Values ('2310660', '', 'Govesa Motors Veiculos, Pecas e Servicos Ltda', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Uberaba')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'07.066.165/0001-05' )
--Insert Into @CodigoToyota Values ('2310649', '', 'Futura Veiculos Ltda', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Uberl�ndia')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'02.563.250/0001-65' )
--Insert Into @CodigoToyota Values ('2312400', '', 'Niponica Comercio de Veiculos Ltda', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Varginha')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'07.215.045/0001-22' )
--Insert Into @CodigoToyota Values ('2339696', '', 'Toyama Automoveis Ltda.', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Barra Mansa')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RJ')), (Select HANDLE From ESTADOS Where SIGLA ='RJ'),'21.460.858/0001-09' )
--Insert Into @CodigoToyota Values ('2337150', '', 'Toyoserra Veiculos Ltda', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Cabo Frio')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RJ')), (Select HANDLE From ESTADOS Where SIGLA ='RJ'),'32.565.848/0002-35' )
--Insert Into @CodigoToyota Values ('2331281', '', 'SGA Niteroi Veiculos e Pecas S.A.', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Campos dos Goytacazes')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RJ')), (Select HANDLE From ESTADOS Where SIGLA ='RJ'),'36.152.916/0004-57' )
--Insert Into @CodigoToyota Values ('2331278', '', 'SGA Niteroi Veiculos e Pecas S.A.', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Maca�')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RJ')), (Select HANDLE From ESTADOS Where SIGLA ='RJ'),'36,152,916/0001-04' )
--Insert Into @CodigoToyota Values ('2331279', '', 'SGA Niteroi Veiculos e Pecas S.A.', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Niteroi')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RJ')), (Select HANDLE From ESTADOS Where SIGLA ='RJ'),'36.152.916/0003-76' )
--Insert Into @CodigoToyota Values ('2330240', '', 'Toyoserra Veiculos Ltda', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Nova Friburgo')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RJ')), (Select HANDLE From ESTADOS Where SIGLA ='RJ'),'32.565.848/0001-54' )
--Insert Into @CodigoToyota Values ('2312354', '', 'Kuruma Veiculos S.A', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Rio de Janeiro')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RJ')), (Select HANDLE From ESTADOS Where SIGLA ='RJ'),'00.827.783/0015-87' )
--Insert Into @CodigoToyota Values ('2331048', '', 'Moitinho Automoveis Ltda.', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Rio de Janeiro')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RJ')), (Select HANDLE From ESTADOS Where SIGLA ='RJ'),'22.460.858/0001-09' )
--Insert Into @CodigoToyota Values ('2331500', '', 'Rodobens Comercio e Locacao de Veiculos Ltda', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Rio de Janeiro')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RJ')), (Select HANDLE From ESTADOS Where SIGLA ='RJ'),'65.993.453/0029-02' )
--Insert Into @CodigoToyota Values ('2331550', '', 'Rodobens Comercio e Locacao de Veiculos Ltda', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Rio de Janeiro')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RJ')), (Select HANDLE From ESTADOS Where SIGLA ='RJ'),'65.993.453/0030-46' )
--Insert Into @CodigoToyota Values ('2338233', '', 'Inter Japan Veiculos Ltda', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Rio de Janeiro')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RJ')), (Select HANDLE From ESTADOS Where SIGLA ='RJ'),'05.027.327/0006-85' )
--Insert Into @CodigoToyota Values ('2338194', '', 'Inter Japan Veiculos Ltda', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('S�o Jo�o de Meriti')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RJ')), (Select HANDLE From ESTADOS Where SIGLA ='RJ'),'05.027.327/0004-13' )
--Insert Into @CodigoToyota Values ('2326297', '', 'Kuruma Veiculos S.A', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Cariacica')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='ES')), (Select HANDLE From ESTADOS Where SIGLA ='ES'),'00.827.783/0023-97 ' )
--Insert Into @CodigoToyota Values ('TBD', '', 'Futura Veiculos Ltda', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Araguar�')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'' )
--Insert Into @CodigoToyota Values ('TBD', '', 'Topazio Veiculos Ltda', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Jacobina')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='BA')), (Select HANDLE From ESTADOS Where SIGLA ='BA'),'' )
--Insert Into @CodigoToyota Values ('TBD', '', 'Kuruma Veiculos S.A', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Aracruz')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='ES')), (Select HANDLE From ESTADOS Where SIGLA ='ES'),'' )
--Insert Into @CodigoToyota Values ('2328887', '', 'Kuruma Veiculos S.A', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Guarapari')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='ES')), (Select HANDLE From ESTADOS Where SIGLA ='ES'),'00.827.783/0025-59 ' )
--Insert Into @CodigoToyota Values ('2328885', '', 'Kuruma Veiculos S.A', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('S�o Mateus')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='ES')), (Select HANDLE From ESTADOS Where SIGLA ='ES'),'00.827.783/0024-78 ' )
--Insert Into @CodigoToyota Values ('TBD', '', 'GNC Comercio de Veiculos Ltda', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Formiga')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'' )
--Insert Into @CodigoToyota Values ('TBD', '', 'SGA Niteroi Veiculos e Pecas S.A.', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('S�o Gon�alo')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RJ')), (Select HANDLE From ESTADOS Where SIGLA ='RJ'),'' )
--Insert Into @CodigoToyota Values ('TBD', '', 'Para Automoveis Ltda', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Belo Horizonte')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'74.386.137/0026-10' )
--Insert Into @CodigoToyota Values ('TBD', '', 'Kaizen Automoveis Ltda.', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Rio de Janeiro')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RJ')), (Select HANDLE From ESTADOS Where SIGLA ='RJ'),'' )
--Insert Into @CodigoToyota Values ('2312403', '', 'Kaizen Automoveis Ltda.', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Rio de Janeiro')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RJ')), (Select HANDLE From ESTADOS Where SIGLA ='RJ'),'10.678.989/0001-40' )
--Insert Into @CodigoToyota Values ('28200', '', '01 - TEGMA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Cariacica')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='ES')), (Select HANDLE From ESTADOS Where SIGLA ='ES'),'01.233.263/0001-03' )
--Insert Into @CodigoToyota Values ('2328168', '', 'Kuruma Veiculos S.A', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Serra')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='ES')), (Select HANDLE From ESTADOS Where SIGLA ='ES'),'00.827.783/0020-44' )
--Insert Into @CodigoToyota Values ('2310725', '', 'GNC COMERCIO DE VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('Nova Serrana')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'09.564.676/0006-97' )
--Insert Into @CodigoToyota Values ('2334960', '', 'KURUMA VEICULOS SA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('RIO DE JANEIRO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RJ')), (Select HANDLE From ESTADOS Where SIGLA ='RJ'),'00.827.783/0027-10' )
--Insert Into @CodigoToyota Values ('2311320', '', 'NIPONICA COMERCIO DE VEICULOS LIMITADA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('POUSO ALEGRE')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'07.215.045/0006-37' )
--Insert Into @CodigoToyota Values ('2331048', '', 'MOITINHO AUTOMOVEIS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('RIO DE JANEIRO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RJ')), (Select HANDLE From ESTADOS Where SIGLA ='RJ'),'22.134.988/0001-14' )
--Insert Into @CodigoToyota Values ('2331278', '', 'SGA Niteroi Veiculos Pecas S.A', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('MACAE')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RJ')), (Select HANDLE From ESTADOS Where SIGLA ='RJ'),'36.152.916/0001-04' )
--Insert Into @CodigoToyota Values ('2142377', '', 'MOITINHO AUTOMOVEIS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('RIO DE JANEIRO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RJ')), (Select HANDLE From ESTADOS Where SIGLA ='RJ'),'22.134.988/0004-67' )
--Insert Into @CodigoToyota Values ('2142379', '', 'MOITINHO AUTOMOVEIS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('RIO DE JANEIRO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RJ')), (Select HANDLE From ESTADOS Where SIGLA ='RJ'),'22.134.988/0003-86' )
--Insert Into @CodigoToyota Values ('2318445', '', 'KURUMA VEICULOS S.A.', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('UBERLANDIA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'),'00.827.783/0028-00' )
--Insert Into @CodigoToyota Values ('2332254', '', 'SGA NITEROI VEICULOS E PECAS S A', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('ITAPERUNA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='RJ')), (Select HANDLE From ESTADOS Where SIGLA ='RJ'),'36.152.916/0006-19' )
--Insert Into @CodigoToyota Values ('4293270', '', 'DIAMANTINA VEICULOS LTDA', (Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('GUANAMBI')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA ='BA')), (Select HANDLE From ESTADOS Where SIGLA ='BA'),'04.542.610/0002-59' )
--Insert Into @CodigoToyota Values ('2315298', '', 'AB COMERCIO DE VEICULOS LTDA				',(Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('CONTAGEM')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA = 'MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'), '07.124.577/0005-88')
--Insert Into @CodigoToyota Values ('2142377', '', 'MOITINHO AUTOMOVEIS LTDA					',(Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('RIO DE JANEIRO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA = 'RJ')), (Select HANDLE From ESTADOS Where SIGLA ='RJ'), '22.134.988/0004-67')
--Insert Into @CodigoToyota Values ('4293270', '', 'DIAMANTINA VEICULOS LTDA					',(Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('GUANAMBI')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA = 'BA')), (Select HANDLE From ESTADOS Where SIGLA ='BA'), '04.542.610/0002-59')
--Insert Into @CodigoToyota Values ('4172024', '', 'GNC COMERCIO DE VEICULOS LTDA			',(Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('SALVADOR')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA = 'BA')), (Select HANDLE From ESTADOS Where SIGLA ='BA'), '09.564.676/0009-30')
--Insert Into @CodigoToyota Values ('2310725', '', 'GNC COMERCIO DE VEICULOS LTDA			',(Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('NOVA SERRANA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA = 'MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'), '09.564.676/0006-97')
--Insert Into @CodigoToyota Values ('2142379', '', 'MOITINHO AUTOMOVEIS LTDA					',(Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('RIO DE JANEIRO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA = 'RJ')), (Select HANDLE From ESTADOS Where SIGLA ='RJ'), '22.134.988/0003-86')
--Insert Into @CodigoToyota Values ('4291743', '', 'GUEBOR COMERCIAL DISTRIBUIDORA LTDA		',(Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('SALVADOR')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA = 'BA')), (Select HANDLE From ESTADOS Where SIGLA ='BA'), '15.137.417/0018-16')
--Insert Into @CodigoToyota Values ('2181733', '', 'INTER JAPAN VEICULOS LTDA				',(Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('RIO DE JANEIRO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA = 'RJ')), (Select HANDLE From ESTADOS Where SIGLA ='RJ'), '05.027.327/0009-28')
--Insert Into @CodigoToyota Values ('2313163', '', 'KURUMA VEICULOS S A						',(Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('UBERABA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA = 'MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'), '00.827.783/0029-82')
--Insert Into @CodigoToyota Values ('2330797', '', 'MOITINHO AUTOMOVEIS LTDA					',(Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('RIO DE JANEIRO')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA = 'RJ')), (Select HANDLE From ESTADOS Where SIGLA ='RJ'), '22.134.988/0002-03')
--Insert Into @CodigoToyota Values ('2317859', '', 'NIPONICA COMERCIO DE VEICULOS LIMITADA	',(Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('PASSOS')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA = 'MG')), (Select HANDLE From ESTADOS Where SIGLA ='MG'), '07.215.045/0007-18')
--Insert Into @CodigoToyota Values ('2337309', '', 'SGA NITEROI VEICULOS E PECAS S.A.		',(Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('ITABORAI')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA = 'RJ')), (Select HANDLE From ESTADOS Where SIGLA ='RJ'), '36.152.916/0007-08')
--Insert Into @CodigoToyota Values ('4294581', '', 'TOPAZIO VEICULOS LTDA					',(Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('IRECE')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA = 'BA')), (Select HANDLE From ESTADOS Where SIGLA ='BA'), '13.398.201/0005-64')
--Insert Into @CodigoToyota Values ('2336480', '', 'TOYOSERRA VEICULOS LTDA.					',(Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('PETROPOLIS')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA = 'RJ')), (Select HANDLE From ESTADOS Where SIGLA ='RJ'), '32.565.848/0003-16')
--Insert Into @CodigoToyota Values ('35397', '', 'TOYOTA DO BRASIL LTDA					',(Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('CARIACICA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA = 'ES')), (Select HANDLE From ESTADOS Where SIGLA ='ES'), '59.104.760/0007-87')
--Insert Into @CodigoToyota Values ('4294013', '', 'GNC COMERCIO DE VEICULOS LTDA			',(Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('SALVADOR')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA = 'BA')), (Select HANDLE From ESTADOS Where SIGLA ='BA'), '09.564.676/0008-59')
--Insert Into @CodigoToyota Values ('12541', '', 'TEGMA LOGISTICA INTEGRADA S.A.',(Select HANDLE FROM MUNICIPIOS Where NOME =Rtrim(Ltrim('CARIACICA')) And ESTADO = (Select HANDLE From ESTADOS Where SIGLA = 'ES')), (Select HANDLE From ESTADOS Where SIGLA ='ES'), '03.649.560/0001-60')

--Devolucao
Select 
	DISTINCT 
	'Devolucao' as [Operacoes]
	,GLFT_FATURAS.NUMERO AS [Fatura]
	,GLGL_DOCUMENTOS.NUMERO AS [Numero CTe]
	,Convert(VarChar(10), GLGL_DOCUMENTOS.DATAEMISSAO, 103) AS [Data Emissao CTe]
	,STUFF((Select ',' + cast(X.NUMERO as varchar(9))
				From GLGL_DOCUMENTOCLIENTES X
			   Inner Join GLGL_DOCUMENTOASSOCIADOS K
				  On K.DOCUMENTOCLIENTE		= X.HANDLE
			   Where K.DOCUMENTOLOGISTICA	= GLGL_DOCUMENTOS.HANDLE
				 For XML PATH ('')),1,1,'') AS [Numeros NFs]
	,Convert(VarChar(10), (Select Min(GLGL_DOCUMENTOCLIENTES.DATAEMISSAO)
							   From GLGL_DOCUMENTOCLIENTES
							  Inner Join GLGL_DOCUMENTOASSOCIADOS
								 On GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOCLIENTE	= GLGL_DOCUMENTOCLIENTES.HANDLE
							  Where GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOLOGISTICA	= GLGL_DOCUMENTOS.HANDLE), 103) AS [Data Emissao NF]
	
	,CodigoToyota.CODIGOCONCESSIOARIA AS [Cod. Remetente]
	,GN_PESSOASREM.NOME AS [Remetente]
	,GN_PESSOASREM.CGCCPF AS [CNPJ (Remetente)]
	,MUNICIPIOSREM.NOME	AS [Cidade (Remetente)]
	,ESTADOSREM.SIGLA AS [UF (Remetente)]
	,GN_PESSOASDES.NOME	AS [Destinatario]
	,GN_PESSOASDES.CGCCPF AS [CNPJ (Destinatario)]
	,MUNICIPIOSDES.NOME AS [Cidade (Destinatario)]
	,ESTADOSDES.SIGLA AS [UF (Destinatario)]
	,GLGL_DOCUMENTOS.DOCCLIVOLUME AS [Quant. de Volumes]
	,GLGL_DOCUMENTOS.DOCCLIPESOTOTAL AS [Peso Real em Kgs]
	,(Select Sum(IsNull(GLGL_DOCCLICUBAGENS.M3,0))
		  From GLGL_DOCUMENTOCLIENTES X
	     Inner Join GLGL_DOCUMENTOASSOCIADOS
		    On GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOLOGISTICA	= GLGL_DOCUMENTOS.HANDLE
		 Inner Join GLGL_DOCCLICUBAGENS 
			On GLGL_DOCCLICUBAGENS.DOCUMENTOCLIENTE			= X.HANDLE
		 Where X.HANDLE	= GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOCLIENTE) AS [Tamanho real em m3]
	,GLGL_DOCUMENTOS.DOCCLIPESOCONSIDERADO AS [Peso Cobrado]
	,GLGL_DOCUMENTOS.DOCCLIVALORTOTAL AS [Valor NF]
	,GLGL_DOCUMENTOS.VALORCONTABIL AS [Valor do Frete]
	,GLGL_DOCUMENTOS.CHAVECTE AS [Chave de acesso CTe]
	,CAST(GLGL_DOCUMENTOS.OBSERVACOESIMPRESSAS AS NVARCHAR(1000)) AS [Observacoes]
	   
  From GLGL_DOCUMENTOS
 --Inner Join GLGL_DOCUMENTOASSOCIADOS
	--On GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOLOGISTICA	= GLGL_DOCUMENTOS.HANDLE
 --Inner Join GLGL_DOCUMENTOCLIENTES
	--On GLGL_DOCUMENTOCLIENTES.HANDLE				= GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOCLIENTE
 -- Left Join GLGL_DOCCLICUBAGENS 
	--On GLGL_DOCCLICUBAGENS.DOCUMENTOCLIENTE			= GLGL_DOCUMENTOCLIENTES.HANDLE
 Inner Join GN_PESSOAS GN_PESSOASREM
	On GN_PESSOASREM.HANDLE							= GLGL_DOCUMENTOS.REMETENTE
 Inner Join GLGL_PESSOAENDERECOS GLGL_PESSOAENDERECOSREM
	On GLGL_PESSOAENDERECOSREM.HANDLE				= GLGL_DOCUMENTOS.REMETENTEENDERECO
 Inner Join MUNICIPIOS MUNICIPIOSREM
	On MUNICIPIOSREM.HANDLE							= GLGL_PESSOAENDERECOSREM.MUNICIPIO
 Inner Join ESTADOS ESTADOSREM
	On ESTADOSREM.HANDLE							= MUNICIPIOSREM.ESTADO
 Inner Join GN_PESSOAS GN_PESSOASDES
	On GN_PESSOASDES.HANDLE							= GLGL_DOCUMENTOS.DESTINATARIO
 Inner Join GLGL_PESSOAENDERECOS GLGL_PESSOAENDERECOSDES
	On GLGL_PESSOAENDERECOSDES.HANDLE				= GLGL_DOCUMENTOS.DESTINOENDERECO
 Inner Join MUNICIPIOS MUNICIPIOSDES
	On MUNICIPIOSDES.HANDLE							= GLGL_PESSOAENDERECOSDES.MUNICIPIO
 Inner Join ESTADOS ESTADOSDES
	On ESTADOSDES.HANDLE							= MUNICIPIOSDES.ESTADO
 -- Left Join GLCM_CONTRATOS
	--On GLCM_CONTRATOS.HANDLE						= GLGL_DOCUMENTOCLIENTES.CONTRATO
 -- Left Join GLCM_REGOPERACIONAIS
	--On GLCM_REGOPERACIONAIS.CONTRATO				= GLCM_CONTRATOS.HANDLE
  Left Join @CodigoToyota CodigoToyota
	On CodigoToyota.CGCCPF							= GN_PESSOASREM.CGCCPF
  Left Join GLOP_COLETAPEDIDOS
	On GLOP_COLETAPEDIDOS.HANDLE					= (Select Max(X.PEDIDOCOLETA)
													     From GLGL_DOCUMENTOCLIENTES X
													    Inner Join GLGL_DOCUMENTOASSOCIADOS Y
														   On Y.DOCUMENTOCLIENTE	= X.HANDLE
													    Where Y.DOCUMENTOLOGISTICA	= GLGL_DOCUMENTOS.HANDLE)
  Left Join GLFT_FATURADOCUMENTOS
	On GLFT_FATURADOCUMENTOS.DOCUMENTO				= GLGL_DOCUMENTOS.HANDLE
  Left Join GLFT_FATURAS
	On GLFT_FATURAS.HANDLE							= GLFT_FATURADOCUMENTOS.FATURA
   And Not GLFT_FATURAS.STATUS							In (335, 1150, 327, 1174)
 Where Cast(GLGL_DOCUMENTOS.DATAEMISSAO As date)	Between @DATAI
														And @DATAF
   And Not GLGL_DOCUMENTOS.STATUS					In (236, 237, 417)
   And (GLGL_DOCUMENTOS.TIPODOCUMENTO				In (1, 2)
	Or (GLGL_DOCUMENTOS.TIPODOCUMENTO				= 6
   And  GLGL_DOCUMENTOS.TIPORPS						<> 324))
   And (GLGL_DOCUMENTOS.TIPODOCUMENTO				= 2
   And GLGL_DOCUMENTOS.TIPODOCUMENTOFRETE			In (153)
    Or GLGL_DOCUMENTOS.TIPODOCUMENTO				= 6)
   --And (Not GLGL_DOCUMENTOS.STATUS					In (235)
   --And GLGL_DOCUMENTOS.RECUSADO						='N')
   And (((GLGL_DOCUMENTOS.DESTINATARIO				= (Select HANDLE From GN_PESSOAS Where GN_PESSOAS.CGCCPF ='59.104.760/0001-91')
	Or    GLGL_DOCUMENTOS.TOMADORSERVICOPESSOA		= (Select HANDLE From GN_PESSOAS Where GN_PESSOAS.CGCCPF ='59.104.760/0001-91'))
   And Not GLGL_DOCUMENTOS.REMETENTE				= (Select HANDLE From GN_PESSOAS Where GN_PESSOAS.CGCCPF ='59.104.760/0001-91'))
    Or (GLGL_DOCUMENTOS.DESTINATARIO				= (Select HANDLE From GN_PESSOAS Where GN_PESSOAS.CGCCPF ='59.104.760/0009-49'))
    Or (GLGL_DOCUMENTOS.DESTINATARIO				= (Select HANDLE From GN_PESSOAS Where GN_PESSOAS.CGCCPF ='59.104.760/0003-53'))
	Or (GLGL_DOCUMENTOS.DESTINATARIO				= (Select HANDLE From GN_PESSOAS Where GN_PESSOAS.CGCCPF ='59.104.760/0012-44'))
	Or ((GLGL_DOCUMENTOS.DESTINATARIO				= (Select HANDLE From GN_PESSOAS Where GN_PESSOAS.CGCCPF ='59.106.245/0001-40'))
   And  (GLGL_DOCUMENTOS.TOMADORSERVICOPESSOA		= (Select HANDLE From GN_PESSOAS Where GN_PESSOAS.CGCCPF ='59.104.760/0003-53'))))

)