SELECT 
	[IntFilial],
	[Dia],
	SUM(QtdeTotal) AS QtdeTotal,
	SUM([QtdSync]) AS [QtdSync]

FROM (

Select FILIAIS.NOME											[IntFilial],
			   Day(OCC.INCLUIDOEM)				[Dia],
			   Count(DISTINCT DOC.HANDLE)		QtdeTotal,
			   0 AS               [QtdSync]
			   --ISNULL(SUM(QTD),0)               [QtdeTotal]		

		  From  GLGL_DOCUMENTOS DOC
				INNER JOIN GLOP_OCORRENCIAS OCC ON OCC.DOCUMENTO = DOC.HANDLE
				INNER JOIN GLOP_MOTIVOOCORRENCIAS MOTOCC ON MOTOCC.HANDLE = OCC.OCORRENCIA
				INNER JOIN FILIAIS ON FILIAIS.HANDLE = OCC.FILIAL
				
				LEFT JOIN GLOP_VIAGEMDOCUMENTOS VIAGEMDOC ON VIAGEMDOC.DOCUMENTOLOGISTICA = DOC.HANDLE And VIAGEMDOC.SITUACAO					= 209
				LEFT JOIN GLOP_VIAGENS VIAGEM ON VIAGEM.HANDLE = VIAGEMDOC.VIAGEM AND VIAGEM.TIPOVIAGEM							in (170, 173)
				LEFT JOIN GLOP_VIAGEMPARADAS PARADA ON PARADA.HANDLE = VIAGEMDOC.PARADA AND PARADA.VIAGEM = VIAGEM.HANDLE AND  Cast(PARADA.INICIOVIAGEM As Date)	<= Cast(DateAdd(DAY, -1, GetDate()) As Date)
				LEFT JOIN GLOP_RADIOMENSAGENS RADIOMENSAGEM ON RADIOMENSAGEM.DOCUMENTOVIAGEM = VIAGEMDOC.HANDLE AND RADIOMENSAGEM.OCORRENCIAASSOCIADA = 1


	  --  Left Join GLOP_RADIOMENSAGENS
			--On GLOP_RADIOMENSAGENS.DOCUMENTOLOGISTICA			= GLOP_VIAGEMDOCUMENTOS.DOCUMENTOLOGISTICA
		 --  And GLOP_RADIOMENSAGENS.DOCUMENTOVIAGEM				= GLOP_VIAGEMDOCUMENTOS.HANDLE
		 --  And GLOP_RADIOMENSAGENS.DATAINCLUSAO					= (Select Max(X.DATAINCLUSAO)
			--														 From GLOP_RADIOMENSAGENS X
			--														Where X.DOCUMENTOLOGISTICA		= GLOP_VIAGEMDOCUMENTOS.DOCUMENTOLOGISTICA
			--														   And X.DOCUMENTOVIAGEM			= GLOP_VIAGEMDOCUMENTOS.HANDLE)
		 --  And GLOP_RADIOMENSAGENS.OCORRENCIAASSOCIADA			= 1


		 Where Year(OCC.INCLUIDOEM)		= Year(getdate())
		   And Month(OCC.INCLUIDOEM)		= Month(getdate())
		   And (DOC.TIPODOCUMENTO					In (1, 2) 
			Or (DOC.TIPODOCUMENTO					= 6 
		   And  DOC.TIPORPS							<> 323))
		   AND (MOTOCC.HANDLE = 1 OR MOTOCC.OCORRENCIAPADRAO = 1)
		   AND OCC.ESTORNADO =  'N'
		   --AND FILIAIS.NOME ='Agência Barra Mansa - QBN'
		 Group By FILIAIS.NOME,
				  Day(OCC.INCLUIDOEM)
				

UNION ALL

Select FILIAIS.NOME											[IntFilial],
			   Day(GLOP_RADIOMENSAGENS.DATAHORARETORNO)				[Dia],
			   0 AS QtdeTotal,
			   Count(GLOP_RADIOMENSAGENS.OCORRENCIAASSOCIADA)		[QtdeSync]
			   --ISNULL(SUM(QTD),0)               [QtdeTotal]		
		  From GLOP_VIAGENS
		 Inner Join FILIAIS
			On FILIAIS.HANDLE									= GLOP_VIAGENS.FILIALORIGEM
		 Inner Join GLOP_VIAGEMDOCUMENTOS
			On GLOP_VIAGEMDOCUMENTOS.VIAGEM						= GLOP_VIAGENS.HANDLE
		 Inner Join GLOP_VIAGEMPARADAS
			On GLOP_VIAGEMPARADAS.VIAGEM						= GLOP_VIAGENS.HANDLE
		 Inner Join GLGL_DOCUMENTOS
			On GLGL_DOCUMENTOS.HANDLE							= GLOP_VIAGEMDOCUMENTOS.DOCUMENTOLOGISTICA
		  Left Join GLOP_RADIOMENSAGENS
			On GLOP_RADIOMENSAGENS.DOCUMENTOLOGISTICA			= GLOP_VIAGEMDOCUMENTOS.DOCUMENTOLOGISTICA
		   And GLOP_RADIOMENSAGENS.DOCUMENTOVIAGEM				= GLOP_VIAGEMDOCUMENTOS.HANDLE
		   And GLOP_RADIOMENSAGENS.DATAINCLUSAO					= (Select Max(X.DATAINCLUSAO)
																	 From GLOP_RADIOMENSAGENS X
																	Where X.DOCUMENTOLOGISTICA		= GLOP_VIAGEMDOCUMENTOS.DOCUMENTOLOGISTICA
																	  And X.DOCUMENTOVIAGEM			= GLOP_VIAGEMDOCUMENTOS.HANDLE)
		

		 Where GLOP_VIAGENS.TIPOVIAGEM							in (170, 173)
		   And Year(GLOP_RADIOMENSAGENS.DATAHORARETORNO)		= Year(getdate())
		   And Month(GLOP_RADIOMENSAGENS.DATAHORARETORNO)		= Month(getdate())
		   And GLOP_VIAGEMDOCUMENTOS.SITUACAO					= 209
		   And GLOP_RADIOMENSAGENS.OCORRENCIAASSOCIADA			= 1
		   And (GLGL_DOCUMENTOS.TIPODOCUMENTO					In (1, 2) 
			Or (GLGL_DOCUMENTOS.TIPODOCUMENTO					= 6 
		   And  GLGL_DOCUMENTOS.TIPORPS							<> 323))
		   And Cast(GLOP_VIAGEMPARADAS.INICIOVIAGEM As Date)	<= Cast(DateAdd(DAY, -1, GetDate()) As Date)
		   --AND FILIAIS.NOME ='Agência Barra Mansa - QBN'
		 Group By FILIAIS.NOME,
				  Day(GLOP_RADIOMENSAGENS.DATAHORARETORNO)
) AS T			

GROUP BY [IntFilial],
		 [Dia]