declare @DTAINI DATE = '2020-01-01'
declare @DTAFIM DATE = '2020-03-01'




Select PSUBTIPO,
	   Sum(VOLUME) [VOL],
	   DESTINO
  From (Select Case GLGV_ETIQUETAS.PALETIZADA
					When 'N' Then IIF(Not IsNull(GLGL_DOCUMENTOS.DOCCLIVOLUME, GLGL_DOCUMENTOCLIENTES.VOLUME) Is Null, IsNull(GLGL_DOCUMENTOS.DOCCLIVOLUME, GLGL_DOCUMENTOCLIENTES.VOLUME),  Count(Distinct GLGV_PROCESSOITENS.HANDLE))
					When 'S' Then IsNull(GLGL_DOCUMENTOS.DOCCLIVOLUME, GLGL_DOCUMENTOCLIENTES.VOLUME)
					Else Count(Distinct GLGV_PROCESSOITENS.HANDLE)
			   End										[VOLUME],
			   GLGV_PROCESSOS.HANDLE					[PROCESSO],
			   GLGL_DOCUMENTOCLIENTES.HANDLE			[HDLCLIENTE],
			   GLGL_DOCUMENTOS.HANDLE					[HDLMINUTA],
			   Case GLGV_PROCESSOS.SUBTIPO
					When 1 Then 'Transferência'
					When 2 Then 'Distribuição'
					When 3 Then 'Coleta'
					When 4 Then 'Unitizador'
			   End										[PSUBTIPO],  
			   IIF(GLGL_FILIAIS.SIGLA = IsNull(GVEUNIT.SIGLADESTINO, GLGV_ETIQUETAS.SIGLADESTINO), 'Distribuição', 'Transferência')	[DESTINO]
		  From GLOP_VIAGENS
		 Inner Join GLGV_PLANOCARGADESCARGAS			On GLGV_PLANOCARGADESCARGAS.VIAGEM				= GLOP_VIAGENS.HANDLE
		 Inner Join MA_RECURSOS							On MA_RECURSOS.HANDLE							= GLGV_PLANOCARGADESCARGAS.VEICULO 

		 Inner Join GLGL_FILIAIS						On GLGL_FILIAIS.FILIAL							= GLGV_PLANOCARGADESCARGAS.FILIAL 

		 Inner Join GLOP_VIAGEMPARADAS					On GLOP_VIAGEMPARADAS.HANDLE					= GLGV_PLANOCARGADESCARGAS.PARADA

		 Inner Join GLGV_PROCESSOS						On GLGV_PROCESSOS.PLANOCARGADESCARGA			= GLGV_PLANOCARGADESCARGAS.HANDLE
		 Inner Join GLGV_PROCESSOITENS					On GLGV_PROCESSOITENS.PROCESSO					= GLGV_PROCESSOS.HANDLE
													   And GLGV_PROCESSOITENS.RETIRADO					= 'N'
		 Inner Join GLGV_ETIQUETAVOLUMES				On GLGV_ETIQUETAVOLUMES.HANDLE					= GLGV_PROCESSOITENS.VOLUME
		 Inner Join GLGV_ETIQUETAS						On GLGV_ETIQUETAS.HANDLE						= GLGV_ETIQUETAVOLUMES.ETIQUETA
			
		  Left Join GLGV_PROCESSOS			GVPUNIT		On GVPUNIT.UNITIZADOR							= GLGV_ETIQUETAS.UNITIZADOR
													   And GVPUNIT.STATUS								<> 1336
		  Left Join GLGV_PROCESSOITENS		GVPIUNIT	On GVPIUNIT.PROCESSO							= GVPUNIT.HANDLE
													   And GVPIUNIT.RETIRADO							= 'N'
		  Left Join GLGV_ETIQUETAVOLUMES	GVEVUNIT	On GVEVUNIT.HANDLE								= GVPIUNIT.VOLUME
		  Left Join GLGV_ETIQUETAS			GVEUNIT		On GVEUNIT.HANDLE								= GVEVUNIT.ETIQUETA
		
		  Left Join GLGL_DOCUMENTOCLIENTES				On GLGL_DOCUMENTOCLIENTES.HANDLE				= IsNull(GVEUNIT.DOCUMENTOCLIENTE, GLGV_ETIQUETAS.DOCUMENTOCLIENTE)
		  Left Join GLGL_DOCUMENTOS						On GLGL_DOCUMENTOS.HANDLE						= IsNull(GVEUNIT.MINUTA , GLGV_ETIQUETAS.MINUTA)
		  
		  Left Join GLGV_PROCESSOPARTICIPANTES			
		 Inner Join GN_PESSOAS							On GN_PESSOAS.HANDLE							= GLGV_PROCESSOPARTICIPANTES.PESSOA
														On GLGV_PROCESSOPARTICIPANTES.PROCESSO			= GLGV_PROCESSOS.HANDLE
													   And GLGV_PROCESSOPARTICIPANTES.TIPOPARTICIPANTE	= 511
		
		 Where  GLGV_PLANOCARGADESCARGAS.TIPO															= 'D'
		   And GLGV_PROCESSOS.STATUS																	<> 1336
		   And GLGV_PROCESSOS.TIPO																		In (2)
		   And GLGV_PROCESSOS.SUBTIPO																	In (1)
   		   And GLGV_PLANOCARGADESCARGAS.FILIAL															= 2
		   And Cast(GLGV_PROCESSOS.DATAABERTURA	As Date) >= @DTAINI
		   And Cast(GLGV_PROCESSOS.DATAABERTURA	As Date) < @DTAFIM
		 Group By GLGL_DOCUMENTOCLIENTES.HANDLE,
				  GLGL_DOCUMENTOS.HANDLE,
				  GLGV_PROCESSOS.HANDLE,
				  GLGV_ETIQUETAS.PALETIZADA,
				  GLGL_DOCUMENTOS.DOCCLIVOLUME,
				  GLGL_DOCUMENTOCLIENTES.VOLUME,
				  GLGV_PROCESSOS.SUBTIPO,
				  GLGL_FILIAIS.SIGLA,
				  GLGV_ETIQUETAS.SIGLADESTINO,
				  GVEUNIT.SIGLADESTINO) TB

 Group By PSUBTIPO,
		  DESTINO
 Union All
Select 'Coleta'							[PSUBTIPO],
	   GLGL_DOCUMENTOCLIENTES.VOLUME	[VOL],
	   IIF(GLGL_DOCUMENTOS.FILIALENTREGA <> GLGL_DOCUMENTOS.FILIAL, 'Transferência', 'Distribuição') [DESTINO]
  From GLOP_COLETAPEDIDOS
 Inner Join GLGL_DOCUMENTOCLIENTES		On GLGL_DOCUMENTOCLIENTES.PEDIDOCOLETA			= GLOP_COLETAPEDIDOS.HANDLE
 Inner Join GLGL_DOCUMENTOASSOCIADOS	On GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOCLIENTE	= GLGL_DOCUMENTOCLIENTES.HANDLE
 Inner Join GLGL_DOCUMENTOS				On GLGL_DOCUMENTOS.HANDLE						= GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOLOGISTICA
 Where ((GLGL_DOCUMENTOS.TIPODOCUMENTO													In (2)
   And   GLGL_DOCUMENTOS.TIPODOCUMENTOFRETE												= 153)
	Or (GLGL_DOCUMENTOS.TIPODOCUMENTO													In (6)
   And  GLGL_DOCUMENTOS.TIPORPS															= 322))
   And GLOP_COLETAPEDIDOS.COLETAFILIAL													= 2
   And GLOP_COLETAPEDIDOS.DATACANCELAMENTO												Is Null
   And GLGL_DOCUMENTOCLIENTES.DATACANCELAMENTO											Is Null
   And Cast(GLOP_COLETAPEDIDOS.DATACONCLUSAO As Date)									>= @DTAINI
																							And Cast(GLOP_COLETAPEDIDOS.DATACONCLUSAO As Date) < @DTAFIM