--•	Número Viagem
--•	Início Efetivo
--•	Chegada Efetiva
--•	Tipo
--•	SubTipo
--•	Destino
--•	Status
--•	Qt. Documentos
--•	Qt. Realizadas
--•	% Efetividade


SELECT
	NUMEROVIAGEM
	,INICIOEFETIVO
	,CHEGADAEFETIVA
	,TIPOVIAGEM
	,SUBTIPOVIAGEM
	,FILIALDESTINO
	,[STATUS] 
	,SUM([Qt. Documentos]) AS [Qt. Documentos]
	,SUM([Qt. Realizadas]) AS [Qt. Realizadas]	
	,CONCAT(CONVERT(NUMERIC(10,2),ISNULL(ROUND(((CAST(NULLIF(SUM([Qt. Realizadas]),0) AS DECIMAL)*100)/(CAST(NULLIF(SUM([Qt. Documentos]),0) AS DECIMAL))),2),0)), ' ', '%') AS [% Efetividade]

FROM(
SELECT
	V.NUMEROVIAGEM
	,V.INICIOEFETIVO
	,V.CHEGADAEFETIVA
	,EI.NOME AS TIPOVIAGEM
	,SUBTIPO.NOME AS SUBTIPOVIAGEM
	,F.NOME AS FILIALDESTINO
	,EIS.NOME AS [STATUS]
	,COUNT(D.NUMERO) AS [Qt. Documentos]
	,CASE 
		WHEN DV.SITUACAO <> 216 THEN COUNT(D.NUMERO)
	ELSE 0
	END AS [Qt. Realizadas]	
	,EIS.NOME AS STATUSVIAGEM

FROM GLOP_VIAGENS V
LEFT JOIN GLGL_ENUMERACAOITEMS EI ON V.TIPOVIAGEM = EI.HANDLE
INNER JOIN GLGL_ENUMERACAOITEMS EIS ON V.STATUS = EIS.HANDLE
INNER JOIN GLGL_SUBTIPOVIAGENS SUBTIPO ON V.SUBTIPOVIAGEM = SUBTIPO.HANDLE
LEFT JOIN GLGL_SUBTIPOVIAGENS SBV ON SBV.HANDLE = V.SUBTIPOVIAGEM
LEFT JOIN GLOP_VIAGEMDOCUMENTOS DV ON DV.VIAGEM = V.HANDLE
LEFT JOIN GLGL_DOCUMENTOS D ON DV.DOCUMENTOLOGISTICA = D.HANDLE
INNER JOIN GLGL_ENUMERACAOITEMS EIDV ON DV.SITUACAO = EIDV.HANDLE
INNER JOIN FILIAIS F ON V.FILIALDESTINO = F.HANDLE

WHERE 1=1
AND EI.CODIGO IN (169, 170, 173)
AND EIS.NOME LIKE '%Aguardando Finalização%'
AND V.CHEGADAEFETIVA < DATEADD(DD,-3, GETDATE())
--AND V.CHEGADAEFETIVA < GETDATE()
--AND DV.SITUACAO = 216 STATUS DO QUE NAO FOI ENTREGUE
--AND V.NUMEROVIAGEM IN 
--(
--'2019/285868-29'
--,'2019/322655-7'
--,'2019/346137-3'
--,'2019/355202-29'

--)

--AND K_DATACHEGADADIGITADA

GROUP BY 
		V.NUMEROVIAGEM
		,V.INICIOEFETIVO
		,V.CHEGADAEFETIVA
		,EI.NOME
		,SUBTIPO.NOME
		,F.NOME
		,EIS.NOME
		,DV.SITUACAO
		,EIS.NOME
) AS T1

GROUP BY NUMEROVIAGEM
	,INICIOEFETIVO
	,CHEGADAEFETIVA
	,TIPOVIAGEM
	,SUBTIPOVIAGEM
	,FILIALDESTINO
	,[STATUS] 
	,STATUSVIAGEM