--1º	Nº CT-E
--2º	Data Emissão CT-E
--3º	Cliente Remetente
--4º	Cidade destinatário
--5º	Região
--6º	CEP
--7º	UF
--8º	NF
--9º	Valor NF
--10º	Peso real
--11º	Peso cubado
--12º	Peso Considerado 
--13º	Frete peso
--14º	GRIS
--15º	Pedágio
--16º	ADV. (Frete Valor)
--17º	Aliquita de ICMS
--18º	ICMS
--19º	Frete Total
--20º	Vol.
--21º	Pedido
--22º	Chave CTe
--23º	Tipo Entrega

--DECLARE @BeginDate DATETIME = '2019-12-01'
--DECLARE @EndDate DATETIME = '2019-12-01'
--DECLARE @Tomador varchar(100) = ''
--DECLARE @FATURA VARCHAR(100) = ''

SELECT DISTINCT
	D.NUMERO AS [Nº CT-E]
	,D.DATAEMISSAO AS [Data Emissão CT-E]
	,REM.NOME AS [Cliente Remetente]
	,MUN.NOME AS [Cidade destinatário]
	,FENT.NOME AS FILIALENTREGAREGIAO
	--,REG.NOME AS [Região]
	,DEST.CEP AS CEP
	,EST.SIGLA AS ESTADO
	,DC.NUMERO AS [Número NF]
	,D.DOCCLIATUALVALORTOTAL AS [Valor NF]
	,ISNULL(D.DOCCLIPESOTOTAL, 0) AS [Peso real]
	,ISNULL(D.DOCCLIPESOCUBADOTOTAL, 0) AS [Peso cubado]
	,ISNULL(D.DOCCLIPESOCONSIDERADO,0) AS [Peso Considerado]
	,D.VALORFRETEPESO  AS [Frete peso]
	,D.VALORGRIS AS [GRIS]
	,D.VALORPEDAGIO AS [Pedágio]
	,D.VALORFRETEVALOR AS [ADV] --(Frete Valor)
	,DT.ALIQUOTAICMS AS [Aliquita de ICMS]
	,DT.VALORICMS AS [ICMS]
	,D.VALORCONTABIL AS [Frete Total]
	,D.DOCCLIVOLUME AS [Vol.]
	,DC.PEDIDO AS [Pedido]
	,CHAVECTE AS [Chave CTe]
	,EI.NOME AS [Tipo Entrega]
	,CASE
		WHEN D.TIPODOCUMENTO = 2 THEN 'CT-e'
		WHEN D.TIPODOCUMENTO = 6 THEN 'RPS'
	ELSE ''
	END AS TIPO
	,TOMADOR.NOME
	,TOMADOR.CGCCPF
	,FAT.NUMERO AS [Número da Fatura]

FROM GLGL_DOCUMENTOS D

INNER JOIN GN_PESSOAS REM 
	ON D.REMETENTE = REM.HANDLE

INNER JOIN GN_PESSOAS DEST
	ON D.DESTINATARIO = DEST.HANDLE

INNER JOIN MUNICIPIOS MUN
	ON DEST.MUNICIPIO = MUN.HANDLE

INNER JOIN ESTADOS EST
	ON DEST.ESTADO = EST.HANDLE

INNER JOIN GLGL_DOCUMENTOTRIBUTOS DT
	ON DT.DOCUMENTO = D.HANDLE

LEFT JOIN GLGL_DOCUMENTOASSOCIADOS DA
	ON DA.DOCUMENTOLOGISTICA = D.HANDLE

LEFT JOIN GLGL_DOCUMENTOCLIENTES DC 
	ON DC.HANDLE = DA.DOCUMENTOCLIENTE

INNER JOIN GLGL_ENUMERACAOITEMS EI
	ON EI.CODIGO = D.TIPOSERVICOFRETE

INNER JOIN FILIAIS FENT
	ON D.FILIALENTREGA = FENT.HANDLE

LEFT JOIN GN_PESSOAS TOMADOR
	ON D.TOMADORSERVICOPESSOA = TOMADOR.HANDLE

LEFT JOIN GLFT_FATURADOCUMENTOS FD 
	ON D.HANDLE = FD.DOCUMENTO

LEFT JOIN GLFT_FATURAS FAT
	ON FD.FATURA = FAT.HANDLE


WHERE 1=1
AND (FAT.NUMERO IN (@FATURA) OR @FATURA IS NULL OR @FATURA = '')
AND D.TIPODOCUMENTO IN (2,6)
AND REM.CGCCPF IN ( '11.200.418/0001-69'
					,'11.200.418/0006-73'
					,'11.200.418/0004-01'
				  )
AND (TOMADOR.CGCCPF LIKE '%' + @Tomador + '%' OR @Tomador IS NULL)
AND (D.DATAEMISSAO >= @BeginDate 
	OR FAT.DATAEMISSAO >= @BeginDate OR @BeginDate IS NULL)
AND (D.DATAEMISSAO < DATEADD(DD, 1, @EndDate)
	OR FAT.DATAEMISSAO < DATEADD(DD, 1, @EndDate) OR @EndDate IS NULL)