--DECLARE @DTINICIAL DATETIME = '2019-10-23'
--DECLARE @DTFINAL DATETIME = '2019-10-23'
--DECLARE @FILIAL INT = 5

DROP TABLE IF EXISTS #TempDOCS
SELECT 
	D.HANDLE,
	GN_PESSOAS.CGCCPF,
	GN_PESSOAS.NOME,
	D.NUMERO					[NUMERODOCUMENTO],
	D.DATAEMISSAO,
	GLGL_ENUMERACAOITEMS.NOME				[BASECALCULO],
	D.VALORCONTABIL			[VALORCONTABIL],
	1										[Qntde],
	D.DOCCLIVOLUME,
	D.DOCCLIPESOTOTAL,
	FILIAIS.NOME AS FILIAIS,
	GLGL_TIPODOCUMENTOS.NOME AS TIPODOC,
	T1.VALOR,
	T1.TIPO,
	T1.DIFCALCULOEDI,
	T1.DIFFRETEMANUAL,
	T1.DIFCALCULO

INTO #TempDOCS
FROM GLGL_DOCUMENTOS D
Inner Join GLGL_PESSOAS GLP
	On GLP.HANDLE = D.TOMADORSERVICOPESSOA
Inner Join GN_PESSOAS 
	On GN_PESSOAS.HANDLE = GLP.PESSOA
Left Join GLGL_DOCUMENTOCALCULOS
Inner Join GLGL_ENUMERACAOITEMS
	On GLGL_ENUMERACAOITEMS.HANDLE	    = GLGL_DOCUMENTOCALCULOS.PESOBASECALCULO
	On GLGL_DOCUMENTOCALCULOS.DOCUMENTO	= D.HANDLE
INNER JOIN FILIAIS
	ON D.FILIAL = FILIAIS.HANDLE
INNER JOIN GLGL_TIPODOCUMENTOS
	ON D.TIPODOCUMENTO = GLGL_TIPODOCUMENTOS.HANDLE 
LEFT JOIN 
		 (

			--SEM CUBAGEM
					SELECT DISTINCT 
						D.HANDLE AS [JOIN]
						,D.NUMERO
						,D.VALORCONTABIL AS VALOR
						,'Valor Sem Cubagem' AS TIPO
						,0 AS DIFFRETEMANUAL
						,0 AS [DIFCALCULOEDI]
						,0 AS DIFCALCULO

					FROM GLGL_DOCUMENTOASSOCIADOS
					INNER JOIN GLGL_DOCUMENTOCLIENTES
						ON (GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOCLIENTE		= GLGL_DOCUMENTOCLIENTES.HANDLE)
					INNER JOIN GLGL_DOCUMENTOS D
						ON GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOLOGISTICA = D.HANDLE
					WHERE 1=1 
						AND ((GLGL_DOCUMENTOCLIENTES.K_AFERIDOCARGOSCAN		= 'N')
						AND   (GLGL_DOCUMENTOCLIENTES.CUBAGEM					= 'N'
						AND D.DOCCLIPESOCUBADOTOTAL= 0))

					UNION ALL

					--VALORCUBADOMANUAL
					SELECT DISTINCT D.HANDLE AS [JOIN], D.NUMERO, D.VALORCONTABIL AS VALOR, 'Valor Cubado Manual' AS TIPO,
					CASE
					WHEN D.K_VALORRECALCULADOPESO IS NOT NULL THEN (D.VALORCONTABIL - D.K_VALORRECALCULADOPESO)
					ELSE 0 END AS DIFFRETEMANUAL, 0 AS [DIFCALCULOEDI],
					CASE
					WHEN D.K_VALORRECALCULADOPESO IS NOT NULL THEN (D.VALORCONTABIL - D.K_VALORRECALCULADOPESO)
					ELSE 0 END AS DIFCALCULO


					FROM GLGL_DOCUMENTOASSOCIADOS
					INNER JOIN GLGL_DOCUMENTOCLIENTES
						ON (GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOCLIENTE		= GLGL_DOCUMENTOCLIENTES.HANDLE)
					INNER JOIN GLGL_DOCUMENTOS D
						ON GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOLOGISTICA = D.HANDLE
					WHERE 1=1
						AND GLGL_DOCUMENTOCLIENTES.K_AFERIDOCARGOSCAN		= 'N'
						AND (GLGL_DOCUMENTOCLIENTES.CUBAGEM				= 'S'
						Or Exists (Select 1
									From GLGL_DOCCLICUBAGENS
									Where GLGL_DOCCLICUBAGENS.DOCUMENTOCLIENTE = GLGL_DOCUMENTOCLIENTES.HANDLE))
					And Not Exists (Select 1
										From GLID_IMPDOCCLIS 
										Where GLID_IMPDOCCLIS.DOCUMENTOCLIENTE  = GLGL_DOCUMENTOCLIENTES.HANDLE 
											And (GLID_IMPDOCCLIS.EDIPESOCUBADO > 0
											OR GLID_IMPDOCCLIS.EDIM3 > 0
											OR (EXISTS(SELECT 1
																FROM GLCM_REGOPEDI RE
																INNER JOIN GLCM_REGOPEDIEXTRAIRDADOS EXT ON RE.HANDLE = EXT.REGRAOPERACIONALEDI
														WHERE ((EXT.CAMPODESTINO = 1268 AND GLID_IMPDOCCLIS.M3 > 0)  
															OR (EXT.CAMPODESTINO = 1270 AND GLID_IMPDOCCLIS.PESOCUBADO > 0))
															AND RE.CONTRATO = D.CONTRATO))))

					UNION ALL

					--VALOR CUBADO EDI
					SELECT DISTINCT D.HANDLE AS [JOIN], D.NUMERO, D.VALORCONTABIL AS VALOR, 'Valor Cubado EDI' AS TIPO, 0 AS DIFFRETEMANUAL, 
					CASE
						WHEN D.K_VALORRECALCULADOPESO IS NOT NULL THEN (D.VALORCONTABIL - D.K_VALORRECALCULADOPESO)
					ELSE 0
					END AS [DIFCALCULOEDI],
					CASE
					WHEN D.K_VALORRECALCULADOPESO IS NOT NULL THEN (D.VALORCONTABIL - D.K_VALORRECALCULADOPESO)
					ELSE 0 END AS DIFCALCULO
					FROM GLGL_DOCUMENTOASSOCIADOS
					INNER JOIN GLGL_DOCUMENTOCLIENTES
						ON (GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOCLIENTE		= GLGL_DOCUMENTOCLIENTES.HANDLE)
					INNER JOIN GLGL_DOCUMENTOS D
						ON GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOLOGISTICA = D.HANDLE
					WHERE GLGL_DOCUMENTOCLIENTES.K_AFERIDOCARGOSCAN		= 'N'
						AND (GLGL_DOCUMENTOCLIENTES.CUBAGEM				= 'S'
						Or Exists (Select 1
									From GLGL_DOCCLICUBAGENS
								Where GLGL_DOCCLICUBAGENS.DOCUMENTOCLIENTE = GLGL_DOCUMENTOCLIENTES.HANDLE))
					And Exists (Select 1
										From GLID_IMPDOCCLIS 
								Where GLID_IMPDOCCLIS.DOCUMENTOCLIENTE                           = GLGL_DOCUMENTOCLIENTES.HANDLE 
									And (GLID_IMPDOCCLIS.EDIPESOCUBADO > 0
									OR GLID_IMPDOCCLIS.EDIM3 > 0
									OR (EXISTS(SELECT 1
														FROM GLCM_REGOPEDI RE
														INNER JOIN GLCM_REGOPEDIEXTRAIRDADOS EXT ON RE.HANDLE = EXT.REGRAOPERACIONALEDI
												WHERE ((EXT.CAMPODESTINO = 1268 AND GLID_IMPDOCCLIS.M3 > 0)  
													OR (EXT.CAMPODESTINO = 1270 AND GLID_IMPDOCCLIS.PESOCUBADO > 0))
													AND RE.CONTRATO = D.CONTRATO))))

					UNION ALL

					--VALOR CUBADO CARGO SCAN
					SELECT DISTINCT D.HANDLE AS [JOIN], D.NUMERO, D.VALORCONTABIL AS VALORSEMCUBAGEM, 'Valor Cubado Cargo Scan' AS TIPO, 0 AS DIFFRETEMANUAL, 0 AS [DIFCALCULOEDI], 
					CASE
					WHEN D.K_VALORRECALCULADOPESO IS NOT NULL THEN (D.VALORCONTABIL - D.K_VALORRECALCULADOPESO)
					ELSE 0 END AS DIFCALCULO
					FROM GLGL_DOCUMENTOASSOCIADOS
					INNER JOIN GLGL_DOCUMENTOCLIENTES
						ON (GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOCLIENTE		= GLGL_DOCUMENTOCLIENTES.HANDLE)
					INNER JOIN GLGL_DOCUMENTOS D
						ON GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOLOGISTICA = D.HANDLE
					WHERE 1=1 
						AND ((GLGL_DOCUMENTOCLIENTES.K_AFERIDOCARGOSCAN		= 'S')
						AND   (GLGL_DOCUMENTOCLIENTES.CUBAGEM					= 'S'
						AND Exists (Select 1
									From GLGL_DOCCLICUBAGENS
									Where GLGL_DOCCLICUBAGENS.DOCUMENTOCLIENTE = GLGL_DOCUMENTOCLIENTES.HANDLE)))

		 ) AS T1 
		 ON D.HANDLE = T1.[JOIN]

WHERE Cast(D.DATAEMISSAO As Date)	Between @DTINICIAL
																And @DTFINAL
		   --and D.NUMERO in (5760152, 5760361,5760142,5760398)
		   AND D.FILIAL						In (@FILIAL)
		   AND ((D.STATUSCTE					= 7
		   AND   D.TIPODOCUMENTO				= 2
		   AND	 D.TIPODOCUMENTOFRETE			= 153)
			OR (D.TIPODOCUMENTO				= 6
		   AND  D.TIPORPS						IN (322, 902)))


SELECT DISTINCT 
	   CGCCPF,
	   NOME,
	   BASECALCULO					[BaseCalculo],
       CASE	
			WHEN TIPO IN ('Valor Cubado Manual', 'Valor Cubado Cargo Scan', 'Valor Cubado EDI') THEN 'S'
	   ELSE 'N'
	   END AS [Cubagem],
	   TIPO						[Descricao],
	   NUMERODOCUMENTO				[NumeroDoc],
	   CASE 
		   WHEN TIPO = 'Valor Cubado Cargo Scan' THEN 'Cliente c/ mercadoria cubada CargoScan'
		   WHEN TIPO = 'Valor Cubado Manual' THEN 'Cliente c/ mercadoria cubada Manual'
		   WHEN TIPO = 'Valor Cubado EDI' THEN 'Cliente c/ mercadoria cubada EDI'
		   WHEN TIPO = 'Valor Sem Cubagem' THEN 'Cliente s/ mercadoria cubada'
	   ELSE ''
	   END AS TIPODESCRICAO,
	   FILIAIS,
	   TIPODOC,
	   CAST(DATAEMISSAO AS DATE)            [DataEmissao],
	   DATEPART(DD, CAST(DATAEMISSAO AS DATE)) AS DIADATA,
	   CASE	
			WHEN DATEPART(DW, CAST(DATAEMISSAO AS DATE)) = 1 THEN 'Domingo'
			WHEN DATEPART(DW, CAST(DATAEMISSAO AS DATE)) = 2 THEN 'Segunda'
			WHEN DATEPART(DW, CAST(DATAEMISSAO AS DATE)) = 3 THEN 'Terça'
			WHEN DATEPART(DW, CAST(DATAEMISSAO AS DATE)) = 4 THEN 'Quarta'
			WHEN DATEPART(DW, CAST(DATAEMISSAO AS DATE)) = 5 THEN 'Quinta'
			WHEN DATEPART(DW, CAST(DATAEMISSAO AS DATE)) = 6 THEN 'Sexta'
			WHEN DATEPART(DW, CAST(DATAEMISSAO AS DATE)) = 7 THEN 'Sabado'
	   ELSE ''
	   END AS DIASEMANA,
	   Sum(Qntde)					[Qntde],
	   Sum(DOCCLIVOLUME)				[Volume],
	   Sum(DOCCLIPESOTOTAL)					[PesoNF],
	  CASE 
		   WHEN TIPO = 'Valor Cubado Cargo Scan' THEN SUM(VALOR)
	   ELSE 0
	   END AS [ValorCubado],
	   CASE 
		   WHEN TIPO = 'Valor Cubado Cargo Scan' THEN Sum(TD.DIFCALCULO)
	   ELSE 0
	   END AS [DifFrete],
	   --
	   CASE 
		   WHEN TIPO = 'Valor Sem Cubagem' THEN SUM(VALOR)
	   ELSE 0
	   END AS [ValorSemCubagem],
	   --
	   CASE 
		   WHEN TIPO = 'Valor Cubado Manual' THEN Sum(TD.DIFCALCULO)
	   ELSE 0
	   END AS [DifFreteManual],
	   CASE 
		   WHEN TIPO = 'Valor Cubado Manual' THEN SUM(VALOR)
	   ELSE 0
	   END AS [ValorCubadoManual],
	   --
	   CASE 
		   WHEN TIPO = 'Valor Cubado EDI' THEN Sum(TD.DIFCALCULO)
	   ELSE 0
	   END AS [DifFreteEDI],
	   CASE 
		   WHEN TIPO = 'Valor Cubado EDI' THEN SUM(VALOR)
	   ELSE 0
	   END AS [ValorCubadoEDI],
	   Sum(VALOR)					[ValorTotal]
 
FROM #TempDOCS TD

GROUP BY 
	  CGCCPF,
	   NOME,
	   BASECALCULO,
	 --  IIF(Sum(TBBase.VALORCUBADO)			> 0
		--Or Sum(TBBase.VALORCUBADOMANUAL)	> 0
		--Or Sum(TBBase.VALORCUBADOEDI)		> 0,
		--'S', 'N')							[Cubagem],
	   TIPO,
	   NUMERODOCUMENTO,
	   CASE 
		   WHEN TIPO = 'Valor Cubado Cargo Scan' THEN 'Cliente c/ mercadoria cubada CargoScan'
		   WHEN TIPO = 'Valor Cubado Manual' THEN 'Cliente c/ mercadoria cubada Manual'
		   WHEN TIPO = 'Valor Cubado EDI' THEN 'Cliente c/ mercadoria cubada EDI'
		   WHEN TIPO = 'Valor Sem Cubagem' THEN 'Cliente s/ mercadoria cubada'
	   ELSE ''
	   END,
	   FILIAIS,
	   TIPODOC,
	   CAST(DATAEMISSAO AS DATE),
	   DATEPART(DD, CAST(DATAEMISSAO AS DATE)),
	   CASE	
			WHEN DATEPART(DW, CAST(DATAEMISSAO AS DATE)) = 1 THEN 'Domingo'
			WHEN DATEPART(DW, CAST(DATAEMISSAO AS DATE)) = 2 THEN 'Segunda'
			WHEN DATEPART(DW, CAST(DATAEMISSAO AS DATE)) = 3 THEN 'Terça'
			WHEN DATEPART(DW, CAST(DATAEMISSAO AS DATE)) = 4 THEN 'Quarta'
			WHEN DATEPART(DW, CAST(DATAEMISSAO AS DATE)) = 5 THEN 'Quinta'
			WHEN DATEPART(DW, CAST(DATAEMISSAO AS DATE)) = 6 THEN 'Sexta'
			WHEN DATEPART(DW, CAST(DATAEMISSAO AS DATE)) = 7 THEN 'Sabado'
	   ELSE ''
	   END
ORDER BY NUMERODOCUMENTO