SELECT TOP(10)
	--R.HANDLE
	R.FILIAL AS FILIALCONTABIL
	,F.NOME AS NOMEFILIALCONTABIL
	,R.LOCALFILIAL AS FILIALLOCALIZACAO
	,FO.NOME AS NOMEFILIALLOCALIZACAO
	,GETDATE() AS DATAGERACAODADOS
	,R.DATAINCLUSAO
	,R.DATAALTERACAO	
	,R.CODIGO
	,R.TIPOVEICULO
	,VT.NOME as VEICULOTIPO
	,R.GLSUBTIPO
	,VST.NOME AS VEICULOSUBTIPO
	,VM.NOME AS VEICULOMODELO
--*

FROM MA_RECURSOS R
INNER JOIN MF_VEICULOTIPOS VT 
	ON R.TIPOVEICULO = VT.HANDLE
LEFT JOIN FILIAIS F
	ON R.FILIAL = F.HANDLE
LEFT JOIN FILIAIS FO
	ON R.LOCALFILIAL = FO.HANDLE
LEFT JOIN GLMF_VEICULOSUBTIPOS VST
	ON R.GLSUBTIPO = VST.HANDLE
LEFT JOIN MF_VEICULOMODELOS VM
	ON R.MODELOVEICULO = VM.HANDLE

WHERE 1=1
--AND R.CODIGO LIKE '%03240%' 
AND VT.NOME IN ('Unitizador')