/****** Script for SelectTopNRows command from SSMS  ******/
SELECT [HANDLE]
      ,[UFHANDLE]
      ,[ESTNOME]
      ,[REGIONAL]
      ,[FILIAL]
      ,[DATA]
      ,[CATEGORIA]
      ,[VALOR]
      ,[VALORTOTALANTERIOR]
      ,[VALORACUMULADOANT]
      ,[TOTALLIBERADONAOLIBERADO]
      ,[DISPONIVELFATURAR]
      ,[NAODISPONIVELFATURAR]
	  ,CASE
			WHEN CAST([DATA] AS DATE) = DATEADD(DD, -1, CAST(GETDATE() AS DATE)) THEN [VALOR]
	   ELSE 0
	   END AS ONTEM 
	  ,CASE
			WHEN MONTH(CAST([DATA] AS DATE)) = MONTH(CAST(GETDATE() AS DATE)) AND CAST([DATA] AS DATE) <= CAST(GETDATE() AS DATE) THEN [VALOR]
	   ELSE 0
	   END AS ESSEMES 
  FROM [BI_PATRUS].[dbo].[TEMP_Diretoria_Faturamento]
