DECLARE @BeginDate DATE = DateAdd(yy, DateDiff(yy,0,GetDate()) - 1, 0)
DECLARE @EndDate DATE = getdate()

SELECT 
*
,cast (QTDHORASMANUTENCAO / 60 as varchar) + ':' + cast (QTDHORASMANUTENCAO - ((QTDHORASMANUTENCAO / 60) * 60) as varchar) as TEMPOmANUTENCAO
,ROUND(((CAST(QTDCARRETASTOTAL AS NUMERIC(10,2))/CAST(QTDVEICULOSCADASTRADOS AS NUMERIC(10,2)))*100),2) AS '% Carreta'

FROM(
SELECT 
		A.HANDLE
		,A.CODIGO
		,A.DESCRICAO
		,C.SIGLA
		,B.CODIGO AS PLACA
		,VEICULOTIPO.NOME AS TIPOVEICULO
		,substring(A.CODIGO, 1, (charindex('.',A.CODIGO,1)-1)) as TIPOOS
		,YEAR(CAST(DATAINICIAL AS DATE)) AS ANO
		,CAST(DATAINICIAL AS DATE) AS DATAINICIAL
		,CAST(DATAFINAL AS DATE) AS DATAFINAL
		,DATEDIFF(MI,DATAINICIAL,DATAFINAL) AS QTDHORASMANUTENCAO
		,COUNT(CAST(DATAINICIAL AS DATE)) AS QTDABERTONODIA
		,COUNT(CAST(DATAFINAL AS DATE)) AS QTDFECHADONODIA
		,CASE 
			WHEN VEICULOTIPO.NOME = 'Carreta' THEN 1
		ELSE 0
		END AS QTDCARRETAS

		,(SELECT COUNT(DISTINCT CODIGO) FROM [DBRodo].[dbo].MA_RECURSOS B 
			INNER JOIN MF_VEICULOTIPOS VEICULOTIPO 
				ON VEICULOTIPO.HANDLE = B.TIPOVEICULO
		 WHERE  VEICULOTIPO.NOME = 'Carreta') AS QTDCARRETASTOTAL

		,SUM(A.VALORTOTAL) AS VALORTOTAL
		,(SELECT COUNT(DISTINCT CODIGO) FROM [DBRodo].[dbo].MA_RECURSOS) AS QTDVEICULOSCADASTRADOS

FROM [DBRodo].[dbo].MF_ORDEMSERVICOS A
LEFT JOIN [DBRodo].[dbo].MA_RECURSOS B 
	ON A.VEICULO = B.HANDLE
INNER JOIN MF_VEICULOTIPOS VEICULOTIPO 
	ON VEICULOTIPO.HANDLE = B.TIPOVEICULO
INNER JOIN GLGL_FILIAIS C
	ON A.FILIAL = C.HANDLE

WHERE DATAINICIAL >= @BeginDate
AND DATAINICIAL < @EndDate
--AND CAST(DATAFINAL AS DATE) <> CAST(DATAINICIAL AS DATE)
--AND A.CODIGO = 'MCI.0002787/19'

GROUP BY A.HANDLE
		,A.CODIGO
		,A.DESCRICAO
		,C.SIGLA
		,B.CODIGO
		,VEICULOTIPO.NOME
		,substring(A.CODIGO, 1, (charindex('.',A.CODIGO,1)-1))
		,DATEDIFF(MI,DATAINICIAL,DATAFINAL)
		,YEAR(CAST(DATAINICIAL AS DATE))
		,CAST(DATAINICIAL AS DATE)
		,CAST(DATAFINAL AS DATE)
) AS T