DROP TABLE IF EXISTS #TESTE


SELECT DISTINCT 
	
	P.NOME
	,P.CGCCPF
	
	--,E.HANDLE AS CODETIQUETAHDL
	--,E.ETIQUETAINICIAL
	--,E.DOCUMENTOCLIENTE

	,CASE
		WHEN ORIGEM IN (2,3) THEN 'CLIENTE'
	ELSE 'PATRUS'
	END AS [ORIGEM ETIQUETA]
	,SUM(VOLUMES) AS QTDVOLUME
	
INTO #TESTE
FROM GLGV_ETIQUETAS E
--INNER JOIN GLGV_ETIQUETAVOLUMES EV ON E.HANDLE = EV.ETIQUETA
INNER JOIN GLGL_DOCUMENTOCLIENTES DC ON E.DOCUMENTOCLIENTE = DC.HANDLE
INNER JOIN GN_PESSOAS P ON DC.TOMADORSERVICOPESSOA = P.HANDLE  


WHERE E.DATAEMISSAO >= '2019-03-01'
AND E.DATAEMISSAO < '2020-03-10'
AND ORIGEM <> 1


GROUP BY P.NOME
	,P.CGCCPF
	
	--,E.HANDLE AS CODETIQUETAHDL
	--,E.ETIQUETAINICIAL
	--,E.DOCUMENTOCLIENTE

	,CASE
		WHEN ORIGEM IN (2,3) THEN 'CLIENTE'
	ELSE 'PATRUS'
	END

SELECT * FROM #TESTE
ORDER BY QTDVOLUME DESC