Select EMPRESAS.CGC,
	EMPRESAS.NOME,
	GN_PESSOAS.NOME															[BENEFICIARIO],
	   GN_PESSOAS.CGCCPF,
	   Cast(GLOP_CONTRATOFRETES.DATAEMISSAO	As Date)							[DATA],
	   IsNull(GLCM_LEIAUTETARIFAS.NOME, 'Valor Combinado / Complementar')		[TITULO],
	   IsNull(GLCM_COMPONENTECALCULOS.NOME, GLCM_COMCALCLASSIFICACOES.NOME)		[DESCRICAO],
	   GLOP_CONTRATOFRETCALCULOS.VALORFINAL,
	   GLOP_CONTRATOFRETES.NUMERO												[CONTRATOFRETE],
	   IIF(GLOP_RCF.STATUS = 601, 0, GLOP_CONTRATOFRETCALCULOS.VALORFINAL)   	[PAGARDESCONTAR], 
IIF(IsNull(GLCM_COMPONENTECALCULOS.HANDLE, GLCM_COMCALCLASSIFICACOES.HANDLE)	In (10, 51, 74),
(Select Sum(DISTANCIA) [DISTANCIA]
From (Select Sum(GLOP_LINHAVIAGEMFILIAIS.DISTANCIA)								[DISTANCIA]
				  From GLOP_CONTRATOFRETEVIAGENS
				 Inner Join GLOP_VIAGENS				On GLOP_VIAGENS.HANDLE						= GLOP_CONTRATOFRETEVIAGENS.VIAGEM
				 Inner Join GLOP_LINHAVIAGENS			On GLOP_LINHAVIAGENS.HANDLE					= GLOP_VIAGENS.LINHAVIAGEM
				 Inner Join GLOP_LINHAVIAGEMFILIAIS		On GLOP_LINHAVIAGEMFILIAIS.LINHAVIAGEM		= GLOP_LINHAVIAGENS.HANDLE
				 Where GLOP_CONTRATOFRETEVIAGENS.CONTRATOFRETE										= GLOP_CONTRATOFRETES.HANDLE
				   And Not GLOP_VIAGENS.TIPOVIAGEM													In (169, 170, 173)
				 Union All
Select Sum(IsNull(GLOP_VIAGENS.DISTANCIACONSIDERADA, GLOP_VIAGENS.DISTANCIATOTAL))	[DISTANCIA]
				  From GLOP_CONTRATOFRETEVIAGENS
				 Inner Join GLOP_VIAGENS				On GLOP_VIAGENS.HANDLE						= GLOP_CONTRATOFRETEVIAGENS.VIAGEM
				 Where GLOP_CONTRATOFRETEVIAGENS.CONTRATOFRETE										= GLOP_CONTRATOFRETES.HANDLE
				   And GLOP_VIAGENS.TIPOVIAGEM														In (169, 170, 173)) TB), 0) [DISTANCIA],
(Select Sum(PESOREAL) AS PESOREAL
From (Select Sum(B.DOCCLIPESOTOTAL) AS PESOREAL 
	From GLOP_CONTRATOFRDOCUMENTOS A
				 INNER JOIN GLGL_DOCUMENTOS B							On B.HANDLE		= A.DOCUMENTO
				 Where A.CONTRATOFRETE													= GLOP_CONTRATOFRETES.HANDLE
				   AND (B.TIPODOCUMENTO													<> 6 
				    OR (B.TIPODOCUMENTO													= 6 
				   AND (B.TIPORPS														<> 324 
				    OR B.RPSINTERNACIONAL												= 'S') ))
				 Union All
Select Sum(DOCLOG.DOCCLIPESOTOTAL) AS PESOREAL
	From GLOP_VIAGEMDOCUMENTOS A
				 Inner Join GLOP_CONTRATOFRETEVIAGENS B		On B.VIAGEM					= A.VIAGEM
				  Left JOIN GLGL_DOCUMENTOS DOCLOG			On (A.DOCUMENTOLOGISTICA	= DOCLOG.HANDLE)
				 Where B.CONTRATOFRETE													= GLOP_CONTRATOFRETES.HANDLE
				   And (A.DOCUMENTOCOLETA												IS NOT NULL 
				    Or A.DOCUMENTOLOGISTICA												IS NOT NULL)
				   And (A.DOCUMENTOLOGISTICA											= 0 
				    Or 0																= 0)) TB)	[PESOREAL],
	   FILIAIS.NOME																					[FILIAL]
  From GLOP_CONTRATOFRETES
 Inner Join GLOP_CONTRATOFRETEVIAGENS		On GLOP_CONTRATOFRETEVIAGENS.CONTRATOFRETE	= GLOP_CONTRATOFRETES.HANDLE
 Inner Join GLOP_VIAGENS					On GLOP_VIAGENS.HANDLE						= GLOP_CONTRATOFRETEVIAGENS.VIAGEM
 Inner Join GLOP_CONTRATOFRETCALCULOS		On GLOP_CONTRATOFRETCALCULOS.CONTRATOFRETE	= GLOP_CONTRATOFRETES.HANDLE
  Left Join GLCM_LEIAUTETARIFAS				On GLCM_LEIAUTETARIFAS.HANDLE				= GLOP_CONTRATOFRETCALCULOS.LEIAUTETARIFA
  Left Join GLCM_LEIAUTETACOMPONENTES		On GLCM_LEIAUTETACOMPONENTES.HANDLE			= GLOP_CONTRATOFRETCALCULOS.COMPONENTETARIFA
										   And GLCM_LEIAUTETACOMPONENTES.LEIAUTETARIFA	= GLCM_LEIAUTETARIFAS.HANDLE
  Left Join GLCM_COMPONENTECALCULOS			On GLCM_COMPONENTECALCULOS.HANDLE			= GLCM_LEIAUTETACOMPONENTES.COMPONENTECALCULO
  Left Join GLCM_COMCALCLASSIFICACOES 		On GLCM_COMCALCLASSIFICACOES.HANDLE			= GLOP_CONTRATOFRETCALCULOS.CLASSIFICACAO
 Inner Join GN_PESSOAS						On GN_PESSOAS.HANDLE						= GLOP_CONTRATOFRETES.BENEFICIARIO
  Left Join GLOP_RCFASSOCIADOS				
 Inner Join GLOP_RCF						On GLOP_RCF.HANDLE							= GLOP_RCFASSOCIADOS.RELACAO
										   And GLOP_RCF.STATUS							= 601
										    On GLOP_RCFASSOCIADOS.CONTRATOFRETE			= GLOP_CONTRATOFRETES.HANDLE
 Inner Join EMPRESAS						On EMPRESAS.HANDLE							= GLOP_CONTRATOFRETES.EMPRESA
 Inner Join FILIAIS							On FILIAIS.HANDLE							= GLOP_CONTRATOFRETES.FILIAL
 Where GLOP_CONTRATOFRETES.STATUS														<> 433
   And GLOP_CONTRATOFRETES.TIPOCONTRATO													= 300
   And Cast(GLOP_CONTRATOFRETES.DATAEMISSAO	As Date)									Between @CAMPO(DTINI)
																							And @CAMPO(DTFIM)
   And GLOP_CONTRATOFRETES.VALORPARCELAS												>= 0
   And GLOP_CONTRATOFRETCALCULOS.NIVEL													= 285
   And GLOP_CONTRATOFRETCALCULOS.VALORFINAL												> 0
{FilterEntity.Fields["FILIAL"] != null ? "   And GLOP_CONTRATOFRETES.FILIAL			In (@CAMPO(FILIAL)) " : ""}
{FilterEntity.Fields["BENEFICIARIO"] != null ? "   And GLOP_CONTRATOFRETES.BENEFICIARIO	In (@CAMPO(BENEFICIARIO)) " : ""}
{FilterEntity.Fields["TIPODEVIAGEM"] != null ? "   And AND GLOP_VIAGENS.TIPOVIAGEM =			In (@CAMPO(TIPODEVIAGEM)) " : ""}
 Union All
Select EMPRESAS.CGC,
	EMPRESAS.NOME,
	GN_PESSOAS.NOME															[BENEFICIARIO],
	   GN_PESSOAS.CGCCPF,
 	   Cast(GLOP_CONTRATODESPVENCTOS.DATAVENCIMENTO As Date)				[DATA], 
	   'Descontos'															[TITULO],
	   GLGL_TIPOLANCAMENTOS.DESCRICAO										[DESCRICAO],
	   GLOP_CONTRATODESPVENCTOS.VALOR*(-1)									[VALORFINAL],
	   Cast(GLOP_CONTRATODESPESAS.NUMERO As VarChar(Max))					[CONTRATODESPESA],
	   IIF(GLOP_RCF.STATUS = 601, 0, GLOP_CONTRATODESPVENCTOS.VALOR*(-1))	[PAGARDESCONTAR],
	   0																	[DISTANCIA],
	   0																	[PESOREAL],
	   FILIAIS.NOME															[FILIAL]
  From GLOP_CONTRATODESPESAS
 Inner Join GLOP_CONTRATODESPVENCTOS	On GLOP_CONTRATODESPVENCTOS.CONTRATODESPESA		= GLOP_CONTRATODESPESAS.HANDLE
  Left Join GLGL_TIPOLANCAMENTOS		On GLGL_TIPOLANCAMENTOS.HANDLE					= GLOP_CONTRATODESPESAS.TIPOLANCAMENTO
 Inner Join GN_PESSOAS					On GN_PESSOAS.HANDLE							= GLOP_CONTRATODESPESAS.BENEFICIARIO
  Left Join GLOP_RCFDESPESAASSOCIADAS	On GLOP_RCFDESPESAASSOCIADAS.CONTRATODESPESA	= GLOP_CONTRATODESPESAS.HANDLE
  Left Join GLOP_RCF					On GLOP_RCF.HANDLE								= GLOP_RCFDESPESAASSOCIADAS.RELACAO
									   And GLOP_RCF.STATUS								= 601
 Inner Join EMPRESAS					On EMPRESAS.HANDLE								= GLOP_CONTRATODESPESAS.EMPRESA
 Inner Join FILIAIS						On FILIAIS.HANDLE								= GLOP_CONTRATODESPESAS.FILIAL
 Where Cast(GLOP_CONTRATODESPVENCTOS.DATAVENCIMENTO	As Date)							Between @CAMPO(DTINI)
																							And @CAMPO(DTFIM)
   And GLOP_CONTRATODESPESAS.STATUS														<> 434
{FilterEntity.Fields["FILIAL"] != null ? "	And GLOP_CONTRATODESPESAS.FILIAL			In (@CAMPO(FILIAL)) " : ""}
{FilterEntity.Fields["BENEFICIARIO"] != null ? "   And GLOP_CONTRATODESPESAS.BENEFICIARIO	In (@CAMPO(BENEFICIARIO)) " : ""}