/****** Script for SelectTopNRows command from SSMS  ******/

--Gustavo, conforme conversamos, segue relatório a ser criado.

--O cliente MWM CNPJ 02.162.259/0003-26 precisa receber diariamente um relatório com o seguintes dados.

--CTRC(CTE), DATA DA COLETA, NOTA FISCAL, VALOR DA NF, VOLUMES, PESO, DESTINATARIO, CIDADE UF, TRANSIT TIME, STATUS, DATA DE ENTREGA



SELECT 
		F.HANDLE AS CODFILIAL
	   ,F.NOME AS NOMEFILIAL
	   ,FET.HANDLE AS CODFILIALENTREGA
	   ,FET.NOME AS NOMEFILIALENTREGA
	   ,F.CGC AS CNPJ
	   ,GNP.NOME AS NOMECLIENTE
	   ,GEX.NOME AS NOMEDESTINATARIO
	   ,D.HANDLE AS CODDOCPATRUS
	   ,DA.HANDLE AS CODDOCASSOCIADO
	   ,DT.[BASECALCULOICMS]
       ,DT.[BASECALCULOPIS]
       ,DT.[BASECALCULOCOFINS]
       ,DT.[VALORICMS]
       ,DT.[VALORPIS]
       ,DT.[VALORCOFINS]


  --COUNT(DA.HANDLE)
  --,COUNT(DISTINCT DA.HANDLE)
  

FROM [DBRodo].[dbo].[GLGL_DOCUMENTOS] D WITH(NOLOCK)

INNER JOIN [DBRodo].[dbo].[GLGL_DOCUMENTOASSOCIADOS] DA WITH(NOLOCK)
 ON D.HANDLE = DA.DOCUMENTOLOGISTICA

INNER JOIN [DBRodo].[dbo].[GLGL_DOCUMENTOCLIENTES] DC WITH(NOLOCK)
 ON DA.DOCUMENTOCLIENTE = DC.HANDLE

INNER JOIN [DBRodo].[dbo].[GLGL_PESSOAS] P WITH(NOLOCK)
 ON D.REMETENTE = P.HANDLE

INNER JOIN [DBRodo].[dbo].[GN_PESSOAS] GNP WITH(NOLOCK)
 ON P.PESSOA = GNP.HANDLE 

INNER JOIN [DBRodo].[dbo].[GLGL_PESSOAS] PEX WITH(NOLOCK)
 ON D.DESTINATARIO = PEX.HANDLE

INNER JOIN [DBRodo].[dbo].[GN_PESSOAS] GEX WITH(NOLOCK) 
 ON PEX.PESSOA = GEX.HANDLE 

INNER JOIN [DBRodo].[dbo].[FILIAIS] F WITH(NOLOCK)
 ON D.FILIAL = F.HANDLE

LEFT JOIN [DBRodo].[dbo].[FILIAIS] FET WITH(NOLOCK)
 ON D.FILIALENTREGA = FET.HANDLE

INNER JOIN [DBRodo].[dbo].[GLGL_DOCUMENTOTRIBUTOS] DT WITH(NOLOCK)
 ON DT.DOCUMENTO = D.HANDLE

WHERE D.DATAEMISSAO >= '2019-09-01' 
AND D.DATAEMISSAO < '2019-09-10'
--AND D.HANDLE = 38752375


--ORDER BY D.HANDLE