--Emissao
Select DISTINCT 

'Emissao' as [Operacoes]
	,GLFT_FATURAS.NUMERO AS [Fatura]
	,GLGL_DOCUMENTOS.NUMERO AS [Numero CTe]
	,Convert(VarChar(10), GLGL_DOCUMENTOS.DATAEMISSAO, 103) AS [Data Emissao CTe]
	,STUFF((Select ',' + cast(X.NUMERO as varchar(9))
				From GLGL_DOCUMENTOCLIENTES X
			   Inner Join GLGL_DOCUMENTOASSOCIADOS K
				  On K.DOCUMENTOCLIENTE		= X.HANDLE
			   Where K.DOCUMENTOLOGISTICA	= GLGL_DOCUMENTOS.HANDLE
				 For XML PATH ('')),1,1,'') AS [Numeros NFs]
	,Convert(VarChar(10), (Select Min(GLGL_DOCUMENTOCLIENTES.DATAEMISSAO)
							   From GLGL_DOCUMENTOCLIENTES
							  Inner Join GLGL_DOCUMENTOASSOCIADOS
								 On GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOCLIENTE	= GLGL_DOCUMENTOCLIENTES.HANDLE
							  Where GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOLOGISTICA	= GLGL_DOCUMENTOS.HANDLE), 103) AS [Data Emissao NF]
	
	,CodigoToyota.CODIGOCONCESSIOARIA AS [Cod. Remetente]
	,GN_PESSOASREM.NOME AS [Remetente]
	,GN_PESSOASREM.CGCCPF AS [CNPJ (Remetente)]
	,MUNICIPIOSREM.NOME	AS [Cidade (Remetente)]
	,ESTADOSREM.SIGLA AS [UF (Remetente)]
	,GN_PESSOASDES.NOME	AS [Destinatario]
	,GN_PESSOASDES.CGCCPF AS [CNPJ (Destinatario)]
	,MUNICIPIOSDES.NOME AS [Cidade (Destinatario)]
	,ESTADOSDES.SIGLA AS [UF (Destinatario)]
	,GLGL_DOCUMENTOS.DOCCLIVOLUME AS [Quant. de Volumes]
	,GLGL_DOCUMENTOS.DOCCLIPESOTOTAL AS [Peso Real em Kgs]
	,(Select Sum(IsNull(GLGL_DOCCLICUBAGENS.M3,0))
		  From GLGL_DOCUMENTOCLIENTES X
	     Inner Join GLGL_DOCUMENTOASSOCIADOS
		    On GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOLOGISTICA	= GLGL_DOCUMENTOS.HANDLE
		 Inner Join GLGL_DOCCLICUBAGENS 
			On GLGL_DOCCLICUBAGENS.DOCUMENTOCLIENTE			= X.HANDLE
		 Where X.HANDLE	= GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOCLIENTE) AS [Tamanho real em m3]
	,GLGL_DOCUMENTOS.DOCCLIPESOCONSIDERADO AS [Peso Cobrado]
	,GLGL_DOCUMENTOS.DOCCLIVALORTOTAL AS [Valor NF]
	,GLGL_DOCUMENTOS.VALORCONTABIL AS [Valor do Frete]
	,GLGL_DOCUMENTOS.CHAVECTE AS [Chave de acesso CTe]
	,CAST(GLGL_DOCUMENTOS.OBSERVACOESIMPRESSAS AS NVARCHAR(1000)) AS [Observacoes]
  From GLGL_DOCUMENTOS																												
 --Inner Join GLGL_DOCUMENTOASSOCIADOS																								
	--On GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOLOGISTICA	= GLGL_DOCUMENTOS.HANDLE														
 --Inner Join GLGL_DOCUMENTOCLIENTES																									
	--On GLGL_DOCUMENTOCLIENTES.HANDLE				= GLGL_DOCUMENTOASSOCIADOS.DOCUMENTOCLIENTE
 Inner Join GN_PESSOAS GN_PESSOASREM
	On GN_PESSOASREM.HANDLE							= GLGL_DOCUMENTOS.REMETENTE
 Inner Join GLGL_PESSOAENDERECOS GLGL_PESSOAENDERECOSREM
	On GLGL_PESSOAENDERECOSREM.HANDLE				= GLGL_DOCUMENTOS.REMETENTEENDERECO
 Inner Join MUNICIPIOS MUNICIPIOSREM
	On MUNICIPIOSREM.HANDLE							= GLGL_PESSOAENDERECOSREM.MUNICIPIO
 Inner Join ESTADOS ESTADOSREM
	On ESTADOSREM.HANDLE							= MUNICIPIOSREM.ESTADO
 Inner Join GN_PESSOAS GN_PESSOASDES
	On GN_PESSOASDES.HANDLE							= GLGL_DOCUMENTOS.DESTINATARIO
 Inner Join GLGL_PESSOAENDERECOS GLGL_PESSOAENDERECOSDES
	On GLGL_PESSOAENDERECOSDES.HANDLE				= GLGL_DOCUMENTOS.DESTINOENDERECO
 Inner Join MUNICIPIOS MUNICIPIOSDES
	On MUNICIPIOSDES.HANDLE							= GLGL_PESSOAENDERECOSDES.MUNICIPIO
 Inner Join ESTADOS ESTADOSDES
	On ESTADOSDES.HANDLE							= MUNICIPIOSDES.ESTADO
  Left Join [SQLAZGERAL].[BI_PATRUS].[dbo].[CodigoToyota] CodigoToyota
	On CodigoToyota.CGCCPF collate SQL_Latin1_General_CP850_CI_AS = GN_PESSOASDES.CGCCPF collate SQL_Latin1_General_CP850_CI_AS
  Left Join GLFT_FATURADOCUMENTOS
	On GLFT_FATURADOCUMENTOS.DOCUMENTO				= GLGL_DOCUMENTOS.HANDLE
  Left Join GLFT_FATURAS
	On GLFT_FATURAS.HANDLE							= GLFT_FATURADOCUMENTOS.FATURA
   And Not GLFT_FATURAS.STATUS							In (335, 1150, 327, 1174)
 Where Cast(GLGL_DOCUMENTOS.DATAEMISSAO As date)	Between @DATAI
														And @DATAF
   And Not GLGL_DOCUMENTOS.STATUS					In (236, 237, 417)
   And (GLGL_DOCUMENTOS.TIPODOCUMENTO				In (1, 2)
	Or (GLGL_DOCUMENTOS.TIPODOCUMENTO				= 6
   And  GLGL_DOCUMENTOS.TIPORPS						<> 324))
   And (GLGL_DOCUMENTOS.TIPODOCUMENTO				= 2
   And GLGL_DOCUMENTOS.TIPODOCUMENTOFRETE			In (153, 154)
    Or GLGL_DOCUMENTOS.TIPODOCUMENTO				= 6)
   And (Not GLGL_DOCUMENTOS.STATUS					In (235)
   And GLGL_DOCUMENTOS.RECUSADO						='N')
   And ((GLGL_DOCUMENTOS.FILIAL						= 5
   And   (GLGL_DOCUMENTOS.REMETENTE					= (Select HANDLE From GN_PESSOAS Where GN_PESSOAS.CGCCPF ='59.104.760/0001-91')
	Or    GLGL_DOCUMENTOS.TOMADORSERVICOPESSOA		= (Select HANDLE From GN_PESSOAS Where GN_PESSOAS.CGCCPF ='59.104.760/0001-91')))
	Or (GLGL_DOCUMENTOS.FILIAL						= 8
   And  GLGL_DOCUMENTOS.REMETENTE					= (Select HANDLE From GN_PESSOAS Where GN_PESSOAS.CGCCPF ='59.104.760/0009-49'))
    Or (GLGL_DOCUMENTOS.REMETENTE					= (Select HANDLE From GN_PESSOAS Where GN_PESSOAS.CGCCPF ='59.104.760/0012-44')))