DECLARE @BeginDate DATE = DateAdd(yy, DateDiff(yy,0,GetDate()) - 1, 0)
DECLARE @EndDate DATE = getdate()

SELECT TOP(10)
		A.HANDLE
		,A.CODIGO
		,A.DESCRICAO
		,A.FILIAL
		,B.CODIGO AS PLACA
		,VEICULOTIPO.NOME AS TIPOVEICULO
		,CAST(DATAINICIAL AS DATE) AS DATAINICIAL
		,'' AS DATAFINAL
		,COUNT(A.CODIGO) AS QTDABERTONODIA
		,0 AS QTDFECHADONODIA

FROM [DBRodo].[dbo].MF_ORDEMSERVICOS A
LEFT JOIN [DBRodo].[dbo].MA_RECURSOS B ON A.VEICULO = B.HANDLE
INNER JOIN MF_VEICULOTIPOS VEICULOTIPO 
	ON VEICULOTIPO.HANDLE = B.TIPOVEICULO

WHERE DATAINICIAL >= @BeginDate
AND DATAINICIAL < @EndDate
AND A.CODIGO = 'MCI.0002787/19'

GROUP BY A.HANDLE
		,A.CODIGO
		,A.DESCRICAO
		,A.FILIAL
		,B.CODIGO
		,VEICULOTIPO.NOME
		,CAST(DATAINICIAL AS DATE)

UNION ALL

SELECT TOP(10)
		A.HANDLE
		,A.CODIGO
		,A.DESCRICAO
		,A.FILIAL
		,B.CODIGO AS PLACA
		,VEICULOTIPO.NOME AS TIPOVEICULO
		,'' AS DATAINICIAL
		,CAST(DATAFINAL AS DATE) AS DATAFINAL
		,0 AS QTDABERTONODIA
		,COUNT(A.CODIGO) AS QTDFECHADONODIA

FROM [DBRodo].[dbo].MF_ORDEMSERVICOS A
LEFT JOIN [DBRodo].[dbo].MA_RECURSOS B ON A.VEICULO = B.HANDLE
INNER JOIN MF_VEICULOTIPOS VEICULOTIPO 
	ON VEICULOTIPO.HANDLE = B.TIPOVEICULO

WHERE DATAFINAL >= @BeginDate
AND DATAFINAL < @EndDate
AND A.CODIGO = 'MCI.0002787/19'

GROUP BY A.HANDLE
		,A.CODIGO
		,A.DESCRICAO
		,A.FILIAL
		,B.CODIGO
		,VEICULOTIPO.NOME
		,CAST(DATAFINAL AS DATE)